// BOMCheck 语言包 (默认 zh-CN; 缺失词条回退默认语言)
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= 'BOM 检查')
    pickFile: '选择文件',
    clear: '清除',
    dropHint: '点击左侧按钮选择文件, 或把文件拖到这里',
    dropActive: '松开鼠标即可载入文件',
    // 文件信息
    fileTitle: '文件信息',
    fileName: '文件名',
    fileSize: '文件大小',
    fileSizeWithBom: '文件大小 (含 BOM {num} 字节)',
    modifiedAt: '修改时间',
    headBytes: '首部字节',
    // 检查结果
    resultTitle: '检查结果',
    hasBom: '检测到 BOM',
    hasBomTip: '文件开头存在 BOM 标记, 可能导致 PHP / JSON / 配置文件解析异常, 建议去除',
    noBom: '未检测到 BOM',
    noBomTip: '文件开头没有 BOM 标记, 内容从第一个字节开始',
    bomType: 'BOM 类型',
    bomBytesLabel: 'BOM 字节',
    bomSizeLabel: 'BOM 长度',
    bytesUnit: '{num} 字节',
    alsoMatch: '同时符合 {list} 的字节特征, 去除时可切换「BOM 类型」指定按哪种处理',
    guessTitle: '编码推测 (无 BOM)',
    guess_utf8: 'UTF-8',
    guess_utf16le: 'UTF-16 LE (小端, 无 BOM)',
    guess_utf16be: 'UTF-16 BE (大端, 无 BOM)',
    guess_gbk: 'GBK / Big5 等本地编码 (非 UTF-8)',
    guess_binary: '二进制文件',
    guessTip_utf16le: '字节形如 41 00 42 00, 很可能是无 BOM 的 UTF-16 LE 文本, 部分编辑器会显示乱码',
    guessTip_utf16be: '字节形如 00 41 00 42, 很可能是无 BOM 的 UTF-16 BE 文本, 部分编辑器会显示乱码',
    guessTip_gbk: '不是合法的 UTF-8 序列且无 0 字节, 可能是 GBK / Big5 等中文编码',
    guessTip_binary: '含 0 字节, 按二进制处理, 不显示文本预览',
    // 操作
    opTitle: '处理并下载',
    bomTypeLabel: 'BOM 类型',
    removeBtn: '去除 BOM 并下载',
    addBtn: '添加 / 替换 BOM 并下载',
    removeDisabled: '当前文件没有 BOM, 无需去除',
    previewTitle: '文本预览 (最多 2000 字符)',
    previewEmpty: '文件内容为空, 没有可预览的文本',
    previewBinary: '二进制文件, 不显示文本预览',
    tips: '使用说明',
    tip_1: 'BOM (Byte Order Mark) 是文件开头的字节标记, 由 Windows 记事本「另存为 UTF-8」自动写入; 它不属于文件内容, 但会作为普通字节被程序读到, 常导致 PHP 页面顶部多出一行空白、JSON 解析失败、Shell / 配置文件首行解析异常等问题。',
    tip_2: '各编码的 BOM 字节: UTF-8 = EF BB BF (3 字节), UTF-16 LE = FF FE (2 字节), UTF-16 BE = FE FF (2 字节), UTF-32 LE = FF FE 00 00 (4 字节), UTF-32 BE = 00 00 FE FF (4 字节)。',
    tip_3: '「去除 BOM」只删除开头的 BOM 字节, 其余字节原样保留; 「添加 / 替换 BOM」会先移除已有 BOM 再写入所选类型的 BOM, 因此也用于在不同编码间转换 BOM。',
    tip_4: 'UTF-32 LE 的 BOM 以 FF FE 开头, 与 UTF-16 LE 的前两字节相同, 遇到此类文件时检查结果会同时列出两种类型, 可用「BOM 类型」下拉框指定按哪种长度去除。',
    tip_5: '去掉 BOM 不会改变文件的编码本身: 例如 UTF-16 LE 文件去掉 BOM 后仍是 UTF-16 LE 内容, 只是不再有标记, 若程序依赖 BOM 识别编码则可能出现乱码, 需要时请再添加回去。',
    e_needFile: '请先选择文件',
    e_tooLarge: '文件过大 ({size}), 超过 {max} 上限',
    e_noBom: '当前文件没有检测到 BOM, 无需去除',
    e_readFail: '读取文件失败: {msg}',
    okRemove: '已下载去除 BOM 的文件 {name} (减少 {num} 字节)',
    okAdd: '已下载添加 BOM 的文件 {name} ({type}, 增加 {num} 字节)',
    okReplace: '已下载替换 BOM 的文件 {name} ({from} → {type}, {num} 字节 → {num2} 字节)',
    filterFile: '文件',
    saveRemoveTitle: '保存已去除 BOM 的文件',
    saveAddTitle: '保存已添加 BOM 的文件',
    copyHead: '点击复制首部字节',
    copyOk: '复制到粘贴板成功！！！',
  },
  'zh-TW': {
    appName: 'BOM 檢查',
    pickFile: '選擇檔案',
    clear: '清除',
    dropHint: '點擊左側按鈕選擇檔案, 或把檔案拖到這裡',
    dropActive: '放開滑鼠即可載入檔案',
    fileTitle: '檔案資訊',
    fileName: '檔案名稱',
    fileSize: '檔案大小',
    fileSizeWithBom: '檔案大小 (含 BOM {num} 位元組)',
    modifiedAt: '修改時間',
    headBytes: '首部位元組',
    resultTitle: '檢查結果',
    hasBom: '偵測到 BOM',
    hasBomTip: '檔案開頭存在 BOM 標記, 可能導致 PHP / JSON / 設定檔解析異常, 建議移除',
    noBom: '未偵測到 BOM',
    noBomTip: '檔案開頭沒有 BOM 標記, 內容從第一個位元組開始',
    bomType: 'BOM 類型',
    bomBytesLabel: 'BOM 位元組',
    bomSizeLabel: 'BOM 長度',
    bytesUnit: '{num} 位元組',
    alsoMatch: '同時符合 {list} 的位元組特徵, 移除時可切換「BOM 類型」指定按哪種處理',
    guessTitle: '編碼推測 (無 BOM)',
    guess_utf8: 'UTF-8',
    guess_utf16le: 'UTF-16 LE (小端, 無 BOM)',
    guess_utf16be: 'UTF-16 BE (大端, 無 BOM)',
    guess_gbk: 'GBK / Big5 等本地編碼 (非 UTF-8)',
    guess_binary: '二進位檔案',
    guessTip_utf16le: '位元組形如 41 00 42 00, 很可能是無 BOM 的 UTF-16 LE 文字, 部分編輯器會顯示亂碼',
    guessTip_utf16be: '位元組形如 00 41 00 42, 很可能是無 BOM 的 UTF-16 BE 文字, 部分編輯器會顯示亂碼',
    guessTip_gbk: '不是合法的 UTF-8 序列且無 0 位元組, 可能是 GBK / Big5 等中文編碼',
    guessTip_binary: '含 0 位元組, 按二進位處理, 不顯示文字預覽',
    opTitle: '處理並下載',
    bomTypeLabel: 'BOM 類型',
    removeBtn: '移除 BOM 並下載',
    addBtn: '新增 / 取代 BOM 並下載',
    removeDisabled: '目前檔案沒有 BOM, 無需移除',
    previewTitle: '文字預覽 (最多 2000 字元)',
    previewEmpty: '檔案內容為空, 沒有可預覽的文字',
    previewBinary: '二進位檔案, 不顯示文字預覽',
    tips: '使用說明',
    tip_1: 'BOM (Byte Order Mark) 是檔案開頭的位元組標記, 由 Windows 記事本「另存為 UTF-8」自動寫入; 它不屬於檔案內容, 但會當作一般位元組被程式讀到, 常導致 PHP 頁面頂部多出一行空白、JSON 解析失敗、Shell / 設定檔首行解析異常等問題。',
    tip_2: '各編碼的 BOM 位元組: UTF-8 = EF BB BF (3 位元組), UTF-16 LE = FF FE (2 位元組), UTF-16 BE = FE FF (2 位元組), UTF-32 LE = FF FE 00 00 (4 位元組), UTF-32 BE = 00 00 FE FF (4 位元組)。',
    tip_3: '「移除 BOM」只刪除開頭的 BOM 位元組, 其餘位元組原樣保留; 「新增 / 取代 BOM」會先移除已有 BOM 再寫入所選類型的 BOM, 因此也用於在不同編碼間轉換 BOM。',
    tip_4: 'UTF-32 LE 的 BOM 以 FF FE 開頭, 與 UTF-16 LE 的前兩個位元組相同, 遇到此類檔案時檢查結果會同時列出兩種類型, 可用「BOM 類型」下拉框指定按哪種長度移除。',
    tip_5: '移除 BOM 不會改變檔案的編碼本身: 例如 UTF-16 LE 檔案移除 BOM 後仍是 UTF-16 LE 內容, 只是不再有標記, 若程式依賴 BOM 辨識編碼則可能出現亂碼, 需要時請再新增回去。',
    e_needFile: '請先選擇檔案',
    e_tooLarge: '檔案過大 ({size}), 超過 {max} 上限',
    e_noBom: '目前檔案沒有偵測到 BOM, 無需移除',
    e_readFail: '讀取檔案失敗: {msg}',
    okRemove: '已下載移除 BOM 的檔案 {name} (減少 {num} 位元組)',
    okAdd: '已下載新增 BOM 的檔案 {name} ({type}, 增加 {num} 位元組)',
    okReplace: '已下載取代 BOM 的檔案 {name} ({from} → {type}, {num} 位元組 → {num2} 位元組)',
    filterFile: '檔案',
    saveRemoveTitle: '儲存已移除 BOM 的檔案',
    saveAddTitle: '儲存已新增 BOM 的檔案',
    copyHead: '點擊複製首部位元組',
    copyOk: '複製到貼上板成功！！！',
  },
  en: {
    appName: 'BOM Inspector',
    pickFile: 'Choose File',
    clear: 'Clear',
    dropHint: 'Click the button on the left to choose a file, or drop a file here',
    dropActive: 'Release to load the file',
    fileTitle: 'File Info',
    fileName: 'Name',
    fileSize: 'Size',
    fileSizeWithBom: 'Size (BOM included, {num} bytes)',
    modifiedAt: 'Modified',
    headBytes: 'Leading Bytes',
    resultTitle: 'Inspection Result',
    hasBom: 'BOM detected',
    hasBomTip: 'The file starts with a BOM, which often breaks PHP / JSON / config parsing — removing it is usually the fix',
    noBom: 'No BOM detected',
    noBomTip: 'The file starts without a BOM, content begins at the very first byte',
    bomType: 'BOM Type',
    bomBytesLabel: 'BOM Bytes',
    bomSizeLabel: 'BOM Length',
    bytesUnit: '{num} bytes',
    alsoMatch: 'Also matches the byte pattern of {list}; switch “BOM Type” to choose which one to strip',
    guessTitle: 'Encoding Guess (no BOM)',
    guess_utf8: 'UTF-8',
    guess_utf16le: 'UTF-16 LE (little endian, no BOM)',
    guess_utf16be: 'UTF-16 BE (big endian, no BOM)',
    guess_gbk: 'GBK / Big5 or another legacy encoding (not UTF-8)',
    guess_binary: 'Binary file',
    guessTip_utf16le: 'Bytes look like 41 00 42 00, most likely UTF-16 LE text without a BOM — some editors show it as garbage',
    guessTip_utf16be: 'Bytes look like 00 41 00 42, most likely UTF-16 BE text without a BOM — some editors show it as garbage',
    guessTip_gbk: 'Not valid UTF-8 and contains no 0 bytes, so it may be GBK / Big5 or similar',
    guessTip_binary: 'Contains 0 bytes, treated as binary — no text preview',
    opTitle: 'Fix & Download',
    bomTypeLabel: 'BOM Type',
    removeBtn: 'Remove BOM & Download',
    addBtn: 'Add / Replace BOM & Download',
    removeDisabled: 'This file has no BOM, nothing to remove',
    previewTitle: 'Text Preview (up to 2000 characters)',
    previewEmpty: 'The file is empty, nothing to preview',
    previewBinary: 'Binary file, no text preview',
    tips: 'How It Works',
    tip_1: 'A BOM (Byte Order Mark) is a byte marker at the very start of a file, written by Windows Notepad when saving as UTF-8. It is not part of the content but is read as ordinary bytes, which commonly causes a blank first line in PHP pages, JSON parse errors and broken shell / config first lines.',
    tip_2: 'BOM bytes per encoding: UTF-8 = EF BB BF (3 bytes), UTF-16 LE = FF FE (2 bytes), UTF-16 BE = FE FF (2 bytes), UTF-32 LE = FF FE 00 00 (4 bytes), UTF-32 BE = 00 00 FE FF (4 bytes).',
    tip_3: '“Remove BOM” only deletes the leading BOM bytes and keeps everything else untouched. “Add / Replace BOM” first removes any existing BOM and then writes the selected one, so it also converts between BOM kinds.',
    tip_4: 'The UTF-32 LE BOM starts with FF FE, exactly like the first two bytes of UTF-16 LE. For such files the result lists both kinds — pick one in the “BOM Type” list to control how many bytes are stripped.',
    tip_5: 'Removing a BOM does not change the file encoding itself: a UTF-16 LE file stays UTF-16 LE without the marker afterwards, so a program that relies on the BOM to detect the encoding may show garbage — add it back if needed.',
    e_needFile: 'Please choose a file first',
    e_tooLarge: 'The file is too large ({size}), exceeding the {max} limit',
    e_noBom: 'No BOM was detected in this file, nothing to remove',
    e_readFail: 'Failed to read the file: {msg}',
    okRemove: 'Downloaded {name} without the BOM ({num} bytes smaller)',
    okAdd: 'Downloaded {name} with a {type} BOM ({num} bytes larger)',
    okReplace: 'Downloaded {name} with a replaced BOM ({from} → {type}, {num} → {num2} bytes)',
    filterFile: 'File',
    saveRemoveTitle: 'Save the file without BOM',
    saveAddTitle: 'Save the file with BOM',
    copyHead: 'Click to copy the leading bytes',
    copyOk: 'Copied to clipboard !!!',
  },
} as const;
