// 字幕示例内容 (如 SAMPLE_SRT 中的字幕行) 属演示数据不翻译
export default {
  default: 'zh-CN',
  'zh-CN': {
    alertTitle: '字幕格式转换',
    alertDesc: '在浏览器本地完成 SRT / VTT / SBV / SUB / SSA / ASS / SMI / LRC / JSON 九种字幕格式互相转换，内容不会上传到任何服务器。各格式的样式指令（如 ASS {\\pos}、SRT <i>、MicroDVD {y:..}）在转换时会剥除，仅保留文本与时间轴。',
    cardIn: '输入', cardOut: '输出',
    lbInFmt: '输入格式', lbFps: '帧率 (fps)', lbOutFmt: '输出格式',
    optAuto: '自动检测',
    fmt_lrc: 'LRC (歌词)',
    uploadBtn: '上传字幕文件', loadBtn: '载入示例',
    ph: '粘贴字幕文本…（也可点击上方按钮上传文件）\n\n示例:\n1\n00:00:01,000 --> 00:00:03,000\n你好',
    loadedFile: '已载入文件: {name}',
    convertBtn: '转换',
    tagCues: '{n} 条字幕', tagDur: '总时长 {dur}',
    dlFile: '下载 {ext} 文件',
    copyBtn: '复制结果',
    jsonNote: 'JSON 结构: [{"start":毫秒,"end":毫秒,"text":"文本"}]',
    previewTitle: '内容预览 (前 {n} 条)',
    colStart: '开始', colText: '文本',
    warnNeedText: '请先粘贴或上传字幕文本',
    errAuto: '未能自动识别输入格式，请手动选择',
    warnNoCue: '未解析到任何字幕条目，请检查内容',
    convertedTpl: '已转换 {n} 条字幕 ({src} → {target})',
    fileReadFail: '文件读取失败',
    downloadedTpl: '已下载 {file}',
    copiedOk: '已复制',
    e_timeFmt: '时间格式无法识别: {v}',
    e_webvtt: '不是有效的 WebVTT 文件 (缺少 WEBVTT 头)',
    e_sami: '不是有效的 SAMI 文件',
    e_json: '不是有效的 JSON',
    e_jsonArr: 'JSON 顶层需为数组: [{"start":ms,"end":ms,"text":"..."}] (毫秒)',
    e_jsonArrMs: 'JSON 顶层需为数组 (毫秒)',
    e_jsonItem: 'JSON 第 {n} 项不是对象',
    e_jsonMiss: 'JSON 第 {n} 项缺 start/end 时间 (毫秒)',
  },
  'zh-TW': {
    appName: '字幕格式轉換',
    alertTitle: '字幕格式轉換',
    alertDesc: '在瀏覽器本機完成 SRT / VTT / SBV / SUB / SSA / ASS / SMI / LRC / JSON 九種字幕格式互相轉換，內容不會上傳到任何伺服器。各格式的樣式指令（如 ASS {\\pos}、SRT <i>、MicroDVD {y:..}）在轉換時會剝除，僅保留文字與時間軸。',
    cardIn: '輸入', cardOut: '輸出',
    lbInFmt: '輸入格式', lbFps: '幀率 (fps)', lbOutFmt: '輸出格式',
    optAuto: '自動偵測',
    fmt_lrc: 'LRC (歌詞)',
    uploadBtn: '上傳字幕檔', loadBtn: '載入範例',
    ph: '貼上字幕文字…（也可點擊上方按鈕上傳檔案）\n\n範例:\n1\n00:00:01,000 --> 00:00:03,000\n你好',
    loadedFile: '已載入檔案: {name}',
    convertBtn: '轉換',
    tagCues: '{n} 條字幕', tagDur: '總時長 {dur}',
    dlFile: '下載 {ext} 檔案',
    copyBtn: '複製結果',
    jsonNote: 'JSON 結構: [{"start":毫秒,"end":毫秒,"text":"文字"}]',
    previewTitle: '內容預覽 (前 {n} 條)',
    colStart: '開始', colText: '文字',
    warnNeedText: '請先貼上或上傳字幕文字',
    errAuto: '未能自動辨識輸入格式，請手動選擇',
    warnNoCue: '未解析到任何字幕條目，請檢查內容',
    convertedTpl: '已轉換 {n} 條字幕 ({src} → {target})',
    fileReadFail: '檔案讀取失敗',
    downloadedTpl: '已下載 {file}',
    copiedOk: '已複製',
    e_timeFmt: '時間格式無法辨識: {v}',
    e_webvtt: '不是有效的 WebVTT 檔案 (缺少 WEBVTT 標頭)',
    e_sami: '不是有效的 SAMI 檔案',
    e_json: '不是有效的 JSON',
    e_jsonArr: 'JSON 頂層需為陣列: [{"start":ms,"end":ms,"text":"..."}] (毫秒)',
    e_jsonArrMs: 'JSON 頂層需為陣列 (毫秒)',
    e_jsonItem: 'JSON 第 {n} 項不是物件',
    e_jsonMiss: 'JSON 第 {n} 項缺少 start/end 時間 (毫秒)',
  },
  en: {
    appName: 'Subtitle Format Converter',
    alertTitle: 'Subtitle Format Convert',
    alertDesc: 'Convert between nine subtitle formats — SRT / VTT / SBV / SUB / SSA / ASS / SMI / LRC / JSON — entirely in your browser; nothing is uploaded to any server. Formatting tags (e.g. ASS {\\pos}, SRT <i>, MicroDVD {y:..}) are stripped during conversion, leaving only text and the timeline.',
    cardIn: 'Input', cardOut: 'Output',
    lbInFmt: 'Input format', lbFps: 'Frame rate (fps)', lbOutFmt: 'Output format',
    optAuto: 'Auto-detect',
    fmt_lrc: 'LRC (lyrics)',
    uploadBtn: 'Upload subtitle file', loadBtn: 'Load sample',
    ph: 'Paste subtitle text… (or click the button above to upload a file)\n\nExample:\n1\n00:00:01,000 --> 00:00:03,000\n你好',
    loadedFile: 'File loaded: {name}',
    convertBtn: 'Convert',
    tagCues: '{n} cues', tagDur: 'Duration {dur}',
    dlFile: 'Download {ext} file',
    copyBtn: 'Copy result',
    jsonNote: 'JSON structure: [{"start":ms,"end":ms,"text":"text"}]',
    previewTitle: 'Preview (first {n} cues)',
    colStart: 'Start', colText: 'Text',
    warnNeedText: 'Please paste or upload subtitle text first',
    errAuto: 'Could not auto-detect the input format; please select it manually',
    warnNoCue: 'No subtitle cues were parsed — please check the content',
    convertedTpl: 'Converted {n} cues ({src} → {target})',
    fileReadFail: 'Failed to read the file',
    downloadedTpl: 'Downloaded {file}',
    copiedOk: 'Copied',
    e_timeFmt: 'Cannot parse time format: {v}',
    e_webvtt: 'Not a valid WebVTT file (missing WEBVTT header)',
    e_sami: 'Not a valid SAMI file',
    e_json: 'Not valid JSON',
    e_jsonArr: 'JSON top level must be an array: [{"start":ms,"end":ms,"text":"..."}] (ms)',
    e_jsonArrMs: 'JSON top level must be an array (ms)',
    e_jsonItem: 'JSON item {n} is not an object',
    e_jsonMiss: 'JSON item {n} is missing start/end time (ms)',
  },
} as const;
