// JWTDecoder 语言包 (默认 zh-CN; 缺失词条回退默认语言)
// 面板交互文案 (按需扩展); 说明性长文 (tips/intro/算法说明) 暂保留简中, 后续批次再翻
// lib 内解析错误提示为内容数据保留原文
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= 'JWT 解码')
    placeholder: '粘贴 JWT (header.payload.signature, 例如 eyJhbGciOi...)',
    copyOk: '复制到粘贴板成功！！！',
    copyTitle: '双击复制内容到粘贴板',
    metaInfo: 'Header 元信息: {meta}',
    metaNone: '无 alg/typ/kid 字段',
    headerTitle: '① 头部 (Header)',
    payloadTitle: '② 负载 (Payload)',
    sigTitle: '③ 签名 (Signature)',
    sigEmpty: '(空签名, 可能为 none 算法)',
    clickTitle: '点击复制 HEX 签名',
    divider: 'JWT 说明',
    tabDecode: '解析',
    tabEncode: '生成',
    encAlg: '算法',
    algNone: 'none (不签名)',
    encSecret: '密钥',
    encSecretPh: 'HMAC 签名密钥 (secret)',
    encSecretB64: '密钥为 Base64',
    encNoneWarn: 'alg=none 表示不签名, 生成的 token 可被任意篡改, 仅用于调试',
    encHeaderTitle: '① 头部 (Header, JSON)',
    encPayloadTitle: '② 负载 (Payload, JSON)',
    encFillTime: '填入 iat / exp (当前时间 + 1 小时)',
    encGenerate: '生成 JWT',
    encCopy: '复制 token',
    encReset: '重置',
    encResultTitle: '③ 生成的 JWT',
    encClickCopy: '点击复制',
    encPartsTitle: '分段预览 (base64url)',
    encNoSig: '(空签名, alg=none)',
    encSigHex: '签名 HEX',
  },
  'zh-TW': {
    appName: 'JWT 編解碼器',
    placeholder: '貼上 JWT (header.payload.signature，例如 eyJhbGciOi...)',
    copyOk: '複製到剪貼簿成功！！！',
    copyTitle: '雙擊複製內容到剪貼簿',
    metaInfo: 'Header 元資訊：{meta}',
    metaNone: '無 alg/typ/kid 欄位',
    headerTitle: '① 標頭 (Header)',
    payloadTitle: '② 負載 (Payload)',
    sigTitle: '③ 簽名 (Signature)',
    sigEmpty: '(空簽名，可能為 none 演算法)',
    clickTitle: '點擊複製 HEX 簽名',
    divider: 'JWT 說明',
    tabDecode: '解析',
    tabEncode: '產生',
    encAlg: '演算法',
    algNone: 'none (不簽章)',
    encSecret: '金鑰',
    encSecretPh: 'HMAC 簽章金鑰 (secret)',
    encSecretB64: '金鑰為 Base64',
    encNoneWarn: 'alg=none 表示不簽章, 產生的 token 可被任意竄改, 僅供除錯使用',
    encHeaderTitle: '① 標頭 (Header, JSON)',
    encPayloadTitle: '② 負載 (Payload, JSON)',
    encFillTime: '填入 iat / exp (目前時間 + 1 小時)',
    encGenerate: '產生 JWT',
    encCopy: '複製 token',
    encReset: '重設',
    encResultTitle: '③ 產生的 JWT',
    encClickCopy: '點擊複製',
    encPartsTitle: '分段預覽 (base64url)',
    encNoSig: '(空簽章, alg=none)',
    encSigHex: '簽章 HEX',
  },
  en: {
    appName: 'JWT Encoder & Decoder',
    placeholder: 'Paste a JWT (header.payload.signature, e.g. eyJhbGciOi...)',
    copyOk: 'Copied to clipboard!',
    copyTitle: 'Double-click to copy',
    metaInfo: 'Header metadata: {meta}',
    metaNone: 'no alg/typ/kid field',
    headerTitle: '① Header',
    payloadTitle: '② Payload',
    sigTitle: '③ Signature',
    sigEmpty: '(no signature; possibly a "none" algorithm)',
    clickTitle: 'Click to copy HEX signature',
    divider: 'About JWT',
    tabDecode: 'Decode',
    tabEncode: 'Generate',
    encAlg: 'Algorithm',
    algNone: 'none (unsigned)',
    encSecret: 'Secret',
    encSecretPh: 'HMAC signing secret',
    encSecretB64: 'Secret is Base64',
    encNoneWarn: 'alg=none means unsigned: the resulting token can be tampered with freely — for debugging only',
    encHeaderTitle: '① Header (JSON)',
    encPayloadTitle: '② Payload (JSON)',
    encFillTime: 'Fill iat / exp (now + 1 hour)',
    encGenerate: 'Generate JWT',
    encCopy: 'Copy token',
    encReset: 'Reset',
    encResultTitle: '③ Generated JWT',
    encClickCopy: 'Click to copy',
    encPartsTitle: 'Segments (base64url)',
    encNoSig: '(empty signature, alg=none)',
    encSigHex: 'Signature HEX',
  },
} as const;
