// LatLngConvert 语言包 (默认 zh-CN; 缺失词条回退默认语言)
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= '经纬度格式转换')
    labelFormat: '输入格式',
    labelOrder: '书写顺序',
    fmt_AUTO: '自动识别',
    fmt_DD: '十进制 (DD)',
    fmt_DMS: '度分秒 (DMS)',
    fmt_DM: '度分 (DM)',
    fmt_NMEA: '国家标准 (DDMM.mm)',
    ph_AUTO: '自动识别十进制 / 度分秒 / 度分 / 国家标准格式',
    ph_DD: '39.20567, 116.12345',
    ph_DMS: '39°12′20.41″N, 116°07′24.42″E',
    ph_DM: '39°12.3402′N, 116°07.407′E',
    ph_NMEA: '3912.3402N, 11607.4070E',
    order_latlng: '纬度在前',
    order_lnglat: '经度在前',
    clear: '清除',
    copyOk: '复制到粘贴板成功！！！',
    clickCopy: '点击复制到粘贴板',
    latShort: '纬度',
    lngShort: '经度',
    resultTitle: '转换结果',
    refTitle: '格式说明',
    ref_1: '十进制 (DD): 直接以度为单位, 小数部分表示分秒的换算值 (如 39.20567° 等同于 39°12′20.41″); 北纬 / 东经为正数, 南纬 / 西经为负数。',
    ref_2: '度分秒 (DMS): 度 (°) / 分 (′) / 秒 (″) 三级单位, 1° = 60′ = 3600″; 如 39°54′27″N 表示北纬 39 度 54 分 27 秒。',
    ref_3: '书写顺序: 通常先写纬度后写经度, 中间用逗号分隔 (如 39°N, 116°E); 也有先写经度后写纬度的写法, 可用「书写顺序」切换。',
    ref_4: '方向标识: 纬度用 N (北纬) / S (南纬), 经度用 E (东经) / W (西经); 带方向字母时自动按其判定纬度与经度。',
    ref_5: '度分 (DM): 介于十进制与六十进制之间, 分部分保留小数 (如 116°23.26′)。',
    ref_6: '国家标准 (DDMM.mm): 中国曾采用 DDMM.mmN 与 DDDMM.mmE 格式 (如 3912.34N / 11607.41E)。',
    e_EMPTY: '请输入经纬度',
    e_PAIR: '请输入一对经纬度 (纬度, 经度)',
    e_INVALID: '无法识别坐标: {value}',
    e_LAT_RANGE: '纬度超出范围 (-90 ~ 90): {value}',
    e_LNG_RANGE: '经度超出范围 (-180 ~ 180): {value}',
    e_UNKNOWN: '未知错误',
  },
  'zh-TW': {
    appName: '經緯度格式轉換',
    labelFormat: '輸入格式',
    labelOrder: '書寫順序',
    fmt_AUTO: '自動辨識',
    fmt_DD: '十進位 (DD)',
    fmt_DMS: '度分秒 (DMS)',
    fmt_DM: '度分 (DM)',
    fmt_NMEA: '國家標準 (DDMM.mm)',
    ph_AUTO: '自動辨識十進位 / 度分秒 / 度分 / 國家標準格式',
    ph_DD: '39.20567, 116.12345',
    ph_DMS: '39°12′20.41″N, 116°07′24.42″E',
    ph_DM: '39°12.3402′N, 116°07.407′E',
    ph_NMEA: '3912.3402N, 11607.4070E',
    order_latlng: '緯度在前',
    order_lnglat: '經度在前',
    clear: '清除',
    copyOk: '複製到剪貼簿成功！！！',
    clickCopy: '點擊複製到剪貼簿',
    latShort: '緯度',
    lngShort: '經度',
    resultTitle: '轉換結果',
    refTitle: '格式說明',
    ref_1: '十進位 (DD): 直接以度為單位, 小數部分表示分秒的換算值 (如 39.20567° 等同於 39°12′20.41″); 北緯 / 東經為正數, 南緯 / 西經為負數。',
    ref_2: '度分秒 (DMS): 度 (°) / 分 (′) / 秒 (″) 三級單位, 1° = 60′ = 3600″; 如 39°54′27″N 表示北緯 39 度 54 分 27 秒。',
    ref_3: '書寫順序: 通常先寫緯度後寫經度, 中間用逗號分隔 (如 39°N, 116°E); 也有先寫經度後寫緯度的寫法, 可用「書寫順序」切換。',
    ref_4: '方向標識: 緯度用 N (北緯) / S (南緯), 經度用 E (東經) / W (西經); 帶方向字母時自動依其判定緯度與經度。',
    ref_5: '度分 (DM): 介於十進位與六十進位之間, 分部分保留小數 (如 116°23.26′)。',
    ref_6: '國家標準 (DDMM.mm): 中國曾採用 DDMM.mmN 與 DDDMM.mmE 格式 (如 3912.34N / 11607.41E)。',
    e_EMPTY: '請輸入經緯度',
    e_PAIR: '請輸入一對經緯度 (緯度, 經度)',
    e_INVALID: '無法辨識座標: {value}',
    e_LAT_RANGE: '緯度超出範圍 (-90 ~ 90): {value}',
    e_LNG_RANGE: '經度超出範圍 (-180 ~ 180): {value}',
    e_UNKNOWN: '未知錯誤',
  },
  en: {
    appName: 'Latitude / Longitude Format Converter',
    labelFormat: 'Input format',
    labelOrder: 'Order',
    fmt_AUTO: 'Auto detect',
    fmt_DD: 'Decimal degrees (DD)',
    fmt_DMS: 'Degrees minutes seconds (DMS)',
    fmt_DM: 'Degrees decimal minutes (DM)',
    fmt_NMEA: 'National standard (DDMM.mm)',
    ph_AUTO: 'Auto detect DD / DMS / DM / DDMM.mm',
    ph_DD: '39.20567, 116.12345',
    ph_DMS: '39°12′20.41″N, 116°07′24.42″E',
    ph_DM: '39°12.3402′N, 116°07.407′E',
    ph_NMEA: '3912.3402N, 11607.4070E',
    order_latlng: 'Latitude first',
    order_lnglat: 'Longitude first',
    clear: 'Clear',
    copyOk: 'Copied to clipboard!',
    clickCopy: 'Click to copy',
    latShort: 'Latitude',
    lngShort: 'Longitude',
    resultTitle: 'Result',
    refTitle: 'Format reference',
    ref_1: 'Decimal degrees (DD): degrees with a decimal fraction (39.20567° = 39°12′20.41″). North / East are positive, South / West negative.',
    ref_2: 'Degrees minutes seconds (DMS): 1° = 60′ = 3600″; e.g. 39°54′27″N is 39 degrees 54 minutes 27 seconds north.',
    ref_3: 'Order: latitude usually comes first, separated by a comma (e.g. 39°N, 116°E); longitude-first is also valid — switch it with “Order”.',
    ref_4: 'Hemisphere: latitude uses N / S, longitude uses E / W; hemisphere letters are used to decide which value is latitude.',
    ref_5: 'Degrees decimal minutes (DM): between DD and DMS, minutes keep a decimal fraction (e.g. 116°23.26′).',
    ref_6: 'National standard (DDMM.mm): China once used DDMM.mmN and DDDMM.mmE (e.g. 3912.34N / 11607.41E).',
    e_EMPTY: 'Please enter coordinates',
    e_PAIR: 'Please enter a coordinate pair (latitude, longitude)',
    e_INVALID: 'Unrecognized coordinate: {value}',
    e_LAT_RANGE: 'Latitude out of range (-90 ~ 90): {value}',
    e_LNG_RANGE: 'Longitude out of range (-180 ~ 180): {value}',
    e_UNKNOWN: 'Unknown error',
  },
} as const;
