// BasicAuthCodec 语言包 (默认 zh-CN; 缺失词条回退默认语言)
// 面板交互文案 (按需扩展); 说明性长文 (tips/intro) 暂保留简中, 后续批次再翻
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= 'HTTP Basic Auth 编解码')
    userLabel: '用户名:',
    passLabel: '密码:',
    userPh: '如 admin',
    passPh: '留空也允许',
    fullHeader: '生成完整 Authorization 请求头',
    encode: '编码',
    decode: '解读',
    clear: '清除',
    copyOk: '复制到粘贴板成功！！！',
    copyTitle: '双击复制内容到粘贴板',
    userEmpty: '用户名不能为空',
    decodeOk: '解读成功',
    decodeFail: '解读失败: {msg}',
    tokenOutPh: '点击「编码」后在此生成 Base64 Token / 完整请求头, 双击可复制',
    dividerDecode: '解读 Authorization / Token',
    authInPh: '粘贴 "Authorization: Basic dXNlcjpwYXNz" / "Basic xxx" / 裸 Token 进行解读',
    outUserPh: '解读出的用户名',
    outPassPh: '解读出的密码',
    dividerIntro: 'HTTP Basic Authentication 说明',
  },
  'zh-TW': {
    appName: 'HTTP Basic Auth 編解碼',
    userLabel: '使用者名稱：',
    passLabel: '密碼：',
    userPh: '如 admin',
    passPh: '留空也允許',
    fullHeader: '產生完整 Authorization 請求標頭',
    encode: '編碼',
    decode: '解讀',
    clear: '清除',
    copyOk: '複製到剪貼簿成功！！！',
    copyTitle: '雙擊複製內容到剪貼簿',
    userEmpty: '使用者名稱不能為空',
    decodeOk: '解讀成功',
    decodeFail: '解讀失敗：{msg}',
    tokenOutPh: '點擊「編碼」後在此產生 Base64 Token / 完整請求標頭，雙擊可複製',
    dividerDecode: '解讀 Authorization / Token',
    authInPh: '貼上 "Authorization: Basic dXNlcjpwYXNz" / "Basic xxx" / 裸 Token 進行解讀',
    outUserPh: '解讀出的使用者名稱',
    outPassPh: '解讀出的密碼',
    dividerIntro: 'HTTP Basic Authentication 說明',
  },
  en: {
    appName: 'HTTP Basic Auth Codec',
    userLabel: 'Username:',
    passLabel: 'Password:',
    userPh: 'e.g. admin',
    passPh: 'may be empty',
    fullHeader: 'Generate full Authorization header',
    encode: 'Encode',
    decode: 'Parse',
    clear: 'Clear',
    copyOk: 'Copied to clipboard!',
    copyTitle: 'Double-click to copy',
    userEmpty: 'Username cannot be empty',
    decodeOk: 'Parsed successfully',
    decodeFail: 'Parse failed: {msg}',
    tokenOutPh: 'Click “Encode” to generate a Base64 token / full header here. Double-click to copy.',
    dividerDecode: 'Parse Authorization / Token',
    authInPh: 'Paste "Authorization: Basic dXNlcjpwYXNz" / "Basic xxx" / a raw token to parse',
    outUserPh: 'Parsed username',
    outPassPh: 'Parsed password',
    dividerIntro: 'About HTTP Basic Authentication',
  },
} as const;
