// GzipCodec 语言包 (默认 zh-CN; 缺失词条回退默认语言)
// 面板交互文案 (按需扩展); 说明性长文 (tips/intro/算法说明) 暂保留简中, 后续批次再翻
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= 'Gzip 编解码')
    copied: '已复制到剪贴板',
    copyTitle: '双击复制内容到剪贴板',
    plainPh: '输入要 Gzip 压缩的文本, 或拖拽文件到框内以文件内容为输入',
    gzip: 'Gzip 压缩',
    gunzip: 'Gzip 解压',
    clear: '清除',
    noPlain: '请先输入要压缩的内容',
    noInput: '请先输入要解压的 Gzip 串 (Base64 或 Hex)',
    compressFail: '压缩失败',
    gunzipFail: '解压失败',
    statText: '明文 {src} 字节 → Gzip {dst} 字节 ({pct}%)',
    statHint: '压缩率按输入输出字节计算; 点击下方说明了解格式差异',
    intro1: 'Gzip 是广泛使用的数据压缩格式: 压缩(编码)把文本变为二进制 gzip 流, 解压(解码)还原原文, 压缩率取决于内容重复度。',
    intro2a: '结果为二进制, 本工具用',
    intro2b: '(更紧凑) 或',
    intro2c: '(可读/便于调试) 两种文本格式展示, 可在「设置 → 编解码」里修改默认格式。',
    intro3: '解压输入 Base64 / Hex 均可自动识别; 输入必须带 Gzip 文件头 (1F 8B), 普通 Base64 文本(非 gzip 数据)会提示无效。',
    intro4: '压缩解压在本地浏览器/WebView 完成 (CompressionStream API), 内容不出本机, 无需网络。',
    resultHexPh: 'Gzip 压缩结果 (Hex, 可双击复制), 或粘贴待解压的 Gzip 串 (Base64/Hex 均可)',
    resultB64Ph: 'Gzip 压缩结果 (Base64, 可双击复制), 或粘贴待解压的 Gzip 串 (Base64/Hex 均可)',
    divider: 'Gzip 编解码说明',
  },
  'zh-TW': {
    appName: 'Gzip 編解碼',
    copied: '已複製到剪貼簿',
    copyTitle: '雙擊複製內容到剪貼簿',
    plainPh: '輸入要 Gzip 壓縮的文字，或拖曳檔案到框內以檔案內容為輸入',
    gzip: 'Gzip 壓縮',
    gunzip: 'Gzip 解壓',
    clear: '清除',
    noPlain: '請先輸入要壓縮的內容',
    noInput: '請先輸入要解壓的 Gzip 字串 (Base64 或 Hex)',
    compressFail: '壓縮失敗',
    gunzipFail: '解壓失敗',
    statText: '明文 {src} 位元組 → Gzip {dst} 位元組（{pct}%）',
    statHint: '壓縮率按輸入輸出位元組計算；點擊下方說明了解格式差異',
    resultHexPh: 'Gzip 壓縮結果 (Hex，可雙擊複製)，或貼上待解壓的 Gzip 字串 (Base64/Hex 均可)',
    resultB64Ph: 'Gzip 壓縮結果 (Base64，可雙擊複製)，或貼上待解壓的 Gzip 字串 (Base64/Hex 均可)',
    divider: 'Gzip 編解碼說明',
    intro1: 'Gzip 是廣泛使用的資料壓縮格式: 壓縮(編碼)把文字變為二進位 gzip 串流, 解壓(解碼)還原原文, 壓縮率取決於內容重複度。',
    intro2a: '結果為二進位, 本工具用',
    intro2b: '(更緊湊) 或',
    intro2c: '(可讀/易於除錯) 兩種文字格式顯示, 可在「設定 → 編解碼」裡修改預設格式。',
    intro3: '解壓輸入 Base64 / Hex 皆可自動辨識; 輸入必須帶 Gzip 檔頭 (1F 8B), 一般 Base64 文字(非 gzip 資料)會提示無效。',
    intro4: '壓縮解壓在本地瀏覽器/WebView 完成 (CompressionStream API), 內容不離開本機, 無需網路。',
  },
  en: {
    appName: 'Gzip Codec',
    copied: 'Copied to clipboard',
    copyTitle: 'Double-click to copy',
    plainPh: 'Enter text to Gzip, or drop a file here to use its contents as input',
    gzip: 'Gzip',
    gunzip: 'Gunzip',
    clear: 'Clear',
    noPlain: 'Enter some content to compress first',
    noInput: 'Enter a Gzip string (Base64 or Hex) to decompress first',
    compressFail: 'Compression failed',
    gunzipFail: 'Decompression failed',
    statText: '{src} bytes plaintext → Gzip {dst} bytes ({pct}%)',
    statHint: 'Ratio is based on input/output bytes; see the notes below for format differences',
    resultHexPh: 'Gzip output (Hex, double-click to copy), or paste a Gzip string (Base64/Hex) to decompress',
    resultB64Ph: 'Gzip output (Base64, double-click to copy), or paste a Gzip string (Base64/Hex) to decompress',
    divider: 'About Gzip Codec',
    intro1: 'Gzip is a widely used compression format: compressing (encoding) turns text into a binary gzip stream and decompressing (decoding) restores the original; the ratio depends on content redundancy.',
    intro2a: 'The result is binary; this tool shows it as either',
    intro2b: '(more compact) or',
    intro2c: '(readable / easier to debug). Change the default format under Settings → Codecs.',
    intro3: 'Both Base64 and Hex input are auto-detected when decompressing; input must carry the Gzip header (1F 8B) — plain Base64 text (non-gzip data) is reported as invalid.',
    intro4: 'Compression and decompression run locally in the browser/WebView (CompressionStream API); content never leaves your machine and no network is needed.',
  },
} as const;
