// GzipCodec 语言包 (默认 zh-CN; 缺失词条回退默认语言)
// 面板交互文案 (按需扩展); 说明性长文 (tips/intro/算法说明) 暂保留简中, 后续批次再翻
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= 'Gzip 编解码')
    copied: '已复制到剪贴板',
    copyTitle: '双击复制内容到剪贴板',
    plainPh: '输入要 Gzip 压缩的文本, 或拖拽文件到框内以文件内容为输入',
    gzip: 'Gzip 压缩',
    gunzip: 'Gzip 解压',
    clear: '清除',
    noPlain: '请先输入要压缩的内容',
    noInput: '请先输入要解压的 Gzip 串 (Base64 或 Hex)',
    compressFail: '压缩失败',
    gunzipFail: '解压失败',
    statText: '明文 {src} 字节 → Gzip {dst} 字节 ({pct}%)',
    statHint: '压缩率按输入输出字节计算; 点击下方说明了解格式差异',
    resultHexPh: 'Gzip 压缩结果 (Hex, 可双击复制), 或粘贴待解压的 Gzip 串 (Base64/Hex 均可)',
    resultB64Ph: 'Gzip 压缩结果 (Base64, 可双击复制), 或粘贴待解压的 Gzip 串 (Base64/Hex 均可)',
    divider: 'Gzip 编解码说明',
  },
  'zh-TW': {
    appName: 'Gzip 編解碼',
    copied: '已複製到剪貼簿',
    copyTitle: '雙擊複製內容到剪貼簿',
    plainPh: '輸入要 Gzip 壓縮的文字，或拖曳檔案到框內以檔案內容為輸入',
    gzip: 'Gzip 壓縮',
    gunzip: 'Gzip 解壓',
    clear: '清除',
    noPlain: '請先輸入要壓縮的內容',
    noInput: '請先輸入要解壓的 Gzip 字串 (Base64 或 Hex)',
    compressFail: '壓縮失敗',
    gunzipFail: '解壓失敗',
    statText: '明文 {src} 位元組 → Gzip {dst} 位元組（{pct}%）',
    statHint: '壓縮率按輸入輸出位元組計算；點擊下方說明了解格式差異',
    resultHexPh: 'Gzip 壓縮結果 (Hex，可雙擊複製)，或貼上待解壓的 Gzip 字串 (Base64/Hex 均可)',
    resultB64Ph: 'Gzip 壓縮結果 (Base64，可雙擊複製)，或貼上待解壓的 Gzip 字串 (Base64/Hex 均可)',
    divider: 'Gzip 編解碼說明',
  },
  en: {
    appName: 'Gzip Codec',
    copied: 'Copied to clipboard',
    copyTitle: 'Double-click to copy',
    plainPh: 'Enter text to Gzip, or drop a file here to use its contents as input',
    gzip: 'Gzip',
    gunzip: 'Gunzip',
    clear: 'Clear',
    noPlain: 'Enter some content to compress first',
    noInput: 'Enter a Gzip string (Base64 or Hex) to decompress first',
    compressFail: 'Compression failed',
    gunzipFail: 'Decompression failed',
    statText: '{src} bytes plaintext → Gzip {dst} bytes ({pct}%)',
    statHint: 'Ratio is based on input/output bytes; see the notes below for format differences',
    resultHexPh: 'Gzip output (Hex, double-click to copy), or paste a Gzip string (Base64/Hex) to decompress',
    resultB64Ph: 'Gzip output (Base64, double-click to copy), or paste a Gzip string (Base64/Hex) to decompress',
    divider: 'About Gzip Codec',
  },
} as const;
