import { useLocale } from '../../hook/locale-context';

const introZh = `
<h2>SM9 标识密码</h2>
<blockquote><p>SM9 是国家密码管理局发布的<b>标识密码 (IBC, Identity-Based Cryptography)</b> 算法 (GM/T 0044-2016), 基于 <b>256 位 BN 曲线</b>上的双线性对。与 SM2 不同, SM9 <b>不需要证书</b>: 直接用「邮箱 / 手机号 / 工号」等<b>标识 (ID)</b> 作为公钥, 由密钥中心用主私钥为该 ID 提取用户私钥。本工具使用 <b>GmSSL (C) 编译的 WebAssembly</b> 实现, 与 GmSSL 命令行 / SDK 结果互通。</p>
</blockquote>
<h2>密钥体系</h2>
<ul>
<li><p><b>加密 (SM9-Enc)</b> 与 <b>签名 (SM9-Sign)</b> 是两套<b>互相独立</b>的主密钥, 不能混用</p></li>
<li><p><b>主私钥 (msk)</b>：由密钥中心生成并严格保密 (DER HEX); <b>主公钥 (mpk)</b>：由主私钥导出, 可公开分发 (未压缩点 HEX)</p></li>
<li><p><b>用户私钥 (usk)</b>：由「主私钥 + ID」提取, 交给该 ID 的用户保管, 用于解密 / 签名</p></li>
<li><p>规格: 加密主公钥 <b>65 字节</b> (04‖X‖Y), 签名主公钥 <b>129 字节</b>; 主私钥 / 用户私钥为 GmSSL 的 DER 编码</p></li>
</ul>
<h2>使用流程</h2>
<ul>
<li><p><b>密钥生成</b>：设定用户 ID → 生成主密钥对 → 导出主公钥 (分发) → 提取用户私钥 (交付该 ID 用户)</p></li>
<li><p><b>加密</b>：发送方需 <b>接收方主公钥 + 接收方 ID</b>, 明文单组上限 <b>255 字节</b>, 输出 DER HEX 密文</p></li>
<li><p><b>解密</b>：接收方用 <b>自己的用户私钥 + 自己的 ID</b> 解密; ID 不一致会解密失败 (校验 C3 的 HMAC-SM3 标签)</p></li>
<li><p><b>签名验签</b>：签名用签名用户私钥; 验签只需 <b>签名者主公钥 + 签名者 ID + 数据 + 签名值</b></p></li>
<li><p>四个标签页<b>共享同一组密钥</b>与 ID; 「保存为默认密钥」存于浏览器本地 (localStorage), 不会上传</p></li>
</ul>
<h2>数据格式</h2>
<ul>
<li><p>界面统一使用 <b>HEX</b> 表示密钥与密文, 粘贴时允许空格 / 换行</p></li>
<li><p>密文 DER 结构: <code>SEQUENCE { INTEGER(0), BIT STRING(C1 65B), OCTET STRING(C3 32B), OCTET STRING(C2) }</code> (XOR 模式, 与 GmSSL <code>sm9_ciphertext_to_der</code> 一致)</p></li>
<li><p>签名值 DER 结构: <code>SEQUENCE { OCTET STRING(h 32B), BIT STRING(S 65B) }</code>, 共 <b>104 字节</b></p></li>
<li><p>签名值与加密主私钥同为 104 字节, 但首元素标签不同 (<code>OCTET STRING</code> / <code>INTEGER</code>), 工具会自动识别并在输入框下方提示类型</p></li>
<li><p>明文以 UTF-8 编码参与运算, 因此字节数按 UTF-8 计 (中文 1 字 = 3 字节)</p></li>
</ul>
<h2>安全提醒</h2>
<blockquote><p>主私钥 / 用户私钥切勿泄露; 全部运算在浏览器本地完成 (WebAssembly), 密钥不会上传。密钥生成需要安全随机数, 非 HTTPS/localhost 环境下浏览器会禁用 <code>crypto.getRandomValues</code>, 此时工具会直接报错而不会使用弱随机 (无 HTTPS 时可用桌面版或 GitHub Pages 版本)。</p>
</blockquote>
`;

const introTw = `
<h2>SM9 識別密碼</h2>
<blockquote><p>SM9 是中國國家密碼管理局發布的<b>識別密碼 (IBC, Identity-Based Cryptography)</b> 演算法 (GM/T 0044-2016), 基於 <b>256 位元 BN 曲線</b>上的雙線性對。與 SM2 不同, SM9 <b>不需要憑證</b>: 直接用「信箱 / 手機號 / 工號」等<b>識別碼 (ID)</b> 作為公鑰, 由金鑰中心用主私鑰為該 ID 提取使用者私鑰。本工具使用 <b>GmSSL (C) 編譯的 WebAssembly</b> 實作, 與 GmSSL 命令列 / SDK 結果互通。</p>
</blockquote>
<h2>金鑰體系</h2>
<ul>
<li><p><b>加密 (SM9-Enc)</b> 與 <b>簽章 (SM9-Sign)</b> 是兩套<b>互相獨立</b>的主金鑰, 不能混用</p></li>
<li><p><b>主私鑰 (msk)</b>：由金鑰中心產生並嚴格保密 (DER HEX); <b>主公鑰 (mpk)</b>：由主私鑰匯出, 可公開分發 (未壓縮點 HEX)</p></li>
<li><p><b>使用者私鑰 (usk)</b>：由「主私鑰 + ID」提取, 交給該 ID 的使用者保管, 用於解密 / 簽章</p></li>
<li><p>規格: 加密主公鑰 <b>65 位元組</b> (04‖X‖Y), 簽章主公鑰 <b>129 位元組</b>; 主私鑰 / 使用者私鑰為 GmSSL 的 DER 編碼</p></li>
</ul>
<h2>使用流程</h2>
<ul>
<li><p><b>金鑰產生</b>：設定使用者 ID → 產生主金鑰對 → 匯出主公鑰 (分發) → 提取使用者私鑰 (交付該 ID 使用者)</p></li>
<li><p><b>加密</b>：傳送方需 <b>接收方主公鑰 + 接收方 ID</b>, 明文單組上限 <b>255 位元組</b>, 輸出 DER HEX 密文</p></li>
<li><p><b>解密</b>：接收方用 <b>自己的使用者私鑰 + 自己的 ID</b> 解密; ID 不一致會解密失敗 (校驗 C3 的 HMAC-SM3 標籤)</p></li>
<li><p><b>簽章驗章</b>：簽章用簽章使用者私鑰; 驗章只需 <b>簽章者主公鑰 + 簽章者 ID + 資料 + 簽章值</b></p></li>
<li><p>四個頁籤<b>共用同一組金鑰</b>與 ID; 「儲存為預設金鑰」存於瀏覽器本機 (localStorage), 不會上傳</p></li>
</ul>
<h2>資料格式</h2>
<ul>
<li><p>介面統一使用 <b>HEX</b> 表示金鑰與密文, 貼上時允許空白 / 換行</p></li>
<li><p>密文 DER 結構: <code>SEQUENCE { INTEGER(0), BIT STRING(C1 65B), OCTET STRING(C3 32B), OCTET STRING(C2) }</code> (XOR 模式, 與 GmSSL <code>sm9_ciphertext_to_der</code> 一致)</p></li>
<li><p>簽章值 DER 結構: <code>SEQUENCE { OCTET STRING(h 32B), BIT STRING(S 65B) }</code>, 共 <b>104 位元組</b></p></li>
<li><p>簽章值與加密主私鑰同為 104 位元組, 但首元素標籤不同 (<code>OCTET STRING</code> / <code>INTEGER</code>), 工具會自動識別並在輸入框下方提示類型</p></li>
<li><p>明文以 UTF-8 編碼參與運算, 因此位元組數按 UTF-8 計 (中文 1 字 = 3 位元組)</p></li>
</ul>
<h2>安全提醒</h2>
<blockquote><p>主私鑰 / 使用者私鑰切勿洩漏; 全部運算在瀏覽器本機完成 (WebAssembly), 金鑰不會上傳。金鑰產生需要安全隨機數, 非 HTTPS/localhost 環境下瀏覽器會停用 <code>crypto.getRandomValues</code>, 此時工具會直接報錯而不會使用弱隨機 (無 HTTPS 時可用桌面版或 GitHub Pages 版本)。</p>
</blockquote>
`;

const introEn = `
<h2>SM9 identity-based cryptography</h2>
<blockquote><p>SM9 is the <b>identity-based cryptography (IBC)</b> algorithm published by China's National Cryptography Administration (GM/T 0044-2016), built on a bilinear pairing over a <b>256-bit BN curve</b>. Unlike SM2, SM9 <b>needs no certificates</b>: an <b>identifier (ID)</b> such as an e-mail address, phone number or employee number is itself the public key, and the key center derives each user's private key from the master private key. This tool is powered by <b>GmSSL (C) compiled to WebAssembly</b> and interoperates with the GmSSL CLI / SDK.</p>
</blockquote>
<h2>Key hierarchy</h2>
<ul>
<li><p><b>Encryption (SM9-Enc)</b> and <b>signature (SM9-Sign)</b> use two <b>independent</b> master key pairs and must not be mixed</p></li>
<li><p><b>Master private key (msk)</b>: generated by the key center and kept strictly secret (DER HEX); <b>master public key (mpk)</b>: derived from it and publicly distributable (uncompressed point HEX)</p></li>
<li><p><b>User private key (usk)</b>: derived from "master private key + ID" and handed to the owner of that ID; used for decryption / signing</p></li>
<li><p>Formats: encryption master public key <b>65 bytes</b> (04‖X‖Y), signature master public key <b>129 bytes</b>; master and user private keys use GmSSL DER encoding</p></li>
</ul>
<h2>Workflow</h2>
<ul>
<li><p><b>Key generation</b>: set the user ID → generate the master key pair → export the master public key (distribute it) → extract the user private key (deliver it to that ID's owner)</p></li>
<li><p><b>Encryption</b>: the sender needs the <b>recipient's master public key + ID</b>; one group of plaintext is limited to <b>255 bytes</b>; the output is DER HEX ciphertext</p></li>
<li><p><b>Decryption</b>: the recipient uses <b>their own user private key + ID</b>; a mismatching ID fails decryption (the C3 HMAC-SM3 tag is verified)</p></li>
<li><p><b>Signature / verification</b>: sign with the signature user private key; verification only needs the <b>signer's master public key + signer ID + data + signature</b></p></li>
<li><p>All four tabs <b>share one key set</b> and ID; "Save as default keys" stores them only in your browser (localStorage) — nothing is uploaded</p></li>
</ul>
<h2>Data formats</h2>
<ul>
<li><p>The UI uses <b>HEX</b> for keys and ciphertext throughout; spaces / line breaks are allowed when pasting</p></li>
<li><p>Ciphertext DER: <code>SEQUENCE { INTEGER(0), BIT STRING(C1 65B), OCTET STRING(C3 32B), OCTET STRING(C2) }</code> (XOR mode, identical to GmSSL's <code>sm9_ciphertext_to_der</code>)</p></li>
<li><p>Signature DER: <code>SEQUENCE { OCTET STRING(h 32B), BIT STRING(S 65B) }</code>, <b>104 bytes</b> in total</p></li>
<li><p>A signature and an encryption master private key are both 104 bytes, but their first element tag differs (<code>OCTET STRING</code> vs <code>INTEGER</code>); the tool detects the type and shows it below the input box</p></li>
<li><p>Plaintext is processed as UTF-8, so sizes are counted in UTF-8 bytes (one Chinese character = 3 bytes)</p></li>
</ul>
<h2>Security note</h2>
<blockquote><p>Never leak master or user private keys. All computation happens locally in your browser (WebAssembly); keys are never uploaded. Key generation needs a secure random source — outside HTTPS/localhost browsers disable <code>crypto.getRandomValues</code> and this tool fails loudly instead of using weak randomness (use the desktop build or the GitHub Pages version when HTTPS is unavailable).</p>
</blockquote>
`;

const Intro = () => {
  const { locale } = useLocale();
  return <div dangerouslySetInnerHTML={ { __html: locale === 'zh-TW' ? introTw : locale === 'en' ? introEn : introZh } } />;
}
export default Intro;
