// SM9Crypto 语言包: 名称 (zh-CN = define.tsx AppName 默认; 缺省回退 zh-CN)
export default {
  default: 'zh-CN',
  en: { appName: "SM9 Encrypt / Decrypt" },
} as const;

// 界面文案词条 (zh 短语即 key; 缺 zh-CN 时回退原文)
const cryptolangRows: Record<string, [string, string]> = {
  '双击复制内容到粘贴板': ['雙擊複製內容到剪貼簿', 'Double-click to copy'],
  // ---- 通用 ----
  '{tip} 已复制到粘贴板': ['{tip} 已複製到剪貼簿', '{tip} copied to clipboard'],
  '内容': ['內容', 'content'],
  '明文': ['明文', 'plaintext'],
  '密文': ['密文', 'ciphertext'],
  '数据': ['資料', 'data'],
  '主私钥': ['主私鑰', 'master private key'],
  '主公钥': ['主公鑰', 'master public key'],
  '用户私钥': ['使用者私鑰', 'user private key'],
  '加密主私钥': ['加密主私鑰', 'encryption master private key'],
  '签名主私钥': ['簽章主私鑰', 'signature master private key'],
  '加密主公钥': ['加密主公鑰', 'encryption master public key'],
  '签名主公钥': ['簽章主公鑰', 'signature master public key'],
  '签名值': ['簽章值', 'signature value'],
  '没有可导出的内容, 请先生成': ['沒有可匯出的內容, 請先產生', 'Nothing to export — generate something first'],
  '保存密钥文件': ['儲存金鑰檔案', 'Save key file'],
  '保存文件': ['儲存檔案', 'Save file'],
  '已保存到文件': ['已儲存到檔案', 'Saved to file'],
  '操作失败: {m}': ['操作失敗: {m}', 'Operation failed: {m}'],
  '请先填写{name}': ['請先填寫{name}', 'Please fill in {name} first'],
  '{name}: {m}': ['{name}: {m}', '{name}: {m}'],
  '示例': ['範例', 'Sample'],
  // ---- 数据类型识别 ----
  '识别为: {label} ({n} 字节)': ['識別為: {label} ({n} 位元組)', 'Detected: {label} ({n} bytes)'],
  '无法识别为 SM9 数据 ({n} 字节)': ['無法識別為 SM9 資料 ({n} 位元組)', 'Not recognized as SM9 data ({n} bytes)'],
  'SM9-Enc 主私钥': ['SM9-Enc 主私鑰', 'SM9-Enc master private key'],
  'SM9-Sign 主私钥': ['SM9-Sign 主私鑰', 'SM9-Sign master private key'],
  'SM9-Enc 用户私钥': ['SM9-Enc 使用者私鑰', 'SM9-Enc user private key'],
  'SM9-Sign 用户私钥': ['SM9-Sign 使用者私鑰', 'SM9-Sign user private key'],
  'SM9-Enc 主公钥': ['SM9-Enc 主公鑰', 'SM9-Enc master public key'],
  'SM9-Sign 主公钥': ['SM9-Sign 主公鑰', 'SM9-Sign master public key'],
  'SM9 密文 (DER)': ['SM9 密文 (DER)', 'SM9 ciphertext (DER)'],
  'SM9 签名值 (DER)': ['SM9 簽章值 (DER)', 'SM9 signature (DER)'],
  '未识别': ['未識別', 'Unrecognized'],
  // ---- 错误 ----
  'HEX 长度需为偶数': ['HEX 長度需為偶數', 'HEX length must be even'],
  '内容不是合法的十六进制 (HEX)': ['內容不是合法的十六進位 (HEX)', 'Content is not valid hexadecimal (HEX)'],
  '内容含非十六进制字符': ['內容含非十六進位字元', 'Content contains non-hex characters'],
  'SM9 运算失败: 密钥/ID/数据不匹配或参数不合法 ({what})': ['SM9 運算失敗: 金鑰/ID/資料不匹配或參數不合法 ({what})', 'SM9 operation failed: key/ID/data mismatch or invalid parameters ({what})'],
  '生成加密主密钥': ['產生加密主金鑰', 'generate encryption master key'],
  '导出加密主公钥': ['匯出加密主公鑰', 'export encryption master public key'],
  '提取加密用户私钥': ['提取加密使用者私鑰', 'extract encryption user private key'],
  '生成签名主密钥': ['產生簽章主金鑰', 'generate signature master key'],
  '导出签名主公钥': ['匯出簽章主公鑰', 'export signature master public key'],
  '提取签名用户私钥': ['提取簽章使用者私鑰', 'extract signature user private key'],
  '当前环境不支持 crypto.getRandomValues (需要 HTTPS 或 localhost), 无法安全生成密钥': ['目前環境不支援 crypto.getRandomValues (需要 HTTPS 或 localhost), 無法安全產生金鑰', 'This environment lacks crypto.getRandomValues (HTTPS or localhost required) — refusing to generate keys insecurely'],
  'SM9 引擎 (WebAssembly) 加载失败': ['SM9 引擎 (WebAssembly) 載入失敗', 'Failed to load the SM9 engine (WebAssembly)'],
  '重试': ['重試', 'Retry'],
  // ---- 密钥生成页 ----
  '密钥生成': ['金鑰產生', 'Key generation'],
  '加密': ['加密', 'Encrypt'],
  '解密': ['解密', 'Decrypt'],
  '签名': ['簽章', 'Signature'],
  '签名验签': ['簽章驗章', 'Sign / Verify'],
  'SM9 是标识密码 (IBC): 主公钥/主私钥由密钥中心生成, 用户私钥由「主私钥 + ID」提取。': ['SM9 是識別密碼 (IBC): 主公鑰/主私鑰由金鑰中心產生, 使用者私鑰由「主私鑰 + ID」提取。', 'SM9 is identity-based cryptography (IBC): the key center generates the master key pair, and a user private key is extracted from the master private key plus the ID.'],
  '加密与签名是两套独立的主密钥 (SM9-Enc / SM9-Sign), 不能混用; 发送方只需主公钥与接收方 ID, 接收方用自己的用户私钥解密。': ['加密與簽章是兩套獨立的主金鑰 (SM9-Enc / SM9-Sign), 不能混用; 傳送方只需主公鑰與接收方 ID, 接收方用自己的使用者私鑰解密。', 'Encryption and signature use two independent master key pairs (SM9-Enc / SM9-Sign) that must not be mixed. The sender needs only the master public key and the recipient ID; the recipient decrypts with their own user private key.'],
  '用户 ID': ['使用者 ID', 'User ID'],
  '例如 alice@example.com (UTF-8, 建议不超过 64 字节)': ['例如 alice@example.com (UTF-8, 建議不超過 64 位元組)', 'e.g. alice@example.com (UTF-8, 64 bytes or fewer recommended)'],
  '当前 ID 长度: {n} 字节': ['目前 ID 長度: {n} 位元組', 'Current ID length: {n} bytes'],
  '保存为默认密钥': ['儲存為預設金鑰', 'Save as default keys'],
  '清空默认密钥': ['清空預設金鑰', 'Clear default keys'],
  '默认密钥只保存在浏览器本地 (localStorage), 不会上传; 四个标签页共享同一组密钥, 解密/签名用的用户私钥必须是同一 ID 提取的。': ['預設金鑰只儲存在瀏覽器本機 (localStorage), 不會上傳; 四個頁籤共用同一組金鑰, 解密/簽章用的使用者私鑰必須由同一 ID 提取。', 'Default keys are stored only in your browser (localStorage) and are never uploaded. All four tabs share one key set, and the user private key used for decryption/signing must have been extracted from the same ID.'],
  '{label}主密钥 (SM9-{alg})': ['{label}主金鑰 (SM9-{alg})', '{label} master key (SM9-{alg})'],
  ' 用于加密 / 解密': [' 用於加密 / 解密', ' for encryption / decryption'],
  ' 用于签名 / 验签': [' 用於簽章 / 驗章', ' for signing / verification'],
  '生成主密钥对': ['產生主金鑰對', 'Generate master key pair'],
  '导出主公钥': ['匯出主公鑰', 'Export master public key'],
  '提取用户私钥 (按上方 ID)': ['提取使用者私鑰 (依上方 ID)', 'Extract user private key (using the ID above)'],
  '主私钥 (DER HEX, 请保密)': ['主私鑰 (DER HEX, 請保密)', 'Master private key (DER HEX, keep secret)'],
  '生成后自动填充; 也可粘贴其他工具导出的主私钥 (DER HEX)': ['產生後自動填入; 也可貼上其他工具匯出的主私鑰 (DER HEX)', 'Filled in automatically after generation; you can also paste a master private key exported by other tools (DER HEX)'],
  '主公钥 (未压缩点 HEX, 可公开)': ['主公鑰 (未壓縮點 HEX, 可公開)', 'Master public key (uncompressed point HEX, public)'],
  '点「导出主公钥」得到 (04 开头 65 字节); 可粘贴他人的主公钥用于加密': ['點「匯出主公鑰」取得 (04 開頭 65 位元組); 可貼上他人的主公鑰用於加密', 'Click "Export master public key" to get it (65 bytes, starting with 04); you can paste another party master public key to encrypt'],
  '点「导出主公钥」得到 (04 开头 129 字节); 可粘贴他人的主公钥用于验签': ['點「匯出主公鑰」取得 (04 開頭 129 位元組); 可貼上他人的主公鑰用於驗章', 'Click "Export master public key" to get it (129 bytes, starting with 04); you can paste another party master public key to verify'],
  '用户私钥 (DER HEX, 按 ID 提取, 请保密)': ['使用者私鑰 (DER HEX, 依 ID 提取, 請保密)', 'User private key (DER HEX, extracted per ID, keep secret)'],
  '输入 ID 后点「提取用户私钥」得到; 解密 / 签名时需要它': ['輸入 ID 後點「提取使用者私鑰」取得; 解密 / 簽章時需要它', 'Fill in the ID and click "Extract user private key"; decryption / signing needs it'],
  '复制主私钥': ['複製主私鑰', 'Copy master private key'],
  '复制主公钥': ['複製主公鑰', 'Copy master public key'],
  '复制用户私钥': ['複製使用者私鑰', 'Copy user private key'],
  '复制密文': ['複製密文', 'Copy ciphertext'],
  '复制明文': ['複製明文', 'Copy plaintext'],
  '导出主私钥': ['匯出主私鑰', 'Export master private key'],
  '导出用户私钥': ['匯出使用者私鑰', 'Export user private key'],
  '导出密文': ['匯出密文', 'Export ciphertext'],
  'SM9 加密主密钥生成成功, 请再导出主公钥 / 提取用户私钥': ['SM9 加密主金鑰產生成功, 請再匯出主公鑰 / 提取使用者私鑰', 'SM9 encryption master key generated — now export the master public key / extract a user private key'],
  'SM9 签名主密钥生成成功, 请再导出主公钥 / 提取用户私钥': ['SM9 簽章主金鑰產生成功, 請再匯出主公鑰 / 提取使用者私鑰', 'SM9 signature master key generated — now export the master public key / extract a user private key'],
  '主公钥导出成功 (可公开分发, 加密/验签只需主公钥)': ['主公鑰匯出成功 (可公開分發, 加密/驗章只需主公鑰)', 'Master public key exported (distributable; encryption / verification needs only the master public key)'],
  '请先填写用户 ID': ['請先填寫使用者 ID', 'Please fill in the user ID first'],
  '用户私钥提取成功 (ID: {id})': ['使用者私鑰提取成功 (ID: {id})', 'User private key extracted (ID: {id})'],
  '已保存为默认密钥与 ID (下次打开自动填充)': ['已儲存為預設金鑰與 ID (下次開啟自動填入)', 'Saved as default keys and ID (auto-filled next time)'],
  '已清空默认密钥': ['已清空預設金鑰', 'Default keys cleared'],
  // ---- 加密页 ----
  '加密只需接收方的主公钥与 ID; 主公钥留空时使用上方「加密主私钥」加密 (效果相同)。': ['加密只需接收方的主公鑰與 ID; 主公鑰留空時使用上方「加密主私鑰」加密 (效果相同)。', 'Encryption needs only the recipient master public key and ID; when the master public key is empty, the encryption master private key above is used instead (same result).'],
  '加密主公钥 (65 字节 HEX)': ['加密主公鑰 (65 位元組 HEX)', 'Encryption master public key (65 bytes HEX)'],
  '04 开头 130 位 HEX; 留空则用「加密主私钥」加密': ['04 開頭 130 位 HEX; 留空則用「加密主私鑰」加密', '130 HEX digits starting with 04; leave empty to encrypt with the encryption master private key'],
  '明文 (UTF-8, 单组上限 255 字节)': ['明文 (UTF-8, 單組上限 255 位元組)', 'Plaintext (UTF-8, max 255 bytes per group)'],
  '输入需要加密的明文  或 拖拽文件到框内打开': ['輸入需要加密的明文  或 拖曳檔案到框內開啟', 'Enter plaintext to encrypt, or drag a file into the box'],
  '当前 {n} / 255 字节': ['目前 {n} / 255 位元組', 'Current {n} / 255 bytes'],
  'SM9 示例明文': ['SM9 範例明文', 'SM9 sample plaintext'],
  '请输入需要加密的明文': ['請輸入需要加密的明文', 'Enter the plaintext to encrypt'],
  'SM9 单组明文上限为 255 字节, 当前 {n} 字节, 请分段加密': ['SM9 單組明文上限為 255 位元組, 目前 {n} 位元組, 請分段加密', 'One SM9 plaintext group is limited to 255 bytes (currently {n} bytes) — please split it into groups'],
  '请先填写用户 ID (需与接收方解密时一致)': ['請先填寫使用者 ID (需與接收方解密時一致)', 'Please fill in the user ID (it must match the one used for decryption)'],
  '未配置加密主公钥/主私钥, 请先在「密钥生成」页生成或粘贴': ['未設定加密主公鑰/主私鑰, 請先在「金鑰產生」頁產生或貼上', 'No encryption master public/private key configured — generate or paste one on the Key generation tab first'],
  '加密成功 (密文为 DER HEX, 可发给接收方)': ['加密成功 (密文為 DER HEX, 可傳給接收方)', 'Encrypted (ciphertext is DER HEX and can be sent to the recipient)'],
  '清空明文': ['清空明文', 'Clear plaintext'],
  '密文 (DER HEX)': ['密文 (DER HEX)', 'Ciphertext (DER HEX)'],
  '加密后自动显示在此; 可粘贴密文用于「解密」页': ['加密後自動顯示在此; 可貼上密文用於「解密」頁', 'Shown here after encryption; paste ciphertext here to use the Decrypt tab'],
  // ---- 解密页 ----
  '解密需要「用户私钥」与加密时相同的 ID; 用户私钥由接收方从主私钥提取 (见「密钥生成」页)。': ['解密需要「使用者私鑰」與加密時相同的 ID; 使用者私鑰由接收方從主私鑰提取 (見「金鑰產生」頁)。', 'Decryption needs a user private key and the same ID used for encryption; the user private key is extracted by the recipient from the master private key (see the Key generation tab).'],
  '加密用户私钥 (DER HEX)': ['加密使用者私鑰 (DER HEX)', 'Encryption user private key (DER HEX)'],
  '粘贴用户私钥 (DER HEX), 或在上方「密钥生成」页提取': ['貼上使用者私鑰 (DER HEX), 或在上方「金鑰產生」頁提取', 'Paste a user private key (DER HEX), or extract one on the Key generation tab'],
  '请先填写用户 ID (需与加密时一致)': ['請先填寫使用者 ID (需與加密時一致)', 'Please fill in the user ID (it must match the one used for encryption)'],
  '粘贴密文 (DER HEX)  或 拖拽文件到框内打开': ['貼上密文 (DER HEX)  或 拖曳檔案到框內開啟', 'Paste ciphertext (DER HEX), or drag a file into the box'],
  '清除': ['清除', 'Clear'],
  '明文 (非文本内容按 HEX 显示)': ['明文 (非文字內容以 HEX 顯示)', 'Plaintext (non-text content is shown as HEX)'],
  '解密后自动显示在此': ['解密後自動顯示在此', 'Shown here after decryption'],
  '解密成功': ['解密成功', 'Decrypted'],
  // ---- 签名验签页 ----
  '签名用「签名用户私钥」(与签名者 ID 绑定), 验签只需签名者主公钥 + ID + 数据 + 签名值。': ['簽章用「簽章使用者私鑰」(與簽章者 ID 綁定), 驗章只需簽章者主公鑰 + ID + 資料 + 簽章值。', 'Sign with the signature user private key (bound to the signer ID); verification needs only the signer master public key + ID + data + signature.'],
  '签名用户私钥 (DER HEX)': ['簽章使用者私鑰 (DER HEX)', 'Signature user private key (DER HEX)'],
  '粘贴签名用户私钥 (DER HEX), 或在上方「密钥生成」页提取': ['貼上簽章使用者私鑰 (DER HEX), 或在上方「金鑰產生」頁提取', 'Paste a signature user private key (DER HEX), or extract one on the Key generation tab'],
  '数据 (待签名 / 待验签, UTF-8)': ['資料 (待簽章 / 待驗章, UTF-8)', 'Data (to sign / to verify, UTF-8)'],
  '输入数据  或 拖拽文件到框内打开 (签名与验签使用同一数据)': ['輸入資料  或 拖曳檔案到框內開啟 (簽章與驗章使用同一資料)', 'Enter data, or drag a file into the box (signing and verification use the same data)'],
  'SM9 示例签名数据': ['SM9 範例簽章資料', 'SM9 sample signing data'],
  '请输入需要签名的数据': ['請輸入需要簽章的資料', 'Enter the data to sign'],
  '签名 (用户私钥)': ['簽章 (使用者私鑰)', 'Sign (user private key)'],
  '签名成功 (签名值为 DER HEX)': ['簽章成功 (簽章值為 DER HEX)', 'Signed (the signature is DER HEX)'],
  '签名值 (DER HEX)': ['簽章值 (DER HEX)', 'Signature (DER HEX)'],
  '签名后自动显示在此; 也可粘贴他人给的签名值用于验签': ['簽章後自動顯示在此; 也可貼上他人給的簽章值用於驗章', 'Shown here after signing; you can also paste a signature received from someone else to verify'],
  '签名主公钥 (129 字节 HEX)': ['簽章主公鑰 (129 位元組 HEX)', 'Signature master public key (129 bytes HEX)'],
  '04 开头 258 位 HEX; 留空则用「签名主私钥」验签': ['04 開頭 258 位 HEX; 留空則用「簽章主私鑰」驗章', '258 HEX digits starting with 04; leave empty to verify with the signature master private key'],
  '签名者 ID': ['簽章者 ID', 'Signer ID'],
  '验签 (主公钥 + ID)': ['驗章 (主公鑰 + ID)', 'Verify (master public key + ID)'],
  '验签通过': ['驗章通過', 'Verified'],
  '验签失败': ['驗章失敗', 'Verification failed'],
  '请输入需要验签的数据': ['請輸入需要驗章的資料', 'Enter the data to verify'],
  '请先填写签名者 ID': ['請先填寫簽章者 ID', 'Please fill in the signer ID first'],
  '未配置签名主公钥/主私钥, 请先在「密钥生成」页生成或粘贴': ['未設定簽章主公鑰/主私鑰, 請先在「金鑰產生」頁產生或貼上', 'No signature master public/private key configured — generate or paste one on the Key generation tab first'],
  '验签通过: 签名有效且数据未被篡改': ['驗章通過: 簽章有效且資料未被竄改', 'Verification passed: the signature is valid and the data is intact'],
  '验签失败: 签名/数据/ID/主公钥不匹配': ['驗章失敗: 簽章/資料/ID/主公鑰不匹配', 'Verification failed: signature / data / ID / master public key mismatch'],
  ' SM9 说明 ': [' SM9 說明 ', ' SM9 notes '],
  // ---- 设置页 ----
  'SM9 加解密': ['SM9 加解密', 'SM9 Encrypt / Decrypt'],
  '默认用户 ID': ['預設使用者 ID', 'Default user ID'],
  '例如 alice@example.com; 解密/验签需与加密/签名时一致': ['例如 alice@example.com; 解密/驗章需與加密/簽章時一致', 'e.g. alice@example.com; decryption / verification must use the same ID as encryption / signing'],
  '默认加密主私钥 (DER HEX)': ['預設加密主私鑰 (DER HEX)', 'Default encryption master private key (DER HEX)'],
  '用于导出主公钥与提取用户私钥; 留空表示不配置': ['用於匯出主公鑰與提取使用者私鑰; 留空表示不設定', 'Used to export the master public key and extract user private keys; leave empty to skip'],
  '默认加密用户私钥 (DER HEX)': ['預設加密使用者私鑰 (DER HEX)', 'Default encryption user private key (DER HEX)'],
  'SM9 页「解密」使用; 留空表示不配置': ['SM9 頁「解密」使用; 留空表示不設定', 'Used by the Decrypt tab of the SM9 page; leave empty to skip'],
  '默认签名主私钥 (DER HEX)': ['預設簽章主私鑰 (DER HEX)', 'Default signature master private key (DER HEX)'],
  '用于导出签名主公钥; 留空表示不配置': ['用於匯出簽章主公鑰; 留空表示不設定', 'Used to export the signature master public key; leave empty to skip'],
  '默认签名用户私钥 (DER HEX)': ['預設簽章使用者私鑰 (DER HEX)', 'Default signature user private key (DER HEX)'],
  'SM9 页「签名验签」使用; 留空表示不配置': ['SM9 頁「簽章驗章」使用; 留空表示不設定', 'Used by the Sign / Verify tab of the SM9 page; leave empty to skip'],
  '默认密钥保存在浏览器本地, 打开 SM9 页会自动带出': ['預設金鑰儲存在瀏覽器本機, 開啟 SM9 頁會自動帶出', 'Default keys are stored in your browser and loaded automatically when the SM9 page opens'],
};

// 取词: 无命中回退 zh 原文 (与共享 crypto-lang 行为一致)
export const sr = (locale: string, zh: string): string => {
  const e = cryptolangRows[zh];
  if (!e) return zh;
  return locale === 'zh-TW' ? e[0] : locale === 'en' ? e[1] : zh;
};
export const srT = (locale: string, zh: string, v?: Record<string, string | number>): string => {
  let s = sr(locale, zh);
  if (v) for (const [k, val] of Object.entries(v)) s = s.split('{'+k+'}').join(String(val));
  return s;
};
export const srErr = (locale: string, m: string): string => {
  let mm: RegExpExecArray | null;
  if ((mm = /^SM9 运算失败: 密钥\/ID\/数据不匹配或参数不合法 \((.+)\)$/.exec(m)))
    return srT(locale, 'SM9 运算失败: 密钥/ID/数据不匹配或参数不合法 ({what})', { what: sr(locale, mm[1]) });
  return sr(locale, m);
};
