// NumberConvert 语言包 (默认 zh-CN; 缺失词条回退默认语言)
// 面板交互文案 (按需扩展); 说明性长文 (tips/intro/算法说明) 暂保留简中, 后续批次再翻
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= '进制转换')
    clear: '清除',
    copyOk: '复制到粘贴板成功！！！',
    formatErr: '输入的数据格式错误!!!',
    upperLabel: '大写字符显示',
    groupedLabel: '结果插入空格',
    unit_BIN: '二进制',
    unit_OCT: '八进制',
    unit_DEC: '十进制',
    unit_HEX: '十六进制',
    ph_BIN: '输入只包含 0-1 的字符串',
    ph_OCT: '输入只包含 0-7 的字符串',
    ph_DEC: '输入只包含 0-9 的字符串',
    ph_HEX: '输入只包含 0-9 A-F 的字符串',
  },
  'zh-TW': {
    appName: '進制轉換',
    clear: '清除',
    copyOk: '複製到剪貼簿成功！！！',
    formatErr: '輸入的資料格式錯誤!!!',
    upperLabel: '大寫字元顯示',
    groupedLabel: '結果插入空格',
    unit_BIN: '二進位',
    unit_OCT: '八進位',
    unit_DEC: '十進位',
    unit_HEX: '十六進位',
    ph_BIN: '請輸入只包含 0-1 的字串',
    ph_OCT: '請輸入只包含 0-7 的字串',
    ph_DEC: '請輸入只包含 0-9 的字串',
    ph_HEX: '請輸入只包含 0-9 A-F 的字串',
  },
  en: {
    appName: 'Number Base Converter',
    clear: 'Clear',
    copyOk: 'Copied to clipboard!',
    formatErr: 'Invalid input format!',
    upperLabel: 'Uppercase output',
    groupedLabel: 'Group digits with spaces',
    unit_BIN: 'Binary',
    unit_OCT: 'Octal',
    unit_DEC: 'Decimal',
    unit_HEX: 'Hexadecimal',
    ph_BIN: 'Enter a string containing only 0-1',
    ph_OCT: 'Enter a string containing only 0-7',
    ph_DEC: 'Enter a string containing only 0-9',
    ph_HEX: 'Enter a string containing only 0-9 A-F',
  },
} as const;
