// 说明性长文 (data.ts 内单位注释文档) 暂保留简中, 后续批次再翻
export default {
  default: 'zh-CN',
  'zh-CN': {
    clear: '清除',
    copyOk: '复制到粘贴板成功！！！',
    ut_ms: '公制',
    ut_iu: '英制',
    ut_cn: '市制',
    u_kt: '千吨', u_t: '吨', u_kg: '千克', u_g: '克', u_mg: '毫克', u_mcg: '微克', u_ng: '纳克', u_ct: '克拉',
    u_oz: '盎司', u_lb: '磅', u_st: '英石', u_gr: '格令', u_dr: '打兰', u_qr: '夸特', u_hw: '英担', u_md: '美担', u_longton: '英吨', u_shortton: '美吨',
    u_dan: '担', u_jin: '斤', u_liang: '两', u_qian: '钱', u_fen: '分', u_li: '厘',
    r_kt: '千吨(kt)', r_t: '吨(t)', r_kg: '千克(kg)', r_g: '克(g)', r_mg: '毫克(mg)', r_ug: '微克(μg)', r_ng: '纳克(ng)', r_ct: '克拉(ct)',
    r_oz: '盎司(ounce)', r_lb: '磅(pound)', r_st: '英石(stone)', r_gr: '格令(grain)', r_dr: '打兰(drachm)', r_qr: '夸特(quarter)', r_hw: '英担', r_md: '美担', r_lt: '英吨(long ton)', r_stn: '美吨(short ton)',
    r_dan: '担', r_jin: '斤', r_liang: '两', r_qian: '钱', r_fen: '分', r_li: '厘',
    p_kt: 'kilo ton', p_t: 'ton', p_kg: 'kilo gram', p_g: 'gram', p_mg: 'milligram', p_mcg: 'micro gram', p_ng: 'nanogram',
    p_ct: '钻石的质量（重量）单位，现定1克拉等于0.2克或200毫克',
    p_oz: '1 盎司 = 1/16 磅（pound）= 28.349523125 克',
    p_lb: '1 磅 = 7000 格令 = 453.59237 克',
    p_st: '1 英石（stone）= 14 磅 = 6.35029318 千克',
    p_gr: '1 格令（grain）= 64.79891 毫克',
    p_dr: '1 打兰（drachm）= 1/16 盎司（ounce） = 1.77 克',
    p_qr: '1 夸特（quarter）= 2 英石 = 28 磅 = 12.7 千克',
    p_hw: '1 英担（hundredweight）= 4 夸特 = 112 磅 = 50.8 千克',
    p_md: '1 美担 = 45.359237 千克',
    p_longton: '1 英吨（ton）= 20 英担 = 2240 磅 = 1016 千克 英吨（长吨long ton）是2240磅',
    p_shortton: '美吨（短吨short ton）是2000磅（907千克）',
  },
  'zh-TW': {
    appName: '重量轉換',
    clear: '清除',
    copyOk: '複製到剪貼簿成功！！！',
    ut_ms: '公制',
    ut_iu: '英制',
    ut_cn: '市制',
    u_kt: '千噸', u_t: '噸', u_kg: '公斤', u_g: '公克', u_mg: '毫克', u_mcg: '微克', u_ng: '奈克', u_ct: '克拉',
    u_oz: '盎司', u_lb: '磅', u_st: '英石', u_gr: '格令', u_dr: '打蘭', u_qr: '夸特', u_hw: '英擔', u_md: '美擔', u_longton: '英噸', u_shortton: '美噸',
    u_dan: '擔', u_jin: '斤', u_liang: '兩', u_qian: '錢', u_fen: '分', u_li: '釐',
    r_kt: '千噸 (kt)', r_t: '噸 (t)', r_kg: '公斤 (kg)', r_g: '公克 (g)', r_mg: '毫克 (mg)', r_ug: '微克 (μg)', r_ng: '奈克 (ng)', r_ct: '克拉 (ct)',
    r_oz: '盎司 (ounce)', r_lb: '磅 (pound)', r_st: '英石 (stone)', r_gr: '格令 (grain)', r_dr: '打蘭 (drachm)', r_qr: '夸特 (quarter)', r_hw: '英擔', r_md: '美擔', r_lt: '英噸 (long ton)', r_stn: '美噸 (short ton)',
    r_dan: '擔', r_jin: '斤', r_liang: '兩', r_qian: '錢', r_fen: '分', r_li: '釐',
    p_kt: '千噸', p_t: '噸', p_kg: '公斤', p_g: '公克', p_mg: '毫克', p_mcg: '微克', p_ng: '奈克',
    p_ct: '鑽石的質量（重量）單位，現定 1 克拉等於 0.2 克或 200 毫克',
    p_oz: '1 盎司 = 1/16 磅 (pound) = 28.349523125 公克',
    p_lb: '1 磅 = 7000 格令 = 453.59237 公克',
    p_st: '1 英石 (stone) = 14 磅 = 6.35029318 公斤',
    p_gr: '1 格令 (grain) = 64.79891 毫克',
    p_dr: '1 打蘭 (drachm) = 1/16 盎司 (ounce) = 1.77 公克',
    p_qr: '1 夸特 (quarter) = 2 英石 = 28 磅 = 12.7 公斤',
    p_hw: '1 英擔 (hundredweight) = 4 夸特 = 112 磅 = 50.8 公斤',
    p_md: '1 美擔 = 45.359237 公斤',
    p_longton: '1 英噸 = 20 英擔 = 2240 磅 = 1016 公斤；英噸（長噸 long ton）是 2240 磅',
    p_shortton: '美噸（短噸 short ton）是 2000 磅（907 公斤）',
  },
  en: {
    appName: 'Weight Converter',
    clear: 'Clear',
    copyOk: 'Copied to clipboard!!!',
    ut_ms: 'Metric',
    ut_iu: 'Imperial',
    ut_cn: 'Chinese',
    u_kt: 'Kilotonne', u_t: 'Tonne', u_kg: 'Kilogram', u_g: 'Gram', u_mg: 'Milligram', u_mcg: 'Microgram', u_ng: 'Nanogram', u_ct: 'Carat',
    u_oz: 'Ounce', u_lb: 'Pound', u_st: 'Stone', u_gr: 'Grain', u_dr: 'Dram', u_qr: 'Quarter', u_hw: 'Hundredweight', u_md: 'US hundredweight', u_longton: 'Long ton', u_shortton: 'Short ton',
    u_dan: 'Dan', u_jin: 'Jin', u_liang: 'Liang', u_qian: 'Qian', u_fen: 'Fen', u_li: 'Li',
    r_kt: 'Kilotonne (kt)', r_t: 'Tonne (t)', r_kg: 'Kilogram (kg)', r_g: 'Gram (g)', r_mg: 'Milligram (mg)', r_ug: 'Microgram (μg)', r_ng: 'Nanogram (ng)', r_ct: 'Carat (ct)',
    r_oz: 'Ounce (oz)', r_lb: 'Pound (lb)', r_st: 'Stone (st)', r_gr: 'Grain (gr)', r_dr: 'Dram (dr)', r_qr: 'Quarter (qr)', r_hw: 'Hundredweight', r_md: 'US hundredweight', r_lt: 'Long ton', r_stn: 'Short ton',
    r_dan: 'Dan', r_jin: 'Jin', r_liang: 'Liang', r_qian: 'Qian', r_fen: 'Fen', r_li: 'Li',
    p_kt: 'Kilotonne', p_t: 'Tonne', p_kg: 'Kilogram', p_g: 'Gram', p_mg: 'Milligram', p_mcg: 'Microgram', p_ng: 'Nanogram',
    p_ct: 'Unit of mass for gemstones: 1 carat = 0.2 g (200 mg)',
    p_oz: '1 oz = 1/16 lb = 28.349523125 g',
    p_lb: '1 lb = 7000 grains = 453.59237 g',
    p_st: '1 stone = 14 lb = 6.35029318 kg',
    p_gr: '1 grain = 64.79891 mg',
    p_dr: '1 dram = 1/16 ounce = 1.77 g',
    p_qr: '1 quarter = 2 stone = 28 lb = 12.7 kg',
    p_hw: '1 hundredweight = 4 quarters = 112 lb = 50.8 kg',
    p_md: '1 US hundredweight = 45.359237 kg',
    p_longton: '1 long ton = 20 hundredweight = 2240 lb = 1016 kg',
    p_shortton: '1 short ton = 2000 lb (907 kg)',
  },
} as const;
