// PasswordGenerator 语言包: 名称 (zh-CN = define.tsx AppName 默认; 缺省回退 zh-CN)
export default {
  default: 'zh-CN',
  'zh-TW': { appName: "密碼生成" },
  en: { appName: "Password Generator" },
} as const;

// 界面文案词条 (zh 短语即 key; 缺 zh-CN 时回退原文)
const uilangRows: Record<string, [string, string]> = {
  '已复制': ['已複製', 'Copied'],
  '清空': ['清空', 'Clear'],
  '复制': ['複製', 'Copy'],
  '格式化': ['格式化', 'Format'],
  '读': ['讀', 'Read'],
  '写': ['寫', 'Write'],
  '数值': ['數值', 'Numeric'],
  '符号': ['符號', 'Symbols'],
  '数字': ['數字', 'Numeric'],
  '(bit)': ['(bit)', '(bit)'],
  '6 位': ['6 位', '6 digits'],
  '高': ['高', 'Height'],
  'px': ['px', 'px'],
  '输入或生成一个密码后显示强度评估': ['輸入或產生一個密碼後顯示強度評估', 'Type or generate a password to see its strength'],
  '强度:': ['強度:', 'Strength:'],
  '参考熵:': ['參考熵:', 'Entropy:'],
  '按每秒 1 万亿次猜测约需 {t}': ['按每秒 1 兆次猜測約需 {t}', 'At 1 trillion guesses/sec it would take about {t}'],
  '在线攻击:': ['線上攻擊:', 'Online attack:'],
  '按每秒 1000 次猜测约需 {t}': ['按每秒 1000 次猜測約需 {t}', 'At 1,000 guesses/sec it would take about {t}'],
  '极弱': ['極弱', 'Very weak'],
  '弱': ['弱', 'Weak'],
  '一般': ['一般', 'Fair'],
  '强': ['強', 'Strong'],
  '极强': ['極強', 'Very strong'],
  '极易被暴力/字典破解, 请勿使用': ['極易被暴力/字典破解, 請勿使用', 'Trivially broken by brute force / dictionary attacks — do not use'],
  '容易被破解, 建议增加长度与字符类型': ['容易被破解, 建議增加長度與字元類型', 'Easy to crack — increase the length and add more character types'],
  '对普通场景可用, 敏感账户建议加强': ['對一般場景可用, 敏感帳戶建議加強', 'Fine for everyday use; strengthen it for sensitive accounts'],
  '当前配置较难被暴力破解': ['目前設定較難被暴力破解', 'Hard to brute force with the current settings'],
  '按现有算力需极长时间, 安全性很高': ['按現有算力需極長時間, 安全性很高', "Would take an extremely long time with today's hardware — very secure"],
  '长度 {n} (推荐 ≥12)': ['長度 {n} (建議 ≥12)', 'Length {n} (≥12 recommended)'],
  '大小写混合': ['大小寫混合', 'Mixed case'],
  '建议混合大小写': ['建議混合大小寫', 'Use mixed case'],
  '包含数字': ['包含數字', 'Has digits'],
  '建议包含数字': ['建議包含數字', 'Add digits'],
  '包含符号': ['包含符號', 'Has symbols'],
  '包含中文/符号': ['包含中文/符號', 'Has CJK / symbols'],
  '建议包含符号或中文': ['建議包含符號或中文', 'Add symbols or CJK characters'],
  '命中常见弱口令库': ['命中常見弱密碼庫', 'Hit the common-password list'],
  '未命中常见弱口令库': ['未命中常見弱密碼庫', 'Not on the common-password list'],
  '存在连续 {n} 个相同字符': ['存在連續 {n} 個相同字元', 'Has {n} identical characters in a row'],
  '无连续重复字符': ['無連續重複字元', 'No repeated-run characters'],
  '存在键盘/字母/数字连续序列': ['存在鍵盤/字母/數字連續序列', 'Has a keyboard/alphabet/digit sequence'],
  '无连续序列': ['無連續序列', 'No consecutive sequences'],
  '当前强度: ': ['目前強度: ', 'Current strength: '],
  '所有生成与强度评估均在本地完成, 密码不会离开设备; 建议长度 ≥ 12 并混合大小写、数字与符号。强度仅为启发式估算, 不能替代权威评估。': ['所有產生與強度評估均在本機完成, 密碼不會離開裝置; 建議長度 ≥ 12 並混合大小寫、數字與符號。強度僅為啟發式估算, 不能取代權威評估。', 'Generation and strength checks all run locally — the password never leaves your device. A length ≥ 12 mixing upper/lower case, digits and symbols is recommended. Strength is only a heuristic estimate, not a substitute for authoritative evaluation.'],
  '生成': ['產生', 'Generate'],
  '长度:': ['長度:', 'Length:'],
  '字符集:': ['字元集:', 'Character set:'],
  '大写 A-Z': ['大寫 A-Z', 'Uppercase A-Z'],
  '小写 a-z': ['小寫 a-z', 'Lowercase a-z'],
  '数字 0-9': ['數字 0-9', 'Digits 0-9'],
  '符号 !@#…': ['符號 !@#…', 'Symbols !@#…'],
  '选项:': ['選項:', 'Options:'],
  '排除易混淆字符 (IOlo01)': ['排除易混淆字元 (IOlo01)', 'Exclude ambiguous characters (IOlo01)'],
  '生成密码': ['產生密碼', 'Generate password'],
  '点击上方按钮生成随机密码': ['點擊上方按鈕產生隨機密碼', 'Click the button above to generate a random password'],
  '请先生成或输入密码': ['請先產生或輸入密碼', 'Generate or enter a password first'],
  '已复制到剪贴板': ['已複製到剪貼簿', 'Copied to clipboard'],
  '强度检测 (支持手工输入任意密码)': ['強度檢測 (支援手動輸入任意密碼)', 'Strength check (paste any password)'],
  '在此输入或粘贴要检测的密码': ['在此輸入或貼上要檢測的密碼', 'Enter or paste a password to check'],
  '次': ['次', 'times'],
  '位': ['位', 'bits'],
  '口令': ['口令', 'Password'],
  'r:': ['r:', 'r:'],
  'p:': ['p:', 'p:'],
  '密码': ['密碼', 'Password'],
  '输入密码': ['輸入密碼', 'Enter password'],
  '字符': ['字元', 'Characters'],
  '全部': ['全部', 'All'],
  '随机': ['隨機', 'Random'],
  '标准': ['標準', 'Standard'],
  '时间': ['時間', 'Time'],
  '时长': ['時長', 'Duration'],
  '个': ['個', ''],
  '至': ['至', 'to'],
  '每': ['每', 'Every'],
  '秒': ['秒', 's'],
  '分': ['分', 'm'],
  '时': ['時', 'h'],
  '月': ['月', 'mo'],
  '年': ['年', 'y'],
  '或': ['或', 'OR'],
};

// 取词: 无命中回退 zh 原文 (与共享 ui-lang 行为一致)
export const u = (locale: string, zh: string): string => {
  const hit = uilangRows[zh];
  if (!hit) return zh;
  return locale === 'zh-TW' ? hit[0] : locale === 'en' ? hit[1] : zh;
};
export const uT = (locale: string, zhTpl: string, vars?: Record<string, string | number>): string => {
  let out = u(locale, zhTpl);
  if (vars) out = out.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));
  return out;
};

