// TemperatureConvert 语言包 (默认 zh-CN; 缺失词条回退默认语言)
// 面板交互文案 (按需扩展); 说明性长文 (tips/intro/算法说明) 暂保留简中, 后续批次再翻
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= '温度转换')
    clear: '清除',
    copyOk: '复制到粘贴板成功！！！',
    unit_c: '摄氏度 °C',
    unit_f: '华氏度 °F',
    unit_k: '开尔文 K',
    unit_r: '兰金温标 °R',
    unit_d: '德利尔温标 °D',
    unit_n: '牛顿温标 °N',
    unit_re: '列氏温标 °Ré',
    unit_ra: '罗氏温标 °Rø',
    ph_c: '在 1 标准大气压下，纯净的冰水混合物的温度为 0 °C，水的沸点为 100 °C',
    ph_f: '在标准大气压下，冰的熔点为 32 ℉，水的沸点为 212 ℉，中间有 180 等分，每等分为华氏1度',
    ph_k: '开尔文是以绝对零度作为计算起点，即 -273.15 ℃ = 0K',
    ph_r: '以绝对零度为计算起点的华氏温度',
    ph_d: '将水的沸点定于零度，然后将水银体积随温度降低收缩十万分之一定为一个间隔',
    ph_n: '0 °N 定义为雪融化的温度（水的冰点）， 33 °N 定义为水沸腾的温度（水的沸点）',
    ph_re: '水的冰点被定为列氏 0 度，而沸点则为列氏 80 度',
    ph_ra: '将水的冰点定为罗氏 7.5 度，沸点定为罗氏 60 度',
  },
  'zh-TW': {
    appName: '溫度轉換',
    clear: '清除',
    copyOk: '複製到剪貼簿成功！！！',
    unit_c: '攝氏度 °C',
    unit_f: '華氏度 °F',
    unit_k: '克耳文 K',
    unit_r: '蘭金溫標 °R',
    unit_d: '德利爾溫標 °D',
    unit_n: '牛頓溫標 °N',
    unit_re: '列氏溫標 °Ré',
    unit_ra: '羅氏溫標 °Rø',
    ph_c: '在 1 標準大氣壓下，純淨冰水混合物的溫度為 0 °C，水的沸點為 100 °C',
    ph_f: '在標準大氣壓下，冰的熔點為 32 ℉，水的沸點為 212 ℉，中間有 180 等分，每等分為華氏 1 度',
    ph_k: '克耳文是以絕對零度為計算起點，即 -273.15 ℃ = 0 K',
    ph_r: '以絕對零度為計算起點的華氏溫度',
    ph_d: '將水的沸點定於零度，然後將水銀體積隨溫度降低收縮十萬分之一定為一個間隔',
    ph_n: '0 °N 定義為雪融化的溫度（水的冰點），33 °N 定義為水沸騰的溫度（水的沸點）',
    ph_re: '水的冰點被定為列氏 0 度，而沸點則為列氏 80 度',
    ph_ra: '將水的冰點定為羅氏 7.5 度，沸點定為羅氏 60 度',
  },
  en: {
    appName: 'Temperature Converter',
    clear: 'Clear',
    copyOk: 'Copied to clipboard!',
    unit_c: 'Celsius °C',
    unit_f: 'Fahrenheit °F',
    unit_k: 'Kelvin K',
    unit_r: 'Rankine °R',
    unit_d: 'Delisle °D',
    unit_n: 'Newton °N',
    unit_re: 'Réaumur °Ré',
    unit_ra: 'Rømer °Rø',
    ph_c: 'At 1 atm, pure ice-water mixture is 0 °C and boiling water is 100 °C',
    ph_f: 'At 1 atm, ice melts at 32 ℉ and water boils at 212 ℉, divided into 180 parts of one degree Fahrenheit each',
    ph_k: 'Kelvin starts from absolute zero, i.e. -273.15 ℃ = 0 K',
    ph_r: 'A Fahrenheit-based scale starting at absolute zero',
    ph_d: 'Sets the boiling point of water to zero; each degree is 1/100,000 of the mercury contraction as temperature falls',
    ph_n: '0 °N is the temperature of melting snow (water freezing point); 33 °N is boiling water',
    ph_re: 'Water freezes at 0 °Ré and boils at 80 °Ré',
    ph_ra: 'Water freezes at 7.5 °Rø and boils at 60 °Rø',
  },
} as const;
