// ByteConvert 语言包 (默认 zh-CN; 缺失词条回退默认语言)
// 面板交互文案 (按需扩展); 说明性长文 (tips/intro/算法说明) 暂保留简中, 后续批次再翻
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= '字节转换')
    clear: '清除',
    copyOk: '复制到粘贴板成功！！！',
    divByte: '字节 ( Byte )',
    divBit: '位 ( bit )',
    ph_B: '字节 byte',
    ph_KB: '千字节 Kilo Byte',
    ph_MB: '兆字节 Mega Byte',
    ph_GB: '吉字节 Giga Byte',
    ph_TB: '太字节 Trillion Byte',
    ph_PB: '拍字节 Peta Byte',
    ph_EB: '艾字节 Exa Byte',
    ph_ZB: '泽字节 Zetta Byte',
    ph_YB: '尧字节 Yotta Byte',
  },
  'zh-TW': {
    appName: '位元組轉換',
    clear: '清除',
    copyOk: '複製到剪貼簿成功！！！',
    divByte: '位元組 ( Byte )',
    divBit: '位元 ( bit )',
    ph_B: '位元組 byte',
    ph_KB: '千位元組 Kilo Byte',
    ph_MB: '兆位元組 Mega Byte',
    ph_GB: '吉位元組 Giga Byte',
    ph_TB: '太位元組 Trillion Byte',
    ph_PB: '拍位元組 Peta Byte',
    ph_EB: '艾位元組 Exa Byte',
    ph_ZB: '澤位元組 Zetta Byte',
    ph_YB: '堯位元組 Yotta Byte',
  },
  en: {
    appName: 'Byte Converter',
    clear: 'Clear',
    copyOk: 'Copied to clipboard!',
    divByte: 'Bytes',
    divBit: 'Bits',
    ph_B: 'Byte',
    ph_KB: 'Kilo Byte',
    ph_MB: 'Mega Byte',
    ph_GB: 'Giga Byte',
    ph_TB: 'Trillion Byte',
    ph_PB: 'Peta Byte',
    ph_EB: 'Exa Byte',
    ph_ZB: 'Zetta Byte',
    ph_YB: 'Yotta Byte',
  },
} as const;
