// Setting 语言包 (默认 zh-CN; 缺失词条回退默认语言)
// 系统设置各条目文案 (设置中心 -> 系统设置); 其它分类条目沿用各工具语言包
export default {
  default: 'zh-CN',
  'zh-CN': {
    appName: '设置',
    // 系统设置 (设置中心右侧各条目)
    lang: '界面语言',
    mode: '显示模式',
    modeLight: '浅色',
    modeDark: '深色',
    modeSystem: '系统跟随',
    sider: '默认展开右边栏',
    siderWidth: '侧边栏宽度',
    // 应用中心默认应用 (AppStoreSetting)
    appstoreDivider: '应用中心',
    defaultApp: '默认展示应用',
    // 配置文件导入 / 导出 (SettingConfig)
    configDivider: '配置文件',
    configLabel: '导入 / 导出',
    configExport: '导出配置',
    configImport: '导入配置',
    configHint: '导出为 JSON 文件 (含版本号与时间), 导入后自动刷新页面',
    configSaveTitle: '保存配置文件',
    configFilter: 'JSON 配置文件',
    configExported: '已导出 {n} 项配置',
    configImported: '已导入 {n} 项配置, 页面即将刷新',
    configErrExport: '导出配置文件失败',
    configErrRead: '读取配置文件失败',
    configErrInvalidJson: '不是合法的 JSON 文件',
    configErrFormat: '配置文件格式不正确',
    configErrNotMagicTools: '不是 MagicTools 配置文件',
    configErrMissingSettings: '配置文件缺少 settings 字段',
  },
  'zh-TW': {
    appName: '設定',
    lang: '介面語言',
    mode: '顯示模式',
    modeLight: '淺色',
    modeDark: '深色',
    modeSystem: '跟隨系統',
    sider: '預設展開右側欄',
    siderWidth: '側邊欄寬度',
    appstoreDivider: '應用中心',
    defaultApp: '預設展示應用',
    configDivider: '設定檔',
    configLabel: '匯入 / 匯出',
    configExport: '匯出設定',
    configImport: '匯入設定',
    configHint: '匯出為 JSON 檔案 (含版本號與時間), 匯入後自動重新整理頁面',
    configSaveTitle: '儲存設定檔',
    configFilter: 'JSON 設定檔',
    configExported: '已匯出 {n} 項設定',
    configImported: '已匯入 {n} 項設定, 頁面即將重新整理',
    configErrExport: '匯出設定檔失敗',
    configErrRead: '讀取設定檔失敗',
    configErrInvalidJson: '不是合法的 JSON 檔案',
    configErrFormat: '設定檔格式不正確',
    configErrNotMagicTools: '不是 MagicTools 設定檔',
    configErrMissingSettings: '設定檔缺少 settings 欄位',
  },
  en: {
    appName: 'Settings',
    lang: 'Language',
    mode: 'Display Mode',
    modeLight: 'Light',
    modeDark: 'Dark',
    modeSystem: 'Follow System',
    sider: 'Expand Sidebar by Default',
    siderWidth: 'Sidebar Width',
    appstoreDivider: 'App Store',
    defaultApp: 'Default App',
    configDivider: 'Configuration File',
    configLabel: 'Import / Export',
    configExport: 'Export Settings',
    configImport: 'Import Settings',
    configHint: 'Export as a JSON file (with version and timestamp); the page reloads after import',
    configSaveTitle: 'Save Configuration File',
    configFilter: 'JSON Configuration File',
    configExported: 'Exported {n} settings',
    configImported: 'Imported {n} settings, the page will reload shortly',
    configErrExport: 'Failed to export the configuration file',
    configErrRead: 'Failed to read the configuration file',
    configErrInvalidJson: 'Not a valid JSON file',
    configErrFormat: 'Invalid configuration file format',
    configErrNotMagicTools: 'Not a MagicTools configuration file',
    configErrMissingSettings: 'Configuration file is missing the settings field',
  },
} as const;
