export default {
  default: 'zh-CN',
  'zh-CN': {
    tab_single: '单个转换', tab_batch: '批量转换',
    fmt_real: '真实地址', fmt_thunder: '迅雷地址', fmt_qqdl: '快车地址', fmt_qdl: '旋风地址',
    phSingle: '在此粘贴下载地址, 自动识别并转换。支持:\n- 真实地址 http(s):// 或 ftp://\n- 迅雷地址 thunder://\n- 快车地址 qqdl://\n- 旋风地址 qdl://',
    clearSmall: '清空',
    clickCopy: '点击复制到剪贴板',
    copied: '已复制 {label} 到剪贴板',
    phBatch: '每行粘贴一个下载地址 (自动识别):\nhttp(s):// 或 ftp:// 真实地址\nthunder:// 迅雷地址\nqqdl:// 快车地址\nqdl:// 旋风地址',
    convertTo: '转换为',
    outNote: '输出按行对应输入, 结果可点击复制',
    phOutput: '转换结果将显示在这里',
    copyAll: '已复制全部结果到剪贴板 ({n} 条)',
    titleAll: '点击复制全部结果到剪贴板',
    e_EMPTY: '请输入下载地址',
    e_B64: '链接内容 Base64 解码失败',
    e_THUNDER: '迅雷地址内容无效 (缺少 AA/ZZ 标记)',
    e_UNREC: '无法识别: 请输入 http(s)/ftp 真实地址, 或 thunder://、qqdl://、qdl:// 专用链接',
    e_REAL: '识别结果不是有效地址: {url}',
    e_LINE: '第 {n} 行: {msg}',
    e_UNKNOWN: '未知错误',
  },
  'zh-TW': {
    tab_single: '單個轉換', tab_batch: '批量轉換',
    fmt_real: '真實網址', fmt_thunder: '迅雷網址', fmt_qqdl: '快車網址', fmt_qdl: '旋風網址',
    phSingle: '在此貼上下載網址, 自動辨識並轉換。支援:\n- 真實網址 http(s):// 或 ftp://\n- 迅雷網址 thunder://\n- 快車網址 qqdl://\n- 旋風網址 qdl://',
    clearSmall: '清空',
    clickCopy: '點擊複製到剪貼簿',
    copied: '已複製 {label} 到剪貼簿',
    phBatch: '每行貼上一個下載網址 (自動辨識):\nhttp(s):// 或 ftp:// 真實網址\nthunder:// 迅雷網址\nqqdl:// 快車網址\nqdl:// 旋風網址',
    convertTo: '轉換為',
    outNote: '輸出按行對應輸入, 結果可點擊複製',
    phOutput: '轉換結果將顯示在這裡',
    copyAll: '已複製全部結果到剪貼簿 ({n} 條)',
    titleAll: '點擊複製全部結果到剪貼簿',
    e_EMPTY: '請輸入下載網址',
    e_B64: '連結內容 Base64 解碼失敗',
    e_THUNDER: '迅雷網址內容無效 (缺少 AA/ZZ 標記)',
    e_UNREC: '無法辨識: 請輸入 http(s)/ftp 真實網址, 或 thunder://、qqdl://、qdl:// 專用連結',
    e_REAL: '辨識結果不是有效網址: {url}',
    e_LINE: '第 {n} 行: {msg}',
    e_UNKNOWN: '未知錯誤',
  },
  en: {
    tab_single: 'Single', tab_batch: 'Batch',
    fmt_real: 'Real URL', fmt_thunder: 'Thunder', fmt_qqdl: 'QQDL', fmt_qdl: 'QDL',
    phSingle: 'Paste a download link here — auto-detected and converted. Supported:\n- Real URL http(s):// or ftp://\n- Thunder link thunder://\n- QQDL link qqdl://\n- QDL link qdl://',
    clearSmall: 'Clear',
    clickCopy: 'Click to copy to clipboard',
    copied: 'Copied {label} to clipboard',
    phBatch: 'One download link per line (auto-detected):\nhttp(s):// or ftp:// real URL\nthunder:// Thunder link\nqqdl:// QQDL link\nqdl:// QDL link',
    convertTo: 'Convert to',
    outNote: 'Output lines correspond to input lines; click to copy',
    phOutput: 'Converted results will appear here',
    copyAll: 'Copied all results to clipboard ({n} items)',
    titleAll: 'Click to copy all results to clipboard',
    e_EMPTY: 'Please enter a download URL',
    e_B64: 'Failed to Base64-decode the link payload',
    e_THUNDER: 'Invalid Thunder link (missing AA/ZZ markers)',
    e_UNREC: 'Cannot recognize: enter an http(s)/ftp real URL, or a thunder://, qqdl://, qdl:// link',
    e_REAL: 'The parsed result is not a valid URL: {url}',
    e_LINE: 'Line {n}: {msg}',
    e_UNKNOWN: 'Unknown error',
  },
} as const;
