// .gitignore 模板库: 全部为静态文本, 不引入任何依赖
// 说明: 每行都是标准 .gitignore 语法; 组内注释行 (# 开头) 会随模板一起输出

export type GitignoreCategory = 'lang' | 'framework' | 'editor' | 'os' | 'misc';

export interface GitignoreTemplate {
  id: string;           // 唯一标识 (勾选状态用)
  label: string;        // 名称 (界面展示, 也是分组注释内容)
  category: GitignoreCategory;
  tags: string[];       // 搜索关键词 (小写)
  lines: string[];      // 忽略规则 (含模板内注释行)
}

// 分类顺序 = 界面分组顺序
export const GITIGNORE_CATEGORIES: Array<{ key: GitignoreCategory; label: string }> = [
  { key: 'lang',      label: '语言' },
  { key: 'framework', label: '框架与工具' },
  { key: 'editor',    label: '编辑器 / IDE' },
  { key: 'os',        label: '操作系统' },
  { key: 'misc',      label: '其它' },
];

// 模板库: 语言 (22)
const LANG_TEMPLATES: GitignoreTemplate[] = [
  {
    id: 'node', label: 'Node.js', category: 'lang',
    tags: [ 'node', 'nodejs', 'npm', 'yarn', 'pnpm', 'javascript', 'js' ],
    lines: [
      '# 依赖',
      'node_modules/',
      'jspm_packages/',
      'bower_components/',
      '# 构建产物',
      'dist/',
      'build/',
      'lib/',
      'out/',
      '# 缓存',
      '.npm/',
      '.eslintcache',
      '.stylelintcache',
      '.node_repl_history',
      '.yarn-integrity',
      '# 调试日志',
      'npm-debug.log*',
      'yarn-debug.log*',
      'yarn-error.log*',
      'pnpm-debug.log*',
      'lerna-debug.log*',
    ],
  },
  {
    id: 'typescript', label: 'TypeScript', category: 'lang',
    tags: [ 'typescript', 'ts', 'tsc' ],
    lines: [
      '*.tsbuildinfo',
      '.tsbuildinfo',
    ],
  },
  {
    id: 'python', label: 'Python', category: 'lang',
    tags: [ 'python', 'py', 'pyc', 'pip' ],
    lines: [
      '# 字节码 / 编译产物',
      '__pycache__/',
      '*.py[cod]',
      '*$py.class',
      '*.so',
      'build/',
      'dist/',
      '*.egg-info/',
      '*.egg',
      '.installed.cfg',
      '# 测试与检查缓存',
      '.pytest_cache/',
      '.tox/',
      '.nox/',
      '.coverage',
      'coverage.xml',
      'htmlcov/',
      '.hypothesis/',
      '.mypy_cache/',
      '.dmypy.json',
      '.ruff_cache/',
      '.pytype/',
    ],
  },
  {
    id: 'java', label: 'Java', category: 'lang',
    tags: [ 'java', 'jar', 'class', 'jvm' ],
    lines: [
      '*.class',
      '*.ctxt',
      '.mtj.tmp/',
      'hs_err_pid*',
      'replay_pid*',
      '# 打包产物',
      '*.jar',
      '*.war',
      '*.nar',
      '*.ear',
    ],
  },
  {
    id: 'kotlin', label: 'Kotlin', category: 'lang',
    tags: [ 'kotlin', 'kt', 'android' ],
    lines: [
      '*.class',
      '.kotlin/',
      'build/',
      'out/',
    ],
  },
  {
    id: 'gradle', label: 'Gradle', category: 'lang',
    tags: [ 'gradle', 'groovy', 'wrapper' ],
    lines: [
      '.gradle/',
      'build/',
      '!gradle/wrapper/gradle-wrapper.jar',
      '!**/src/**/build/',
    ],
  },
  {
    id: 'maven', label: 'Maven', category: 'lang',
    tags: [ 'maven', 'mvn', 'pom', 'java' ],
    lines: [
      'target/',
      'pom.xml.tag',
      'pom.xml.releaseBackup',
      'pom.xml.versionsBackup',
      'pom.xml.next',
      'release.properties',
      'dependency-reduced-pom.xml',
      'buildNumber.properties',
      '.mvn/timing.properties',
      '.mvn/wrapper/maven-wrapper.jar',
    ],
  },
  {
    id: 'go', label: 'Go', category: 'lang',
    tags: [ 'go', 'golang', 'gomod' ],
    lines: [
      '# 编译产物',
      '*.exe',
      '*.exe~',
      '*.dll',
      '*.so',
      '*.dylib',
      '*.test',
      '# 覆盖率 / 输出',
      '*.out',
      '# 工作区与依赖 (vendor 目录如需提交请删除本行)',
      'go.work',
      'go.work.sum',
      'vendor/',
    ],
  },
  {
    id: 'rust', label: 'Rust', category: 'lang',
    tags: [ 'rust', 'cargo', 'crate' ],
    lines: [
      '# 编译产物',
      'target/',
      '**/*.rs.bk',
      '# 调试符号与性能数据',
      '*.pdb',
      '*.profraw',
      'perf.data*',
    ],
  },
  {
    id: 'c', label: 'C', category: 'lang',
    tags: [ 'c', 'gcc', 'clang', 'make' ],
    lines: [
      '# 目标文件与库',
      '*.o',
      '*.obj',
      '*.a',
      '*.so',
      '*.so.*',
      '*.dylib',
      '*.ko',
      '# 可执行文件与调试符号',
      '*.exe',
      '*.out',
      '*.app',
      '*.dSYM/',
      '*.dSYM.zip',
      '# 内核模块构建产物',
      '*.mod.c',
      '*.symvers',
      '*.order',
      '.deps/',
      '.libs/',
    ],
  },
  {
    id: 'cpp', label: 'C++ / CMake', category: 'lang',
    tags: [ 'cpp', 'c++', 'cmake', 'make', 'ninja' ],
    lines: [
      '# 目标文件与库',
      '*.o',
      '*.obj',
      '*.lo',
      '*.la',
      '*.a',
      '*.so',
      '*.so.*',
      '*.dll',
      '*.[Dd][Ll][Ll]',
      '# 可执行文件',
      '*.exe',
      '*.out',
      '*.app',
      '# CMake / 构建目录',
      'build/',
      'cmake-build-*/',
      'CMakeFiles/',
      'CMakeCache.txt',
      'cmake_install.cmake',
      'install_manifest.txt',
      'compile_commands.json',
      'CTestTestfile.cmake',
      '# 编辑器缓存',
      '.ccls-cache/',
      '.cache/',
    ],
  },
  {
    id: 'csharp', label: 'C# / .NET', category: 'lang',
    tags: [ 'csharp', 'c#', 'dotnet', '.net', 'visualstudio' ],
    lines: [
      '[Bb]in/',
      '[Oo]bj/',
      '[Ll]og/',
      '[Ll]ogs/',
      '*.user',
      '*.suo',
      '*.userosscache',
      '*.sln.docstates',
      '*.binlog',
      'packages/',
      'TestResults/',
    ],
  },
  {
    id: 'php', label: 'PHP', category: 'lang',
    tags: [ 'php', 'composer' ],
    lines: [
      '/vendor/',
      'composer.phar',
      '.phpunit.result.cache',
      '.phpunit.cache/',
      '.php-cs-fixer.cache',
      '.php-cs-fixer.php',
      '/var/cache/',
      '/var/logs/',
      '/var/sessions/',
    ],
  },
  {
    id: 'ruby', label: 'Ruby', category: 'lang',
    tags: [ 'ruby', 'gem', 'bundler', 'rake' ],
    lines: [
      '*.gem',
      '*.rbc',
      '/.bundle/',
      '/.yardoc/',
      '/_yardoc/',
      '/doc/',
      '/pkg/',
      '/spec/reports/',
      '/tmp/',
      'vendor/bundle/',
    ],
  },
  {
    id: 'swift', label: 'Swift', category: 'lang',
    tags: [ 'swift', 'spm', 'ios', 'macos' ],
    lines: [
      '/.build/',
      '/Packages/',
      '*.moved-aside',
      '*.hmap',
      'DerivedData/',
      '*.ipa',
      '*.dSYM.zip',
      '*.dSYM',
    ],
  },
  {
    id: 'dart', label: 'Dart / Flutter', category: 'lang',
    tags: [ 'dart', 'flutter', 'pub' ],
    lines: [
      '.dart_tool/',
      '.flutter-plugins',
      '.flutter-plugins-dependencies',
      '.packages',
      '.pub-cache/',
      '.pub/',
      'build/',
    ],
  },
  {
    id: 'scala', label: 'Scala', category: 'lang',
    tags: [ 'scala', 'sbt', 'bloop', 'metals' ],
    lines: [
      '*.class',
      '.bloop/',
      '.metals/',
      '.scala-build/',
      'project/target/',
      'project/project/',
      'target/',
    ],
  },
  {
    id: 'elixir', label: 'Elixir / Erlang', category: 'lang',
    tags: [ 'elixir', 'erlang', 'mix', 'rebar', 'beam' ],
    lines: [
      '/_build/',
      '/cover/',
      '/deps/',
      '/doc/',
      '/.fetch',
      '/rel/',
      'erl_crash.dump',
      '*.ez',
      '*.beam',
      '*.plt',
      '.elixir_ls/',
      '.rebar/',
    ],
  },
  {
    id: 'lua', label: 'Lua / LuaRocks', category: 'lang',
    tags: [ 'lua', 'luarocks', 'luac' ],
    lines: [
      '*.luac',
      'lua_modules/',
      '.luarocks/',
    ],
  },
  {
    id: 'r', label: 'R', category: 'lang',
    tags: [ 'r', 'rstudio', 'rproj' ],
    lines: [
      '.Rproj.user',
      '.Rhistory',
      '.RData',
      '.Ruserdata',
      '.Rprofile',
      '*.Rproj',
    ],
  },
  {
    id: 'julia', label: 'Julia', category: 'lang',
    tags: [ 'julia', 'jl' ],
    lines: [
      '*.jl.cov',
      '*.jl.*.cov',
      '*.jl.mem',
      'Manifest.toml',
      '/docs/build/',
      '/docs/site/',
    ],
  },
  {
    id: 'objectivec', label: 'Objective-C', category: 'lang',
    tags: [ 'objectivec', 'objc', 'ios', 'apple' ],
    lines: [
      '*.o',
      '*.a',
      '*.dSYM/',
      '*.xcuserstate',
      'DerivedData/',
      'build/',
    ],
  },
];

// 模板库: 框架与工具 (20)
const FRAMEWORK_TEMPLATES: GitignoreTemplate[] = [
  {
    id: 'vite', label: 'Vite / React / Vue', category: 'framework',
    tags: [ 'vite', 'react', 'vue', 'spa', 'frontend', 'svelte' ],
    lines: [
      'dist/',
      'dist-ssr/',
      '.vite/',
      '.vite-inspect/',
      'vite.config.*.timestamp-*',
      'stats.html',
      '*.local',
    ],
  },
  {
    id: 'nextjs', label: 'Next.js', category: 'framework',
    tags: [ 'next', 'nextjs', 'react', 'vercel' ],
    lines: [
      '/.next/',
      '/out/',
      '/build/',
      '.vercel',
    ],
  },
  {
    id: 'nuxt', label: 'Nuxt', category: 'framework',
    tags: [ 'nuxt', 'vue', 'nitro' ],
    lines: [
      '.nuxt/',
      '.output/',
      '.data/',
      '.nitro/',
      'dist/',
    ],
  },
  {
    id: 'angular', label: 'Angular', category: 'framework',
    tags: [ 'angular', 'ng' ],
    lines: [
      '/.angular/cache/',
      '/dist/',
      '/tmp/',
      '/coverage/',
      '/connect.lock',
      '/libpeerconnection.log',
      '.sass-cache/',
    ],
  },
  {
    id: 'svelte', label: 'SvelteKit', category: 'framework',
    tags: [ 'svelte', 'sveltekit', 'kit' ],
    lines: [
      '.svelte-kit/',
      '/package/',
      'build/',
      '.vercel/',
      '.netlify/',
    ],
  },
  {
    id: 'astro', label: 'Astro', category: 'framework',
    tags: [ 'astro', 'static' ],
    lines: [
      'dist/',
      '.astro/',
      '.vercel/',
      '.netlify/',
    ],
  },
  {
    id: 'django', label: 'Django', category: 'framework',
    tags: [ 'django', 'python', 'py' ],
    lines: [
      'local_settings.py',
      'db.sqlite3',
      'db.sqlite3-journal',
      '/media/',
      '/staticfiles/',
      '*.log',
    ],
  },
  {
    id: 'flask', label: 'Flask', category: 'framework',
    tags: [ 'flask', 'python', 'py' ],
    lines: [
      'instance/',
      '.webassets-cache',
      '*.sqlite3',
      'app.db',
    ],
  },
  {
    id: 'rails', label: 'Ruby on Rails', category: 'framework',
    tags: [ 'rails', 'ruby', 'ror' ],
    lines: [
      '/log/*',
      '/tmp/*',
      '!/log/.keep',
      '!/tmp/.keep',
      '/storage/*',
      '!/storage/.keep',
      '/public/assets',
      '/public/packs',
      '.byebug_history',
      '/coverage/',
    ],
  },
  {
    id: 'laravel', label: 'Laravel', category: 'framework',
    tags: [ 'laravel', 'php', 'artisan' ],
    lines: [
      '/vendor',
      '/node_modules',
      '/public/hot',
      '/public/storage',
      '/storage/*.key',
      '/storage/pail',
      '.phpunit.result.cache',
      'Homestead.json',
      'Homestead.yaml',
      'auth.json',
    ],
  },
  {
    id: 'jupyter', label: 'Jupyter Notebook', category: 'framework',
    tags: [ 'jupyter', 'notebook', 'ipynb', 'python' ],
    lines: [
      '.ipynb_checkpoints/',
      '*.ipynb_checkpoints',
      '.virtual_documents/',
      'profile_default/',
      'ipython_config.py',
    ],
  },
  {
    id: 'virtualenv', label: 'Python virtualenv', category: 'framework',
    tags: [ 'venv', 'virtualenv', 'python', 'pip' ],
    lines: [
      '.venv/',
      'venv/',
      'env/',
      'ENV/',
      'env.bak/',
      'venv.bak/',
      'virtualenv/',
      'pip-log.txt',
      'pip-delete-this-directory.txt',
      'pip-wheel-metadata/',
    ],
  },
  {
    id: 'unity', label: 'Unity', category: 'framework',
    tags: [ 'unity', 'game', 'csharp' ],
    lines: [
      '/[Ll]ibrary/',
      '/[Tt]emp/',
      '/[Oo]bj/',
      '/[Bb]uild/',
      '/[Bb]uilds/',
      '/[Ll]ogs/',
      '/[Uu]ser[Ss]ettings/',
      '/[Mm]emoryCaptures/',
      '/[Rr]ecordings/',
      '*.pidb.meta',
      '*.pdb.meta',
      '*.mdb.meta',
      'sysinfo.txt',
      '*.apk',
      '*.aab',
      '*.unitypackage',
      '*.app',
      'crashlytics-build.properties',
    ],
  },
  {
    id: 'godot', label: 'Godot', category: 'framework',
    tags: [ 'godot', 'game', 'gdscript' ],
    lines: [
      '.godot/',
      '/.import/',
      'export.cfg',
      'export_presets.cfg',
      '*.translation',
      '/mono_crash.*.json',
    ],
  },
  {
    id: 'terraform', label: 'Terraform', category: 'framework',
    tags: [ 'terraform', 'tf', 'iac', 'cloud' ],
    lines: [
      '**/.terraform/*',
      '*.tfstate',
      '*.tfstate.*',
      '*.tfvars',
      '*.tfvars.json',
      'override.tf',
      'override.tf.json',
      '*_override.tf',
      '*_override.tf.json',
      '.terraformrc',
      'terraform.rc',
      'crash.log',
      'crash.*.log',
    ],
  },
  {
    id: 'serverless', label: 'Serverless / Vercel / Netlify', category: 'framework',
    tags: [ 'serverless', 'vercel', 'netlify', 'aws', 'lambda', 'sam' ],
    lines: [
      '.serverless/',
      '.vercel/',
      '.netlify/',
      '.now/',
      '.aws-sam/',
      '.fusebox/',
      '.dynamodb/',
    ],
  },
  {
    id: 'tauri', label: 'Tauri', category: 'framework',
    tags: [ 'tauri', 'rust', 'desktop', 'electron' ],
    lines: [
      'src-tauri/target/',
      'src-tauri/gen/schemas/',
      'src-tauri/.cargo/',
    ],
  },
  {
    id: 'sphinx', label: 'Sphinx / MkDocs', category: 'framework',
    tags: [ 'sphinx', 'mkdocs', 'docs', 'documentation' ],
    lines: [
      '/docs/_build/',
      'docs/_build/',
      '/site/',
      '_site/',
      '.cache/',
    ],
  },
  {
    id: 'jekyll', label: 'Jekyll', category: 'framework',
    tags: [ 'jekyll', 'static', 'github-pages', 'blog' ],
    lines: [
      '_site/',
      '.sass-cache/',
      '.jekyll-cache/',
      '.jekyll-metadata',
      'vendor/bundle/',
    ],
  },
  {
    id: 'hugo', label: 'Hugo / Hexo', category: 'framework',
    tags: [ 'hugo', 'hexo', 'static', 'blog' ],
    lines: [
      '/public/',
      '/resources/_gen/',
      '.hugo_build.lock',
      '.deploy*/',
      'db.json',
    ],
  },
];

// 模板库: 编辑器 / IDE (9)
const EDITOR_TEMPLATES: GitignoreTemplate[] = [
  {
    id: 'vscode', label: 'VS Code', category: 'editor',
    tags: [ 'vscode', 'visualstudiocode', 'editor' ],
    lines: [
      '.vscode/*',
      '!.vscode/settings.json',
      '!.vscode/tasks.json',
      '!.vscode/launch.json',
      '!.vscode/extensions.json',
      '!.vscode/*.code-snippets',
      '.history/',
      '*.vsix',
    ],
  },
  {
    id: 'jetbrains', label: 'JetBrains', category: 'editor',
    tags: [ 'jetbrains', 'idea', 'intellij', 'pycharm', 'goland', 'webstorm' ],
    lines: [
      '.idea/',
      '*.iml',
      '*.ipr',
      '*.iws',
      '.idea_modules/',
      'out/',
      'atlassian-ide-plugin.xml',
      '.fleet/',
    ],
  },
  {
    id: 'vim', label: 'Vim', category: 'editor',
    tags: [ 'vim', 'neovim', 'swap', 'editor' ],
    lines: [
      '*.sw?',
      '*.swo',
      '*.swp',
      'tags',
      'Session.vim',
      '.netrwhist',
    ],
  },
  {
    id: 'emacs', label: 'Emacs', category: 'editor',
    tags: [ 'emacs', 'editor', 'elisp' ],
    lines: [
      '*~',
      '\\#*\\#',
      '.#*',
      '/.emacs.desktop',
      '/.emacs.desktop.lock',
      '.eshell_history',
      '.org-id-locations',
      '*_archive',
      'eln-cache/',
    ],
  },
  {
    id: 'sublime', label: 'Sublime Text', category: 'editor',
    tags: [ 'sublime', 'editor' ],
    lines: [
      '*.sublime-workspace',
    ],
  },
  {
    id: 'eclipse', label: 'Eclipse', category: 'editor',
    tags: [ 'eclipse', 'editor', 'java' ],
    lines: [
      '.metadata/',
      'bin/',
      'tmp/',
      '*.tmp',
      '.settings/',
      '.loadpath',
      '.apt_generated/',
      '.classpath',
      '.project',
      '.factorypath',
      '.springBeans',
      '.sts4-cache',
    ],
  },
  {
    id: 'netbeans', label: 'NetBeans', category: 'editor',
    tags: [ 'netbeans', 'editor', 'java' ],
    lines: [
      'nbproject/private/',
      'nbbuild/',
      'nbdist/',
      '.nb-gradle/',
      'build/',
      'dist/',
    ],
  },
  {
    id: 'xcode', label: 'Xcode', category: 'editor',
    tags: [ 'xcode', 'apple', 'ios', 'macos', 'swift' ],
    lines: [
      'xcuserdata/',
      '*.xcuserstate',
      '*.xcscmblueprint',
      'DerivedData/',
      '*.moved-aside',
      '*.hmap',
      '*.ipa',
      '*.dSYM.zip',
      '*.dSYM',
      'build/',
    ],
  },
  {
    id: 'visualstudio', label: 'Visual Studio', category: 'editor',
    tags: [ 'visualstudio', 'vs', 'editor', 'csharp' ],
    lines: [
      '.vs/',
      '*.suo',
      '*.user',
      '*.userosscache',
      '*.sln.docstates',
      '[Bb]in/',
      '[Oo]bj/',
      '*.VC.db',
      '*.VC.VC.opendb',
      'packages/',
      'TestResults/',
    ],
  },
];

// 模板库: 操作系统 (3)
const OS_TEMPLATES: GitignoreTemplate[] = [
  {
    id: 'macos', label: 'macOS', category: 'os',
    tags: [ 'macos', 'mac', 'osx', 'darwin', 'ds_store' ],
    lines: [
      '.DS_Store',
      '.AppleDouble',
      '.LSOverride',
      '._*',
      '.DocumentRevisions-V100',
      '.fseventsd',
      '.Spotlight-V100',
      '.TemporaryItems',
      '.Trashes',
      '.VolumeIcon.icns',
      '.com.apple.timemachine.donotpresent',
      '.AppleDB',
      '.AppleDesktop',
      'Network Trash Folder',
      'Temporary Items',
      '.apdisk',
    ],
  },
  {
    id: 'windows', label: 'Windows', category: 'os',
    tags: [ 'windows', 'win', 'thumbs', 'desktop.ini' ],
    lines: [
      'Thumbs.db',
      'Thumbs.db:encryptable',
      'ehthumbs.db',
      'ehthumbs_vista.db',
      '*.stackdump',
      '[Dd]esktop.ini',
      '$RECYCLE.BIN/',
      '*.cab',
      '*.msi',
      '*.msix',
      '*.msm',
      '*.msp',
      '*.lnk',
    ],
  },
  {
    id: 'linux', label: 'Linux', category: 'os',
    tags: [ 'linux', 'trash', 'nfs' ],
    lines: [
      '*~',
      '.fuse_hidden*',
      '.directory',
      '.Trash-*',
      '.nfs*',
      '*.kate-swp',
    ],
  },
];

// 模板库: 其它 (10)
const MISC_TEMPLATES: GitignoreTemplate[] = [
  {
    id: 'env', label: '环境变量 / 密钥', category: 'misc',
    tags: [ 'env', 'dotenv', 'secret', 'key', 'pem', 'cert', 'certificate' ],
    lines: [
      '# 环境变量',
      '.env',
      '.env.*',
      '!.env.example',
      '!.env.sample',
      '!.env.template',
      '# 密钥与证书',
      '*.pem',
      '*.key',
      '*.p12',
      '*.pfx',
      '*.jks',
      '*.keystore',
      'id_rsa',
      'id_rsa.pub',
      'id_ed25519',
      '# 凭据与私有配置 (含 token, 请确认不需要提交)',
      '.npmrc',
      '.yarnrc',
      '.pypirc',
      'secrets.json',
      'credentials.json',
      'service-account.json',
    ],
  },
  {
    id: 'logs', label: '日志与临时文件', category: 'misc',
    tags: [ 'log', 'logs', 'tmp', 'temp', 'debug' ],
    lines: [
      '*.log',
      '*.log.*',
      'logs/',
      'tmp/',
      'temp/',
      '*.tmp',
      '*.temp',
      '*.pid',
      '*.pid.lock',
      '*.seed',
    ],
  },
  {
    id: 'cache', label: '缓存与构建产物', category: 'misc',
    tags: [ 'cache', 'build', 'dist', 'artifact', 'turbo', 'nx' ],
    lines: [
      '.cache/',
      '.parcel-cache/',
      '.sass-cache/',
      '.turbo/',
      '.nx/',
      '.angular/',
      'dist/',
      'build/',
      'out/',
      '*.tsbuildinfo',
    ],
  },
  {
    id: 'coverage', label: '测试与覆盖率', category: 'misc',
    tags: [ 'coverage', 'test', 'nyc', 'jest', 'cypress', 'playwright' ],
    lines: [
      'coverage/',
      'coverage.*',
      '*.lcov',
      'lcov.info',
      '.nyc_output/',
      'test-results/',
      'junit.xml',
      'cypress/videos/',
      'cypress/screenshots/',
      'playwright-report/',
    ],
  },
  {
    id: 'archive', label: '压缩包与安装包', category: 'misc',
    tags: [ 'zip', 'tar', 'archive', 'package', 'installer' ],
    lines: [
      '*.zip',
      '*.tar',
      '*.tar.gz',
      '*.tgz',
      '*.gz',
      '*.bz2',
      '*.xz',
      '*.rar',
      '*.7z',
      '*.iso',
      '*.dmg',
      '*.pkg',
      '*.deb',
      '*.rpm',
      '*.exe',
      '*.msi',
      '*.apk',
      '*.aab',
      '*.ipa',
    ],
  },
  {
    id: 'db', label: '数据库文件', category: 'misc',
    tags: [ 'database', 'sqlite', 'mysql', 'db', 'sql', 'dump' ],
    lines: [
      '*.sqlite',
      '*.sqlite3',
      '*.sqlite3-journal',
      '*.db',
      '*.db-journal',
      '*.mdb',
      '*.accdb',
      'dump.sql',
      '*.dump',
      '*.ibd',
      '*.myd',
      '*.myi',
    ],
  },
  {
    id: 'office', label: 'Office 临时文件', category: 'misc',
    tags: [ 'office', 'word', 'excel', 'ppt', 'lock' ],
    lines: [
      '~$*.doc',
      '~$*.docx',
      '~$*.xls',
      '~$*.xlsx',
      '~$*.ppt',
      '~$*.pptx',
      '*.~vsd*',
      '.~lock.*#',
    ],
  },
  {
    id: 'backup', label: '备份与还原文件', category: 'misc',
    tags: [ 'backup', 'bak', 'old', 'orig', 'rej' ],
    lines: [
      '*.bak',
      '*.backup',
      '*.old',
      '*.orig',
      '*.rej',
      '*.save',
      '*.swn',
      '*.swo',
    ],
  },
  {
    id: 'pkgcache', label: '包管理器缓存', category: 'misc',
    tags: [ 'npm', 'yarn', 'pnpm', 'cache', 'node' ],
    lines: [
      '.npm/',
      '.yarn/cache',
      '.yarn/install-state.gz',
      '.pnp.*',
      '.pnpm-store/',
      '.pnpm-debug.log',
    ],
  },
  {
    id: 'ml', label: '机器学习 / 模型文件', category: 'misc',
    tags: [ 'ml', 'model', 'checkpoint', 'onnx', 'pytorch', 'tensorflow', 'wandb' ],
    lines: [
      '# 模型权重',
      '*.pt',
      '*.pth',
      '*.ckpt',
      '*.onnx',
      '*.h5',
      '*.pkl',
      '*.joblib',
      'checkpoints/',
      'models/',
      'outputs/',
      'wandb/',
      'mlruns/',
      '.hf_cache/',
    ],
  },
];

// 全部模板 (顺序 = 模板库顺序, 也是结果输出的默认顺序)
export const GITIGNORE_TEMPLATES: GitignoreTemplate[] = [
  ...LANG_TEMPLATES,
  ...FRAMEWORK_TEMPLATES,
  ...EDITOR_TEMPLATES,
  ...OS_TEMPLATES,
  ...MISC_TEMPLATES,
];

export interface GitignorePreset {
  id: string;
  name: string;      // 界面展示名 (走语言包)
  ids: string[];     // 覆盖的模板 id
}

// 常用组合 (一键勾选常见技术栈)
export const GITIGNORE_PRESETS: GitignorePreset[] = [
  {
    id: 'frontend',
    name: '前端 (Node + Vite)',
    ids: [ 'node', 'typescript', 'vite', 'macos', 'windows', 'vscode', 'env', 'logs', 'coverage', 'cache' ],
  },
  {
    id: 'python',
    name: 'Python 后端',
    ids: [ 'python', 'virtualenv', 'django', 'jupyter', 'macos', 'windows', 'vscode', 'env', 'logs', 'coverage' ],
  },
  {
    id: 'java',
    name: 'Java / Maven',
    ids: [ 'java', 'maven', 'jetbrains', 'macos', 'windows', 'logs', 'env' ],
  },
  {
    id: 'kotlin',
    name: 'Android / Kotlin',
    ids: [ 'kotlin', 'gradle', 'jetbrains', 'macos', 'windows', 'linux', 'logs' ],
  },
  {
    id: 'go',
    name: 'Go 服务',
    ids: [ 'go', 'vscode', 'macos', 'windows', 'linux', 'logs', 'env', 'db' ],
  },
  {
    id: 'rust',
    name: 'Rust 项目',
    ids: [ 'rust', 'vscode', 'macos', 'windows', 'linux', 'logs', 'env' ],
  },
  {
    id: 'cpp',
    name: 'C / C++ (CMake)',
    ids: [ 'c', 'cpp', 'vscode', 'macos', 'windows', 'linux', 'logs' ],
  },
  {
    id: 'php',
    name: 'PHP / Laravel',
    ids: [ 'php', 'laravel', 'vscode', 'macos', 'windows', 'logs', 'env' ],
  },
  {
    id: 'mobile',
    name: '移动端 (Flutter / 原生)',
    ids: [ 'dart', 'kotlin', 'swift', 'jetbrains', 'xcode', 'macos', 'logs', 'archive' ],
  },
  {
    id: 'ml',
    name: '机器学习 / 数据科学',
    ids: [ 'python', 'virtualenv', 'jupyter', 'ml', 'logs', 'db', 'coverage' ],
  },
  {
    id: 'common',
    name: '通用基础 (系统 + 编辑器 + 密钥)',
    ids: [ 'macos', 'windows', 'linux', 'vscode', 'jetbrains', 'env', 'logs', 'backup' ],
  },
];

// 通用基础组合 (新建仓库时的兜底推荐, 界面提示用)
export const GITIGNORE_COMMON_PRESET_ID = 'common';
