// Image Generators (图片生成) 分类页面共享词条: zh 原文即 key, 值为 [zh-TW, en]
// 用法: const t = (zh:string) => im(locale, zh); 动态模板: imT(locale, zhTpl, {x:...}) (占位符 {x})
// 各工具 data.ts / lib.ts 数据默认文案 (如平台标题) 不修改源码, 在渲染处用 t() 包装翻译
type WmRec = Record<string, [string, string]>;
const D: WmRec = {
  '复制到粘贴板成功！！！': ['複製到剪貼簿成功！！！', 'Copied to clipboard!!!'],
  '拖拽要生成 Base64 编码的图片文件到框内': ['拖曳要產生 Base64 編碼的圖片檔案到框內', 'Drag an image file into the box to Base64-encode it'],
  '点击复制内容到粘贴板': ['點擊複製內容到剪貼簿', 'Click to copy to clipboard'],
  '清除': ['清除', 'Clear'],
  '宽度:': ['寬度:', 'Width:'],
  '高度:': ['高度:', 'Height:'],
  '说明:': ['說明:', 'Alt text:'],
  '预览': ['預覽', 'Preview'],
  'SVG 内容已复制到剪贴板': ['SVG 內容已複製到剪貼簿', 'SVG copied to clipboard'],
  '复制失败, 请手动选中下方代码复制': ['複製失敗, 請手動選取下方程式碼複製', 'Copy failed — please select the code below and copy it manually'],
  '保存 {name}': ['儲存 {name}', 'Save {name}'],
  'SVG 图片': ['SVG 圖片', 'SVG image'],
  '已保存 {name}': ['已儲存 {name}', 'Saved {name}'],
  '保存失败': ['儲存失敗', 'Save failed'],
  '图片加载失败': ['圖片載入失敗', 'Failed to load the image'],
  '当前环境不支持绘制 PNG': ['目前環境不支援繪製 PNG', 'PNG rendering is not supported in this environment'],
  '已保存 {name} ({w}×{h}px)': ['已儲存 {name} ({w}×{h}px)', 'Saved {name} ({w}×{h}px)'],
  'PNG 保存失败': ['PNG 儲存失敗', 'Failed to save PNG'],
  '文字': ['文字', 'Label'],
  '左侧文字 (如 php)': ['左側文字 (如 php)', 'Left text (e.g. php)'],
  '状态': ['狀態', 'Value'],
  '右侧状态文字 (如 8.0)': ['右側狀態文字 (如 8.0)', 'Right status text (e.g. 8.0)'],
  '文字颜色': ['文字顏色', 'Label color'],
  '状态颜色': ['狀態顏色', 'Value color'],
  '左侧底色固定 #555 (shields 风格)': ['左側底色固定為 #555 (shields 風格)', 'Left background is fixed at #555 (shields style)'],
  '图片尺寸': ['圖片尺寸', 'Image scale'],
  '倍率': ['倍率', 'Export size'],
  '导出 PNG 为 {w}×{h}px (badge 高 20, 随文字变宽)': ['匯出 PNG 為 {w}×{h}px (badge 高 20, 隨文字變寬)', 'PNG export is {w}×{h}px (badge height 20, width grows with text)'],
  '实时生成 shields.io 风格 SVG; 文字与状态留空时相应段落自动隐藏; SVG 为矢量格式, 放大不模糊': ['即時產生 shields.io 風格 SVG; 文字與狀態留空時對應區塊會自動隱藏; SVG 為向量格式, 放大不模糊', 'Generates a shields.io-style SVG live; when label or value is empty that segment hides automatically. SVG is vector — it stays sharp when scaled up'],
  '预览 (点击复制 SVG):': ['預覽 (點擊複製 SVG):', 'Preview (click to copy SVG):'],
  '请填写文字或状态后生成预览': ['請填寫文字或狀態後產生預覽', 'Fill in the label or value to see the preview'],
  '点击复制 SVG 内容': ['點擊複製 SVG 內容', 'Click to copy the SVG'],
  '{n} 字符 · {a} | {b}': ['{n} 字元 · {a} | {b}', '{n} chars · {a} | {b}'],
  '复制 SVG 内容': ['複製 SVG 內容', 'Copy SVG'],
  '保存为 .svg': ['儲存為 .svg', 'Save as .svg'],
  '导出 PNG ({s}×)': ['匯出 PNG ({s}×)', 'Export PNG ({s}×)'],
  'SVG 源码:': ['SVG 原始碼:', 'SVG source:'],
  'PNG 生成失败': ['PNG 產生失敗', 'PNG generation failed'],
  '请选择图片文件 (PNG/JPG/WebP 等)': ['請選擇圖片檔案 (PNG/JPG/WebP 等)', 'Choose an image file (PNG/JPG/WebP etc.)'],
  '生成失败': ['產生失敗', 'Generation failed'],
  '请先上传一张图片': ['請先上傳一張圖片', 'Upload an image first'],
  'App Icon 生成 · 批量结果 ({n} 张)': ['App Icon 產生 · 批次結果 ({n} 張)', 'App Icon generator — batch result ({n} icons)'],
  '【{t}】{d}:': ['【{t}】{d}:', '[{t}] {d}:'],
  '批量下载 App 图标': ['批次下載 App 圖示', 'Download app icons (batch)'],
  'ZIP 压缩包': ['ZIP 壓縮檔', 'ZIP archive'],
  '已生成 {n} 张图标并打包下载': ['已產生 {n} 張圖示並打包下載', 'Generated {n} icons and packed them for download'],
  '打包失败': ['打包失敗', 'Packaging failed'],
  '点击或拖拽图片到此处': ['點擊或拖曳圖片到此處', 'Click or drag an image here'],
  '建议 1024×1024 方形、无透明底素材': ['建議 1024×1024 方形、無透明底素材', 'A square 1024×1024 source without transparency is recommended'],
  ' · 当前: {name}': [' · 目前: {name}', ' · current: {name}'],
  '{n} 张': ['{n} 張', '{n} icon(s)'],
  'Apple HIG 规范 (含 iPhone/iPad/App Store 1024)': ['Apple HIG 規範 (含 iPhone/iPad/App Store 1024)', 'Apple HIG spec (incl. iPhone/iPad/App Store 1024)'],
  'Google 官方 mipmap 密度目录': ['Google 官方 mipmap 密度目錄', 'Google official mipmap density folders'],
  'Cordova res/icon 官方目录结构': ['Cordova res/icon 官方目錄結構', 'Cordova res/icon official folder layout'],
  '像素: {p}': ['像素: {p}', 'Pixels: {p}'],
  '点击卡片可勾选 / 取消平台, 选中的平台才会被打包下载 (当前选中 {n} 张)': ['點擊卡片可勾選 / 取消平台, 選中的平台才會被打包下載 (目前選中 {n} 張)', 'Click a card to select / deselect a platform; only selected platforms are packed (currently {n} icons)'],
  '正在生成…': ['正在產生…', 'Generating…'],
  '下载所选平台图标 (.zip · {n} 张)': ['下載所選平台圖示 (.zip · {n} 張)', 'Download icons for selected platforms (.zip · {n} icons)'],
  '1024 主图标预览': ['1024 主圖示預覽', '1024 master icon preview'],
  '上传后预览': ['上傳後預覽', 'Preview after upload'],
  'iOS · Android · PhoneGap 三平台同时生成': ['iOS · Android · PhoneGap 三平台同時產生', 'Generates for all three platforms: iOS · Android · PhoneGap'],
  '查看输出文件清单 ({n} 个可选, 以下仅列出已选平台)': ['查看輸出檔案清單 ({n} 個可選, 以下僅列出已選平台)', 'Output file list ({n} available, only selected platforms listed)'],
  '{s}×{s} · ICO 文件 {n} 字节': ['{s}×{s} · ICO 檔案 {n} 位元組', '{s}×{s} · ICO file {n} bytes'],
  '保存 ICO 图标': ['儲存 ICO 圖示', 'Save ICO icon'],
  'ICO 图标': ['ICO 圖示', 'ICO icon'],
  '已保存 icon-{s}x{s}.ico': ['已儲存 icon-{s}x{s}.ico', 'Saved icon-{s}x{s}.ico'],
  '支持 PNG / JPG / WebP / GIF, 建议使用方形图标素材': ['支援 PNG / JPG / WebP / GIF, 建議使用方形圖示素材', 'PNG / JPG / WebP / GIF supported; a square source is recommended'],
  '生成尺寸': ['產生尺寸', 'Size'],
  '生成预览 ({s}×{s} 放大展示)': ['產生預覽 ({s}×{s} 放大顯示)', 'Preview ({s}×{s}, scaled up)'],
  '点击查看并保存': ['點擊檢視並儲存', 'Click to view and save'],
  '点击图标查看并保存 .ico': ['點擊圖示檢視並儲存 .ico', 'Click the icon to view and save .ico'],
  '暂无图标': ['暫無圖示', 'No icon yet'],
  '保存 ICO 图标 · {s}×{s}': ['儲存 ICO 圖示 · {s}×{s}', 'Save ICO icon · {s}×{s}'],
  '取消': ['取消', 'Cancel'],
  '保存为 {name}': ['儲存為 {name}', 'Save as {name}'],
  '将导出单尺寸 {s}×{s} ICO (32 位带透明通道), 可直接用作网站 favicon 或程序图标': ['將匯出單一尺寸 {s}×{s} ICO (32 位元含透明通道), 可直接用作網站 favicon 或程式圖示', 'Exports a single-size {s}×{s} ICO (32-bit with alpha) — ready to use as a website favicon or app icon'],
  '读取文件失败': ['讀取檔案失敗', 'Failed to read the file'],
  '图片解析失败, 请确认文件格式': ['圖片解析失敗, 請確認檔案格式', 'Failed to decode the image — check the file format'],
  '无法创建画布': ['無法建立畫布', 'Could not create canvas'],
  '请选择图片文件': ['請選擇圖片檔案', 'Choose an image file'],
  '已载入 {name} ({w}×{h}px)': ['已載入 {name} ({w}×{h}px)', 'Loaded {name} ({w}×{h}px)'],
  '载入失败': ['載入失敗', 'Load failed'],
  '已复制 {n} 字符到剪贴板': ['已複製 {n} 字元到剪貼簿', 'Copied {n} characters to clipboard'],
  '复制失败, 请手动选中文本复制': ['複製失敗, 請手動選取文字複製', 'Copy failed — please select the text and copy manually'],
  '文本文件': ['文字檔', 'Text file'],
  '点击或拖拽图片到此处载入': ['點擊或拖曳圖片到此處載入', 'Click or drag an image here to load'],
  '支持 png / jpg / webp / gif (首帧), 自动按最长边 600px 缩小处理': ['支援 png / jpg / webp / gif (首幀), 自動依最長邊 600px 縮小處理', 'Supports png / jpg / webp / gif (first frame); shrunk automatically so the longest side is 600px'],
  '载入图片后自动生成 ASCII 图: 灰度字符按亮度映射, 可用下方参数实时调整': ['載入圖片後自動產生 ASCII 圖: 灰階字元依亮度對應, 可用下方參數即時調整', 'The ASCII art generates automatically after loading: gray levels map to characters by brightness and can be tuned live below'],
  '输出宽': ['輸出寬', 'Output width'],
  '字符': ['字元', 'chars'],
  '字符集': ['字元集', 'Char set'],
  '标准 (10 级 @%#*+=-:. )': ['標準 (10 級 @%#*+=-:. )', 'Standard (10 levels @%#*+=-:. )'],
  '密度块 (Unicode █▓▒░ )': ['密度塊 (Unicode █▓▒░ )', 'Density blocks (Unicode █▓▒░ )'],
  '极简 (2 级 # )': ['極簡 (2 級 # )', 'Minimal (2 levels # )'],
  '自定义…': ['自訂…', 'Custom…'],
  '按暗->亮输入字符, 如 @%# ': ['按暗→亮輸入字元, 如 @%# ', 'Enter chars from dark to light, e.g. @%# '],
  '反色': ['反色', 'Invert'],
  '亮度': ['亮度', 'Brightness'],
  '对比度': ['對比度', 'Contrast'],
  '结果预览 ({l} 行 · {c} 字符 · 点击复制):': ['結果預覽 ({l} 行 · {c} 字元 · 點擊複製):', 'Preview ({l} lines · {c} chars · click to copy):'],
  '复制文本': ['複製文字', 'Copy text'],
  '下载 .txt': ['下載 .txt', 'Download .txt'],
  '提示: 预览按等宽字体 2:1 比例示意, 复制到 Markdown 代码块 / 等宽字体编辑器查看效果最佳': ['提示: 預覽以等寬字型 2:1 比例示意, 複製到 Markdown 程式碼區塊 / 等寬字型編輯器檢視效果最佳', 'Tip: the preview simulates a monospace font at a 2:1 ratio; the result looks best pasted into a Markdown code block or a monospace editor'],
  '请先输入内容生成二维码': ['請先輸入內容產生二維碼', 'Enter content to generate a QR code first'],
  '二维码图片已保存': ['二維碼圖片已儲存', 'QR code image saved'],
  '请先输入内容': ['請先輸入內容', 'Enter some content first'],
  '二维码生成失败, 请检查内容后重试': ['二維碼產生失敗, 請檢查內容後重試', 'QR generation failed — check the content and retry'],
  '已保存 {n} 个 ({f} 行内容过长未生成)': ['已儲存 {n} 個 ({f} 行內容過長未產生)', 'Saved {n} ({f} line(s) too long to generate)'],
  '已保存 {n} 个二维码': ['已儲存 {n} 個二維碼', 'Saved {n} QR code(s)'],
  '已取消保存': ['已取消儲存', 'Save cancelled'],
  '容错等级:': ['容錯等級:', 'Error correction:'],
  '颜色:': ['顏色:', 'Color:'],
  '背景色:': ['背景色:', 'Background:'],
  '尺寸:': ['尺寸:', 'Size:'],
  '单个': ['單個', 'Single'],
  '批量': ['批次', 'Batch'],
  '需要生成二维码的内容': ['需要產生二維碼的內容', 'Content to encode into the QR code'],
  '保存图片': ['儲存圖片', 'Save image'],
  '点击下载二维码': ['點擊下載二維碼', 'Click to download the QR code'],
  '每行一个二维码内容, 一次生成 {n} 行以内; 导出时桌面版选择文件夹一次保存全部图片, 网页版逐个下载。': ['每行一個二維碼內容, 一次產生 {n} 行以內; 匯出時桌面版選擇資料夾一次儲存全部圖片, 網頁版逐個下載。', 'One QR code per line, up to {n} lines at a time; on export the desktop build saves all images into a chosen folder at once, while the web demo downloads them one by one.'],
  '批量内容 (每行一个二维码)\n\n示例:\nhttps://example.com/page/1\nhttps://example.com/page/2\nhttps://example.com/page/3': ['批次內容 (每行一個二維碼)\n\n範例:\nhttps://example.com/page/1\nhttps://example.com/page/2\nhttps://example.com/page/3', 'Batch content (one QR per line)\n\nExample:\nhttps://example.com/page/1\nhttps://example.com/page/2\nhttps://example.com/page/3'],
  '{n} 行': ['{n} 行', '{n} line(s)'],
  ' (超过 {m} 行, 已截断)': [' (超過 {m} 行, 已截斷)', ' (over {m} lines, truncated)'],
  '文件名前缀:': ['檔名前綴:', 'Filename prefix:'],
  '导出全部 PNG': ['匯出全部 PNG', 'Export all PNG'],
  '清空': ['清空', 'Clear'],
  'PNG 图片': ['PNG 圖片', 'PNG image'],
  'JPEG 图片': ['JPEG 圖片', 'JPEG image'],
  'WebP 图片': ['WebP 圖片', 'WebP image'],
  '图片生成失败': ['圖片產生失敗', 'Image generation failed'],
  '我的预设': ['我的預設', 'My presets'],
  '预设': ['預設', 'Preset'],
  '选常用尺寸填充': ['選常用尺寸填入', 'Pick a common size'],
  '尺寸': ['尺寸', 'Size'],
  '宽': ['寬', 'W'],
  '高': ['高', 'H'],
  '格式': ['格式', 'Format'],
  '显示文字': ['顯示文字', 'Text'],
  '留空则显示默认文字: {d}': ['留空則顯示預設文字: {d}', 'Leave blank to show the default text: {d}'],
  '默认': ['預設', 'Default'],
  '背景颜色': ['背景顏色', 'Background color'],
  '生成图片': ['產生圖片', 'Generate'],
  '宽高范围 {a}–{b}px; 文字过长会自动缩小字号或截断; 已生成后修改参数会自动刷新图片; 常用尺寸见预设下拉, 设置页可自定预设': ['寬高範圍 {a}–{b}px; 文字過長會自動縮小字級或截斷; 已產生後修改參數會自動重新整理圖片; 常用尺寸見預設下拉, 設定頁可自訂預設', 'Size range {a}–{b}px; text that is too long shrinks or is truncated; once generated, changing the parameters refreshes the image automatically. Common sizes are in the preset dropdown; the settings page lets you define your own'],
  '预览 (点击图片弹窗保存)': ['預覽 (點擊圖片彈窗儲存)', 'Preview (click the image to open the save dialog)'],
  '{w}×{h} · {f} · 点击图片查看并保存': ['{w}×{h} · {f} · 點擊圖片檢視並儲存', '{w}×{h} · {f} · click the image to view and save'],
  '设置参数后点击「生成图片」, 图片将显示在此处; 点击图片可弹窗下载保存': ['設定參數後點擊「產生圖片」, 圖片將顯示在此處; 點擊圖片可彈窗下載儲存', 'After setting the options click Generate — the image appears here; click it to open the save dialog'],
  '保存占位图 {name}': ['儲存佔位圖 {name}', 'Save placeholder {name}'],
  '保存占位图 · {s}': ['儲存佔位圖 · {s}', 'Save placeholder · {s}'],
  '代码截图': ['程式碼截圖', 'Code Screenshot'],
  'Shiki 语法高亮 + 一键导出 PNG。支持全部内置语言（常用语言置顶），编辑器风格可选 Mac / VSCode / IntelliJ / Sublime / Vim / Emacs，明暗自适应配色，默认值均可在「设置 → 其它」中调整。': ['Shiki 語法高亮 + 一鍵匯出 PNG。支援全部內建語言（常用語言置頂），編輯器風格可選 Mac / VSCode / IntelliJ / Sublime / Vim / Emacs，明暗自適應配色，預設值均可在「設定 → 其它」中調整。', 'Shiki syntax highlighting with one-click PNG export. All built-in languages are supported (common ones on top); editor styles include Mac / VSCode / IntelliJ / Sublime / Vim / Emacs with light/dark-adaptive themes. Defaults can be changed under Settings → Other.'],
  '代码与外观': ['程式碼與外觀', 'Code & appearance'],
  '载入示例': ['載入範例', 'Load sample'],
  '语言': ['語言', 'Language'],
  '常用': ['常用', 'Common'],
  '全部 ({n})': ['全部 ({n})', 'All ({n})'],
  '编辑器': ['編輯器', 'Editor'],
  '外观': ['外觀', 'Appearance'],
  '深色': ['深色', 'Dark'],
  '浅色': ['淺色', 'Light'],
  '内边距': ['內邊距', 'Padding'],
  '显示行号': ['顯示行號', 'Show line numbers'],
  '粘贴需要截图的代码…': ['貼上需要截圖的程式碼…', 'Paste the code you want to capture…'],
  '截图预览': ['截圖預覽', 'Preview'],
  '导出 PNG': ['匯出 PNG', 'Export PNG'],
  '已导出 PNG': ['已匯出 PNG', 'PNG exported'],
  '导出失败: {msg}': ['匯出失敗: {msg}', 'Export failed: {msg}'],
  '高亮失败': ['高亮失敗', 'Highlighting failed'],
  '高亮中…': ['高亮中…', 'Highlighting…'],
  '导出尺寸 = 截图内容实际像素 × 2 (pixelRatio); 行号随行对齐并随 PNG 一并导出。若内边距较小时圆角会自动收小, 避免代码压弧产生暗圈。': ['匯出尺寸 = 截圖內容實際像素 × 2 (pixelRatio); 行號隨行對齊並隨 PNG 一併匯出。若內邊距較小時圓角會自動縮小, 避免程式碼壓弧產生暗圈。', 'Export size = the actual pixels of the captured content × 2 (pixelRatio); line numbers stay aligned with lines and are exported with the PNG. When padding is small the corner radius shrinks so the code never touches the arc edge.'],
  '输入代码后实时预览，点击「导出 PNG」生成图片。': ['輸入程式碼後即時預覽，點擊「匯出 PNG」產生圖片。', 'Preview updates live as you type — click Export PNG to generate the image.'],
  '将保存为': ['將儲存為', 'Will be saved as'],
  ' ({kb} KB)': [' ({kb} KB)', ' ({kb} KB)'],
  '自动切换 A/B/C 子集, 支持全部可打印 ASCII 字符': ['自動切換 A/B/C 子集, 支援全部可列印 ASCII 字元', 'Automatically switches A/B/C subsets; supports all printable ASCII characters'],
  '数字、大写字母与常用符号 (ASCII 32-95)': ['數字、大寫字母與常用符號 (ASCII 32-95)', 'Digits, uppercase letters and common symbols (ASCII 32-95)'],
  'ASCII 32-127 (含小写字母)': ['ASCII 32-127 (含小寫字母)', 'ASCII 32-127 (including lowercase letters)'],
  '仅数字且位数必须为偶数': ['僅數字且位數必須為偶數', 'Digits only and the length must be even'],
  '输入 12 位自动补校验位, 或输入完整 13 位': ['輸入 12 位自動補檢查碼, 或輸入完整 13 位', 'Enter 12 digits and the check digit is added automatically, or enter the full 13'],
  '输入 7 位自动补校验位, 或输入完整 8 位': ['輸入 7 位自動補檢查碼, 或輸入完整 8 位', 'Enter 7 digits and the check digit is added automatically, or enter the full 8'],
  '输入 11 位自动补校验位, 或输入完整 12 位': ['輸入 11 位自動補檢查碼, 或輸入完整 12 位', 'Enter 11 digits and the check digit is added automatically, or enter the full 12'],
  '0-9 A-Z 及 - . 空格 $ / + %': ['0-9 A-Z 及 - . 空格 $ / + %', '0-9 A-Z and - . space $ / + %'],
  '输入 13 位自动补校验位, 或输入完整 14 位': ['輸入 13 位自動補檢查碼, 或輸入完整 14 位', 'Enter 13 digits and the check digit is added automatically, or enter the full 14'],
  'MSI (Mod 10 校验)': ['MSI (Mod 10 檢查碼)', 'MSI (Mod 10 checksum)'],
  'Mod 10 校验位': ['Mod 10 檢查碼', 'Mod 10 check digit'],
  'Mod 11 校验位': ['Mod 11 檢查碼', 'Mod 11 check digit'],
  '双 Mod 10 校验位': ['雙 Mod 10 檢查碼', 'Double Mod 10 check digit'],
  'Mod 11 + Mod 10 校验位': ['Mod 11 + Mod 10 檢查碼', 'Mod 11 + Mod 10 check digit'],
  '取值范围 3-131070': ['取值範圍 3-131070', 'Value range 3-131070'],
  'ITF 交错 2/5': ['ITF 交錯 2/5', 'ITF 2/5 Interleaved'],
  '校验位不正确, 请检查最后一位数字': ['檢查碼不正確, 請檢查最後一位數字', 'Incorrect check digit — please check the last digit'],
  'CODE128 仅支持可打印 ASCII 字符 (空格及可见字符)': ['CODE128 僅支援可列印 ASCII 字元 (空格及可見字元)', 'CODE128 supports printable ASCII characters only (space and visible characters)'],
  'CODE128 A 仅支持数字、大写字母与常用符号 (ASCII 32-95)': ['CODE128 A 僅支援數字、大寫字母與常用符號 (ASCII 32-95)', 'CODE128 A supports digits, uppercase letters and common symbols only (ASCII 32-95)'],
  'CODE128 B 仅支持 ASCII 32-126 (含小写字母)': ['CODE128 B 僅支援 ASCII 32-126 (含小寫字母)', 'CODE128 B supports ASCII 32-126 only (including lowercase letters)'],
  'CODE128 C 仅支持数字且位数必须为偶数': ['CODE128 C 僅支援數字且位數必須為偶數', 'CODE128 C supports digits only and the length must be even'],
  'EAN-13 需要 12 或 13 位数字': ['EAN-13 需要 12 或 13 位數字', 'EAN-13 needs 12 or 13 digits'],
  'EAN-8 需要 7 或 8 位数字': ['EAN-8 需要 7 或 8 位數字', 'EAN-8 needs 7 or 8 digits'],
  'UPC-A 需要 11 或 12 位数字': ['UPC-A 需要 11 或 12 位數字', 'UPC-A needs 11 or 12 digits'],
  'CODE39 仅支持: 0-9 A-Z 及 - . 空格 $ / + %': ['CODE39 僅支援: 0-9 A-Z 及 - . 空格 $ / + %', 'CODE39 supports: 0-9 A-Z and - . space $ / + %'],
  'ITF-14 需要 13 或 14 位数字': ['ITF-14 需要 13 或 14 位數字', 'ITF-14 needs 13 or 14 digits'],
  'ITF 仅支持数字且位数必须为偶数': ['ITF 僅支援數字且位數必須為偶數', 'ITF supports digits only and the length must be even'],
  'MSI 系列仅支持数字': ['MSI 系列僅支援數字', 'MSI variants support digits only'],
  'Pharmacode 仅支持数字': ['Pharmacode 僅支援數字', 'Pharmacode supports digits only'],
  'Pharmacode 取值范围为 3-131070': ['Pharmacode 取值範圍為 3-131070', 'Pharmacode value must be in 3-131070'],
  '请先输入内容生成条形码': ['請先輸入內容產生條碼', 'Enter content to generate a barcode first'],
  '条形码图片已保存': ['條碼圖片已儲存', 'Barcode image saved'],
  '条形码生成失败, 请检查内容后重试': ['條碼產生失敗, 請檢查內容後重試', 'Barcode generation failed — check the content and retry'],
  '已保存 {n} 个 ({f} 行内容不符合 {fmt} 规则被跳过)': ['已儲存 {n} 個 ({f} 行內容不符合 {fmt} 規則被跳過)', 'Saved {n} ({f} line(s) skipped for not matching the {fmt} rules)'],
  '已保存 {n} 个条形码': ['已儲存 {n} 個條碼', 'Saved {n} barcode(s)'],
  '格式:': ['格式:', 'Format:'],
  '条宽:': ['條寬:', 'Bar width:'],
  '显示内容:': ['顯示內容:', 'Show text:'],
  '显示': ['顯示', 'Show'],
  '隐藏': ['隱藏', 'Hide'],
  '输入内容后自动生成条形码 ({h})': ['輸入內容後自動產生條碼 ({h})', 'The barcode is generated automatically as you type ({h})'],
  '下载 PNG': ['下載 PNG', 'Download PNG'],
  '点击下载条形码 PNG': ['點擊下載條碼 PNG', 'Click to download the barcode PNG'],
  '每行一个编码内容, 一次生成 {n} 行以内; 不符合当前 {fmt} 编码规则的行走自动跳过; 导出时桌面版选择文件夹一次保存全部图片, 网页版逐个下载。': ['每行一個編碼內容, 一次產生 {n} 行以內; 不符合目前 {fmt} 編碼規則的行會自動跳過; 匯出時桌面版選擇資料夾一次儲存全部圖片, 網頁版逐個下載。', 'One encoded value per line, up to {n} lines at a time; lines not matching the current {fmt} rules are skipped automatically. On export the desktop build saves all images into a chosen folder at once, while the web demo downloads them one by one.'],
  '批量内容 (每行一个条形码)\n\n示例:\n6901028040479\n4006381333931\nABC-12345\nhttps://example.com': ['批次內容 (每行一個條碼)\n\n範例:\n6901028040479\n4006381333931\nABC-12345\nhttps://example.com', 'Batch content (one barcode per line)\n\nExample:\n6901028040479\n4006381333931\nABC-12345\nhttps://example.com'],
  '生成失败: ': ['產生失敗: ', 'Generation failed: '],
};
export const im = (locale: string, zh: string): string => {
  const e = D[zh];
  if (!e) return zh;
  return locale === 'zh-TW' ? e[0] : locale === 'en' ? e[1] : zh;
};
export const imT = (locale: string, zh: string, v?: Record<string, string | number>): string => {
  let s = im(locale, zh);
  if (v) for (const [k, val] of Object.entries(v)) s = s.split('{'+k+'}').join(String(val));
  return s;
};
