// Image Generators (图片生成) 分类页面共享词条: zh 原文即 key, 值为 [zh-TW, en]
// 用法: const t = (zh:string) => im(locale, zh); 动态模板: imT(locale, zhTpl, {x:...}) (占位符 {x})
// 各工具 data.ts / lib.ts 数据默认文案 (如平台标题) 不修改源码, 在渲染处用 t() 包装翻译
type WmRec = Record<string, [string, string]>;
const D: WmRec = {
  '复制到粘贴板成功！！！': ['複製到剪貼簿成功！！！', 'Copied to clipboard!!!'],
  '拖拽要生成 Base64 编码的图片文件到框内': ['拖曳要產生 Base64 編碼的圖片檔案到框內', 'Drag an image file into the box to Base64-encode it'],
  '点击复制内容到粘贴板': ['點擊複製內容到剪貼簿', 'Click to copy to clipboard'],
  '清除': ['清除', 'Clear'],
  '宽度:': ['寬度:', 'Width:'],
  '高度:': ['高度:', 'Height:'],
  '说明:': ['說明:', 'Alt text:'],
  '预览': ['預覽', 'Preview'],
  'SVG 内容已复制到剪贴板': ['SVG 內容已複製到剪貼簿', 'SVG copied to clipboard'],
  '复制失败, 请手动选中下方代码复制': ['複製失敗, 請手動選取下方程式碼複製', 'Copy failed — please select the code below and copy it manually'],
  '保存 {name}': ['儲存 {name}', 'Save {name}'],
  'SVG 图片': ['SVG 圖片', 'SVG image'],
  '已保存 {name}': ['已儲存 {name}', 'Saved {name}'],
  '保存失败': ['儲存失敗', 'Save failed'],
  '图片加载失败': ['圖片載入失敗', 'Failed to load the image'],
  '当前环境不支持绘制 PNG': ['目前環境不支援繪製 PNG', 'PNG rendering is not supported in this environment'],
  '已保存 {name} ({w}×{h}px)': ['已儲存 {name} ({w}×{h}px)', 'Saved {name} ({w}×{h}px)'],
  'PNG 保存失败': ['PNG 儲存失敗', 'Failed to save PNG'],
  '文字': ['文字', 'Label'],
  '左侧文字 (如 php)': ['左側文字 (如 php)', 'Left text (e.g. php)'],
  '状态': ['狀態', 'Value'],
  '右侧状态文字 (如 8.0)': ['右側狀態文字 (如 8.0)', 'Right status text (e.g. 8.0)'],
  '文字颜色': ['文字顏色', 'Label color'],
  '状态颜色': ['狀態顏色', 'Value color'],
  '左侧底色固定 #555 (shields 风格)': ['左側底色固定為 #555 (shields 風格)', 'Left background is fixed at #555 (shields style)'],
  '图片尺寸': ['圖片尺寸', 'Image scale'],
  '倍率': ['倍率', 'Export size'],
  '导出 PNG 为 {w}×{h}px (badge 高 20, 随文字变宽)': ['匯出 PNG 為 {w}×{h}px (badge 高 20, 隨文字變寬)', 'PNG export is {w}×{h}px (badge height 20, width grows with text)'],
  '实时生成 shields.io 风格 SVG; 文字与状态留空时相应段落自动隐藏; SVG 为矢量格式, 放大不模糊': ['即時產生 shields.io 風格 SVG; 文字與狀態留空時對應區塊會自動隱藏; SVG 為向量格式, 放大不模糊', 'Generates a shields.io-style SVG live; when label or value is empty that segment hides automatically. SVG is vector — it stays sharp when scaled up'],
  '预览 (点击复制 SVG):': ['預覽 (點擊複製 SVG):', 'Preview (click to copy SVG):'],
  '请填写文字或状态后生成预览': ['請填寫文字或狀態後產生預覽', 'Fill in the label or value to see the preview'],
  '点击复制 SVG 内容': ['點擊複製 SVG 內容', 'Click to copy the SVG'],
  '{n} 字符 · {a} | {b}': ['{n} 字元 · {a} | {b}', '{n} chars · {a} | {b}'],
  '复制 SVG 内容': ['複製 SVG 內容', 'Copy SVG'],
  '保存为 .svg': ['儲存為 .svg', 'Save as .svg'],
  '导出 PNG ({s}×)': ['匯出 PNG ({s}×)', 'Export PNG ({s}×)'],
  'SVG 源码:': ['SVG 原始碼:', 'SVG source:'],
  'PNG 生成失败': ['PNG 產生失敗', 'PNG generation failed'],
  '请选择图片文件 (PNG/JPG/WebP 等)': ['請選擇圖片檔案 (PNG/JPG/WebP 等)', 'Choose an image file (PNG/JPG/WebP etc.)'],
  '生成失败': ['產生失敗', 'Generation failed'],
  '请先上传一张图片': ['請先上傳一張圖片', 'Upload an image first'],
  'App Icon 生成 · 批量结果 ({n} 张)': ['App Icon 產生 · 批次結果 ({n} 張)', 'App Icon generator — batch result ({n} icons)'],
  '【{t}】{d}:': ['【{t}】{d}:', '[{t}] {d}:'],
  '批量下载 App 图标': ['批次下載 App 圖示', 'Download app icons (batch)'],
  'ZIP 压缩包': ['ZIP 壓縮檔', 'ZIP archive'],
  '已生成 {n} 张图标并打包下载': ['已產生 {n} 張圖示並打包下載', 'Generated {n} icons and packed them for download'],
  '打包失败': ['打包失敗', 'Packaging failed'],
  '点击或拖拽图片到此处': ['點擊或拖曳圖片到此處', 'Click or drag an image here'],
  '建议 1024×1024 方形、无透明底素材': ['建議 1024×1024 方形、無透明底素材', 'A square 1024×1024 source without transparency is recommended'],
  ' · 当前: {name}': [' · 目前: {name}', ' · current: {name}'],
  '{n} 张': ['{n} 張', '{n} icon(s)'],
  'Apple HIG 规范 (含 iPhone/iPad/App Store 1024)': ['Apple HIG 規範 (含 iPhone/iPad/App Store 1024)', 'Apple HIG spec (incl. iPhone/iPad/App Store 1024)'],
  'Google 官方 mipmap 密度目录': ['Google 官方 mipmap 密度目錄', 'Google official mipmap density folders'],
  'Cordova res/icon 官方目录结构': ['Cordova res/icon 官方目錄結構', 'Cordova res/icon official folder layout'],
  '像素: {p}': ['像素: {p}', 'Pixels: {p}'],
  '点击卡片可勾选 / 取消平台, 选中的平台才会被打包下载 (当前选中 {n} 张)': ['點擊卡片可勾選 / 取消平台, 選中的平台才會被打包下載 (目前選中 {n} 張)', 'Click a card to select / deselect a platform; only selected platforms are packed (currently {n} icons)'],
  '正在生成…': ['正在產生…', 'Generating…'],
  '下载所选平台图标 (.zip · {n} 张)': ['下載所選平台圖示 (.zip · {n} 張)', 'Download icons for selected platforms (.zip · {n} icons)'],
  '1024 主图标预览': ['1024 主圖示預覽', '1024 master icon preview'],
  '上传后预览': ['上傳後預覽', 'Preview after upload'],
  'iOS · Android · PhoneGap 三平台同时生成': ['iOS · Android · PhoneGap 三平台同時產生', 'Generates for all three platforms: iOS · Android · PhoneGap'],
  '查看输出文件清单 ({n} 个可选, 以下仅列出已选平台)': ['查看輸出檔案清單 ({n} 個可選, 以下僅列出已選平台)', 'Output file list ({n} available, only selected platforms listed)'],
  '{s}×{s} · ICO 文件 {n} 字节': ['{s}×{s} · ICO 檔案 {n} 位元組', '{s}×{s} · ICO file {n} bytes'],
  '保存 ICO 图标': ['儲存 ICO 圖示', 'Save ICO icon'],
  'ICO 图标': ['ICO 圖示', 'ICO icon'],
  '已保存 icon-{s}x{s}.ico': ['已儲存 icon-{s}x{s}.ico', 'Saved icon-{s}x{s}.ico'],
  '支持 PNG / JPG / WebP / GIF, 建议使用方形图标素材': ['支援 PNG / JPG / WebP / GIF, 建議使用方形圖示素材', 'PNG / JPG / WebP / GIF supported; a square source is recommended'],
  '生成尺寸': ['產生尺寸', 'Size'],
  '生成预览 ({s}×{s} 放大展示)': ['產生預覽 ({s}×{s} 放大顯示)', 'Preview ({s}×{s}, scaled up)'],
  '点击查看并保存': ['點擊檢視並儲存', 'Click to view and save'],
  '点击图标查看并保存 .ico': ['點擊圖示檢視並儲存 .ico', 'Click the icon to view and save .ico'],
  '暂无图标': ['暫無圖示', 'No icon yet'],
  '保存 ICO 图标 · {s}×{s}': ['儲存 ICO 圖示 · {s}×{s}', 'Save ICO icon · {s}×{s}'],
  '取消': ['取消', 'Cancel'],
  '保存为 {name}': ['儲存為 {name}', 'Save as {name}'],
  '将导出单尺寸 {s}×{s} ICO (32 位带透明通道), 可直接用作网站 favicon 或程序图标': ['將匯出單一尺寸 {s}×{s} ICO (32 位元含透明通道), 可直接用作網站 favicon 或程式圖示', 'Exports a single-size {s}×{s} ICO (32-bit with alpha) — ready to use as a website favicon or app icon'],
  '读取文件失败': ['讀取檔案失敗', 'Failed to read the file'],
  '图片解析失败, 请确认文件格式': ['圖片解析失敗, 請確認檔案格式', 'Failed to decode the image — check the file format'],
  '无法创建画布': ['無法建立畫布', 'Could not create canvas'],
  '请选择图片文件': ['請選擇圖片檔案', 'Choose an image file'],
  '已载入 {name} ({w}×{h}px)': ['已載入 {name} ({w}×{h}px)', 'Loaded {name} ({w}×{h}px)'],
  '载入失败': ['載入失敗', 'Load failed'],
  '已复制 {n} 字符到剪贴板': ['已複製 {n} 字元到剪貼簿', 'Copied {n} characters to clipboard'],
  '复制失败, 请手动选中文本复制': ['複製失敗, 請手動選取文字複製', 'Copy failed — please select the text and copy manually'],
  '文本文件': ['文字檔', 'Text file'],
  '点击或拖拽图片到此处载入': ['點擊或拖曳圖片到此處載入', 'Click or drag an image here to load'],
  '支持 png / jpg / webp / gif (首帧), 自动按最长边 600px 缩小处理': ['支援 png / jpg / webp / gif (首幀), 自動依最長邊 600px 縮小處理', 'Supports png / jpg / webp / gif (first frame); shrunk automatically so the longest side is 600px'],
  '载入图片后自动生成 ASCII 图: 灰度字符按亮度映射, 可用下方参数实时调整': ['載入圖片後自動產生 ASCII 圖: 灰階字元依亮度對應, 可用下方參數即時調整', 'The ASCII art generates automatically after loading: gray levels map to characters by brightness and can be tuned live below'],
  '输出宽': ['輸出寬', 'Output width'],
  '字符': ['字元', 'chars'],
  '字符集': ['字元集', 'Char set'],
  '标准 (10 级 @%#*+=-:. )': ['標準 (10 級 @%#*+=-:. )', 'Standard (10 levels @%#*+=-:. )'],
  '密度块 (Unicode █▓▒░ )': ['密度塊 (Unicode █▓▒░ )', 'Density blocks (Unicode █▓▒░ )'],
  '极简 (2 级 # )': ['極簡 (2 級 # )', 'Minimal (2 levels # )'],
  '自定义…': ['自訂…', 'Custom…'],
  '按暗->亮输入字符, 如 @%# ': ['按暗→亮輸入字元, 如 @%# ', 'Enter chars from dark to light, e.g. @%# '],
  '反色': ['反色', 'Invert'],
  '亮度': ['亮度', 'Brightness'],
  '对比度': ['對比度', 'Contrast'],
  '结果预览 ({l} 行 · {c} 字符 · 点击复制):': ['結果預覽 ({l} 行 · {c} 字元 · 點擊複製):', 'Preview ({l} lines · {c} chars · click to copy):'],
  '复制文本': ['複製文字', 'Copy text'],
  '下载 .txt': ['下載 .txt', 'Download .txt'],
  '提示: 预览按等宽字体 2:1 比例示意, 复制到 Markdown 代码块 / 等宽字体编辑器查看效果最佳': ['提示: 預覽以等寬字型 2:1 比例示意, 複製到 Markdown 程式碼區塊 / 等寬字型編輯器檢視效果最佳', 'Tip: the preview simulates a monospace font at a 2:1 ratio; the result looks best pasted into a Markdown code block or a monospace editor'],
};
export const im = (locale: string, zh: string): string => {
  const e = D[zh];
  if (!e) return zh;
  return locale === 'zh-TW' ? e[0] : locale === 'en' ? e[1] : zh;
};
export const imT = (locale: string, zh: string, v?: Record<string, string | number>): string => {
  let s = im(locale, zh);
  if (v) for (const [k, val] of Object.entries(v)) s = s.split('{'+k+'}').join(String(val));
  return s;
};
