// 其余分类剩余工具共享词条 (formatter / misc / 统计等): zh 原文即 key, 值为 [zh-TW, en]
// 用法: const t = (zh:string) => u(locale, zh); 动态模板: uT(locale, zhTpl, {x:...}) (占位符 {x})
type UiRec = Record<string, [string, string]>;
const D: UiRec = {
  // 通用
  '已解读: {a} / {b}': ['已解讀: {a} / {b}', 'Parsed: {a} / {b}'],
  '解读失败: {m}': ['解讀失敗: {m}', 'Parse failed: {m}'],
  '已复制': ['已複製', 'Copied'],
  '载入示例': ['載入範例', 'Load sample'],
  '清空': ['清空', 'Clear'],
  '复制': ['複製', 'Copy'],
  '暂无结果 — 输入文本后自动排版。': ['尚無結果 — 輸入文字後自動排版。', 'No result yet — typing text reformats it automatically.'],
  '复制到粘贴板成功！！！': ['複製到剪貼簿成功！！！', 'Copied to clipboard!!!'],
  // CnEnSpacing 中英混排
  '中英文自动排版': ['中英文自動排版', 'Auto-spacing between Chinese and English'],
  '自动在中文与英文字母、数字之间插入空格（如 “使用HTML” → “使用 HTML”）。仅处理紧邻的混排边界：已存在的空格不会重复添加；标点符号、换行与段落结构不会被修改。': ['自動在中文與英文字母、數字之間插入空格（如「使用HTML」→「使用 HTML」）。僅處理緊鄰的混排邊界：已存在的空格不會重複加入；標點符號、換行與段落結構不會被修改。', 'Automatically inserts spaces between Chinese and adjacent Latin letters/digits (e.g. “使用HTML” → “使用 HTML”). Only tight mixed-script boundaries are touched: existing spaces are never duplicated, and punctuation, line breaks and paragraph structure are left intact.'],
  '待排版文本': ['待排版文字', 'Text to space'],
  '排版结果': ['排版結果', 'Result'],
  '粘贴中英混排文本…': ['貼上中英混排文字…', 'Paste mixed Chinese/English text…'],
  '已插入 ': ['已插入 ', 'Inserted '],
  ' 个空格': [' 個空格', ' space(s)'],
  // HtmlFormat
  'HTML 格式化': ['HTML 格式化', 'HTML formatter'],
  '美化格式化 HTML 代码: 块级元素缩进换行、行内元素保留在一行、文本空白自动折叠。script / style / pre / textarea 内容原样保留。缩进空格数可在右侧或「设置 → 格式化」中切换 2 / 4 空格。': ['美化格式化 HTML 程式碼: 區塊元素縮排換行、行內元素保留在同一行、文字空白自動摺疊。script / style / pre / textarea 內容原樣保留。縮排空格數可在右側或「設定 → 格式化」中切換 2 / 4 空格。', 'Prettifies HTML: block-level elements are indented on new lines, inline elements stay on one line, and text whitespace collapses. Content inside script / style / pre / textarea is preserved as-is. The indentation can be switched between 2 / 4 spaces on the right or under Settings → Formatting.'],
  'HTML 源码': ['HTML 原始碼', 'HTML source'],
  '格式化结果': ['格式化結果', 'Formatted result'],
  '2 空格': ['2 空格', '2 spaces'],
  '4 空格': ['4 空格', '4 spaces'],
  '粘贴 HTML 代码…': ['貼上 HTML 程式碼…', 'Paste HTML code…'],
  '如: <div><p>你好</p></div>': ['如: <div><p>你好</p></div>', 'e.g. <div><p>hello</p></div>'],
  '{n} 字符': ['{n} 字元', '{n} characters'],
  '暂无结果 — 输入 HTML 后自动格式化。': ['尚無結果 — 輸入 HTML 後自動格式化。', 'No result yet — pasting HTML formats it automatically.'],
  // LineCount 内容统计
  '选取内容已复制到粘贴板!!!': ['選取內容已複製到剪貼簿!!!', 'Selected content copied to clipboard!!!'],
  '去除空行': ['移除空行', 'Remove empty lines'],
  '提取内容': ['提取內容', 'Extract range'],
  '打开文件': ['開啟檔案', 'Open file'],
  '开始行数': ['開始行數', 'Start line'],
  '结束行数': ['結束行數', 'End line'],
  '行数:': ['行數:', 'Lines:'],
  '字符数:': ['字元數:', 'Characters:'],
  '输入需要统计的内容 或 拖拽文件到框内': ['輸入需要統計的內容 或 拖曳檔案到框內', 'Enter the content to count, or drop a file into the box'],
  '已复制格式化结果': ['已複製格式化結果', 'Formatted result copied'],
  '已下载 formatted.xml': ['已下載 formatted.xml', 'formatted.xml downloaded'],
  '已载入示例 XML': ['已載入範例 XML', 'Sample XML loaded'],
  '复制失败, 请手动全选复制': ['複製失敗, 請手動全選複製', 'Copy failed — select and copy manually'],
  'XML 格式化': ['XML 格式化', 'XML formatter'],
  'XML / XAML / SVG / plist / 配置文件美化缩进，支持 XML 声明、注释、CDATA 与处理指令的保留。标签未闭合、交叉嵌套或多余闭合会给出带行号的错误提示。': ['XML / XAML / SVG / plist / 設定檔美化縮排，支援 XML 宣告、註解、CDATA 與處理指令的保留。標籤未閉合、交叉巢狀或多餘閉合會給出帶行號的錯誤提示。', 'Prettifies XML / XAML / SVG / plist / config files; XML declarations, comments, CDATA and processing instructions are preserved. Unclosed tags, interleaved nesting or stray closing tags produce an error message with a line number.'],
  '原始 XML': ['原始 XML', 'Raw XML'],
  '在此粘贴 XML 源码…': ['在此貼上 XML 原始碼…', 'Paste XML source here…'],
  '例如: <config><server host="127.0.0.1"/></config>': ['例如: <config><server host="127.0.0.1"/></config>', 'e.g. <config><server host="127.0.0.1"/></config>'],
  '下载 .xml': ['下載 .xml', 'Download .xml'],
  'XML 语法错误': ['XML 語法錯誤', 'XML syntax error'],
  '原始 {c} 字符 / {n} 行': ['原始 {c} 字元 / {n} 行', 'Raw: {c} characters / {n} lines'],
  '格式化后 {c} 字符': ['格式化後 {c} 字元', 'After formatting: {c} characters'],
  '{n} 行': ['{n} 行', '{n} lines'],
  '暂无结果 — 在上方粘贴 XML 后自动格式化。': ['尚無結果 — 在上方貼上 XML 後自動格式化。', 'No result yet — pasting XML above formats it automatically.'],
  'SVG 格式化 / 压缩': ['SVG 格式化 / 壓縮', 'SVG formatter / minifier'],
  '基于 SVGO 引擎处理 SVG: 去除注释、冗余属性、多余分组并优化路径等。可「美化」为多行缩进或「压缩」为单行最小体积, 适合发布到网页前瘦身。': ['基於 SVGO 引擎處理 SVG: 移除註解、冗餘屬性、多餘群組並最佳化路徑等。可「美化」為多行縮排或「壓縮」為單行最小體積, 適合發佈到網頁前瘦身。', 'Processes SVG with the SVGO engine: removes comments, redundant attributes and extra groups, and optimizes paths. "Pretty" reformats to multi-line indentation, "Minify" produces a single-line minimum-size file — great for slimming SVGs before publishing.'],
  'SVG 源码': ['SVG 原始碼', 'SVG source'],
  '读取 .svg 文件': ['讀取 .svg 檔案', 'Read .svg file'],
  '粘贴 SVG 代码, 或读取本地 .svg 文件…': ['貼上 SVG 程式碼, 或讀取本機 .svg 檔案…', 'Paste SVG code, or read a local .svg file…'],
  '优化选项与结果': ['最佳化選項與結果', 'Options & result'],
  '压缩 (单行)': ['壓縮 (單行)', 'Minify (one line)'],
  '美化 (多行)': ['美化 (多行)', 'Pretty (multi-line)'],
  '优化中…': ['最佳化中…', 'Optimizing…'],
  '处理失败': ['處理失敗', 'Processing failed'],
  '节省 {a} B ({p}%)': ['節省 {a} B ({p}%)', 'Saved {a} B ({p}%)'],
  '体积无变化': ['體積無變化', 'No size change'],
  '下载 .svg': ['下載 .svg', 'Download .svg'],
  '预览:': ['預覽:', 'Preview:'],
  'SVG 预览': ['SVG 預覽', 'SVG preview'],
  '输入 SVG 后自动优化。文件 → 网络: 平均可缩小 30%~60%。': ['輸入 SVG 後自動最佳化。檔案 → 網路: 平均可縮小 30%~60%。', 'SVG is optimized automatically as you type. File → web: typically 30%~60% smaller.'],
  '已读取 {name} ({c} 字符)': ['已讀取 {name} ({c} 字元)', '{name} loaded ({c} characters)'],
  '数组': ['陣列', 'Array'],
  '对象': ['物件', 'Object'],
  '请先输入 JSON 字符串': ['請先輸入 JSON 字串', 'Enter a JSON string first'],
  '请先输入 JSON5 字符串': ['請先輸入 JSON5 字串', 'Enter a JSON5 string first'],
  'JSON 解析失败: {m}': ['JSON 解析失敗: {m}', 'JSON parse failed: {m}'],
  'JSON5 解析失败: {m}': ['JSON5 解析失敗: {m}', 'JSON5 parse failed: {m}'],
  '请先格式化 JSON 再保存': ['請先格式化 JSON 再儲存', 'Format the JSON before saving'],
  '请先格式化 JSON5 再保存': ['請先格式化 JSON5 再儲存', 'Format the JSON5 before saving'],
  'JSON 文件': ['JSON 檔案', 'JSON file'],
  'JSON5 文件': ['JSON5 檔案', 'JSON5 file'],
  '已保存 JSON 文件': ['已儲存 JSON 檔案', 'JSON file saved'],
  '已保存 JSON5 文件': ['已儲存 JSON5 檔案', 'JSON5 file saved'],
  '保存失败: {m}': ['儲存失敗: {m}', 'Save failed: {m}'],
  '请选择 .json 文件': ['請選擇 .json 檔案', 'Please choose a .json file'],
  '请选择 .json5 / .json 文件': ['請選擇 .json5 / .json 檔案', 'Please choose a .json5 / .json file'],
  '格式化后的 JSON 将显示在这里（每行左侧带行号，点击结果可复制）': ['格式化後的 JSON 將顯示在這裡（每行左側帶行號，點擊結果可複製）', 'The formatted JSON appears here (line numbers on the left; click the result to copy it)'],
  '格式化后的 JSON5 将显示在这里（每行左侧带行号，点击结果可复制）': ['格式化後的 JSON5 將顯示在這裡（每行左側帶行號，點擊結果可複製）', 'The formatted JSON5 appears here (line numbers on the left; click the result to copy it)'],
  '先在上方输入 JSON 并点击「格式化」，即可在此折叠/展开查看结构': ['先在上方輸入 JSON 並點擊「格式化」，即可在此摺疊/展開檢視結構', 'Enter JSON above and click Format, then fold/expand the structure here'],
  '先在上方输入 JSON5 并点击「格式化」，即可在此折叠/展开查看结构': ['先在上方輸入 JSON5 並點擊「格式化」，即可在此摺疊/展開檢視結構', 'Enter JSON5 above and click Format, then fold/expand the structure here'],
  '行号': ['行號', 'Line numbers'],
  '点击复制内容到粘贴板': ['點擊複製內容到剪貼簿', 'Click to copy'],
  '格式化': ['格式化', 'Format'],
  '转一行': ['轉一行', 'Minify'],
  '保存为 .json': ['儲存為 .json', 'Save as .json'],
  '保存为 .json5': ['儲存為 .json5', 'Save as .json5'],
  '打开 .json': ['開啟 .json', 'Open .json'],
  '打开 .json5': ['開啟 .json5', 'Open .json5'],
  '输入需要格式化的 JSON 字符串  或 拖拽 .json 文件到框内打开': ['輸入需要格式化的 JSON 字串  或 拖曳 .json 檔案到框內開啟', 'Enter the JSON to format, or drop a .json file into the box'],
  '输入 JSON5 字符串 (支持注释 // /* */、单引号、无引号键名、尾逗号)  或拖拽 .json5 文件到框内打开': ['輸入 JSON5 字串 (支援註解 // /* */、單引號、無引號鍵名、尾逗號)  或拖曳 .json5 檔案到框內開啟', 'Enter a JSON5 string (comments // /* */, single quotes, unquoted keys and trailing commas are supported), or drop a .json5 file into the box'],
  '文本（行号）': ['文字（行號）', 'Text (line numbers)'],
  '树形折叠': ['樹形摺疊', 'Tree view'],
  '请先输入 SQL 语句进行格式化': ['請先輸入 SQL 語句進行格式化', 'Enter a SQL statement to format first'],
  '语言类型:': ['語言類型:', 'Dialect:'],
  '关键字格式:': ['關鍵字格式:', 'Keyword case:'],
  '对齐方式:': ['對齊方式:', 'Indent style:'],
  '保存为 .sql': ['儲存為 .sql', 'Save as .sql'],
  '打开 SQL 文件': ['開啟 SQL 檔案', 'Open SQL file'],
  '输入需要格式化的 SQL 语句 或 拖拽 .sql 文件到框内': ['輸入需要格式化的 SQL 語句 或 拖曳 .sql 檔案到框內', 'Enter the SQL to format, or drop a .sql file into the box'],
  '保存 SQL 文件': ['儲存 SQL 檔案', 'Save SQL file'],
  'SQL 文件': ['SQL 檔案', 'SQL file'],
  '已保存 SQL 文件': ['已儲存 SQL 檔案', 'SQL file saved'],
  '读取文件失败: {m}': ['讀取檔案失敗: {m}', 'Failed to read file: {m}'],
  '左': ['左', 'Left'],
  '右': ['右', 'Right'],
  '已载入 {s}侧文件: {name} ({n} 行)': ['已載入 {s}側檔案: {name} ({n} 行)', 'Loaded {s}-side file: {name} ({n} lines)'],
  '点击选择文件，或将文件拖到此处': ['點擊選擇檔案，或將檔案拖到此處', 'Click to choose a file, or drop one here'],
  '左文件 (被比较基准)': ['左檔案 (被比較基準)', 'Left file (base for comparison)'],
  '右文件 (待比较)': ['右檔案 (待比較)', 'Right file (to compare)'],
  '{n} 行相同': ['{n} 行相同', '{n} lines identical'],
  '{n} 行仅左侧有': ['{n} 行僅左側有', '{n} lines only on the left'],
  '{n} 行仅右侧有': ['{n} 行僅右側有', '{n} lines only on the right'],
  '文本超长已截断比较前 4000 行': ['文字過長已截斷，比較前 4000 行', 'Input too long — only the first 4000 lines were compared'],
  '选择左侧文件': ['選擇左側檔案', 'Choose left file'],
  '选择右侧文件': ['選擇右側檔案', 'Choose right file'],
  '交换左右': ['交換左右', 'Swap sides'],
  '在左右区域各载入一个文件 (点击选择 / 拖拽), 自动按行 diff, 左侧红色 = 删除行, 右侧绿色 = 新增行': ['在左右區域各載入一個檔案 (點擊選擇 / 拖曳), 自動逐行 diff, 左側紅色 = 刪除行, 右側綠色 = 新增行', 'Load one file into each zone (click or drag) — rows are diffed automatically: red on the left = deleted lines, green on the right = added lines'],
  '左侧文件': ['左側檔案', 'Left file'],
  '右侧文件': ['右側檔案', 'Right file'],
  '(删除行红色)': ['(刪除行紅色)', '(deleted lines in red)'],
  '(新增行绿色)': ['(新增行綠色)', '(added lines in green)'],
  '共 {n} 个 diff 行, 仅渲染前 {m} 行': ['共 {n} 個 diff 行, 僅渲染前 {m} 行', '{n} diff lines total — only the first {m} are rendered'],
  '{n} 行 · {s} KB': ['{n} 行 · {s} KB', '{n} lines · {s} KB'],
  '拖拽要提取主体色的图片文件到框内': ['拖曳要提取主體色的圖片檔案到框內', 'Drop an image to extract its dominant colors'],
  '主题色提取中': ['主體色提取中', 'Extracting theme colors…'],
  '提取计算需要时间': ['提取計算需要時間', 'This may take a moment'],
  '读': ['讀', 'Read'],
  '写': ['寫', 'Write'],
  '执行': ['執行', 'Execute'],
  '属主 (u)': ['屬主 (u)', 'Owner (u)'],
  '属组 (g)': ['屬組 (g)', 'Group (g)'],
  '其它 (o)': ['其它 (o)', 'Others (o)'],
  '属主 (user / u)': ['屬主 (user / u)', 'Owner (user / u)'],
  '属组 (group / g)': ['屬組 (group / g)', 'Group (group / g)'],
  '其它 (other / o)': ['其它 (other / o)', 'Others (other / o)'],
  '输入 755 / 4755 / -rwxr-xr-x / chmod 命令': ['輸入 755 / 4755 / -rwxr-xr-x / chmod 命令', 'Enter 755 / 4755 / -rwxr-xr-x / a chmod command'],
  '解读': ['解讀', 'Parse'],
  '解读结果会同步到下方勾选区': ['解讀結果會同步到下方勾選區', 'The parsed result is synced to the checkboxes below'],
  '配置权限 (勾选后实时生成命令)': ['設定權限 (勾選後即時產生命令)', 'Set permissions (the command is generated live)'],
  '特殊位': ['特殊位', 'Special bits'],
  'setuid (4)': ['setuid (4)', 'setuid (4)'],
  'setgid (2)': ['setgid (2)', 'setgid (2)'],
  'sticky (1)': ['sticky (1)', 'sticky (1)'],
  '数值': ['數值', 'Numeric'],
  '符号': ['符號', 'Symbols'],
  '权限含义': ['權限含義', 'Permission meaning'],
  '无权限': ['無權限', 'No permission'],
  '文件名:': ['檔名:', 'File name:'],
  '复制命令': ['複製命令', 'Copy command'],
  '符号写法:': ['符號寫法:', 'Symbolic mode:'],
  'ls 显示:': ['ls 顯示:', 'ls display:'],
  '数字:': ['數字:', 'Numeric:'],
  ' chmod 权限说明 ': [' chmod 權限說明 ', ' chmod notes '],
  '数字': ['數字', 'Numeric'],
  '含义': ['含義', 'Meaning'],
  'Linux 权限分三组：属主 (u)、属组 (g)、其它 (o)，每组含读 (r=4)、写 (w=2)、执行 (x=1) 三个位，数值求和即为 0-7 的数字权限。数字串从左到右依次为 u/g/o，如': ['Linux 權限分三組：屬主 (u)、屬組 (g)、其它 (o)，每組含讀 (r=4)、寫 (w=2)、執行 (x=1) 三個位，數值求和即為 0-7 的數字權限。數字串從左到右依序為 u/g/o，如', 'Linux permissions have three scopes: owner (u), group (g) and others (o). Each scope has read (r=4), write (w=2) and execute (x=1) bits; summing them gives the 0-7 numeric permission. The digits map to u/g/o from left to right, e.g.'],
  '= u:rwx, g:r-x, o:r-x。': ['= u:rwx, g:r-x, o:r-x。', '= u:rwx, g:r-x, o:r-x.'],
  '首位为特殊位：4 = setuid（执行时以属主身份运行，如 passwd）、2 = setgid（目录内新建文件继承属组）、1 = sticky（仅属主可删除，如 /tmp）。ls 显示时 setuid/setgid 使 x 变为小写 s（无执行则为大写 S），sticky 使其它执行位变为 t/T。': ['首位為特殊位：4 = setuid（執行時以屬主身份執行，如 passwd）、2 = setgid（目錄內新建檔案繼承屬組）、1 = sticky（僅屬主可刪除，如 /tmp）。ls 顯示時 setuid/setgid 使 x 變成小寫 s（無執行則為大寫 S），sticky 使其它執行位變成 t/T。', 'The first digit is the special bit: 4 = setuid (runs with the owner identity, e.g. passwd), 2 = setgid (new files in the directory inherit the group), 1 = sticky (only the owner may delete, e.g. /tmp). In ls output, setuid/setgid turns x into lowercase s (uppercase S when not executable) and sticky turns the others-execute bit into t/T.'],
  '补码 (二进制)': ['補碼 (二進位)', "Two's complement (binary)"],
  '补码 (十六进制)': ['補碼 (十六進位)', "Two's complement (hex)"],
  '原码 (二进制)': ['原碼 (二進位)', 'Sign-magnitude (binary)'],
  '反码 (二进制)': ['反碼 (二進位)', "One's complement (binary)"],
  '十进制 → 原/反/补码': ['十進位 → 原/反/補碼', "Decimal → SM/1's/2's complement"],
  '编码 → 十进制': ['編碼 → 十進位', 'Encoding → decimal'],
  '位宽': ['位寬', 'Bit width'],
  '(bit)': ['(bit)', '(bit)'],
  '有符号 {r}': ['有符號 {r}', 'Signed {r}'],
  '无符号 {r}': ['無符號 {r}', 'Unsigned {r}'],
  '十进制整数': ['十進位整數', 'Decimal integer'],
  '输入十进制整数 (范围 {r})': ['輸入十進位整數 (範圍 {r})', 'Enter a decimal integer (range {r})'],
  '编码类型': ['編碼類型', 'Encoding type'],
  '十六进制': ['十六進位', 'Hexadecimal'],
  '二进制串': ['二進位串', 'Binary string'],
  '原码': ['原碼', 'Sign-magnitude'],
  '反码': ['反碼', "One's complement"],
  '补码': ['補碼', "Two's complement"],
  '十进制结果': ['十進位結果', 'Decimal result'],
  '输入 {b} 位补码十六进制 (可带 0x, 最多 {c} 位)': ['輸入 {b} 位補碼十六進位 (可帶 0x, 最多 {c} 位)', "Enter {b}-bit two's-complement hex (0x optional, up to {c} digits)"],
  '输入 {b} 位{k}二进制 (可少于 {b} 位, 高位补 0)': ['輸入 {b} 位{k}二進位 (可少於 {b} 位, 高位補 0)', 'Enter a {b}-bit {k} binary string (fewer than {b} bits allowed — padded with leading 0s)'],
  '−2^{b} 超出原码表示范围 (±(2^{b}−1))': ['−2^{b} 超出原碼表示範圍 (±(2^{b}−1))', '−2^{b} is outside the sign-magnitude range (±(2^{b}−1))'],
  '−2^{b} 超出反码表示范围 (±(2^{b}−1))': ['−2^{b} 超出反碼表示範圍 (±(2^{b}−1))', "−2^{b} is outside the one's-complement range (±(2^{b}−1))"],
  '{k} ({b}位)': ['{k} ({b}位)', '{k} ({b}-bit)'],
  '说明: 正数的原码 / 反码 / 补码相同; 负数的补码 = 反码 + 1。最左位为符号位 (0 正 / 1 负)。原码与反码可表示范围仅 ±(2^(N−1)−1), 因此 −2^(N−1) 只有补码表示。': ['說明: 正數的原碼 / 反碼 / 補碼相同; 負數的補碼 = 反碼 + 1。最左位為符號位 (0 正 / 1 負)。原碼與反碼可表示範圍僅 ±(2^(N−1)−1)，因此 −2^(N−1) 只有補碼表示。', "Notes: for positive numbers, sign-magnitude / one's complement / two's complement are identical; for negatives, two's complement = one's complement + 1. The leftmost bit is the sign bit (0 positive / 1 negative). Sign-magnitude and one's complement can only cover ±(2^(N−1)−1), so −2^(N−1) has a two's-complement representation only."],
  '动态口令': ['動態口令', 'One-time password'],
  'TOTP (时间)': ['TOTP (時間)', 'TOTP (time-based)'],
  'HOTP (计数)': ['HOTP (計數)', 'HOTP (counter-based)'],
  '兼容 Google / Microsoft Authenticator': ['相容 Google / Microsoft Authenticator', 'Works with Google / Microsoft Authenticator'],
  '密钥': ['金鑰', 'Secret'],
  '算法': ['演算法', 'Algorithm'],
  '位数': ['位數', 'Digits'],
  '步长(秒)': ['步長(秒)', 'Step (sec)'],
  '计数': ['計數', 'Counter'],
  '+1': ['+1', '+1'],
  'Base32, 如 GEZDGNBV…': ['Base32, 如 GEZDGNBV…', 'Base32, e.g. GEZDGNBV…'],
  '随机生成密钥': ['隨機產生金鑰', 'Generate a random secret'],
  '6 位': ['6 位', '6 digits'],
  '7 位': ['7 位', '7 digits'],
  '8 位': ['8 位', '8 digits'],
  '名称': ['名稱', 'Issuer'],
  '账号': ['帳號', 'Account'],
  '如 GitHub (可选)': ['如 GitHub (可選)', 'e.g. GitHub (optional)'],
  '用于扫码导入的标签': ['用於掃碼匯入的標籤', 'Label used when importing via QR'],
  '当前验证码': ['目前驗證碼', 'Current code'],
  '当前验证码 (每次使用后计数 +1)': ['目前驗證碼 (每次使用後計數 +1)', 'Current code (counter +1 after each use)'],
  '验证码已复制': ['驗證碼已複製', 'Code copied'],
  'otpauth 链接已复制': ['otpauth 連結已複製', 'otpauth link copied'],
  '{r} 秒后刷新': ['{r} 秒後刷新', 'Refreshes in {r}s'],
  '扫码添加至 Authenticator (otpauth://)': ['掃碼加入 Authenticator (otpauth://)', 'Scan to add to Authenticator (otpauth://)'],
  '复制导入链接': ['複製匯入連結', 'Copy import link'],
  '请输入或生成密钥': ['請輸入或產生金鑰', 'Enter or generate a secret'],
  '密钥格式有误': ['金鑰格式有誤', 'Invalid secret format'],
  'PPI = √(宽² + 高²) ÷ 对角线英寸': ['PPI = √(寬² + 高²) ÷ 對角線英吋', 'PPI = √(width² + height²) ÷ diagonal inches'],
  'Pentile 等效 ≈ RGB PPI × √(2/3) ≈ ×0.8165': ['Pentile 等效 ≈ RGB PPI × √(2/3) ≈ ×0.8165', 'Pentile equivalent ≈ RGB PPI × √(2/3) ≈ ×0.8165'],
  'RGB 排列: 每像素 3 子像素 | Pentile: 2 子像素': ['RGB 排列: 每像素 3 子像素 | Pentile: 2 子像素', 'RGB layout: 3 subpixels per pixel | Pentile: 2'],
  '常用屏幕:': ['常用螢幕:', 'Common screens:'],
  '选择常用分辨率 (可手动修改下方数值)': ['選擇常用解析度 (可手動修改下方數值)', 'Pick a common resolution (the values below stay editable)'],
  '分辨率:': ['解析度:', 'Resolution:'],
  '宽': ['寬', 'Width'],
  '高': ['高', 'Height'],
  'px': ['px', 'px'],
  '屏幕尺寸:': ['螢幕尺寸:', 'Screen size:'],
  '英寸': ['英吋', 'inches'],
  '请输入有效的分辨率(正整数)与屏幕尺寸(大于 0 英寸)': ['請輸入有效的解析度(正整數)與螢幕尺寸(大於 0 英吋)', 'Enter a valid resolution (positive integers) and screen size (greater than 0 inches)'],
  '标准 RGB 排列 PPI': ['標準 RGB 排列 PPI', 'Standard RGB PPI'],
  '每英寸像素 (对角线方向)': ['每英吋像素 (對角線方向)', 'Pixels per inch (diagonal)'],
  'Pentile 排列等效 PPI': ['Pentile 排列等效 PPI', 'Pentile-equivalent PPI'],
  'OLED 菱形排列, 红/蓝子像素共享, 等效 ≈ RGB × 0.8165': ['OLED 菱形排列, 紅/藍子像素共享, 等效 ≈ RGB × 0.8165', 'OLED diamond layout shares red/blue subpixels — equivalent ≈ RGB × 0.8165'],
  '物理尺寸 (宽 × 高)': ['物理尺寸 (寬 × 高)', 'Physical size (width × height)'],
  'RGB 子像素密度': ['RGB 子像素密度', 'RGB subpixel density'],
  'Pentile 子像素密度': ['Pentile 子像素密度', 'Pentile subpixel density'],
  '总像素': ['總像素', 'Total pixels'],
  '宽高比': ['寬高比', 'Aspect ratio'],
  '{a} × {b} 英寸': ['{a} × {b} 英吋', '{a} × {b} inches'],
  '{n} 个/英寸': ['{n} 個/英吋', '{n} per inch'],
  '{p} ({m} MP)': ['{p} ({m} MP)', '{p} ({m} MP)'],
  '提示: Pentile (如三星 Diamond 排列) 每个像素仅 2 个子像素, 等效视觉密度约为标准 RGB 的 √(2/3) ≈ 81.65%; 同分辨率下 Pentile 屏的理论细腻度低于 RGB 排列, 厂商常以更高分辨率(如 QHD+)弥补。': ['提示: Pentile (如三星 Diamond 排列) 每個像素僅 2 個子像素, 等效視覺密度約為標準 RGB 的 √(2/3) ≈ 81.65%; 同解析度下 Pentile 螢幕的理論細膩度低於 RGB 排列, 廠商常以更高解析度(如 QHD+)彌補。', "Note: on Pentile (e.g. Samsung's Diamond layout) each pixel has only 2 subpixels, so the perceived density is about √(2/3) ≈ 81.65% of standard RGB. At the same resolution a Pentile panel is theoretically less sharp than RGB; makers compensate with higher resolutions (e.g. QHD+)."],
  '输入或生成一个密码后显示强度评估': ['輸入或產生一個密碼後顯示強度評估', 'Type or generate a password to see its strength'],
  '强度:': ['強度:', 'Strength:'],
  '参考熵:': ['參考熵:', 'Entropy:'],
  '按每秒 1 万亿次猜测约需 {t}': ['按每秒 1 兆次猜測約需 {t}', 'At 1 trillion guesses/sec it would take about {t}'],
  '在线攻击:': ['線上攻擊:', 'Online attack:'],
  '按每秒 1000 次猜测约需 {t}': ['按每秒 1000 次猜測約需 {t}', 'At 1,000 guesses/sec it would take about {t}'],
  '极弱': ['極弱', 'Very weak'],
  '弱': ['弱', 'Weak'],
  '一般': ['一般', 'Fair'],
  '强': ['強', 'Strong'],
  '极强': ['極強', 'Very strong'],
  '极易被暴力/字典破解, 请勿使用': ['極易被暴力/字典破解, 請勿使用', 'Trivially broken by brute force / dictionary attacks — do not use'],
  '容易被破解, 建议增加长度与字符类型': ['容易被破解, 建議增加長度與字元類型', 'Easy to crack — increase the length and add more character types'],
  '对普通场景可用, 敏感账户建议加强': ['對一般場景可用, 敏感帳戶建議加強', 'Fine for everyday use; strengthen it for sensitive accounts'],
  '当前配置较难被暴力破解': ['目前設定較難被暴力破解', 'Hard to brute force with the current settings'],
  '按现有算力需极长时间, 安全性很高': ['按現有算力需極長時間, 安全性很高', "Would take an extremely long time with today's hardware — very secure"],
  '长度 {n} (推荐 ≥12)': ['長度 {n} (建議 ≥12)', 'Length {n} (≥12 recommended)'],
  '大小写混合': ['大小寫混合', 'Mixed case'],
  '建议混合大小写': ['建議混合大小寫', 'Use mixed case'],
  '包含数字': ['包含數字', 'Has digits'],
  '建议包含数字': ['建議包含數字', 'Add digits'],
  '包含符号': ['包含符號', 'Has symbols'],
  '包含中文/符号': ['包含中文/符號', 'Has CJK / symbols'],
  '建议包含符号或中文': ['建議包含符號或中文', 'Add symbols or CJK characters'],
  '命中常见弱口令库': ['命中常見弱密碼庫', 'Hit the common-password list'],
  '未命中常见弱口令库': ['未命中常見弱密碼庫', 'Not on the common-password list'],
  '存在连续 {n} 个相同字符': ['存在連續 {n} 個相同字元', 'Has {n} identical characters in a row'],
  '无连续重复字符': ['無連續重複字元', 'No repeated-run characters'],
  '存在键盘/字母/数字连续序列': ['存在鍵盤/字母/數字連續序列', 'Has a keyboard/alphabet/digit sequence'],
  '无连续序列': ['無連續序列', 'No consecutive sequences'],
  '当前强度: ': ['目前強度: ', 'Current strength: '],
  '所有生成与强度评估均在本地完成, 密码不会离开设备; 建议长度 ≥ 12 并混合大小写、数字与符号。强度仅为启发式估算, 不能替代权威评估。': ['所有產生與強度評估均在本機完成, 密碼不會離開裝置; 建議長度 ≥ 12 並混合大小寫、數字與符號。強度僅為啟發式估算, 不能取代權威評估。', 'Generation and strength checks all run locally — the password never leaves your device. A length ≥ 12 mixing upper/lower case, digits and symbols is recommended. Strength is only a heuristic estimate, not a substitute for authoritative evaluation.'],
  '生成': ['產生', 'Generate'],
  '长度:': ['長度:', 'Length:'],
  '字符集:': ['字元集:', 'Character set:'],
  '大写 A-Z': ['大寫 A-Z', 'Uppercase A-Z'],
  '小写 a-z': ['小寫 a-z', 'Lowercase a-z'],
  '数字 0-9': ['數字 0-9', 'Digits 0-9'],
  '符号 !@#…': ['符號 !@#…', 'Symbols !@#…'],
  '选项:': ['選項:', 'Options:'],
  '排除易混淆字符 (IOlo01)': ['排除易混淆字元 (IOlo01)', 'Exclude ambiguous characters (IOlo01)'],
  '生成密码': ['產生密碼', 'Generate password'],
  '点击上方按钮生成随机密码': ['點擊上方按鈕產生隨機密碼', 'Click the button above to generate a random password'],
  '请先生成或输入密码': ['請先產生或輸入密碼', 'Generate or enter a password first'],
  '已复制到剪贴板': ['已複製到剪貼簿', 'Copied to clipboard'],
  '强度检测 (支持手工输入任意密码)': ['強度檢測 (支援手動輸入任意密碼)', 'Strength check (paste any password)'],
  '在此输入或粘贴要检测的密码': ['在此輸入或貼上要檢測的密碼', 'Enter or paste a password to check'],
  '常用正则 (在 设置 → 其它 中管理)': ['常用正則 (在 設定 → 其它 中管理)', 'Common regexes (managed under Settings → Misc)'],
  '一键复制规则: {p}': ['一鍵複製規則: {p}', 'Copy this rule: {p}'],
  '一键复制当前正则规则': ['一鍵複製目前正則規則', 'Copy the current regex'],
  '复制规则': ['複製規則', 'Copy rule'],
  '重新读取设置中的常用正则': ['重新讀取設定中的常用正則', 'Reload common regexes from settings'],
  '刷新': ['重新整理', 'Refresh'],
  '正则': ['正則', 'Regex'],
  '输入正则表达式, 例如 ^1[3-9]\\d{9}$': ['輸入正則表達式, 例如 ^1[3-9]\\d{9}$', 'Enter a regex, e.g. ^1[3-9]\\d{9}$'],
  'i 忽略大小写': ['i 忽略大小寫', 'i case-insensitive'],
  'g 全局': ['g 全域', 'g global'],
  'm 多行': ['m 多行', 'm multi-line'],
  's 点匹配换行': ['s 點匹配換行', 's dot matches newlines'],
  '正则表达式无效:': ['正則表達式無效:', 'Invalid regex:'],
  '在此输入多行内容, 逐行与正则匹配: 匹配行显示为绿色, 不匹配行显示为红色': ['在此輸入多行內容, 逐行與正則比對: 符合行顯示為綠色, 不符合行顯示為紅色', 'Enter multi-line content here — each line is matched: green = matched, red = not matched'],
  '复制匹配行': ['複製符合行', 'Copy matched lines'],
  '填入示例': ['填入範例', 'Load sample'],
  '清空正则': ['清空正則', 'Clear regex'],
  '匹配 {a} / {b} 行': ['符合 {a} / {b} 行', '{a} / {b} lines matched'],
  ', 共 {n} 处': [', 共 {n} 處', ', {n} matches in total'],
  '请先输入正则表达式': ['請先輸入正則表達式', 'Enter a regex first'],
  '没有匹配的行': ['沒有符合的行', 'No matching lines'],
  ' 正则表达式说明 ': [' 正則表達式說明 ', ' Regex notes '],
};

export const u = (locale: string, zh: string): string => {
  const hit = D[zh];
  if (!hit) return zh;
  return locale === 'zh-TW' ? hit[0] : locale === 'en' ? hit[1] : zh;
};

export const uT = (locale: string, zhTpl: string, vars?: Record<string, string | number>): string => {
  let out = u(locale, zhTpl);
  if (vars) out = out.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));
  return out;
};
