// 其余分类剩余工具共享词条 (formatter / misc / 统计等): zh 原文即 key, 值为 [zh-TW, en]
// 用法: const t = (zh:string) => u(locale, zh); 动态模板: uT(locale, zhTpl, {x:...}) (占位符 {x})
type UiRec = Record<string, [string, string]>;
const D: UiRec = {
  // 通用
  '已解读: {a} / {b}': ['已解讀: {a} / {b}', 'Parsed: {a} / {b}'],
  '解读失败: {m}': ['解讀失敗: {m}', 'Parse failed: {m}'],
  '已复制': ['已複製', 'Copied'],
  '载入示例': ['載入範例', 'Load sample'],
  '清空': ['清空', 'Clear'],
  '复制': ['複製', 'Copy'],
  '暂无结果 — 输入文本后自动排版。': ['尚無結果 — 輸入文字後自動排版。', 'No result yet — typing text reformats it automatically.'],
  '复制到粘贴板成功！！！': ['複製到剪貼簿成功！！！', 'Copied to clipboard!!!'],
  // CnEnSpacing 中英混排
  '中英文自动排版': ['中英文自動排版', 'Auto-spacing between Chinese and English'],
  '自动在中文与英文字母、数字之间插入空格（如 “使用HTML” → “使用 HTML”）。仅处理紧邻的混排边界：已存在的空格不会重复添加；标点符号、换行与段落结构不会被修改。': ['自動在中文與英文字母、數字之間插入空格（如「使用HTML」→「使用 HTML」）。僅處理緊鄰的混排邊界：已存在的空格不會重複加入；標點符號、換行與段落結構不會被修改。', 'Automatically inserts spaces between Chinese and adjacent Latin letters/digits (e.g. “使用HTML” → “使用 HTML”). Only tight mixed-script boundaries are touched: existing spaces are never duplicated, and punctuation, line breaks and paragraph structure are left intact.'],
  '待排版文本': ['待排版文字', 'Text to space'],
  '排版结果': ['排版結果', 'Result'],
  '粘贴中英混排文本…': ['貼上中英混排文字…', 'Paste mixed Chinese/English text…'],
  '已插入 ': ['已插入 ', 'Inserted '],
  ' 个空格': [' 個空格', ' space(s)'],
  // HtmlFormat
  'HTML 格式化': ['HTML 格式化', 'HTML formatter'],
  '美化格式化 HTML 代码: 块级元素缩进换行、行内元素保留在一行、文本空白自动折叠。script / style / pre / textarea 内容原样保留。缩进空格数可在右侧或「设置 → 格式化」中切换 2 / 4 空格。': ['美化格式化 HTML 程式碼: 區塊元素縮排換行、行內元素保留在同一行、文字空白自動摺疊。script / style / pre / textarea 內容原樣保留。縮排空格數可在右側或「設定 → 格式化」中切換 2 / 4 空格。', 'Prettifies HTML: block-level elements are indented on new lines, inline elements stay on one line, and text whitespace collapses. Content inside script / style / pre / textarea is preserved as-is. The indentation can be switched between 2 / 4 spaces on the right or under Settings → Formatting.'],
  'HTML 源码': ['HTML 原始碼', 'HTML source'],
  '格式化结果': ['格式化結果', 'Formatted result'],
  '2 空格': ['2 空格', '2 spaces'],
  '4 空格': ['4 空格', '4 spaces'],
  '粘贴 HTML 代码…': ['貼上 HTML 程式碼…', 'Paste HTML code…'],
  '如: <div><p>你好</p></div>': ['如: <div><p>你好</p></div>', 'e.g. <div><p>hello</p></div>'],
  '{n} 字符': ['{n} 字元', '{n} characters'],
  '暂无结果 — 输入 HTML 后自动格式化。': ['尚無結果 — 輸入 HTML 後自動格式化。', 'No result yet — pasting HTML formats it automatically.'],
  // LineCount 内容统计
  '选取内容已复制到粘贴板!!!': ['選取內容已複製到剪貼簿!!!', 'Selected content copied to clipboard!!!'],
  '去除空行': ['移除空行', 'Remove empty lines'],
  '提取内容': ['提取內容', 'Extract range'],
  '打开文件': ['開啟檔案', 'Open file'],
  '开始行数': ['開始行數', 'Start line'],
  '结束行数': ['結束行數', 'End line'],
  '行数:': ['行數:', 'Lines:'],
  '字符数:': ['字元數:', 'Characters:'],
  '输入需要统计的内容 或 拖拽文件到框内': ['輸入需要統計的內容 或 拖曳檔案到框內', 'Enter the content to count, or drop a file into the box'],
  '已复制格式化结果': ['已複製格式化結果', 'Formatted result copied'],
  '已下载 formatted.xml': ['已下載 formatted.xml', 'formatted.xml downloaded'],
  '已载入示例 XML': ['已載入範例 XML', 'Sample XML loaded'],
  '复制失败, 请手动全选复制': ['複製失敗, 請手動全選複製', 'Copy failed — select and copy manually'],
  'XML 格式化': ['XML 格式化', 'XML formatter'],
  'XML / XAML / SVG / plist / 配置文件美化缩进，支持 XML 声明、注释、CDATA 与处理指令的保留。标签未闭合、交叉嵌套或多余闭合会给出带行号的错误提示。': ['XML / XAML / SVG / plist / 設定檔美化縮排，支援 XML 宣告、註解、CDATA 與處理指令的保留。標籤未閉合、交叉巢狀或多餘閉合會給出帶行號的錯誤提示。', 'Prettifies XML / XAML / SVG / plist / config files; XML declarations, comments, CDATA and processing instructions are preserved. Unclosed tags, interleaved nesting or stray closing tags produce an error message with a line number.'],
  '原始 XML': ['原始 XML', 'Raw XML'],
  '在此粘贴 XML 源码…': ['在此貼上 XML 原始碼…', 'Paste XML source here…'],
  '例如: <config><server host="127.0.0.1"/></config>': ['例如: <config><server host="127.0.0.1"/></config>', 'e.g. <config><server host="127.0.0.1"/></config>'],
  '下载 .xml': ['下載 .xml', 'Download .xml'],
  'XML 语法错误': ['XML 語法錯誤', 'XML syntax error'],
  '原始 {c} 字符 / {n} 行': ['原始 {c} 字元 / {n} 行', 'Raw: {c} characters / {n} lines'],
  '格式化后 {c} 字符': ['格式化後 {c} 字元', 'After formatting: {c} characters'],
  '{n} 行': ['{n} 行', '{n} lines'],
  '暂无结果 — 在上方粘贴 XML 后自动格式化。': ['尚無結果 — 在上方貼上 XML 後自動格式化。', 'No result yet — pasting XML above formats it automatically.'],
  'SVG 格式化 / 压缩': ['SVG 格式化 / 壓縮', 'SVG formatter / minifier'],
  '基于 SVGO 引擎处理 SVG: 去除注释、冗余属性、多余分组并优化路径等。可「美化」为多行缩进或「压缩」为单行最小体积, 适合发布到网页前瘦身。': ['基於 SVGO 引擎處理 SVG: 移除註解、冗餘屬性、多餘群組並最佳化路徑等。可「美化」為多行縮排或「壓縮」為單行最小體積, 適合發佈到網頁前瘦身。', 'Processes SVG with the SVGO engine: removes comments, redundant attributes and extra groups, and optimizes paths. "Pretty" reformats to multi-line indentation, "Minify" produces a single-line minimum-size file — great for slimming SVGs before publishing.'],
  'SVG 源码': ['SVG 原始碼', 'SVG source'],
  '读取 .svg 文件': ['讀取 .svg 檔案', 'Read .svg file'],
  '粘贴 SVG 代码, 或读取本地 .svg 文件…': ['貼上 SVG 程式碼, 或讀取本機 .svg 檔案…', 'Paste SVG code, or read a local .svg file…'],
  '优化选项与结果': ['最佳化選項與結果', 'Options & result'],
  '压缩 (单行)': ['壓縮 (單行)', 'Minify (one line)'],
  '美化 (多行)': ['美化 (多行)', 'Pretty (multi-line)'],
  '优化中…': ['最佳化中…', 'Optimizing…'],
  '处理失败': ['處理失敗', 'Processing failed'],
  '节省 {a} B ({p}%)': ['節省 {a} B ({p}%)', 'Saved {a} B ({p}%)'],
  '体积无变化': ['體積無變化', 'No size change'],
  '下载 .svg': ['下載 .svg', 'Download .svg'],
  '预览:': ['預覽:', 'Preview:'],
  'SVG 预览': ['SVG 預覽', 'SVG preview'],
  '输入 SVG 后自动优化。文件 → 网络: 平均可缩小 30%~60%。': ['輸入 SVG 後自動最佳化。檔案 → 網路: 平均可縮小 30%~60%。', 'SVG is optimized automatically as you type. File → web: typically 30%~60% smaller.'],
  '已读取 {name} ({c} 字符)': ['已讀取 {name} ({c} 字元)', '{name} loaded ({c} characters)'],
  '数组': ['陣列', 'Array'],
  '对象': ['物件', 'Object'],
  '请先输入 JSON 字符串': ['請先輸入 JSON 字串', 'Enter a JSON string first'],
  '请先输入 JSON5 字符串': ['請先輸入 JSON5 字串', 'Enter a JSON5 string first'],
  'JSON 解析失败: {m}': ['JSON 解析失敗: {m}', 'JSON parse failed: {m}'],
  'JSON5 解析失败: {m}': ['JSON5 解析失敗: {m}', 'JSON5 parse failed: {m}'],
  '请先格式化 JSON 再保存': ['請先格式化 JSON 再儲存', 'Format the JSON before saving'],
  '请先格式化 JSON5 再保存': ['請先格式化 JSON5 再儲存', 'Format the JSON5 before saving'],
  'JSON 文件': ['JSON 檔案', 'JSON file'],
  'JSON5 文件': ['JSON5 檔案', 'JSON5 file'],
  '已保存 JSON 文件': ['已儲存 JSON 檔案', 'JSON file saved'],
  '已保存 JSON5 文件': ['已儲存 JSON5 檔案', 'JSON5 file saved'],
  '保存失败: {m}': ['儲存失敗: {m}', 'Save failed: {m}'],
  '请选择 .json 文件': ['請選擇 .json 檔案', 'Please choose a .json file'],
  '请选择 .json5 / .json 文件': ['請選擇 .json5 / .json 檔案', 'Please choose a .json5 / .json file'],
  '格式化后的 JSON 将显示在这里（每行左侧带行号，点击结果可复制）': ['格式化後的 JSON 將顯示在這裡（每行左側帶行號，點擊結果可複製）', 'The formatted JSON appears here (line numbers on the left; click the result to copy it)'],
  '格式化后的 JSON5 将显示在这里（每行左侧带行号，点击结果可复制）': ['格式化後的 JSON5 將顯示在這裡（每行左側帶行號，點擊結果可複製）', 'The formatted JSON5 appears here (line numbers on the left; click the result to copy it)'],
  '先在上方输入 JSON 并点击「格式化」，即可在此折叠/展开查看结构': ['先在上方輸入 JSON 並點擊「格式化」，即可在此摺疊/展開檢視結構', 'Enter JSON above and click Format, then fold/expand the structure here'],
  '先在上方输入 JSON5 并点击「格式化」，即可在此折叠/展开查看结构': ['先在上方輸入 JSON5 並點擊「格式化」，即可在此摺疊/展開檢視結構', 'Enter JSON5 above and click Format, then fold/expand the structure here'],
  '行号': ['行號', 'Line numbers'],
  '点击复制内容到粘贴板': ['點擊複製內容到剪貼簿', 'Click to copy'],
  '格式化': ['格式化', 'Format'],
  '转一行': ['轉一行', 'Minify'],
  '保存为 .json': ['儲存為 .json', 'Save as .json'],
  '保存为 .json5': ['儲存為 .json5', 'Save as .json5'],
  '打开 .json': ['開啟 .json', 'Open .json'],
  '打开 .json5': ['開啟 .json5', 'Open .json5'],
  '输入需要格式化的 JSON 字符串  或 拖拽 .json 文件到框内打开': ['輸入需要格式化的 JSON 字串  或 拖曳 .json 檔案到框內開啟', 'Enter the JSON to format, or drop a .json file into the box'],
  '输入 JSON5 字符串 (支持注释 // /* */、单引号、无引号键名、尾逗号)  或拖拽 .json5 文件到框内打开': ['輸入 JSON5 字串 (支援註解 // /* */、單引號、無引號鍵名、尾逗號)  或拖曳 .json5 檔案到框內開啟', 'Enter a JSON5 string (comments // /* */, single quotes, unquoted keys and trailing commas are supported), or drop a .json5 file into the box'],
  '文本（行号）': ['文字（行號）', 'Text (line numbers)'],
  '树形折叠': ['樹形摺疊', 'Tree view'],
  '请先输入 SQL 语句进行格式化': ['請先輸入 SQL 語句進行格式化', 'Enter a SQL statement to format first'],
  '语言类型:': ['語言類型:', 'Dialect:'],
  '关键字格式:': ['關鍵字格式:', 'Keyword case:'],
  '对齐方式:': ['對齊方式:', 'Indent style:'],
  '保存为 .sql': ['儲存為 .sql', 'Save as .sql'],
  '打开 SQL 文件': ['開啟 SQL 檔案', 'Open SQL file'],
  '输入需要格式化的 SQL 语句 或 拖拽 .sql 文件到框内': ['輸入需要格式化的 SQL 語句 或 拖曳 .sql 檔案到框內', 'Enter the SQL to format, or drop a .sql file into the box'],
  '保存 SQL 文件': ['儲存 SQL 檔案', 'Save SQL file'],
  'SQL 文件': ['SQL 檔案', 'SQL file'],
  '已保存 SQL 文件': ['已儲存 SQL 檔案', 'SQL file saved'],
  '读取文件失败: {m}': ['讀取檔案失敗: {m}', 'Failed to read file: {m}'],
  '左': ['左', 'Left'],
  '右': ['右', 'Right'],
  '已载入 {s}侧文件: {name} ({n} 行)': ['已載入 {s}側檔案: {name} ({n} 行)', 'Loaded {s}-side file: {name} ({n} lines)'],
  '点击选择文件，或将文件拖到此处': ['點擊選擇檔案，或將檔案拖到此處', 'Click to choose a file, or drop one here'],
  '左文件 (被比较基准)': ['左檔案 (被比較基準)', 'Left file (base for comparison)'],
  '右文件 (待比较)': ['右檔案 (待比較)', 'Right file (to compare)'],
  '{n} 行相同': ['{n} 行相同', '{n} lines identical'],
  '{n} 行仅左侧有': ['{n} 行僅左側有', '{n} lines only on the left'],
  '{n} 行仅右侧有': ['{n} 行僅右側有', '{n} lines only on the right'],
  '文本超长已截断比较前 4000 行': ['文字過長已截斷，比較前 4000 行', 'Input too long — only the first 4000 lines were compared'],
  '选择左侧文件': ['選擇左側檔案', 'Choose left file'],
  '选择右侧文件': ['選擇右側檔案', 'Choose right file'],
  '交换左右': ['交換左右', 'Swap sides'],
  '在左右区域各载入一个文件 (点击选择 / 拖拽), 自动按行 diff, 左侧红色 = 删除行, 右侧绿色 = 新增行': ['在左右區域各載入一個檔案 (點擊選擇 / 拖曳), 自動逐行 diff, 左側紅色 = 刪除行, 右側綠色 = 新增行', 'Load one file into each zone (click or drag) — rows are diffed automatically: red on the left = deleted lines, green on the right = added lines'],
  '左侧文件': ['左側檔案', 'Left file'],
  '右侧文件': ['右側檔案', 'Right file'],
  '(删除行红色)': ['(刪除行紅色)', '(deleted lines in red)'],
  '(新增行绿色)': ['(新增行綠色)', '(added lines in green)'],
  '共 {n} 个 diff 行, 仅渲染前 {m} 行': ['共 {n} 個 diff 行, 僅渲染前 {m} 行', '{n} diff lines total — only the first {m} are rendered'],
  '{n} 行 · {s} KB': ['{n} 行 · {s} KB', '{n} lines · {s} KB'],
  '拖拽要提取主体色的图片文件到框内': ['拖曳要提取主體色的圖片檔案到框內', 'Drop an image to extract its dominant colors'],
  '主题色提取中': ['主體色提取中', 'Extracting theme colors…'],
  '提取计算需要时间': ['提取計算需要時間', 'This may take a moment'],
  '读': ['讀', 'Read'],
  '写': ['寫', 'Write'],
  '执行': ['執行', 'Execute'],
  '属主 (u)': ['屬主 (u)', 'Owner (u)'],
  '属组 (g)': ['屬組 (g)', 'Group (g)'],
  '其它 (o)': ['其它 (o)', 'Others (o)'],
  '属主 (user / u)': ['屬主 (user / u)', 'Owner (user / u)'],
  '属组 (group / g)': ['屬組 (group / g)', 'Group (group / g)'],
  '其它 (other / o)': ['其它 (other / o)', 'Others (other / o)'],
  '输入 755 / 4755 / -rwxr-xr-x / chmod 命令': ['輸入 755 / 4755 / -rwxr-xr-x / chmod 命令', 'Enter 755 / 4755 / -rwxr-xr-x / a chmod command'],
  '解读': ['解讀', 'Parse'],
  '解读结果会同步到下方勾选区': ['解讀結果會同步到下方勾選區', 'The parsed result is synced to the checkboxes below'],
  '配置权限 (勾选后实时生成命令)': ['設定權限 (勾選後即時產生命令)', 'Set permissions (the command is generated live)'],
  '特殊位': ['特殊位', 'Special bits'],
  'setuid (4)': ['setuid (4)', 'setuid (4)'],
  'setgid (2)': ['setgid (2)', 'setgid (2)'],
  'sticky (1)': ['sticky (1)', 'sticky (1)'],
  '数值': ['數值', 'Numeric'],
  '符号': ['符號', 'Symbols'],
  '权限含义': ['權限含義', 'Permission meaning'],
  '无权限': ['無權限', 'No permission'],
  '文件名:': ['檔名:', 'File name:'],
  '复制命令': ['複製命令', 'Copy command'],
  '符号写法:': ['符號寫法:', 'Symbolic mode:'],
  'ls 显示:': ['ls 顯示:', 'ls display:'],
  '数字:': ['數字:', 'Numeric:'],
  ' chmod 权限说明 ': [' chmod 權限說明 ', ' chmod notes '],
  '数字': ['數字', 'Numeric'],
  '含义': ['含義', 'Meaning'],
  'Linux 权限分三组：属主 (u)、属组 (g)、其它 (o)，每组含读 (r=4)、写 (w=2)、执行 (x=1) 三个位，数值求和即为 0-7 的数字权限。数字串从左到右依次为 u/g/o，如': ['Linux 權限分三組：屬主 (u)、屬組 (g)、其它 (o)，每組含讀 (r=4)、寫 (w=2)、執行 (x=1) 三個位，數值求和即為 0-7 的數字權限。數字串從左到右依序為 u/g/o，如', 'Linux permissions have three scopes: owner (u), group (g) and others (o). Each scope has read (r=4), write (w=2) and execute (x=1) bits; summing them gives the 0-7 numeric permission. The digits map to u/g/o from left to right, e.g.'],
  '= u:rwx, g:r-x, o:r-x。': ['= u:rwx, g:r-x, o:r-x。', '= u:rwx, g:r-x, o:r-x.'],
  '首位为特殊位：4 = setuid（执行时以属主身份运行，如 passwd）、2 = setgid（目录内新建文件继承属组）、1 = sticky（仅属主可删除，如 /tmp）。ls 显示时 setuid/setgid 使 x 变为小写 s（无执行则为大写 S），sticky 使其它执行位变为 t/T。': ['首位為特殊位：4 = setuid（執行時以屬主身份執行，如 passwd）、2 = setgid（目錄內新建檔案繼承屬組）、1 = sticky（僅屬主可刪除，如 /tmp）。ls 顯示時 setuid/setgid 使 x 變成小寫 s（無執行則為大寫 S），sticky 使其它執行位變成 t/T。', 'The first digit is the special bit: 4 = setuid (runs with the owner identity, e.g. passwd), 2 = setgid (new files in the directory inherit the group), 1 = sticky (only the owner may delete, e.g. /tmp). In ls output, setuid/setgid turns x into lowercase s (uppercase S when not executable) and sticky turns the others-execute bit into t/T.'],
  '补码 (二进制)': ['補碼 (二進位)', "Two's complement (binary)"],
  '补码 (十六进制)': ['補碼 (十六進位)', "Two's complement (hex)"],
  '原码 (二进制)': ['原碼 (二進位)', 'Sign-magnitude (binary)'],
  '反码 (二进制)': ['反碼 (二進位)', "One's complement (binary)"],
  '十进制 → 原/反/补码': ['十進位 → 原/反/補碼', "Decimal → SM/1's/2's complement"],
  '编码 → 十进制': ['編碼 → 十進位', 'Encoding → decimal'],
  '位宽': ['位寬', 'Bit width'],
  '(bit)': ['(bit)', '(bit)'],
  '有符号 {r}': ['有符號 {r}', 'Signed {r}'],
  '无符号 {r}': ['無符號 {r}', 'Unsigned {r}'],
  '十进制整数': ['十進位整數', 'Decimal integer'],
  '输入十进制整数 (范围 {r})': ['輸入十進位整數 (範圍 {r})', 'Enter a decimal integer (range {r})'],
  '编码类型': ['編碼類型', 'Encoding type'],
  '十六进制': ['十六進位', 'Hexadecimal'],
  '二进制串': ['二進位串', 'Binary string'],
  '原码': ['原碼', 'Sign-magnitude'],
  '反码': ['反碼', "One's complement"],
  '补码': ['補碼', "Two's complement"],
  '十进制结果': ['十進位結果', 'Decimal result'],
  '输入 {b} 位补码十六进制 (可带 0x, 最多 {c} 位)': ['輸入 {b} 位補碼十六進位 (可帶 0x, 最多 {c} 位)', "Enter {b}-bit two's-complement hex (0x optional, up to {c} digits)"],
  '输入 {b} 位{k}二进制 (可少于 {b} 位, 高位补 0)': ['輸入 {b} 位{k}二進位 (可少於 {b} 位, 高位補 0)', 'Enter a {b}-bit {k} binary string (fewer than {b} bits allowed — padded with leading 0s)'],
  '−2^{b} 超出原码表示范围 (±(2^{b}−1))': ['−2^{b} 超出原碼表示範圍 (±(2^{b}−1))', '−2^{b} is outside the sign-magnitude range (±(2^{b}−1))'],
  '−2^{b} 超出反码表示范围 (±(2^{b}−1))': ['−2^{b} 超出反碼表示範圍 (±(2^{b}−1))', "−2^{b} is outside the one's-complement range (±(2^{b}−1))"],
  '{k} ({b}位)': ['{k} ({b}位)', '{k} ({b}-bit)'],
  '说明: 正数的原码 / 反码 / 补码相同; 负数的补码 = 反码 + 1。最左位为符号位 (0 正 / 1 负)。原码与反码可表示范围仅 ±(2^(N−1)−1), 因此 −2^(N−1) 只有补码表示。': ['說明: 正數的原碼 / 反碼 / 補碼相同; 負數的補碼 = 反碼 + 1。最左位為符號位 (0 正 / 1 負)。原碼與反碼可表示範圍僅 ±(2^(N−1)−1)，因此 −2^(N−1) 只有補碼表示。', "Notes: for positive numbers, sign-magnitude / one's complement / two's complement are identical; for negatives, two's complement = one's complement + 1. The leftmost bit is the sign bit (0 positive / 1 negative). Sign-magnitude and one's complement can only cover ±(2^(N−1)−1), so −2^(N−1) has a two's-complement representation only."],
  '动态口令': ['動態口令', 'One-time password'],
  'TOTP (时间)': ['TOTP (時間)', 'TOTP (time-based)'],
  'HOTP (计数)': ['HOTP (計數)', 'HOTP (counter-based)'],
  '兼容 Google / Microsoft Authenticator': ['相容 Google / Microsoft Authenticator', 'Works with Google / Microsoft Authenticator'],
  '密钥': ['金鑰', 'Secret'],
  '算法': ['演算法', 'Algorithm'],
  '位数': ['位數', 'Digits'],
  '步长(秒)': ['步長(秒)', 'Step (sec)'],
  '计数': ['計數', 'Counter'],
  '+1': ['+1', '+1'],
  'Base32, 如 GEZDGNBV…': ['Base32, 如 GEZDGNBV…', 'Base32, e.g. GEZDGNBV…'],
  '随机生成密钥': ['隨機產生金鑰', 'Generate a random secret'],
  '6 位': ['6 位', '6 digits'],
  '7 位': ['7 位', '7 digits'],
  '8 位': ['8 位', '8 digits'],
  '名称': ['名稱', 'Issuer'],
  '账号': ['帳號', 'Account'],
  '如 GitHub (可选)': ['如 GitHub (可選)', 'e.g. GitHub (optional)'],
  '用于扫码导入的标签': ['用於掃碼匯入的標籤', 'Label used when importing via QR'],
  '当前验证码': ['目前驗證碼', 'Current code'],
  '当前验证码 (每次使用后计数 +1)': ['目前驗證碼 (每次使用後計數 +1)', 'Current code (counter +1 after each use)'],
  '验证码已复制': ['驗證碼已複製', 'Code copied'],
  'otpauth 链接已复制': ['otpauth 連結已複製', 'otpauth link copied'],
  '{r} 秒后刷新': ['{r} 秒後刷新', 'Refreshes in {r}s'],
  '扫码添加至 Authenticator (otpauth://)': ['掃碼加入 Authenticator (otpauth://)', 'Scan to add to Authenticator (otpauth://)'],
  '复制导入链接': ['複製匯入連結', 'Copy import link'],
  '请输入或生成密钥': ['請輸入或產生金鑰', 'Enter or generate a secret'],
  '密钥格式有误': ['金鑰格式有誤', 'Invalid secret format'],
  'PPI = √(宽² + 高²) ÷ 对角线英寸': ['PPI = √(寬² + 高²) ÷ 對角線英吋', 'PPI = √(width² + height²) ÷ diagonal inches'],
  'Pentile 等效 ≈ RGB PPI × √(2/3) ≈ ×0.8165': ['Pentile 等效 ≈ RGB PPI × √(2/3) ≈ ×0.8165', 'Pentile equivalent ≈ RGB PPI × √(2/3) ≈ ×0.8165'],
  'RGB 排列: 每像素 3 子像素 | Pentile: 2 子像素': ['RGB 排列: 每像素 3 子像素 | Pentile: 2 子像素', 'RGB layout: 3 subpixels per pixel | Pentile: 2'],
  '常用屏幕:': ['常用螢幕:', 'Common screens:'],
  '选择常用分辨率 (可手动修改下方数值)': ['選擇常用解析度 (可手動修改下方數值)', 'Pick a common resolution (the values below stay editable)'],
  '分辨率:': ['解析度:', 'Resolution:'],
  '宽': ['寬', 'Width'],
  '高': ['高', 'Height'],
  'px': ['px', 'px'],
  '屏幕尺寸:': ['螢幕尺寸:', 'Screen size:'],
  '英寸': ['英吋', 'inches'],
  '请输入有效的分辨率(正整数)与屏幕尺寸(大于 0 英寸)': ['請輸入有效的解析度(正整數)與螢幕尺寸(大於 0 英吋)', 'Enter a valid resolution (positive integers) and screen size (greater than 0 inches)'],
  '标准 RGB 排列 PPI': ['標準 RGB 排列 PPI', 'Standard RGB PPI'],
  '每英寸像素 (对角线方向)': ['每英吋像素 (對角線方向)', 'Pixels per inch (diagonal)'],
  'Pentile 排列等效 PPI': ['Pentile 排列等效 PPI', 'Pentile-equivalent PPI'],
  'OLED 菱形排列, 红/蓝子像素共享, 等效 ≈ RGB × 0.8165': ['OLED 菱形排列, 紅/藍子像素共享, 等效 ≈ RGB × 0.8165', 'OLED diamond layout shares red/blue subpixels — equivalent ≈ RGB × 0.8165'],
  '物理尺寸 (宽 × 高)': ['物理尺寸 (寬 × 高)', 'Physical size (width × height)'],
  'RGB 子像素密度': ['RGB 子像素密度', 'RGB subpixel density'],
  'Pentile 子像素密度': ['Pentile 子像素密度', 'Pentile subpixel density'],
  '总像素': ['總像素', 'Total pixels'],
  '宽高比': ['寬高比', 'Aspect ratio'],
  '{a} × {b} 英寸': ['{a} × {b} 英吋', '{a} × {b} inches'],
  '{n} 个/英寸': ['{n} 個/英吋', '{n} per inch'],
  '{p} ({m} MP)': ['{p} ({m} MP)', '{p} ({m} MP)'],
  '提示: Pentile (如三星 Diamond 排列) 每个像素仅 2 个子像素, 等效视觉密度约为标准 RGB 的 √(2/3) ≈ 81.65%; 同分辨率下 Pentile 屏的理论细腻度低于 RGB 排列, 厂商常以更高分辨率(如 QHD+)弥补。': ['提示: Pentile (如三星 Diamond 排列) 每個像素僅 2 個子像素, 等效視覺密度約為標準 RGB 的 √(2/3) ≈ 81.65%; 同解析度下 Pentile 螢幕的理論細膩度低於 RGB 排列, 廠商常以更高解析度(如 QHD+)彌補。', "Note: on Pentile (e.g. Samsung's Diamond layout) each pixel has only 2 subpixels, so the perceived density is about √(2/3) ≈ 81.65% of standard RGB. At the same resolution a Pentile panel is theoretically less sharp than RGB; makers compensate with higher resolutions (e.g. QHD+)."],
  '输入或生成一个密码后显示强度评估': ['輸入或產生一個密碼後顯示強度評估', 'Type or generate a password to see its strength'],
  '强度:': ['強度:', 'Strength:'],
  '参考熵:': ['參考熵:', 'Entropy:'],
  '按每秒 1 万亿次猜测约需 {t}': ['按每秒 1 兆次猜測約需 {t}', 'At 1 trillion guesses/sec it would take about {t}'],
  '在线攻击:': ['線上攻擊:', 'Online attack:'],
  '按每秒 1000 次猜测约需 {t}': ['按每秒 1000 次猜測約需 {t}', 'At 1,000 guesses/sec it would take about {t}'],
  '极弱': ['極弱', 'Very weak'],
  '弱': ['弱', 'Weak'],
  '一般': ['一般', 'Fair'],
  '强': ['強', 'Strong'],
  '极强': ['極強', 'Very strong'],
  '极易被暴力/字典破解, 请勿使用': ['極易被暴力/字典破解, 請勿使用', 'Trivially broken by brute force / dictionary attacks — do not use'],
  '容易被破解, 建议增加长度与字符类型': ['容易被破解, 建議增加長度與字元類型', 'Easy to crack — increase the length and add more character types'],
  '对普通场景可用, 敏感账户建议加强': ['對一般場景可用, 敏感帳戶建議加強', 'Fine for everyday use; strengthen it for sensitive accounts'],
  '当前配置较难被暴力破解': ['目前設定較難被暴力破解', 'Hard to brute force with the current settings'],
  '按现有算力需极长时间, 安全性很高': ['按現有算力需極長時間, 安全性很高', "Would take an extremely long time with today's hardware — very secure"],
  '长度 {n} (推荐 ≥12)': ['長度 {n} (建議 ≥12)', 'Length {n} (≥12 recommended)'],
  '大小写混合': ['大小寫混合', 'Mixed case'],
  '建议混合大小写': ['建議混合大小寫', 'Use mixed case'],
  '包含数字': ['包含數字', 'Has digits'],
  '建议包含数字': ['建議包含數字', 'Add digits'],
  '包含符号': ['包含符號', 'Has symbols'],
  '包含中文/符号': ['包含中文/符號', 'Has CJK / symbols'],
  '建议包含符号或中文': ['建議包含符號或中文', 'Add symbols or CJK characters'],
  '命中常见弱口令库': ['命中常見弱密碼庫', 'Hit the common-password list'],
  '未命中常见弱口令库': ['未命中常見弱密碼庫', 'Not on the common-password list'],
  '存在连续 {n} 个相同字符': ['存在連續 {n} 個相同字元', 'Has {n} identical characters in a row'],
  '无连续重复字符': ['無連續重複字元', 'No repeated-run characters'],
  '存在键盘/字母/数字连续序列': ['存在鍵盤/字母/數字連續序列', 'Has a keyboard/alphabet/digit sequence'],
  '无连续序列': ['無連續序列', 'No consecutive sequences'],
  '当前强度: ': ['目前強度: ', 'Current strength: '],
  '所有生成与强度评估均在本地完成, 密码不会离开设备; 建议长度 ≥ 12 并混合大小写、数字与符号。强度仅为启发式估算, 不能替代权威评估。': ['所有產生與強度評估均在本機完成, 密碼不會離開裝置; 建議長度 ≥ 12 並混合大小寫、數字與符號。強度僅為啟發式估算, 不能取代權威評估。', 'Generation and strength checks all run locally — the password never leaves your device. A length ≥ 12 mixing upper/lower case, digits and symbols is recommended. Strength is only a heuristic estimate, not a substitute for authoritative evaluation.'],
  '生成': ['產生', 'Generate'],
  '长度:': ['長度:', 'Length:'],
  '字符集:': ['字元集:', 'Character set:'],
  '大写 A-Z': ['大寫 A-Z', 'Uppercase A-Z'],
  '小写 a-z': ['小寫 a-z', 'Lowercase a-z'],
  '数字 0-9': ['數字 0-9', 'Digits 0-9'],
  '符号 !@#…': ['符號 !@#…', 'Symbols !@#…'],
  '选项:': ['選項:', 'Options:'],
  '排除易混淆字符 (IOlo01)': ['排除易混淆字元 (IOlo01)', 'Exclude ambiguous characters (IOlo01)'],
  '生成密码': ['產生密碼', 'Generate password'],
  '点击上方按钮生成随机密码': ['點擊上方按鈕產生隨機密碼', 'Click the button above to generate a random password'],
  '请先生成或输入密码': ['請先產生或輸入密碼', 'Generate or enter a password first'],
  '已复制到剪贴板': ['已複製到剪貼簿', 'Copied to clipboard'],
  '强度检测 (支持手工输入任意密码)': ['強度檢測 (支援手動輸入任意密碼)', 'Strength check (paste any password)'],
  '在此输入或粘贴要检测的密码': ['在此輸入或貼上要檢測的密碼', 'Enter or paste a password to check'],
  '常用正则 (在 设置 → 其它 中管理)': ['常用正則 (在 設定 → 其它 中管理)', 'Common regexes (managed under Settings → Misc)'],
  '一键复制规则: {p}': ['一鍵複製規則: {p}', 'Copy this rule: {p}'],
  '一键复制当前正则规则': ['一鍵複製目前正則規則', 'Copy the current regex'],
  '复制规则': ['複製規則', 'Copy rule'],
  '重新读取设置中的常用正则': ['重新讀取設定中的常用正則', 'Reload common regexes from settings'],
  '刷新': ['重新整理', 'Refresh'],
  '正则': ['正則', 'Regex'],
  '输入正则表达式, 例如 ^1[3-9]\\d{9}$': ['輸入正則表達式, 例如 ^1[3-9]\\d{9}$', 'Enter a regex, e.g. ^1[3-9]\\d{9}$'],
  'i 忽略大小写': ['i 忽略大小寫', 'i case-insensitive'],
  'g 全局': ['g 全域', 'g global'],
  'm 多行': ['m 多行', 'm multi-line'],
  's 点匹配换行': ['s 點匹配換行', 's dot matches newlines'],
  '正则表达式无效:': ['正則表達式無效:', 'Invalid regex:'],
  '在此输入多行内容, 逐行与正则匹配: 匹配行显示为绿色, 不匹配行显示为红色': ['在此輸入多行內容, 逐行與正則比對: 符合行顯示為綠色, 不符合行顯示為紅色', 'Enter multi-line content here — each line is matched: green = matched, red = not matched'],
  '复制匹配行': ['複製符合行', 'Copy matched lines'],
  '填入示例': ['填入範例', 'Load sample'],
  '清空正则': ['清空正則', 'Clear regex'],
  '匹配 {a} / {b} 行': ['符合 {a} / {b} 行', '{a} / {b} lines matched'],
  ', 共 {n} 处': [', 共 {n} 處', ', {n} matches in total'],
  '请先输入正则表达式': ['請先輸入正則表達式', 'Enter a regex first'],
  '没有匹配的行': ['沒有符合的行', 'No matching lines'],
  ' 正则表达式说明 ': [' 正則表達式說明 ', ' Regex notes '],
  '输入格式:': ['輸入格式:', 'Input format:'],
  'ASCII / 文本': ['ASCII / 文字', 'ASCII / text'],
  '十六进制字节 (支持 空格/逗号/0x 等分隔)': ['十六進位位元組 (支援 空格/逗號/0x 等分隔)', 'Hex bytes (space / comma / 0x prefixes allowed)'],
  '文本按 UTF-8 编码为字节': ['文字按 UTF-8 編碼為位元組', 'Text is encoded to bytes as UTF-8'],
  '十进制': ['十進位', 'Decimal'],
  '八进制': ['八進位', 'Octal'],
  '二进制': ['二進位', 'Binary'],
  '数据长度': ['資料長度', 'Byte count'],
  '参与计算的字节数': ['參與計算的位元組數', 'Bytes included in the calculation'],
  '{n} 字节': ['{n} 位元組', '{n} bytes'],
  '点击复制 {l} 值': ['點擊複製 {l} 值', 'Click to copy {l} value'],
  '已复制: {t}': ['已複製: {t}', 'Copied: {t}'],
  '输入需要计算 BCC 校验值的十六进制数据 (如: 01 03 00 00 00 02) 或 拖拽文件到框内打开': ['輸入需要計算 BCC 校驗值的十六進位資料 (如: 01 03 00 00 00 02) 或 拖曳檔案到框內開啟', 'Enter hex data to compute the BCC (e.g. 01 03 00 00 00 02), or drag a file into the box'],
  '输入文本 (按 UTF-8 编码为字节参与计算, 如: ABC -> XOR = 0x40) 或 拖拽文件到框内打开': ['輸入文字 (按 UTF-8 編碼為位元組參與計算, 如: ABC -> XOR = 0x40) 或 拖曳檔案到框內開啟', 'Enter text (encoded to bytes as UTF-8, e.g. ABC -> XOR = 0x40), or drag a file into the box'],
  '期望 BCC:': ['期望 BCC:', 'Expected BCC:'],
  '如 00 / 0x5A (十六进制)': ['如 00 / 0x5A (十六進位)', 'e.g. 00 / 0x5A (hex)'],
  '✓ 校验通过': ['✓ 校驗通過', '✓ Check passed'],
  '✗ 校验不通过 (期望 {e})': ['✗ 校驗不通過 (期望 {e})', '✗ Check failed (expected {e})'],
  '期望值格式错误 (需 1-2 位十六进制)': ['期望值格式錯誤 (需 1-2 位十六進位)', 'Invalid expected value (needs 1-2 hex digits)'],
  '填入期望值 (十六进制) 后自动比对': ['填入期望值 (十六進位) 後自動比對', 'Enter the expected value (hex) to compare automatically'],
  '校验算法:': ['校驗演算法:', 'Algorithm:'],
  '选择 CRC 算法': ['選擇 CRC 演算法', 'Pick a CRC algorithm'],
  'CRC 位数': ['CRC 位數', 'CRC width'],
  '生成多项式 (已省略隐含最高位)': ['生成多項式 (已省略隱含最高位)', 'Generator polynomial (implicit top bit omitted)'],
  '寄存器初始值': ['暫存器初始值', 'Register initial value'],
  '最终结果异或值': ['最終結果互斥或值', 'Final XOR value'],
  '输入比特反转 (LSB first)': ['輸入位元反轉 (LSB first)', 'Reverse input bits (LSB first)'],
  '输出比特反转': ['輸出位元反轉', 'Reverse output bits'],
  '输入数据反转 (RefIn)': ['輸入資料反轉 (RefIn)', 'Reverse input data (RefIn)'],
  '输出数据反转 (RefOut)': ['輸出資料反轉 (RefOut)', 'Reverse output data (RefOut)'],
  '输入需要计算 CRC 校验值的数据 (十六进制字节, 如: 01 03 04 02 00 01 00) 或 拖拽文件到框内打开': ['輸入需要計算 CRC 校驗值的資料 (十六進位位元組, 如: 01 03 04 02 00 01 00) 或 拖曳檔案到框內開啟', 'Enter data to compute the CRC (hex bytes, e.g. 01 03 04 02 00 01 00), or drag a file into the box'],
  '输入文本 (按 UTF-8 编码为字节参与计算, 如: 123456789 -> CRC-16/MODBUS = 4B37) 或 拖拽文件到框内打开': ['輸入文字 (按 UTF-8 編碼為位元組參與計算, 如: 123456789 -> CRC-16/MODBUS = 4B37) 或 拖曳檔案到框內開啟', 'Enter text (encoded to bytes as UTF-8, e.g. 123456789 -> CRC-16/MODBUS = 4B37), or drag a file into the box'],
  '补码 LRC (Modbus)': ['補碼 LRC (Modbus)', "Two's-complement LRC (Modbus)"],
  '累加和取低 8 位后求二进制补码 (-sum), Modbus RTU 标准': ['累加和取低 8 位後求二進位補碼 (-sum), Modbus RTU 標準', 'Take the low 8 bits of the sum and negate it (-sum), per Modbus RTU'],
  '累加和 SUM': ['累加和 SUM', 'Checksum SUM'],
  '直接取累加和的低 8 位 (和校验)': ['直接取累加和的低 8 位 (和校驗)', 'Take only the low 8 bits of the sum'],
  '期望': ['期望', 'Expected'],
  '输入需要计算 LRC 校验值的十六进制数据 (如: 01 03 04 02 00 01 00) 或 拖拽文件到框内打开': ['輸入需要計算 LRC 校驗值的十六進位資料 (如: 01 03 04 02 00 01 00) 或 拖曳檔案到框內開啟', 'Enter hex data to compute the LRC (e.g. 01 03 04 02 00 01 00), or drag a file into the box'],
  '输入文本 (按 UTF-8 编码为字节参与计算, 如: ABC -> sum=0xC6, 补码 LRC=0x3A) 或 拖拽文件到框内打开': ['輸入文字 (按 UTF-8 編碼為位元組參與計算, 如: ABC -> sum=0xC6, 補碼 LRC=0x3A) 或 拖曳檔案到框內開啟', "Enter text (encoded to bytes as UTF-8, e.g. ABC -> sum=0xC6, two's-complement LRC=0x3A), or drag a file into the box"],
  'UTF-8 文本': ['UTF-8 文字', 'UTF-8 text'],
  'HEX (十六进制)': ['HEX (十六進位)', 'HEX (hexadecimal)'],
  '消息的十六进制, 如 6bc1bee22e409f96e93d7e117393172a': ['訊息的十六進位, 如 6bc1bee22e409f96e93d7e117393172a', 'Message hex, e.g. 6bc1bee22e409f96e93d7e117393172a'],
  '需要计算 CMAC 的消息内容, 可为空(空消息也合法)': ['需要計算 CMAC 的訊息內容, 可為空(空訊息也合法)', 'Message to compute CMAC for — may be empty (an empty message is valid)'],
  '消息 (M):': ['訊息 (M):', 'Message (M):'],
  '密钥 (K):': ['金鑰 (K):', 'Key (K):'],
  '密钥位数:': ['金鑰位數:', 'Key size:'],
  '密钥的十六进制 ({c} 个字符), 如 2b7e151628aed2a6abf7158809cf4f3c': ['金鑰的十六進位 ({c} 個字元), 如 2b7e151628aed2a6abf7158809cf4f3c', 'Key hex ({c} chars), e.g. 2b7e151628aed2a6abf7158809cf4f3c'],
  '密钥 {b} 字节 (ASCII 即 {b} 个字符)': ['金鑰 {b} 位元組 (ASCII 即 {b} 個字元)', 'Key of {b} bytes ({b} ASCII chars)'],
  '计算 CMAC': ['計算 CMAC', 'Compute CMAC'],
  '大写显示': ['大寫顯示', 'Uppercase output'],
  '密钥不能为空': ['金鑰不能為空', 'Key must not be empty'],
  '消息内容不能为空': ['訊息內容不能為空', 'Message must not be empty'],
  '双击复制结果到粘贴板': ['雙擊複製結果到剪貼簿', 'Double-click to copy the result'],
  'CMAC 标签 (16 字节 / 32 个十六进制字符)': ['CMAC 標籤 (16 位元組 / 32 個十六進位字元)', 'CMAC tag (16 bytes / 32 hex chars)'],
  'HEX 密钥应为 {c} 个十六进制字符 ({b} 字节)': ['HEX 金鑰應為 {c} 個十六進位字元 ({b} 位元組)', 'HEX key must be {c} hex characters ({b} bytes)'],
  '密钥需为 {b} 个字符/字节 (当前 {n} 字节, 中文等多字节字符按 UTF-8 计算)': ['金鑰需為 {b} 個字元/位元組 (目前 {n} 位元組, 中文等多位元組字元按 UTF-8 計算)', 'Key must be {b} characters/bytes (currently {n} bytes; multi-byte chars such as CJK are counted as UTF-8)'],
  '计算失败: {m}': ['計算失敗: {m}', 'Computation failed: {m}'],
  '字节': ['位元組', 'bytes'],
  '次': ['次', 'times'],
  '位': ['位', 'bits'],
  '算法:': ['演算法:', 'Algorithm:'],
  '输出长度:': ['輸出長度:', 'Output length:'],
  'XOF 模式:': ['XOF 模式:', 'XOF mode:'],
  '可变长输出 (XOF)': ['可變長輸出 (XOF)', 'Variable-length output (XOF)'],
  '密钥 K (SP 800-185 建议 ≥ 目标安全强度字节数):': ['金鑰 K (SP 800-185 建議 ≥ 目標安全強度位元組數):', 'Key K (SP 800-185 recommends ≥ the target security strength in bytes):'],
  '密钥十六进制, 如 404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f': ['金鑰十六進位, 如 404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f', 'Key hex, e.g. 404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f'],
  '密钥 (任意文本)': ['金鑰 (任意文字)', 'Key (any text)'],
  '消息 X:': ['訊息 X:', 'Message X:'],
  '消息十六进制 (可空), 如 00010203': ['訊息十六進位 (可空), 如 00010203', 'Message hex (optional), e.g. 00010203'],
  '消息内容 (可空)': ['訊息內容 (可空)', 'Message (optional)'],
  '自定义字符串 S (Customization, 可空):': ['自訂字串 S (Customization, 可空):', 'Custom string S (optional):'],
  '如 My Tagged Application (UTF-8 文本)': ['如 My Tagged Application (UTF-8 文字)', 'e.g. My Tagged Application (UTF-8 text)'],
  '计算 KMAC': ['計算 KMAC', 'Compute KMAC'],
  'KMAC 输出 ({b} 字节, {c} 个十六进制字符)': ['KMAC 輸出 ({b} 位元組, {c} 個十六進位字元)', 'KMAC output ({b} bytes, {c} hex chars)'],
  '散列算法:': ['雜湊演算法:', 'Hash algorithm:'],
  'IKM (输入密钥材料):': ['IKM (輸入金鑰材料):', 'IKM (input keying material):'],
  'IKM 的十六进制, 如 0b0b0b0b...': ['IKM 的十六進位, 如 0b0b0b0b...', 'IKM hex, e.g. 0b0b0b0b...'],
  'IKM 密钥材料 (任意文本)': ['IKM 金鑰材料 (任意文字)', 'IKM keying material (any text)'],
  'Salt (盐值, 可空):': ['Salt (鹽值, 可空):', 'Salt (optional):'],
  '盐值, 为空时使用全零(长度=散列长度)': ['鹽值, 為空時使用全零(長度=雜湊長度)', 'Salt — empty uses all zeros (hash length)'],
  'Info (上下文信息, 可空):': ['Info (上下文資訊, 可空):', 'Info (context, optional):'],
  '可选的应用上下文信息': ['可選的應用上下文資訊', 'Optional application context'],
  '计算 HKDF': ['計算 HKDF', 'Compute HKDF'],
  'IKM 不能为空': ['IKM 不能為空', 'IKM must not be empty'],
  'HKDF 输出 ({b} 字节, {c} 个十六进制字符)': ['HKDF 輸出 ({b} 位元組, {c} 個十六進位字元)', 'HKDF output ({b} bytes, {c} hex chars)'],
  'BCrypt 内置随机盐, 相同口令每次生成结果不同; 使用前请确认与目标系统相同的 $2a/$2b/$2y 前缀与成本因子': ['BCrypt 內建隨機鹽, 相同口令每次生成結果不同; 使用前請確認與目標系統相同的 $2a/$2b/$2y 前綴與成本因子', 'BCrypt embeds a random salt, so the same password yields a different hash each time. Before use, confirm the $2a/$2b/$2y prefix and cost factor match the target system'],
  '生成哈希': ['產生雜湊', 'Generate hash'],
  '口令': ['口令', 'Password'],
  '输入需要计算 BCrypt 哈希的口令 (超过 72 字节的内容会被截断)': ['輸入需要計算 BCrypt 雜湊的口令 (超過 72 位元組的內容會被截斷)', 'Enter the password to hash with BCrypt (content over 72 bytes is truncated)'],
  '成本因子': ['成本因子', 'Cost factor'],
  '生成 BCrypt': ['產生 BCrypt', 'Generate BCrypt'],
  'BCrypt': ['BCrypt', 'BCrypt'],
  '生成结果, 点击可复制': ['產生結果, 點擊可複製', 'Result — click to copy'],
  '校验': ['校驗', 'Verify'],
  '候选口令': ['候選口令', 'Candidate password'],
  'BCrypt 哈希': ['BCrypt 雜湊', 'BCrypt hash'],
  '生成失败: {m}': ['產生失敗: {m}', 'Generation failed: {m}'],
  '校验失败: {m}': ['校驗失敗: {m}', 'Verification failed: {m}'],
  'BCrypt 哈希格式不正确': ['BCrypt 雜湊格式不正確', 'Not a valid BCrypt hash'],
  '校验通过: 口令与哈希匹配': ['校驗通過: 口令與雜湊匹配', 'Match: the password matches the hash'],
  '校验失败: 口令与哈希不匹配': ['校驗失敗: 口令與雜湊不匹配', 'No match: the password does not match the hash'],
  '提示: 目标哈希成本因子为 {a}, 与上方生成区当前成本 {b} 不同': ['提示: 目標雜湊成本因子為 {a}, 與上方生成區目前成本 {b} 不同', 'Note: the target hash uses cost factor {a}, which differs from the current cost {b} in the generator above'],
  '盐': ['鹽', 'Salt'],
  '内存开销 = 128 · N · r 字节': ['記憶體開銷 = 128 · N · r 位元組', 'Memory usage = 128 · N · r bytes'],
  '口令:': ['口令:', 'Password:'],
  '盐值:': ['鹽值:', 'Salt:'],
  '口令 (Password)': ['口令 (Password)', 'Password'],
  '盐 (Salt, 十六进制字符串或任意文本)': ['鹽 (Salt, 十六進位字串或任意文字)', 'Salt (hex string or any text)'],
  '随机盐': ['隨機鹽', 'Random salt'],
  'N:': ['N:', 'N:'],
  'r:': ['r:', 'r:'],
  'p:': ['p:', 'p:'],
  '派生长度:': ['派生長度:', 'Derived length:'],
  '计算': ['計算', 'Compute'],
  '请输入口令': ['請輸入口令', 'Enter a password'],
  '请输入盐值': ['請輸入鹽值', 'Enter a salt'],
  '派生密钥 (十六进制)': ['派生金鑰 (十六進位)', 'Derived key (hex)'],
  '计算耗时: {ms} ms': ['計算耗時: {ms} ms', 'Took {ms} ms'],
  '盐值(Salt)': ['鹽值(Salt)', 'Salt'],
  '迭代次数:': ['疊代次數:', 'Iterations:'],
  '推导密钥长度:': ['推導金鑰長度:', 'Derived key length:'],
  '大写字符显示': ['大寫字元顯示', 'Uppercase output'],
  '计算结果': ['計算結果', 'Result'],
  '密码': ['密碼', 'Password'],
  '加密方式': ['加密方式', 'Encryption method'],
  '如 admin': ['如 admin', 'e.g. admin'],
  '输入密码': ['輸入密碼', 'Enter password'],
  '生成成功, 可双击下方结果复制': ['產生成功, 可雙擊下方結果複製', 'Generated — double-click the result below to copy it'],
  '复制到粘贴板成功!!!': ['複製到剪貼簿成功!!!', 'Copied to clipboard!!!'],
  '保存 .htpasswd 文件': ['儲存 .htpasswd 檔案', 'Save .htpasswd file'],
  '已保存 .htpasswd 文件': ['已儲存 .htpasswd 檔案', '.htpasswd file saved'],
  '生成结果: 用户名:密码哈希': ['產生結果: 使用者名稱:密碼雜湊', 'Result: username:password-hash'],
  '双击复制内容到粘贴板': ['雙擊複製內容到剪貼簿', 'Double-click to copy the content'],
  '保存为 .htpasswd 文件': ['儲存為 .htpasswd 檔案', 'Save as .htpasswd file'],
  'htpasswd 生成说明': ['htpasswd 產生說明', 'About htpasswd generation'],
  'bcrypt ($2y$)': ['bcrypt ($2y$)', 'bcrypt ($2y$)'],
  'Apache MD5 ($apr1$)': ['Apache MD5 ($apr1$)', 'Apache MD5 ($apr1$)'],
  'SHA1 ({SHA})': ['SHA1 ({SHA})', 'SHA1 ({SHA})'],
  '明文 (不推荐)': ['明文 (不推薦)', 'Plain (not recommended)'],
  '自带随机盐, 抗暴力破解能力最强, 新密码推荐使用 (部分旧系统需 Apache 2.4+)': ['內建隨機鹽, 抗暴力破解能力最強, 新密碼建議使用 (部分舊系統需 Apache 2.4+)', 'Built-in random salt; strongest brute-force resistance — recommended for new passwords (some legacy systems need Apache 2.4+)'],
  'Apache 默认算法, 兼容性最好, 除 Apache 外的多数 Web 服务均支持': ['Apache 預設演算法, 相容性最好, 除 Apache 外的多數 Web 服務皆支援', 'Apache default algorithm; best compatibility — supported by most web servers besides Apache'],
  '固定盐值 (无盐), 存在彩虹表风险, 不建议用于新密码': ['固定鹽值 (無鹽), 有彩虹表風險, 不建議用於新密碼', 'Fixed salt (no salt); rainbow-table risk — not recommended for new passwords'],
  '密码以明文存储, 部分服务端编译时已禁用该方式': ['密碼以明文儲存, 部分伺服器編譯時已停用該方式', 'Stores the password in plain text; some server builds disable this method'],
  '规格': ['規格', 'Size'],
  '字符': ['字元', 'Characters'],
  '输入字符, 多个自动去重, 如: 中A8': ['輸入字元, 多個自動去重, 如: 中A8', 'Enter characters; duplicates are removed automatically, e.g. 中A8'],
  '取模方式': ['取模方式', 'Extraction mode'],
  '逐行式': ['逐行式', 'Row-wise'],
  '逐列式': ['逐列式', 'Column-wise'],
  '位序': ['位序', 'Bit order'],
  '高位在前': ['高位在前', 'MSB first'],
  '低位在前': ['低位在前', 'LSB first'],
  '反色 (取白)': ['反色 (取白)', 'Invert (white sampled as on)'],
  '阈值': ['閾值', 'Threshold'],
  '生成取模代码': ['產生取模程式碼', 'Generate code'],
  '复制代码': ['複製程式碼', 'Copy code'],
  '下载 .h': ['下載 .h', 'Download .h'],
  '清除结果': ['清除結果', 'Clear result'],
  '请输入需要取模的字符 (可多个, 自动去重)': ['請輸入需要取模的字元 (可多個, 自動去重)', 'Enter characters to extract (multiple allowed, duplicates removed)'],
  '当前环境不支持 Canvas 字形采样': ['目前環境不支援 Canvas 字形取樣', 'Canvas glyph sampling is not supported in this environment'],
  '已为 {n} 个字符生成取模代码': ['已為 {n} 個字元產生取模程式碼', 'Generated bitmaps for {n} character(s)'],
  '取模代码已复制到粘贴板': ['取模程式碼已複製到剪貼簿', 'Code copied to clipboard'],
  '保存字库头文件': ['儲存字庫標頭檔', 'Save font header'],
  '已保存 .h 文件': ['已儲存 .h 檔案', '.h file saved'],
  '字形按系统字体渲染后以 {w}×{h} 网格采样 (取每格中心判定), 与所选系统字体相关, 与标准字库字形可能有差异; 如需精确标准点阵字库请用字库文件/专业取模软件。': ['字形依系統字型轉譯後以 {w}×{h} 網格取樣 (取每格中心判定), 與所選系統字型相關, 與標準字庫字形可能有差異; 如需精確標準點陣字庫請使用字庫檔/專業取模軟體。', 'Glyphs are rendered with the system font, then sampled on a {w}×{h} grid (center of each cell). Output depends on the selected font and may differ from standard font library glyphs; for exact standard bitmaps use a font file or dedicated sampling software.'],
  '预览 (仅第一个字符 “{c}”)': ['預覽 (僅第一個字元 “{c}”)', 'Preview (first character “{c}” only)'],
  '取模结果 ({n} 字符 · {w}×{h} · {m} · {b})': ['取模結果 ({n} 字元 · {w}×{h} · {m} · {b})', 'Result ({n} chars · {w}×{h} · {m} · {b})'],
  '请在输入框中输入字符后点击「生成取模代码」': ['請在輸入框中輸入字元後點擊「產生取模程式碼」', 'Enter characters in the input above, then click Generate code'],
  'C 头文件': ['C 標頭檔', 'C header'],
  '清除': ['清除', 'Clear'],
  '删除': ['刪除', 'Delete'],
  '取消': ['取消', 'Cancel'],
  '确定': ['確定', 'OK'],
  '全部': ['全部', 'All'],
  '随机': ['隨機', 'Random'],
  '重置': ['重置', 'Reset'],
  '标准': ['標準', 'Standard'],
  '小键盘': ['數字鍵盤', 'Keypad'],
  '移动端': ['行動端', 'Mobile'],
  '游戏手柄': ['遊戲手把', 'Gamepad'],
  'Space (空格)': ['Space (空白)', 'Space'],
  '(无字符)': ['(無字元)', '(no char)'],
  '(无 code)': ['(無 code)', '(no code)'],
  '时间': ['時間', 'Time'],
  '按键': ['按鍵', 'Key'],
  '位置': ['位置', 'Location'],
  '修饰键': ['修飾鍵', 'Modifiers'],
  '时长': ['時長', 'Duration'],
  '按键信息会实时捕获: 无需聚焦本页面, 在应用任意位置按下/松开键盘即可看到结果。': ['按鍵資訊會即時擷取: 無需聚焦本頁面, 在應用任意位置按下/放開鍵盤即可看到結果。', 'Keys are captured in real time: without focusing this page, press/release any key anywhere in the app to see results.'],
  '按任意键查看按键信息…': ['按任意鍵查看按鍵資訊…', 'Press any key to inspect…'],
  '位置: {l}': ['位置: {l}', 'Location: {l}'],
  '修饰键: {m}': ['修飾鍵: {m}', 'Modifiers: {m}'],
  '按住: {d}': ['按住: {d}', 'Held: {d}'],
  '自动重复 ×{n}': ['自動重複 ×{n}', 'Auto-repeat ×{n}'],
  '(按键时同步刷新; 修饰键组合见上方 Tag)': ['(按鍵時同步更新; 修飾鍵組合見上方 Tag)', '(refreshes on key press; modifier combos shown in the tags above)'],
  '最近按键记录': ['最近按鍵記錄', 'Recent key history'],
  '清空记录': ['清空記錄', 'Clear history'],
  '文字': ['文字', 'Text'],
  '输入要生成大字的内容 (支持多行, 每行独立排版)': ['輸入要產生大字內容 (支援多行, 每行獨立排版)', 'Enter the text to render as ASCII art (multi-line supported, each line typeset independently)'],
  '字体': ['字體', 'Font'],
  '选择 figlet 字体': ['選擇 figlet 字體', 'Select a figlet font'],
  '共 {n} 款 figlet 字体': ['共 {n} 款 figlet 字體', '{n} figlet fonts'],
  '预览字号': ['預覽字號', 'Preview size'],
  '仅缩放预览显示, 复制的文本不受影响': ['僅縮放預覽顯示, 複製的文字不受影響', 'Only scales the preview — copied text is unaffected'],
  '字体来自 figlet 经典字体集; 支持英文字母 / 数字 / 常用标点, 中文等未收录字符按字体回退显示 · 默认字体可在「设置 → 其它」中调整': ['字體來自 figlet 經典字體集; 支援英文字母 / 數字 / 常用標點, 中文等未收錄字元依字體回退顯示 · 預設字體可在「設定 → 其他」中調整', 'Fonts come from the classic figlet collection; letters / digits / common punctuation are supported, while unlisted characters (e.g. CJK) fall back per font · the default font can be changed under Settings → Others'],
  '结果 ({r} 行 · {c} 字符):': ['結果 ({r} 行 · {c} 字元):', 'Result ({r} lines · {c} chars):'],
  '复制文本': ['複製文字', 'Copy text'],
  '下载 .txt': ['下載 .txt', 'Download .txt'],
  '提示: 预览按等宽字体近似比例示意, 复制到 Markdown 代码块或等宽字体编辑器效果最佳': ['提示: 預覽以等寬字型近似比例示意, 複製到 Markdown 程式碼區塊或等寬字型編輯器效果最佳', 'Tip: the preview approximates monospace proportions; pasting into a Markdown code block or a monospace editor gives the best result'],
  '已复制 {n} 字符到剪贴板': ['已複製 {n} 字元到剪貼簿', 'Copied {n} characters to the clipboard'],
  '复制失败, 请手动选中文本复制': ['複製失敗, 請手動選取文字複製', 'Copy failed — select the text and copy manually'],
  '保存 {n}': ['儲存 {n}', 'Save {n}'],
  '已保存 {n}': ['已儲存 {n}', 'Saved {n}'],
  '文本文件': ['文字檔', 'Text file'],
  '私有地址 (RFC 1918, 10.0.0.0/8)': ['私有位址 (RFC 1918, 10.0.0.0/8)', 'Private (RFC 1918, 10.0.0.0/8)'],
  '私有地址 (RFC 1918, 172.16.0.0/12)': ['私有位址 (RFC 1918, 172.16.0.0/12)', 'Private (RFC 1918, 172.16.0.0/12)'],
  '私有地址 (RFC 1918, 192.168.0.0/16)': ['私有位址 (RFC 1918, 192.168.0.0/16)', 'Private (RFC 1918, 192.168.0.0/16)'],
  '环回地址 (Loopback 127.0.0.0/8)': ['環回位址 (Loopback 127.0.0.0/8)', 'Loopback (127.0.0.0/8)'],
  '链路本地地址 (Link-Local 169.254.0.0/16)': ['鏈路本地位址 (Link-Local 169.254.0.0/16)', 'Link-Local (169.254.0.0/16)'],
  '运营商级 NAT 共享地址 (CGNAT 100.64.0.0/10)': ['電信級 NAT 共享位址 (CGNAT 100.64.0.0/10)', 'Carrier-grade NAT (CGNAT 100.64.0.0/10)'],
  '文档示例 TEST-NET-1 (192.0.2.0/24, RFC 5737)': ['文件範例 TEST-NET-1 (192.0.2.0/24, RFC 5737)', 'Documentation TEST-NET-1 (192.0.2.0/24, RFC 5737)'],
  '文档示例 TEST-NET-2 (198.51.100.0/24, RFC 5737)': ['文件範例 TEST-NET-2 (198.51.100.0/24, RFC 5737)', 'Documentation TEST-NET-2 (198.51.100.0/24, RFC 5737)'],
  '文档示例 TEST-NET-3 (203.0.113.0/24, RFC 5737)': ['文件範例 TEST-NET-3 (203.0.113.0/24, RFC 5737)', 'Documentation TEST-NET-3 (203.0.113.0/24, RFC 5737)'],
  '组播地址 (Multicast 224.0.0.0/4)': ['群播位址 (Multicast 224.0.0.0/4)', 'Multicast (224.0.0.0/4)'],
  '保留地址 (Reserved 240.0.0.0/4)': ['保留位址 (Reserved 240.0.0.0/4)', 'Reserved (240.0.0.0/4)'],
  '受限广播地址 (255.255.255.255)': ['受限廣播位址 (255.255.255.255)', 'Limited broadcast (255.255.255.255)'],
  '公网地址 (Global Unicast)': ['公網位址 (Global Unicast)', 'Public (Global Unicast)'],
  'A 类': ['A 類', 'Class A'],
  'B 类': ['B 類', 'Class B'],
  'C 类': ['C 類', 'Class C'],
  '单主机': ['單一主機', 'Single host'],
  '点对点': ['點對點', 'Point-to-point'],
  'IP 地址': ['IP 位址', 'IP address'],
  '前缀长度': ['前綴長度', 'Prefix length'],
  '网络地址': ['網路位址', 'Network'],
  '广播地址': ['廣播位址', 'Broadcast'],
  '子网掩码': ['子網路遮罩', 'Subnet mask'],
  '通配符掩码': ['萬用字元遮罩', 'Wildcard mask'],
  '地址总数': ['位址總數', 'Total addresses'],
  '可用主机数': ['可用主機數', 'Usable hosts'],
  '可用地址范围': ['可用位址範圍', 'Usable range'],
  ' (自身)': [' (本身)', ' (itself)'],
  '({n} 位)': ['({n} 位)', '({n} bits)'],
  '个': ['個', ''],
  '— (无可用主机地址)': ['— (無可用主機位址)', '— (no usable host address)'],
  'CIDR 计算器': ['CIDR 計算器', 'CIDR Calculator'],
  '输入 IPv4 CIDR（如 192.168.1.0/24）或纯 IP（按 /32 单主机计算），即时给出网络地址、广播地址、掩码、通配符掩码与主机范围。可直接点下方 A 类 / B 类 / C 类 / 单主机 / 点对点快速示例。': ['輸入 IPv4 CIDR（如 192.168.1.0/24）或純 IP（依 /32 單一主機計算），即時給出網路位址、廣播位址、遮罩、萬用字元遮罩與主機範圍。可直接點下方 A 類 / B 類 / C 類 / 單一主機 / 點對點快速範例。', 'Enter an IPv4 CIDR (e.g. 192.168.1.0/24) or a bare IP (treated as /32 single host) to instantly get the network, broadcast, mask, wildcard mask and host range. Click the Class A / B / C, Single host or Point-to-point quick examples below.'],
  '例如 192.168.1.0/24 或 203.0.113.25': ['例如 192.168.1.0/24 或 203.0.113.25', 'e.g. 192.168.1.0/24 or 203.0.113.25'],
  '已按输入即时计算': ['已依輸入即時計算', 'Calculated instantly from your input'],
  '快速示例:': ['快速範例:', 'Quick examples:'],
  '{i}  →  网络 {n}  /  掩码 {m}': ['{i}  →  網路 {n}  /  遮罩 {m}', '{i}  →  Network {n} / Mask {m}'],
  '/31 网段按 RFC 3021 点对点链路计, 两个地址均可分配使用。': ['/31 網段依 RFC 3021 點對點鏈路計, 兩個位址皆可分配使用。', 'A /31 subnet counts as an RFC 3021 point-to-point link — both addresses are usable.'],
  '/32 为单主机地址 (主机路由), 无网络/广播概念, 仅该 IP 本身可用。': ['/32 為單一主機位址 (主機路由), 無網路/廣播概念, 僅該 IP 本身可用。', 'A /32 is a single-host address (host route) with no network/broadcast concept — only that IP itself is usable.'],
  '无法解析该地址, 请输入形如 192.168.1.0/24 的 CIDR (前缀 0-32), 或直接输入 IPv4 地址 (按 /32 计算)': ['無法解析該位址, 請輸入形如 192.168.1.0/24 的 CIDR (前綴 0-32), 或直接輸入 IPv4 位址 (依 /32 計算)', 'Cannot parse that address. Enter a CIDR such as 192.168.1.0/24 (prefix 0–32), or a bare IPv4 address (treated as /32).'],
  '一级标题': ['一級標題', 'Heading 1'],
  '二级标题': ['二級標題', 'Heading 2'],
  '三级标题': ['三級標題', 'Heading 3'],
  '加粗': ['粗體', 'Bold'],
  '斜体': ['斜體', 'Italic'],
  '删除线': ['刪除線', 'Strikethrough'],
  '行内代码': ['行內程式碼', 'Inline code'],
  '链接 [文字](url)': ['連結 [文字](url)', 'Link [text](url)'],
  '图片 ![alt](url)': ['圖片 ![alt](url)', 'Image ![alt](url)'],
  '无序列表': ['無序清單', 'Unordered list'],
  '有序列表': ['有序清單', 'Ordered list'],
  '插入表格': ['插入表格', 'Insert table'],
  '引用块': ['引用區塊', 'Blockquote'],
  '代码块': ['程式碼區塊', 'Code block'],
  '分隔线': ['分隔線', 'Horizontal rule'],
  '行内公式': ['行內公式', 'Inline formula'],
  '块级公式': ['區塊公式', 'Block formula'],
  'Markdown 编辑器': ['Markdown 編輯器', 'Markdown Editor'],
  '左侧编写': ['左側編寫', 'Write on the left'],
  ', 右侧实时预览(支持常用语法与行内 / 块级 LaTeX 公式子集); 可导出': [', 右側即時預覽(支援常用語法與行內 / 區塊級 LaTeX 公式子集); 可匯出', ', live preview on the right (common syntax plus inline / block-level LaTeX subset); you can export a'],
  ' 源文件或自带样式的独立 ': [' 源檔或自帶樣式的獨立 ', ' source file, or a self-styled standalone '],
  ' 文档。': [' 文件。', ' document.'],
  '工具栏 (光标处插入)': ['工具列 (在游標處插入)', 'Toolbar (insert at cursor)'],
  '已载入示例': ['已載入範例', 'Sample loaded'],
  'Markdown 源码': ['Markdown 源碼', 'Markdown source'],
  '收起右侧预览, 专注编辑': ['收起右側預覽, 專注編輯', 'Collapse the right preview to focus on writing'],
  '恢复右侧预览面板': ['恢復右側預覽面板', 'Restore the right preview panel'],
  '隐藏预览': ['隱藏預覽', 'Hide preview'],
  '显示预览': ['顯示預覽', 'Show preview'],
  '{l} 行 / {c} 字符': ['{l} 行 / {c} 字元', '{l} lines / {c} chars'],
  '在此输入 Markdown…': ['在此輸入 Markdown…', 'Type Markdown here…'],
  '预览': ['預覽', 'Preview'],
  '源文件': ['源檔', 'source file'],
  '已复制预览 HTML': ['已複製預覽 HTML', 'Copied preview HTML'],
  '导出 HTML': ['匯出 HTML', 'Export HTML'],
  '已下载 {file}': ['已下載 {file}', 'Downloaded {file}'],
  '复制失败, 请手动选择复制': ['複製失敗, 請手動選擇複製', 'Copy failed, please copy manually'],
  '解析': ['解析', 'Parse'],
  '表达式格式': ['表達式格式', 'Expression format'],
  '快速预设': ['快速預設', 'Quick presets'],
  '标准 (秒 分 时 日 月 周 年)': ['標準 (秒 分 時 日 月 週 年)', 'Standard (sec min hr day month week year)'],
  'Linux (分 时 日 月 周, 无秒/年)': ['Linux (分 時 日 月 週, 無秒/年)', 'Linux (min hr day month week, no sec/year)'],
  'Linux cron 无「秒 / 年」字段, 已隐藏对应配置行': ['Linux cron 無「秒 / 年」欄位, 已隱藏對應設定列', 'Linux cron has no second/year fields, so their rows are hidden'],
  '任意 (*)': ['任意 (*)', 'Any (*)'],
  '范围 a-b': ['範圍 a-b', 'Range a-b'],
  '每 N 个': ['每 N 個', 'Every N'],
  '指定值': ['指定值', 'Specific values'],
  '至': ['至', 'to'],
  '每': ['每', 'Every'],
  '执行 (即 */N)': ['執行 (即 */N)', '(i.e. */N)'],
  '选择 {x} 中的若干值': ['選擇 {x} 中的若干值', 'Pick values from {x}'],
  '不限制': ['不限制', 'Unrestricted'],
  'Linux (5 段)': ['Linux (5 段)', 'Linux (5 fields)'],
  '标准 (7 段)': ['標準 (7 段)', 'Standard (7 fields)'],
  '标准格式 = 秒 分 时 日 月 周 年; Linux 格式 = 分 时 日 月 周 (crontab 不支持秒/年)': ['標準格式 = 秒 分 時 日 月 週 年; Linux 格式 = 分 時 日 月 週 (crontab 不支援秒/年)', 'Standard = sec min hr day month week year; Linux = min hr day month week (crontab has no seconds/years)'],
  'Cron 规则说明': ['Cron 規則說明', 'About Cron rules'],
  '该预设需要「秒」字段, 请先切换到标准格式': ['該預設需要「秒」欄位, 請先切換到標準格式', 'This preset needs the second field — switch to the standard format first'],
  '每 1 秒': ['每 1 秒', 'Every 1s'],
  '每 30 秒': ['每 30 秒', 'Every 30s'],
  '每 1 分钟': ['每 1 分鐘', 'Every 1 min'],
  '每 5 分钟': ['每 5 分鐘', 'Every 5 min'],
  '每小时整点': ['每小時整點', 'Top of every hour'],
  '每天 00:00': ['每天 00:00', 'Every day at 00:00'],
  '每周一 09:00': ['每週一 09:00', 'Every Mon at 09:00'],
  '每月 1 日 00:00': ['每月 1 日 00:00', '1st of every month at 00:00'],
  '每年 1 月 1 日 00:00': ['每年 1 月 1 日 00:00', 'Jan 1 every year at 00:00'],
  '每秒执行': ['每秒執行', 'Runs every second'],
  '0 与 7 均表示周日': ['0 與 7 均表示週日', '0 and 7 both mean Sunday'],
  '仅标准格式 (可选)': ['僅標準格式 (可選)', 'Standard format only (optional)'],
  '秒': ['秒', 's'],
  '分': ['分', 'm'],
  '时': ['時', 'h'],
  '日': ['日', 'd'],
  '月': ['月', 'mo'],
  '周': ['週', 'w'],
  '年': ['年', 'y'],
  '周日 (0)': ['週日 (0)', 'Sun (0)'],
  '周日 (7)': ['週日 (7)', 'Sun (7)'],
  '周一 (1)': ['週一 (1)', 'Mon (1)'],
  '周二 (2)': ['週二 (2)', 'Tue (2)'],
  '周三 (3)': ['週三 (3)', 'Wed (3)'],
  '周四 (4)': ['週四 (4)', 'Thu (4)'],
  '周五 (5)': ['週五 (5)', 'Fri (5)'],
  '周六 (6)': ['週六 (6)', 'Sat (6)'],
  '解析规则': ['解析規則', 'Parse rule'],
  '试试:': ['試試:', 'Try:'],
  '解析失败': ['解析失敗', 'Parse failed'],
  '复制全部': ['複製全部', 'Copy all'],
  '共 {x} 个取值': ['共 {x} 個取值', '{x} values in total'],
  '提示: 「日」与「周」同时被限制时按': ['提示: 「日」與「週」同時被限制時按', 'Note: when both day & week are restricted it matches with'],
  '或': ['或', 'OR'],
  '匹配 (任一满足即触发, 同 Vixie cron); 单独限制其一则只按该条件': ['匹配 (任一滿足即觸發, 同 Vixie cron); 單獨限制其一則只按該條件', ' (either satisfies → fires, like Vixie cron); with only one restricted, that condition alone is used'],
  '最近 10 次触发时间': ['最近 10 次觸發時間', 'Next 10 fire times'],
  '该规则在 2024-2099 年内无法触发 (请检查规则是否可达, 如 2 月 30 日)': ['該規則在 2024-2099 年內無法觸發 (請檢查規則是否可達, 如 2 月 30 日)', 'This rule cannot fire within 2024-2099 (check whether it is reachable, e.g. Feb 30)'],
  '仅找到 {x} 次 (在 2099 年范围内)': ['僅找到 {x} 次 (在 2099 年範圍內)', 'Only found {x} times (within year 2099)'],
  '即将触发': ['即將觸發', 'Firing now'],
  '约 {n} 天后': ['約 {n} 天後', 'in ~{n} days'],
  '约 {n} 小时后': ['約 {n} 小時後', 'in ~{n} hours'],
  '约 {n} 分钟后': ['約 {n} 分鐘後', 'in ~{n} minutes'],
  '1 分钟内': ['1 分鐘內', 'within 1 minute'],
  '输入 Cron 表达式, 如 0 9 * * 1 (格式需与上方一致)': ['輸入 Cron 表達式, 如 0 9 * * 1 (格式需與上方一致)', 'Enter a cron expression, e.g. 0 9 * * 1 (must match the format above)'],
  '每月 1 日 03:15': ['每月 1 日 03:15', '1st of every month at 03:15'],
  '每年元旦 (2026)': ['每年元旦 (2026)', 'New Year\u2019s Day (2026)'],
  '正在生成…': ['正在生成…', 'Generating…'],
};

export const u = (locale: string, zh: string): string => {
  const hit = D[zh];
  if (!hit) return zh;
  return locale === 'zh-TW' ? hit[0] : locale === 'en' ? hit[1] : zh;
};

export const uT = (locale: string, zhTpl: string, vars?: Record<string, string | number>): string => {
  let out = u(locale, zhTpl);
  if (vars) out = out.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));
  return out;
};
