// 站长工具(Webmaster)分类页面共享词条: zh 原文即 key, 值为 [zh-TW, en]
// 用法: const t = (zh:string) => wm(locale, zh); 动态模板: wmT(locale, zhTpl, {x:...}) (占位符 {x})
type WmRec = Record<string, [string, string]>;
const D: WmRec = {
  '已复制': ['已複製', 'Copied'],
  '复制失败, 请手动选择复制': ['複製失敗, 請手動選擇複製', 'Copy failed — please select and copy manually'],
  '计算失败: {msg}': ['計算失敗: {msg}', 'Computation failed: {msg}'],
  '浏览器指纹': ['瀏覽器指紋', 'Browser Fingerprint'],
  '在本页分别计算 ': ['在本頁分別計算 ', 'On this page we compute '],
  'Canvas / WebGL / 音频': ['Canvas / WebGL / 音訊', 'Canvas / WebGL / Audio'],
  ' 三类指纹并给出对应的可直接复制的 JS 实现。': [' 三類指紋並提供對應可直接複製的 JS 實作。', ' fingerprints and show copy-ready JS implementations for each.'],
  '指纹常用于无感设备识别：同机不同浏览器、同浏览器不同版本、隐身模式等都可能产生不同哈希。': ['指紋常用於無感設備識別：同機不同瀏覽器、同瀏覽器不同版本、無痕模式等都可能產生不同雜湊。', 'Fingerprints are often used for silent device recognition: the same machine on another browser, another browser version, or in private mode may produce different hashes.'],
  '隐私提示:': ['隱私提示:', 'Privacy note:'],
  '请勿在未告知用户的站点中擅自采集并跨站关联指纹，合规用途请先取得用户同意。': ['請勿在未告知使用者的網站中擅自蒐集並跨站關聯指紋，合規用途請先取得使用者同意。', 'Do not collect or cross-site correlate fingerprints without telling the user; obtain consent before any compliant use.'],
  '运行结果': ['運行結果', 'Results'],
  '重新计算全部': ['重新計算全部', 'Re-run all'],
  '复制': ['複製', 'Copy'],
  '不可用': ['不可用', 'Unavailable'],
  '已生成': ['已生成', 'Generated'],
  '计算中…': ['計算中…', 'Computing…'],
  '查看 JS 实现': ['查看 JS 實作', 'View JS implementation'],
  '复制完整代码': ['複製完整程式碼', 'Copy full code'],
  '指纹稳定性说明': ['指紋穩定性說明', 'About fingerprint stability'],
  '三类指纹相加（含 UA、语言、时区、屏幕分辨率等）即构成强标识；WebGL 渲染器与音频指纹在部分系统升级/驱动更新后会变化，Canvas 指纹则相对稳定。本页计算的哈希仅作特征演示，不采集、不存储、不上传任何数据。': ['三類指紋相加（含 UA、語言、時區、螢幕解析度等）即構成強識別；WebGL 渲染器與音訊指紋在部分系統升級/驅動更新後會變化，Canvas 指紋則相對穩定。本頁計算的雜湊僅作特徵展示，不蒐集、不儲存、不上傳任何資料。', 'All three fingerprints combined (plus UA, language, timezone, screen resolution, …) form a strong identifier; the WebGL renderer and audio fingerprints may change after OS upgrades / driver updates, while Canvas tends to stay stable. The hashes computed here are only demos — nothing is collected, stored or uploaded.'],
  '浏览器将文字/图形光栅化后各平台抗锯齿与字体渲染存在细微差异，同一脚本在不同设备输出的像素不同——这是区分度最高的指纹之一。': ['瀏覽器將文字/圖形光柵化後，各平台抗鋸齒與字型渲染存在細微差異，同一腳本在不同裝置輸出的像素不同——這是區分度最高的指紋之一。', 'After the browser rasterizes text/graphics, anti-aliasing and font rendering differ subtly across platforms, so the same script yields different pixels on different devices — one of the most distinctive fingerprints.'],
  '通过 GPU 渲染上下文读取显卡厂商与渲染器标识（可被隐私模式伪装），并结合支持的扩展数量与渲染参数生成指纹。': ['透過 GPU 渲染上下文讀取顯示卡廠商與渲染器識別（可被無痕模式偽裝），並結合支援的擴充數量與渲染參數產生指紋。', 'Reads GPU vendor and renderer identifiers from a WebGL context (spoofable in private mode) and fingerprints the device by them plus the number of supported extensions and rendering parameters.'],
  '利用 OfflineAudioContext 离线合成音频信号，各浏览器的音频处理管线（重采样、压缩器实现）会让输出样本产生微小但稳定的差异。': ['利用 OfflineAudioContext 離線合成音訊訊號，各瀏覽器的音訊處理管線（重取樣、壓縮器實作）會讓輸出樣本產生微小但穩定的差異。', 'Uses OfflineAudioContext to synthesize audio offline; each browser’s audio pipeline (resampling, compressor implementation) produces small yet stable differences in the output samples.'],
  'Canvas 指纹': ['Canvas 指紋', 'Canvas fingerprint'],
  'WebGL 指纹': ['WebGL 指紋', 'WebGL fingerprint'],
  '音频指纹': ['音訊指紋', 'Audio fingerprint'],
  '已复制 {n} 个 URL': ['已複製 {n} 個 URL', 'Copied {n} URLs'],
  '复制失败, 请手动全选复制': ['複製失敗, 請手動全選複製', 'Copy failed — please select all and copy manually'],
  '已下载 urls.txt': ['已下載 urls.txt', 'Downloaded urls.txt'],
  '已载入示例文本': ['已載入範例文字', 'Sample text loaded'],
  'URL 提取': ['URL 提取', 'Extract URLs'],
  '从任意文本（日志、邮件、页面源码…）中批量提取链接。自动清理行尾句读标点与不成对括号；「去重」默认开启，可在 设置 → 站长工具 中调整默认值。': ['從任意文字（日誌、郵件、頁面原始碼…）中批次提取連結。自動清理行尾句讀標點與不成對括號；「去重」預設開啟，可在 設定 → 站長工具 中調整預設值。', 'Bulk-extract links from any text (logs, e-mails, page source…). Trailing punctuation and unbalanced brackets are cleaned automatically; “Deduplicate” is on by default and can be changed in Settings → Webmaster Tools.'],
  '原始文本': ['原始文字', 'Source text'],
  '载入示例': ['載入範例', 'Load sample'],
  '清空': ['清空', 'Clear'],
  '去重': ['去重', 'Deduplicate'],
  '仅 http/https': ['僅 http/https', 'http/https only'],
  '原文 {c} 字符, 检出 {n} 条 (去重前)': ['原文 {c} 字元, 偵測到 {n} 條 (去重前)', '{c} chars in source, {n} found (before dedupe)'],
  '提取结果': ['提取結果', 'Extracted URLs'],
  '下载 .txt': ['下載 .txt', 'Download .txt'],
  '提取 {n} 个 URL': ['提取 {n} 個 URL', 'Extracted {n} URLs'],
  '已去重 {n} 条': ['已去重 {n} 條', '{n} duplicate(s) removed'],
  '暂无结果 — 在上方粘贴包含链接的文本后自动提取。': ['暫無結果 — 在上方貼上包含連結的文字後會自動提取。', 'No results yet — paste text containing links above to extract automatically.'],
  '已载入文件 {name} ({c} 字符)': ['已載入檔案 {name} ({c} 字元)', 'Loaded file {name} ({c} characters)'],
  '文件读取失败': ['檔案讀取失敗', 'Failed to read the file'],
  '已复制提取结果': ['已複製提取結果', 'Extracted text copied'],
  '已下载 extracted-text.txt': ['已下載 extracted-text.txt', 'Downloaded extracted-text.txt'],
  'HTML 标签去除': ['HTML 標籤去除', 'Strip HTML Tags'],
  '去掉 HTML 标签只保留文本内容, 并按段落 / 列表 / 表格结构保留换行。': ['去掉 HTML 標籤只保留文字內容, 並依段落 / 列表 / 表格結構保留換行。', 'Removes HTML tags, keeping only the text while preserving line breaks for paragraphs / lists / tables.'],
  'select 下拉框': ['select 下拉框', 'select dropdown'],
  ': 默认把每个 ': [': 預設會把每個 ', 'Each '],
  ' 提取为': [' 提取為', ' is extracted as'],
  'value: 文本': ['value: 文字', 'value: text'],
  ' 一行(如 ': [' 一行(如 ', ' on one line (e.g. '],
  '), 避免下拉选项文本粘连丢失。': ['), 避免下拉選項文字黏連遺失。', '), so option labels never stick together.'],
  'script / style / 注释等内容自动剔除。': ['script / style / 註解等內容會自動剔除。', 'script / style / comment contents are removed automatically.'],
  '原始 HTML': ['原始 HTML', 'Source HTML'],
  '读取文件': ['讀取檔案', 'Open file'],
  '已载入示例 HTML': ['已載入範例 HTML', 'Sample HTML loaded'],
  'select 下拉框选项提取为': ['select 下拉框選項提取為', 'Extract <select> options as'],
  ' 行': [' 行', ' line'],
  '原始 {c} 字符 / {n} 行': ['原始 {c} 字元 / {n} 行', '{c} chars / {n} lines in source'],
  '提取结果 (纯文本)': ['提取結果 (純文字)', 'Extracted text (plain)'],
  '提取后 {c} 字符': ['提取後 {c} 字元', '{c} characters after extraction'],
  '{n} 行': ['{n} 行', '{n} lines'],
  '暂无结果 — 在上方粘贴 HTML 后会自动提取。': ['暫無結果 — 在上方貼上 HTML 後會自動提取。', 'No results yet — paste HTML above to extract automatically.'],
  '关键词密度': ['關鍵詞密度', 'Keyword Density'],
  '密度 = 出现次数 × 关键词字符数 ÷ 有效字符总数 × 100% (有效字符不含空白与标点)。左侧输入文本, 下方可同时分析多个关键词(逗号分隔); 词频表按英文单词统计。': ['密度 = 出現次數 × 關鍵詞字元數 ÷ 有效字元總數 × 100% (有效字元不含空白與標點)。左側輸入文字, 下方可同時分析多個關鍵詞(逗號分隔); 詞頻表按英文單字統計。', 'Density = occurrences × keyword length ÷ total effective characters × 100% (blank and punctuation are excluded). Paste text on the left; below you can analyze several keywords at once (comma-separated). The frequency table counts English words.'],
  '文本与关键词': ['文字與關鍵詞', 'Text & Keywords'],
  '粘贴要分析的页面文本 / 文章正文…': ['貼上要分析的頁面文字 / 文章內文…', 'Paste the page text / article body to analyze…'],
  '有效字符 {n}': ['有效字元 {n}', '{n} effective chars'],
  '英文词 {n}': ['英文單字 {n}', '{n} English words'],
  '汉字 {n}': ['漢字 {n}', '{n} Han chars'],
  '段落 {n}': ['段落 {n}', '{n} paragraphs'],
  '句子 {n}': ['句子 {n}', '{n} sentences'],
  '关键词': ['關鍵詞', 'Keywords'],
  '关键词密度报告': ['關鍵詞密度報告', 'Keyword Density Report'],
  '出现 {n} 次': ['出現 {n} 次', '{n} occurrences'],
  '建议区间 0.5% ~ 3%': ['建議區間 0.5% ~ 3%', 'Suggested range 0.5% ~ 3%'],
  '未出现': ['未出現', 'Not found'],
  '密度偏低': ['密度偏低', 'Low'],
  '正常': ['正常', 'Normal'],
  '偏高': ['偏高', 'High'],
  '过高(疑似堆砌)': ['過高(疑似堆砌)', 'Too high (keyword stuffing)'],
  '英文词频 Top 50 ': ['英文單字頻率 Top 50 ', 'Top 50 English words '],
  '(词频按英文单词统计, 中文词组请用上方关键词密度)': ['(詞頻按英文單字統計, 中文詞組請用上方關鍵詞密度)', '(frequency counts English words; for Chinese phrases use the keyword density section above)'],
  '忽略停用词': ['忽略停用詞', 'Ignore stop words'],
  '已复制词频 CSV': ['已複製詞頻 CSV', 'Word-frequency CSV copied'],
  '复制 CSV': ['複製 CSV', 'Copy CSV'],
  '单词': ['單字', 'Word'],
  '次数': ['次數', 'Count'],
  '密度 %': ['密度 %', 'Density %'],
  '暂无英文单词 — 中文文本请使用上方关键词分析。': ['暫無英文單字 — 中文文字請使用上方關鍵詞分析。', 'No English words found — for Chinese text use the keyword analysis above.'],
  '多个关键词用逗号分隔, 例如: seo, 关键词密度, 数据分析': ['多個關鍵詞用逗號分隔, 例如: seo, keyword density, data analysis', 'Separate multiple keywords with commas, e.g. seo, keyword density, data analysis'],
  '复制到粘贴板成功!!!': ['複製到剪貼簿成功!!!', 'Copied to clipboard!!!'],
  '保存 robots.txt 文件': ['儲存 robots.txt 檔案', 'Save robots.txt file'],
  '爬虫 User-agent': ['爬蟲 User-agent', 'Crawler User-agent'],
  '为不同爬虫分组时, 请按此页生成多次再合并': ['為不同爬蟲分組時, 請依此頁生成多次再合併', 'To give each crawler its own rules, generate this page once per group and merge the results'],
  '抓取规则': ['抓取規則', 'Crawl rules'],
  '禁止 (Disallow)': ['禁止 (Disallow)', 'Disallow'],
  '允许 (Allow)': ['允許 (Allow)', 'Allow'],
  '清空规则': ['清空規則', 'Clear rules'],
  '禁止': ['禁止', 'Disallow'],
  '允许': ['允許', 'Allow'],
  '路径, 如 /admin/': ['路徑, 如 /admin/', 'Path, e.g. /admin/'],
  '当前无规则 = 允许爬虫抓取全部页面 (等效放行)': ['目前無規則 = 允許爬蟲抓取全部頁面 (等同放行)', 'No rules at all means crawlers may fetch every page (allow-all)'],
  '秒': ['秒', 'seconds'],
  '抓取间隔秒数 (留空不输出; 部分爬虫不支持)': ['抓取間隔秒數 (留空不輸出; 部分爬蟲不支援)', 'Seconds to wait between fetches (omit if blank; not supported by every crawler)'],
  '每行一个 Sitemap 地址, 如 https://example.com/sitemap.xml': ['每行一個 Sitemap 地址, 如 https://example.com/sitemap.xml', 'One Sitemap URL per line, e.g. https://example.com/sitemap.xml'],
  '快捷模板': ['快捷範本', 'Quick templates'],
  '预览': ['預覽', 'Preview'],
  '双击复制内容到粘贴板': ['雙擊複製內容到剪貼簿', 'Double-click to copy the content'],
  '保存为 robots.txt': ['儲存為 robots.txt', 'Save as robots.txt'],
  'robots.txt 生成说明': ['robots.txt 產生說明', 'About robots.txt'],
  '* (所有爬虫)': ['* (所有爬蟲)', '* (all crawlers)'],
  'Googlebot (谷歌)': ['Googlebot (谷歌)', 'Googlebot (Google)'],
  'Baiduspider (百度)': ['Baiduspider (百度)', 'Baiduspider (Baidu)'],
  'Bingbot (必应)': ['Bingbot (必應)', 'Bingbot (Bing)'],
  'Sogou (搜狗)': ['Sogou (搜狗)', 'Sogou (Sogou)'],
  '360Spider (360)': ['360Spider (360)', '360Spider (360)'],
  'Bytespider (字节跳动)': ['Bytespider (位元組跳動)', 'Bytespider (ByteDance)'],
  'YandexBot (Yandex)': ['YandexBot (Yandex)', 'YandexBot (Yandex)'],
  'PetalBot (华为)': ['PetalBot (華為)', 'PetalBot (Huawei)'],
  '示例: 禁止后台目录': ['範例: 禁止後台目錄', 'Example: block admin paths'],
  '允许全部抓取': ['允許全部抓取', 'Allow all crawlers'],
  '禁止全站抓取': ['禁止全站抓取', 'Block the whole site'],
  '校验 ': ['檢核 ', 'Validate '],
  'XML, 检查 URL 格式、': ['XML, 檢查 URL 格式、', 'XML, check URL formats, '],
  ' 日期、': [' 日期、', ' date, '],
  ' 枚举、': [' 枚舉、', ' enum values, '],
  ' 范围与重复 URL。': [' 範圍與重複 URL。', ' range and duplicated URLs.'],
  '支持粘贴或直接抓取在线 sitemap (Tauri 桌面端无跨域限制)。': ['支援貼上或直接抓取線上 sitemap (Tauri 桌面端無跨域限制)。', 'Paste XML or fetch an online sitemap directly (the Tauri desktop build has no CORS restrictions).'],
  'Sitemap 检查': ['Sitemap 檢查', 'Sitemap Check'],
  '输入': ['輸入', 'Input'],
  '粘贴 XML': ['貼上 XML', 'Paste XML'],
  '抓取网址': ['抓取網址', 'Fetch by URL'],
  '在此粘贴 sitemap.xml / sitemap index 的 XML 内容…': ['在此貼上 sitemap.xml / sitemap index 的 XML 內容…', 'Paste the XML of a sitemap.xml / sitemap index here…'],
  '抓取': ['抓取', 'Fetch'],
  '检查结果': ['檢查結果', 'Check results'],
  '无法识别': ['無法識別', 'Unrecognized'],
  '条目 {n}': ['條目 {n}', '{n} entries'],
  '重复 {n}': ['重複 {n}', '{n} duplicates'],
  '错误 {n}': ['錯誤 {n}', '{n} errors'],
  '告警 {n}': ['告警 {n}', '{n} warnings'],
  '已复制 CSV': ['已複製 CSV', 'CSV copied'],
  '下载 CSV': ['下載 CSV', 'Download CSV'],
  '已复制 JSON': ['已複製 JSON', 'JSON copied'],
  '复制 JSON': ['複製 JSON', 'Copy JSON'],
  '… 其余 {n} 条告警已省略': ['… 其餘 {n} 條告警已省略', '… {n} more warnings omitted'],
  '条目列表 ({n})': ['條目列表 ({n})', 'Entry list ({n})'],
  '共 {n} 条': ['共 {n} 條', '{n} in total'],
  '(空)': ['(空)', '(empty)'],
  '请输入 sitemap 网址': ['請輸入 sitemap 網址', 'Enter a sitemap URL'],
  '网址必须以 http:// 或 https:// 开头': ['網址必須以 http:// 或 https:// 開頭', 'The URL must start with http:// or https://'],
  '已抓取 {c} 字符': ['已抓取 {c} 字元', 'Fetched {c} characters'],
  '已下载 sitemap.csv': ['已下載 sitemap.csv', 'Downloaded sitemap.csv'],
  '已下载 {file}': ['已下載 {file}', 'Downloaded {file}'],
  '检测到 .gz 压缩包: 请先本地解压后粘贴内容': ['偵測到 .gz 壓縮檔: 請先在本機解壓後再貼上內容', 'Detected a .gz archive: please decompress it locally and paste the content'],
  '服务器返回 HTTP {code}': ['伺服器回傳 HTTP {code}', 'The server returned HTTP {code}'],
};
export const wm = (locale: string, zh: string): string => {
  const e = D[zh];
  if (!e) return zh;
  return locale === 'zh-TW' ? e[0] : locale === 'en' ? e[1] : zh;
};
export const wmT = (locale: string, zh: string, v?: Record<string, string | number>): string => {
  let s = wm(locale, zh);
  if (v) for (const [k, val] of Object.entries(v)) s = s.split('{'+k+'}').join(String(val));
  return s;
};
