// IptablesRules 语言包: 名称 (zh-CN = define.tsx AppName 默认; 缺省回退 zh-CN)
export default {
  default: 'zh-CN',
  'zh-TW': { appName: "iptables 規則" },
  en: { appName: "iptables Rules" },
} as const;

// 界面文案词条 (zh 短语即 key; 缺 zh-CN 时回退原文)
const iptableslangRows: Record<string, [string, string]> = {
  '解析': ['解析', 'Parse'],
  '生成': ['生成', 'Generate'],
  '规则文本': ['規則文字', 'Rule text'],
  '粘贴 iptables 命令或 iptables-save 输出, 每行一条, 例如:\niptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-ports 80\n:INPUT DROP [0:0]': ['貼上 iptables 命令或 iptables-save 輸出, 每行一條, 例如:\niptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-ports 80\n:INPUT DROP [0:0]', 'Paste iptables commands or iptables-save output, one rule per line, e.g.:\niptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-ports 80\n:INPUT DROP [0:0]'],
  '示例': ['範例', 'Sample'],
  '清空': ['清空', 'Clear'],
  '复制': ['複製', 'Copy'],
  '点击复制': ['點擊複製', 'Click to copy'],
  '匹配条件': ['匹配條件', 'Matches'],
  '表 / 链': ['表 / 鏈', 'Table / Chain'],
  '复制结果': ['複製結果', 'Copy result'],
  '复制表格': ['複製表格', 'Copy table'],
  '复制全部': ['複製全部', 'Copy all'],
  '保存为 .sh': ['儲存為 .sh', 'Save as .sh'],
  '保存成功': ['儲存成功', 'Saved'],
  'Shell 脚本': ['Shell 指令碼', 'Shell script'],
  '复制到粘贴板成功!!!': ['複製到剪貼簿成功!!!', 'Copied to clipboard!!!'],
  '请先输入 iptables 规则文本': ['請先輸入 iptables 規則文字', 'Please enter iptables rule text first'],
  '解析完成, 共 {n} 条规则': ['解析完成, 共 {n} 條規則', 'Parsed {n} rule(s)'],
  '解析后的规则会显示在这里': ['解析後的規則會顯示在這裡', 'Parsed rules will be shown here'],
  '共 {n} 条规则': ['共 {n} 條規則', '{n} rule(s)'],
  '以下 {n} 行无法识别为 iptables 规则:': ['以下 {n} 行無法識別為 iptables 規則:', '{n} line(s) could not be recognized as iptables rules:'],
  '序号': ['序號', '#'],
  '表': ['表', 'Table'],
  '操作': ['操作', 'Op'],
  '链': ['鏈', 'Chain'],
  '协议': ['協定', 'Protocol'],
  '源': ['來源', 'Source'],
  '目的': ['目的', 'Destination'],
  '端口': ['連接埠', 'Port'],
  '状态': ['狀態', 'State'],
  '动作': ['動作', 'Target'],
  '默认策略': ['預設策略', 'Default policy'],
  '备注': ['備註', 'Comment'],
  '原始规则': ['原始規則', 'Raw rule'],
  '位置': ['位置', 'Position'],
  '载入到生成': ['載入到生成', 'Load into Generate'],
  '已载入到「生成」页签': ['已載入到「生成」頁籤', 'Loaded into the "Generate" tab'],
  '{n} 个未识别参数': ['{n} 個未識別參數', '{n} unrecognized option(s)'],
  '该行使用了本工具未建模的参数, 生成时会被忽略': ['該行使用了本工具未建模的參數, 生成時會被忽略', 'This rule uses options this tool does not model; they are ignored when generating'],
  '表名': ['表名', 'Table'],
  '链名': ['鏈名', 'Chain'],
  '插入位置': ['插入位置', 'Insert position'],
  '源地址': ['來源位址', 'Source address'],
  '目的地址': ['目的位址', 'Destination address'],
  '入接口': ['入介面', 'In interface'],
  '出接口': ['出介面', 'Out interface'],
  '源端口': ['來源連接埠', 'Source port'],
  '目的端口': ['目的連接埠', 'Destination port'],
  '连接状态': ['連線狀態', 'Connection state'],
  '限速': ['限速', 'Rate limit'],
  '突发包数': ['突發封包數', 'Burst'],
  'ICMP 类型': ['ICMP 類型', 'ICMP type'],
  '追加参数': ['追加參數', 'Extra options'],
  '不限': ['不限', 'Any'],
  '例如 10/min': ['例如 10/min', 'e.g. 10/min'],
  '例如 echo-request': ['例如 echo-request', 'e.g. echo-request'],
  '附加的原样参数, 会插在 -j 之前': ['附加的原樣參數, 會插在 -j 之前', 'Extra raw options inserted before -j'],
  '新建链名 / 动作参数': ['新建鏈名 / 動作參數', 'New chain name / target options'],
  '日志前缀': ['日誌前綴', 'Log prefix'],
  '日志级别': ['日誌級別', 'Log level'],
  '转发到': ['轉發到', 'To destination'],
  '源地址转换为': ['來源位址轉換為', 'To source'],
  '重定向端口': ['重定向連接埠', 'To ports'],
  '标记值': ['標記值', 'Mark'],
  '拒绝方式': ['拒絕方式', 'Reject with'],
  '生成指令': ['產生指令', 'Generate commands'],
  '重置': ['重設', 'Reset'],
  '生效指令 (iptables 命令)': ['生效指令 (iptables 命令)', 'Apply command (iptables)'],
  'iptables-save 规则行': ['iptables-save 規則行', 'iptables-save rule line'],
  '填入 sudo iptables-restore 或 /etc/iptables/rules.v4': ['填入 sudo iptables-restore 或 /etc/iptables/rules.v4', 'Add to sudo iptables-restore or /etc/iptables/rules.v4'],
  '查看与验证': ['查看與驗證', 'Inspect & verify'],
  '删除指令': ['刪除指令', 'Remove commands'],
  '保存与持久化': ['儲存與持久化', 'Save & persist'],
  '生成的指令仅作参考, 请确认无误后在目标机器上执行 (通常需要 root)': ['產生的指令僅作參考, 請確認無誤後在目標機器上執行 (通常需要 root)', 'Generated commands are for reference — verify them before running (usually as root)'],
  '校验未通过, 请检查以下问题:': ['校驗未通過, 請檢查以下問題:', 'Validation failed, please check the following:'],
  '结果会显示在这里': ['結果會顯示在這裡', 'Results will be shown here'],
  '表不能为空': ['表不能為空', 'Table is required'],
  '链不能为空': ['鏈不能為空', 'Chain is required'],
  '插入 / 删除位置必须是数字': ['插入 / 刪除位置必須是數字', 'Insert/delete position must be a number'],
  '源地址格式不正确': ['來源位址格式不正確', 'Invalid source address'],
  '目的地址格式不正确': ['目的位址格式不正確', 'Invalid destination address'],
  '源端口格式不正确': ['來源連接埠格式不正確', 'Invalid source port'],
  '目的端口格式不正确': ['目的連接埠格式不正確', 'Invalid destination port'],
  '端口匹配需要协议为 tcp / udp / sctp, 或使用逗号列表 (multiport)': ['連接埠匹配需要協定為 tcp / udp / sctp, 或使用逗號列表 (multiport)', 'Port matching needs protocol tcp/udp/sctp, or a comma list (multiport)'],
  '请填写动作 (-j)': ['請填寫動作 (-j)', 'Target (-j) is required'],
  '默认策略只能是 ACCEPT 或 DROP': ['預設策略只能是 ACCEPT 或 DROP', 'Default policy must be ACCEPT or DROP'],
  '拒绝方式取值不正确 (如 icmp-port-unreachable / tcp-reset)': ['拒絕方式取值不正確 (如 icmp-port-unreachable / tcp-reset)', 'Invalid reject-with value (e.g. icmp-port-unreachable / tcp-reset)'],
  '日志级别必须是 0-7': ['日誌級別必須是 0-7', 'Log level must be 0-7'],
  '标记值格式不正确 (如 0x1 或 1)': ['標記值格式不正確 (如 0x1 或 1)', 'Invalid mark value (e.g. 0x1 or 1)'],
  '转发到地址格式不正确': ['轉發到位址格式不正確', 'Invalid to-destination address'],
  '源地址转换格式不正确': ['來源位址轉換格式不正確', 'Invalid to-source address'],
  '重定向端口必须是端口或端口区间': ['重定向連接埠必須是連接埠或連接埠區間', 'To-ports must be a port or port range'],
  '限速格式不正确 (如 10/min)': ['限速格式不正確 (如 10/min)', 'Invalid rate limit format (e.g. 10/min)'],
  '突发包数必须是数字': ['突發封包數必須是數字', 'Burst must be a number'],
  '备注不能超过 256 个字符': ['備註不能超過 256 個字元', 'Comment cannot exceed 256 characters'],
  '日志前缀不能超过 29 个字符': ['日誌前綴不能超過 29 個字元', 'Log prefix cannot exceed 29 characters'],
  '未填插入位置, 将插入到链首 (位置 1)': ['未填插入位置, 將插入到鏈首 (位置 1)', 'No position given — the rule is inserted at the top of the chain (position 1)'],
  '追加规则会放在链末尾, 若前面已有 DROP 规则可能不生效': ['追加規則會放在鏈末尾, 若前面已有 DROP 規則可能不生效', 'Appended rules go to the end of the chain and may be shadowed by an earlier DROP'],
  'NAT 转发需要开启内核转发 (net.ipv4.ip_forward=1)': ['NAT 轉發需要開啟核心轉發 (net.ipv4.ip_forward=1)', 'NAT forwarding requires net.ipv4.ip_forward=1'],
  '清空 / 删除链只在对应表内生效, 请确认表名': ['清空 / 刪除鏈只在對應表內生效, 請確認表名', 'Flushing/deleting chains only affects the selected table — double-check the table name'],
  '简单配置': ['簡單設定', 'Simple config'],
  '使用场景': ['使用情境', 'Scenario'],
  '开放端口': ['開放連接埠', 'Open port'],
  '封禁 IP': ['封鎖 IP', 'Block IP'],
  '封禁网段': ['封鎖網段', 'Block subnet'],
  '端口转发': ['連接埠轉發', 'Port forwarding'],
  '放行本机某个端口的入站访问 (Web / SSH / 数据库等)': ['放行本機某個連接埠的入站存取 (Web / SSH / 資料庫等)', 'Allow inbound traffic to one port on this host (web / SSH / database …)'],
  '丢弃来自指定 IP 的入站流量, 常用于封锁攻击源': ['丟棄來自指定 IP 的入站流量, 常用於封鎖攻擊來源', 'Drop inbound traffic from one IP — handy for blocking an attacker'],
  '丢弃来自指定网段 (CIDR) 的入站流量': ['丟棄來自指定網段 (CIDR) 的入站流量', 'Drop inbound traffic from a CIDR block'],
  '把本机端口的流量转发到内网另一台机器 (DNAT + 内核转发)': ['把本機連接埠的流量轉發到內網另一台機器 (DNAT + 核心轉發)', 'Forward a local port to another host on the internal network (DNAT + IP forwarding)'],
  'IP 地址': ['IP 位址', 'IP address'],
  '网段': ['網段', 'Subnet'],
  '对外端口': ['對外連接埠', 'Public port'],
  '转发目标 IP': ['轉發目標 IP', 'Target IP'],
  '转发目标端口': ['轉發目標連接埠', 'Target port'],
  '出口网卡': ['出口網路卡', 'Out interface'],
  '恢复默认': ['恢復預設', 'Restore defaults'],
  '附加系统指令 (内核转发)': ['附加系統指令 (核心轉發)', 'Extra system commands (IP forwarding)'],
  '请填写端口': ['請填寫連接埠', 'Port is required'],
  '端口格式不正确 (如 80 / 8000:8010 / 80,443)': ['連接埠格式不正確 (如 80 / 8000:8010 / 80,443)', 'Invalid port (e.g. 80 / 8000:8010 / 80,443)'],
  '请填写要封禁的 IP 地址': ['請填寫要封鎖的 IP 位址', 'IP to block is required'],
  'IP 地址格式不正确 (如 203.0.113.10, 不支持主机名)': ['IP 位址格式不正確 (如 203.0.113.10, 不支援主機名稱)', 'Invalid IP address (e.g. 203.0.113.10; hostnames are not supported)'],
  '请填写要封禁的网段': ['請填寫要封鎖的網段', 'Subnet to block is required'],
  '网段格式不正确 (如 203.0.113.0/24)': ['網段格式不正確 (如 203.0.113.0/24)', 'Invalid subnet (e.g. 203.0.113.0/24)'],
  '请填写转发目标 IP': ['請填寫轉發目標 IP', 'Target IP is required'],
  '转发目标 IP 格式不正确': ['轉發目標 IP 格式不正確', 'Invalid target IP'],
  '请填写转发目标端口': ['請填寫轉發目標連接埠', 'Target port is required'],
  '转发目标端口必须是 1-65535 的单个端口': ['轉發目標連接埠必須是 1-65535 的單一連接埠', 'Target port must be a single port in 1-65535'],
  '若 INPUT 默认策略为 DROP, 还需放行 ESTABLISHED,RELATED 连接, 否则现有连接会中断': ['若 INPUT 預設策略為 DROP, 還需放行 ESTABLISHED,RELATED 連線, 否則現有連線會中斷', 'If the INPUT policy is DROP, also allow ESTABLISHED,RELATED state or existing connections break'],
  '放行 22 端口时请先确认规则已生效再断开当前连接 (可用 screen / nohup 执行)': ['放行 22 連接埠時請先確認規則已生效再斷開目前連線 (可用 screen / nohup 執行)', 'Before leaving an SSH session on port 22, make sure the rule works (run it under screen / nohup)'],
  'DROP 只拦截新建连接, 已建立的连接需要手动断开 (ss -K)': ['DROP 只攔截新建連線, 已建立的連線需要手動斷開 (ss -K)', 'DROP only blocks new connections — kill existing ones manually (ss -K)'],
  '本工具只封禁入方向 (INPUT), 需要限制出方向请用「生成」页签': ['本工具只封鎖入方向 (INPUT), 需要限制出方向請用「生成」頁籤', 'Only inbound (INPUT) is blocked here — use the Generate tab to restrict outbound'],
  '未填出口网卡时 MASQUERADE 由路由决定出口, 多网卡机器建议填写': ['未填出口網路卡時 MASQUERADE 由路由決定出口, 多網卡機器建議填寫', 'Without an out interface MASQUERADE follows the route; set it on multi-NIC hosts'],
};

// 取词: 无命中回退 zh 原文 (与项目其它语言包行为一致)
export const ir = (locale: string, zh: string): string => {
  const e = iptableslangRows[zh];
  if (!e) return zh;
  return locale === 'zh-TW' ? e[0] : locale === 'en' ? e[1] : zh;
};
export const irT = (locale: string, zh: string, v?: Record<string, string | number>): string => {
  let s = ir(locale, zh);
  if (v) for (const [ k, val ] of Object.entries(v)) s = s.split('{' + k + '}').join(String(val));
  return s;
};
