// CronRules 语言包: 名称 (zh-CN = define.tsx AppName 默认; 缺省回退 zh-CN)
export default {
  default: 'zh-CN',
  'zh-TW': { appName: "Cron 規則生成" },
  en: { appName: "Cron Expression Generator" },
} as const;

// 界面文案词条 (zh 短语即 key; 缺 zh-CN 时回退原文)
const uilangRows: Record<string, [string, string]> = {
  '复制': ['複製', 'Copy'],
  '复制到粘贴板成功！！！': ['複製到剪貼簿成功！！！', 'Copied to clipboard!!!'],
  '数组': ['陣列', 'Array'],
  '读': ['讀', 'Read'],
  '写': ['寫', 'Write'],
  '执行': ['執行', 'Execute'],
  '解读': ['解讀', 'Parse'],
  '数值': ['數值', 'Numeric'],
  '数字': ['數字', 'Numeric'],
  '含义': ['含義', 'Meaning'],
  '位数': ['位數', 'Digits'],
  'px': ['px', 'px'],
  '生成': ['產生', 'Generate'],
  '次': ['次', 'times'],
  '位': ['位', 'bits'],
  'N:': ['N:', 'N:'],
  'r:': ['r:', 'r:'],
  'p:': ['p:', 'p:'],
  '计算': ['計算', 'Compute'],
  '全部': ['全部', 'All'],
  '重置': ['重置', 'Reset'],
  '标准': ['標準', 'Standard'],
  '时间': ['時間', 'Time'],
  '位置': ['位置', 'Location'],
  '文字': ['文字', 'Text'],
  '个': ['個', ''],
  '解析': ['解析', 'Parse'],
  '表达式格式': ['表達式格式', 'Expression format'],
  '快速预设': ['快速預設', 'Quick presets'],
  '标准 (秒 分 时 日 月 周 年)': ['標準 (秒 分 時 日 月 週 年)', 'Standard (sec min hr day month week year)'],
  'Linux (分 时 日 月 周, 无秒/年)': ['Linux (分 時 日 月 週, 無秒/年)', 'Linux (min hr day month week, no sec/year)'],
  'Linux cron 无「秒 / 年」字段, 已隐藏对应配置行': ['Linux cron 無「秒 / 年」欄位, 已隱藏對應設定列', 'Linux cron has no second/year fields, so their rows are hidden'],
  '任意 (*)': ['任意 (*)', 'Any (*)'],
  '范围 a-b': ['範圍 a-b', 'Range a-b'],
  '每 N 个': ['每 N 個', 'Every N'],
  '指定值': ['指定值', 'Specific values'],
  '至': ['至', 'to'],
  '每': ['每', 'Every'],
  '执行 (即 */N)': ['執行 (即 */N)', '(i.e. */N)'],
  '选择 {x} 中的若干值': ['選擇 {x} 中的若干值', 'Pick values from {x}'],
  '不限制': ['不限制', 'Unrestricted'],
  'Linux (5 段)': ['Linux (5 段)', 'Linux (5 fields)'],
  '标准 (7 段)': ['標準 (7 段)', 'Standard (7 fields)'],
  '标准格式 = 秒 分 时 日 月 周 年; Linux 格式 = 分 时 日 月 周 (crontab 不支持秒/年)': ['標準格式 = 秒 分 時 日 月 週 年; Linux 格式 = 分 時 日 月 週 (crontab 不支援秒/年)', 'Standard = sec min hr day month week year; Linux = min hr day month week (crontab has no seconds/years)'],
  'Cron 规则说明': ['Cron 規則說明', 'About Cron rules'],
  '该预设需要「秒」字段, 请先切换到标准格式': ['該預設需要「秒」欄位, 請先切換到標準格式', 'This preset needs the second field — switch to the standard format first'],
  '每 1 秒': ['每 1 秒', 'Every 1s'],
  '每 30 秒': ['每 30 秒', 'Every 30s'],
  '每 1 分钟': ['每 1 分鐘', 'Every 1 min'],
  '每 5 分钟': ['每 5 分鐘', 'Every 5 min'],
  '每小时整点': ['每小時整點', 'Top of every hour'],
  '每天 00:00': ['每天 00:00', 'Every day at 00:00'],
  '每周一 09:00': ['每週一 09:00', 'Every Mon at 09:00'],
  '每月 1 日 00:00': ['每月 1 日 00:00', '1st of every month at 00:00'],
  '每年 1 月 1 日 00:00': ['每年 1 月 1 日 00:00', 'Jan 1 every year at 00:00'],
  '每秒执行': ['每秒執行', 'Runs every second'],
  '0 与 7 均表示周日': ['0 與 7 均表示週日', '0 and 7 both mean Sunday'],
  '仅标准格式 (可选)': ['僅標準格式 (可選)', 'Standard format only (optional)'],
  '秒': ['秒', 's'],
  '分': ['分', 'm'],
  '时': ['時', 'h'],
  '日': ['日', 'd'],
  '月': ['月', 'mo'],
  '周': ['週', 'w'],
  '年': ['年', 'y'],
  '周日 (0)': ['週日 (0)', 'Sun (0)'],
  '周日 (7)': ['週日 (7)', 'Sun (7)'],
  '周一 (1)': ['週一 (1)', 'Mon (1)'],
  '解析规则': ['解析規則', 'Parse rule'],
  '试试:': ['試試:', 'Try:'],
  '解析失败': ['解析失敗', 'Parse failed'],
  '复制全部': ['複製全部', 'Copy all'],
  '共 {x} 个取值': ['共 {x} 個取值', '{x} values in total'],
  '提示: 「日」与「周」同时被限制时按': ['提示: 「日」與「週」同時被限制時按', 'Note: when both day & week are restricted it matches with'],
  '或': ['或', 'OR'],
  '匹配 (任一满足即触发, 同 Vixie cron); 单独限制其一则只按该条件': ['匹配 (任一滿足即觸發, 同 Vixie cron); 單獨限制其一則只按該條件', ' (either satisfies → fires, like Vixie cron); with only one restricted, that condition alone is used'],
  '最近 10 次触发时间': ['最近 10 次觸發時間', 'Next 10 fire times'],
  '该规则在 2024-2099 年内无法触发 (请检查规则是否可达, 如 2 月 30 日)': ['該規則在 2024-2099 年內無法觸發 (請檢查規則是否可達, 如 2 月 30 日)', 'This rule cannot fire within 2024-2099 (check whether it is reachable, e.g. Feb 30)'],
  '仅找到 {x} 次 (在 2099 年范围内)': ['僅找到 {x} 次 (在 2099 年範圍內)', 'Only found {x} times (within year 2099)'],
  '即将触发': ['即將觸發', 'Firing now'],
  '约 {n} 天后': ['約 {n} 天後', 'in ~{n} days'],
  '约 {n} 小时后': ['約 {n} 小時後', 'in ~{n} hours'],
  '约 {n} 分钟后': ['約 {n} 分鐘後', 'in ~{n} minutes'],
  '1 分钟内': ['1 分鐘內', 'within 1 minute'],
  '输入 Cron 表达式, 如 0 9 * * 1 (格式需与上方一致)': ['輸入 Cron 表達式, 如 0 9 * * 1 (格式需與上方一致)', 'Enter a cron expression, e.g. 0 9 * * 1 (must match the format above)'],
  '每月 1 日 03:15': ['每月 1 日 03:15', '1st of every month at 03:15'],
  '每年元旦 (2026)': ['每年元旦 (2026)', 'New Year\u2019s Day (2026)'],
};

// 取词: 无命中回退 zh 原文 (与共享 ui-lang 行为一致)
export const u = (locale: string, zh: string): string => {
  const hit = uilangRows[zh];
  if (!hit) return zh;
  return locale === 'zh-TW' ? hit[0] : locale === 'en' ? hit[1] : zh;
};
export const uT = (locale: string, zhTpl: string, vars?: Record<string, string | number>): string => {
  let out = u(locale, zhTpl);
  if (vars) out = out.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));
  return out;
};

