// 树形样例内容 (路径名) 属演示数据不翻译
export default {
  default: 'zh-CN',
  'zh-CN': {
    title: '树形和路径转换',
    d1: '在「路径列表 ↔ 树形」之间互转: 每行一条路径(支持 ', d2: ' 与 ', d3: ' 分隔), 树形文本约定每层 2 空格缩进, 也兼容 ', d4: ' 目录树输出; 亦可与嵌套 JSON 互转。',
    tabToTree: '路径 → 树', tabToPaths: '树 → 路径',
    cardPaths: '路径列表 (每行一条)',
    load: '载入示例', clear: '清空',
    copied: '已复制', copyFail: '复制失败, 请手动选择复制',
    cardTree: '树形结构', copyTextBtn: '复制文本',
    emptyTree: '暂无内容 — 输入路径后自动生成树形。',
    cardTreeIn: '树形内容',
    segText: '缩进树文本', segJson: '嵌套 JSON',
    loadInfo: '已载入示例树',
    phIndent: '缩进树文本 (每层 2 空格), 例如:\n\nsrc\n  App\n    CodeShot\n      index.tsx\n  lib\n    string.ts',
    phJson: '嵌套 JSON, 例如:\n{"src":{"App":{"CodeShot":{"index.tsx":null}},"lib":{"string.ts":null}}}',
    phPaths: '每行一条路径, 例如:\n\nsrc/components/App.tsx\nsrc/index.tsx\ndocs/guide.md',
    parseFail: '解析失败',
    copyBtn: '复制', dlBtn: '下载 .txt',
    tagNodes: '共 {n} 个节点 (含目录)',
    emptyOut: '暂无结果 — 输入树形内容后自动生成完整路径。树也可先由左侧「路径 → 树」生成。',
    downloadedTpl: '已下载 {file}',
    statA: '{n} 行, 重复分支自动合并',
    statB: '{n} 行, 重复 {dup} 行, 重复分支自动合并',
    errRoot: 'JSON 根应为对象',
  },
  'zh-TW': {
    appName: '樹形與路徑轉換',
    title: '樹形與路徑轉換',
    d1: '在「路徑清單 ↔ 樹形」之間互轉: 每行一條路徑(支援 ', d2: ' 與 ', d3: ' 分隔), 樹形文字約定每層 2 空格縮排, 也相容 ', d4: ' 目錄樹輸出; 亦可與巢狀 JSON 互轉。',
    tabToTree: '路徑 → 樹', tabToPaths: '樹 → 路徑',
    cardPaths: '路徑清單 (每行一條)',
    load: '載入範例', clear: '清空',
    copied: '已複製', copyFail: '複製失敗, 請手動選擇複製',
    cardTree: '樹形結構', copyTextBtn: '複製文字',
    emptyTree: '尚無內容 — 輸入路徑後自動產生樹形。',
    cardTreeIn: '樹形內容',
    segText: '縮排樹文字', segJson: '巢狀 JSON',
    loadInfo: '已載入範例樹',
    phIndent: '縮排樹文字 (每層 2 空格), 例如:\n\nsrc\n  App\n    CodeShot\n      index.tsx\n  lib\n    string.ts',
    phJson: '巢狀 JSON, 例如:\n{"src":{"App":{"CodeShot":{"index.tsx":null}},"lib":{"string.ts":null}}}',
    phPaths: '每行一條路徑, 例如:\n\nsrc/components/App.tsx\nsrc/index.tsx\ndocs/guide.md',
    parseFail: '解析失敗',
    copyBtn: '複製', dlBtn: '下載 .txt',
    tagNodes: '共 {n} 個節點 (含目錄)',
    emptyOut: '尚無結果 — 輸入樹形內容後自動產生完整路徑。樹也可先由左側「路徑 → 樹」產生。',
    downloadedTpl: '已下載 {file}',
    statA: '{n} 行, 重複分支自動合併',
    statB: '{n} 行, 重複 {dup} 行, 重複分支自動合併',
    errRoot: 'JSON 根應為物件',
  },
  en: {
    appName: 'Tree & Path Converter',
    title: 'Tree & Path Convert',
    d1: 'Convert between a path list ↔ a tree. One path per line, separated by ', d2: ' or ', d3: '); indented tree text uses two spaces per level and also accepts ', d4: ' directory-tree output; nested JSON is supported too.',
    tabToTree: 'Paths → Tree', tabToPaths: 'Tree → Paths',
    cardPaths: 'Path List (one per line)',
    load: 'Load sample', clear: 'Clear',
    copied: 'Copied', copyFail: 'Copy failed, please copy manually',
    cardTree: 'Tree', copyTextBtn: 'Copy text',
    emptyTree: 'No content — the tree is generated automatically once you type paths.',
    cardTreeIn: 'Tree Content',
    segText: 'Indented text', segJson: 'Nested JSON',
    loadInfo: 'Sample tree loaded',
    phIndent: 'Indented tree text (2 spaces per level), e.g.:\n\nsrc\n  App\n    CodeShot\n      index.tsx\n  lib\n    string.ts',
    phJson: 'Nested JSON, e.g.:\n{"src":{"App":{"CodeShot":{"index.tsx":null}},"lib":{"string.ts":null}}}',
    phPaths: 'One path per line, e.g.:\n\nsrc/components/App.tsx\nsrc/index.tsx\ndocs/guide.md',
    parseFail: 'Parse failed',
    copyBtn: 'Copy', dlBtn: 'Download .txt',
    tagNodes: '{n} nodes in total (incl. directories)',
    emptyOut: 'No result — the full paths are generated once you enter tree content. The tree can also be produced first on the Paths → Tree tab.',
    downloadedTpl: 'Downloaded {file}',
    statA: '{n} lines; duplicate branches are merged automatically',
    statB: '{n} lines, {dup} duplicated; duplicate branches are merged automatically',
    errRoot: 'JSON root must be an object',
  },
} as const;
