import { useLocale } from '../../hook/locale-context';

const introZh = `
<h2>RSA 加密算法</h2>
<blockquote><p>RSA 是最经典的非对称加密算法 (1977), 基于大整数分解难题。本工具使用 WebCrypto 标准实现 <b>RSA-OAEP</b> 填充 (SHA-256), 公钥加密、私钥解密。</p>
</blockquote>
<h2>密钥说明</h2>
<ul>
<li><p><b>公钥 (SPKI PEM)</b>：<code>-----BEGIN PUBLIC KEY-----</code>, 可公开分发, 用于<strong>加密</strong></p></li>
<li><p><b>私钥 (PKCS#8 PEM)</b>：<code>-----BEGIN PRIVATE KEY-----</code>, 必须保密, 用于<strong>解密</strong></p></li>
<li><p>支持 2048 / 3072 / 4096 位密钥长度, 生成后可用「导出文件」保存为 .pem / .key</p></li>
<li><p>也可直接粘贴其他工具生成的 PKCS#8 / SPKI PEM (openssl genpkey 默认输出 PKCS#8)</p></li>
</ul>
<h2>加密说明</h2>
<ul>
<li><p>2048 位密钥 + OAEP(SHA-256) 单块明文上限为 <b>190 字节</b>, 超过会自动分段加密 (每段密文 = 模长 256 字节), 密文按 Base64 输出</p></li>
<li><p>OAEP 填充带随机性: 同一明文每次加密结果不同, 属正常现象</p></li>
<li><p>OpenSSL 互操作示例:</p>
<pre><code>openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out pri.pem
openssl pkey -in pri.pem -pubout -out pub.pem
echo -n hello | openssl pkeyutl -encrypt -pubin -inkey pub.pem -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha256 | base64</code></pre>
</li>
</ul>
<h2>安全提醒</h2>
<blockquote><p>私钥请妥善保管, 切勿泄露; 网页工具仅在前端本地计算, 密钥不会上传。</p>
</blockquote>
`;

const introTw = `
<h2>RSA 加密演算法</h2>
<blockquote><p>RSA 是最經典的非對稱加密演算法 (1977), 基於大整數分解難題。本工具使用 WebCrypto 標準實作 <b>RSA-OAEP</b> 填充 (SHA-256), 公鑰加密、私鑰解密。</p>
</blockquote>
<h2>金鑰說明</h2>
<ul>
<li><p><b>公鑰 (SPKI PEM)</b>：<code>-----BEGIN PUBLIC KEY-----</code>, 可公開散佈, 用於<strong>加密</strong></p></li>
<li><p><b>私鑰 (PKCS#8 PEM)</b>：<code>-----BEGIN PRIVATE KEY-----</code>, 必須保密, 用於<strong>解密</strong></p></li>
<li><p>支援 2048 / 3072 / 4096 位金鑰長度, 產生後可用「匯出檔案」儲存為 .pem / .key</p></li>
<li><p>也可直接貼上其他工具產生的 PKCS#8 / SPKI PEM (openssl genpkey 預設輸出 PKCS#8)</p></li>
</ul>
<h2>加密說明</h2>
<ul>
<li><p>2048 位金鑰 + OAEP(SHA-256) 單一區塊明文上限為 <b>190 位元組</b>, 超過會自動分段加密 (每段密文 = 模長 256 位元組), 密文以 Base64 輸出</p></li>
<li><p>OAEP 填充具隨機性: 同一明文每次加密結果不同, 屬正常現象</p></li>
<li><p>OpenSSL 互通範例:</p>
<pre><code>openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out pri.pem
openssl pkey -in pri.pem -pubout -out pub.pem
echo -n hello | openssl pkeyutl -encrypt -pubin -inkey pub.pem -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha256 | base64</code></pre>
</li>
</ul>
<h2>安全提醒</h2>
<blockquote><p>私鑰請妥善保管, 切勿洩漏; 網頁工具僅在前端本機計算, 金鑰不會上傳。</p>
</blockquote>
`;

const introEn = `
<h2>RSA encryption</h2>
<blockquote><p>RSA (1977) is the best-known asymmetric encryption algorithm, whose security relies on the difficulty of factoring large integers. This tool implements <b>RSA-OAEP</b> padding (SHA-256) via the standard WebCrypto API: the public key encrypts and the private key decrypts.</p>
</blockquote>
<h2>Keys</h2>
<ul>
<li><p><b>Public key (SPKI PEM)</b>: <code>-----BEGIN PUBLIC KEY-----</code> — safe to distribute publicly, used for <strong>encryption</strong></p></li>
<li><p><b>Private key (PKCS#8 PEM)</b>: <code>-----BEGIN PRIVATE KEY-----</code> — keep it secret, used for <strong>decryption</strong></p></li>
<li><p>Key sizes of 2048 / 3072 / 4096 bits are supported; use "Export to file" to save generated keys as .pem / .key</p></li>
<li><p>You can also paste PKCS#8 / SPKI PEM generated by other tools (openssl genpkey emits PKCS#8 by default)</p></li>
</ul>
<h2>Encryption notes</h2>
<ul>
<li><p>With a 2048-bit key and OAEP(SHA-256) the single-block plaintext limit is <b>190 bytes</b>; longer input is automatically encrypted in segments (each ciphertext block = the 256-byte modulus), output as Base64</p></li>
<li><p>OAEP padding is randomized, so the same plaintext encrypts differently each time — this is normal</p></li>
<li><p>OpenSSL interop example:</p>
<pre><code>openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out pri.pem
openssl pkey -in pri.pem -pubout -out pub.pem
echo -n hello | openssl pkeyutl -encrypt -pubin -inkey pub.pem -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha256 | base64</code></pre>
</li>
</ul>
<h2>Security note</h2>
<blockquote><p>Keep the private key safe and never leak it. This web tool computes only locally in your browser; keys are never uploaded.</p>
</blockquote>
`;

const Intro = () => {
  const { locale } = useLocale();
  return <div dangerouslySetInnerHTML={ { __html: locale === 'zh-TW' ? introTw : locale === 'en' ? introEn : introZh } } />;
}
export default Intro;
