// MorseCodec 语言包 (默认 zh-CN; 缺失词条回退默认语言)
// 面板交互文案 (按需扩展); 说明性长文 (tips/intro/算法说明) 暂保留简中, 后续批次再翻
// 常用编码分组/短语 (MORSE_PHRASE_GROUPS 内置词表) 为内容数据保留原文
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= '摩斯码编解码')
    phraseLabel: '常用编码',
    phrasePh: '选择常用编码快速填充 (CQ / SOS / Q简语 / 73 等, 自定义见设置)',
    textPh: '输入需要编码的文本 (字母 / 数字 / 常用标点), 或解码结果的回填区',
    toMorse: '文本 → 摩斯码',
    toText: '摩斯码 → 文本',
    playBtn: '播放摩斯码',
    saveBtn: '保存音频 (WAV)',
    stopBtn: '停止',
    clear: '清除',
    copyOk: '复制到粘贴板成功！！！',
    copyTitle: '双击复制内容到粘贴板',
    morsePh: '摩斯码结果区: 字母间空格, 单词间使用 / 分隔, 例如 ... --- ... (SOS)',
    encodeFail: '编码失败: {msg}',
    decodeFail: '解码失败: {msg}',
    fillOk: '已快速填充: {text} ({desc})',
    fillWarn: '已填入文本「{text}」, 但含无法编码的字符',
    playNeed: '请先输入要播放的摩斯码 (或明文后先编码)',
    playNone: '没有可播放的摩斯符号',
    playFail: '播放失败: {msg}',
    exportNeed: '请先输入要导出的摩斯码 (或明文后先编码)',
    exportNone: '没有可导出的摩斯符号',
    saveTitle: '保存摩斯音频',
    saveFilter: 'WAV 音频',
    savedWav: '已保存 WAV 音频 (时长约 {secs}s, {tone})',
    saveFail: '保存失败: {msg}',
    playing: '● 正在播放',
    playingDots: '正在播放…',
    speedLabel: '播放速度',
    freqLabel: '频率',
    toneLabel: '音效',
    custom: '自定义',
    speed_300: '极慢 (300ms)',
    speed_200: '慢 (200ms)',
    speed_120: '标准 (120ms)',
    speed_80: '快 (80ms)',
    tone_telegraph: '电报音 (默认)',
    tone_buzzer: '蜂鸣音',
    tone_soft: '柔和音',
    tone_digital: '电子音',
    divider: '摩斯码编解码说明',
  },
  'zh-TW': {
    appName: '摩斯密碼編解碼',
    phraseLabel: '常用編碼',
    phrasePh: '選擇常用編碼快速填入 (CQ / SOS / Q簡語 / 73 等，自訂見設定)',
    textPh: '輸入需要編碼的文字 (字母 / 數字 / 常用標點)，或解碼結果的回填區',
    toMorse: '文字 → 摩斯碼',
    toText: '摩斯碼 → 文字',
    playBtn: '播放摩斯碼',
    saveBtn: '儲存音訊 (WAV)',
    stopBtn: '停止',
    clear: '清除',
    copyOk: '複製到剪貼簿成功！！！',
    copyTitle: '雙擊複製內容到剪貼簿',
    morsePh: '摩斯碼結果區：字母間以空格分隔，單字間使用 / 分隔，例如 ... --- ... (SOS)',
    encodeFail: '編碼失敗：{msg}',
    decodeFail: '解碼失敗：{msg}',
    fillOk: '已快速填入：{text} ({desc})',
    fillWarn: '已填入文字「{text}」，但含無法編碼的字元',
    playNeed: '請先輸入要播放的摩斯碼 (或明文後先編碼)',
    playNone: '沒有可播放的摩斯符號',
    playFail: '播放失敗：{msg}',
    exportNeed: '請先輸入要匯出的摩斯碼 (或明文後先編碼)',
    exportNone: '沒有可匯出的摩斯符號',
    saveTitle: '儲存摩斯音訊',
    saveFilter: 'WAV 音訊',
    savedWav: '已儲存 WAV 音訊 (時長約 {secs} 秒, {tone})',
    saveFail: '儲存失敗：{msg}',
    playing: '● 正在播放',
    playingDots: '正在播放…',
    speedLabel: '播放速度',
    freqLabel: '頻率',
    toneLabel: '音效',
    custom: '自訂',
    speed_300: '極慢 (300ms)',
    speed_200: '慢 (200ms)',
    speed_120: '標準 (120ms)',
    speed_80: '快 (80ms)',
    tone_telegraph: '電報音 (預設)',
    tone_buzzer: '蜂鳴音',
    tone_soft: '柔和音',
    tone_digital: '電子音',
    divider: '摩斯碼編解碼說明',
  },
  en: {
    appName: 'Morse Code',
    phraseLabel: 'Common codes',
    phrasePh: 'Pick a common code to fill in (CQ / SOS / Q-codes / 73…, customize in Settings)',
    textPh: 'Enter text to encode (letters / digits / common punctuation), or the decode result area',
    toMorse: 'Text → Morse',
    toText: 'Morse → Text',
    playBtn: 'Play Morse',
    saveBtn: 'Save audio (WAV)',
    stopBtn: 'Stop',
    clear: 'Clear',
    copyOk: 'Copied to clipboard!',
    copyTitle: 'Double-click to copy',
    morsePh: 'Morse output area: letters separated by spaces, words by “/”, e.g. ... --- ... (SOS)',
    encodeFail: 'Encode failed: {msg}',
    decodeFail: 'Decode failed: {msg}',
    fillOk: 'Filled: {text} ({desc})',
    fillWarn: 'Filled text “{text}”, but it contains characters that cannot be encoded',
    playNeed: 'Enter a Morse code to play first (or encode your text)',
    playNone: 'No playable Morse symbols',
    playFail: 'Playback failed: {msg}',
    exportNeed: 'Enter a Morse code to export first (or encode your text)',
    exportNone: 'No Morse symbols to export',
    saveTitle: 'Save Morse audio',
    saveFilter: 'WAV audio',
    savedWav: 'WAV saved (about {secs}s, {tone})',
    saveFail: 'Save failed: {msg}',
    playing: '● Playing',
    playingDots: 'Playing…',
    speedLabel: 'Speed',
    freqLabel: 'Frequency',
    toneLabel: 'Tone',
    custom: 'Custom',
    speed_300: 'Very slow (300ms)',
    speed_200: 'Slow (200ms)',
    speed_120: 'Standard (120ms)',
    speed_80: 'Fast (80ms)',
    tone_telegraph: 'Telegraph (default)',
    tone_buzzer: 'Buzzer',
    tone_soft: 'Soft',
    tone_digital: 'Digital',
    divider: 'About Morse Code',
  },
} as const;
