// 说明性长文 (data.ts 内单位注释文档) 暂保留简中, 后续批次再翻
export default {
  default: 'zh-CN',
  'zh-CN': {
    clear: '清除',
    copyOk: '复制到粘贴板成功！！！',
    ut_ms: '公制',
    ut_iu: '英制',
    ut_cn: '市制',
    u_km: '千米', u_m: '米', u_dm: '分米', u_cm: '厘米', u_mm: '毫米', u_μm: '微米', u_nm: '纳米', u_pm: '皮米', u_nmile: '海里',
    u_inch: '英寸', u_foot: '英尺', u_yard: '码', u_mile: '英里', u_fathom: '英寻', u_chain: '链', u_furlong: '化朗',
    u_li: '里', u_ying: '引', u_zhang: '丈', u_chi: '尺', u_cun: '寸', u_fen: '分', u_l: '厘', u_hao: '毫', u_si: '丝',
    r_km: '千米', r_m: '米', r_dm: '分米', r_cm: '厘米', r_mm: '毫米', r_μm: '微米', r_nm: '纳米', r_pm: '皮米', r_nmile: '海里',
    r_inch: '英寸 (inch)', r_foot: '英尺 (foot)', r_yard: '码 (yard)', r_mile: '英里 (mile)', r_fathom: '英寻 (fathom)', r_chain: '链 (chain)', r_furlong: '化朗 (furlong)',
    r_li: '里', r_ying: '引', r_zhang: '丈', r_chi: '尺', r_cun: '寸', r_fen: '分', r_l: '厘', r_hao: '毫', r_si: '丝',
    p_nmile: '等于4千万米除以360然后再除以60，其结果就是大约1852米，也就是说，1海里大约是1.852公里',
    p_chain: '也称 测链 英文：chain，是英美制中一种长度单位 1链 (chain) = 20.1168米 (m)',
    p_furlong: '一单位长度等于660呎(英尺)或220码或10链，约等于公制的201.168米。8化朗等于1哩，5化朗等于1005.84米，约等于1千米',
  },
  'zh-TW': {
    clear: '清除',
    copyOk: '複製到剪貼簿成功！！！',
    ut_ms: '公制',
    ut_iu: '英制',
    ut_cn: '市制',
    u_km: '公里', u_m: '公尺', u_dm: '公寸', u_cm: '公分', u_mm: '公釐', u_μm: '微米', u_nm: '奈米', u_pm: '皮米', u_nmile: '海浬',
    u_inch: '英吋', u_foot: '英呎', u_yard: '碼', u_mile: '英哩', u_fathom: '英尋', u_chain: '鏈', u_furlong: '化朗',
    u_li: '里', u_ying: '引', u_zhang: '丈', u_chi: '尺', u_cun: '寸', u_fen: '分', u_l: '厘', u_hao: '毫', u_si: '絲',
    r_km: '公里', r_m: '公尺', r_dm: '公寸', r_cm: '公分', r_mm: '公釐', r_μm: '微米', r_nm: '奈米', r_pm: '皮米', r_nmile: '海浬',
    r_inch: '英吋 (inch)', r_foot: '英呎 (foot)', r_yard: '碼 (yard)', r_mile: '英哩 (mile)', r_fathom: '英尋 (fathom)', r_chain: '鏈 (chain)', r_furlong: '化朗 (furlong)',
    r_li: '里', r_ying: '引', r_zhang: '丈', r_chi: '尺', r_cun: '寸', r_fen: '分', r_l: '厘', r_hao: '毫', r_si: '絲',
    p_nmile: '等於 4000 萬米除以 360 再除以 60，其結果大約是 1852 米，也就是說，1 海浬約為 1.852 公里',
    p_chain: '又稱測鏈，英文：chain，是英美制中一種長度單位，1 鏈 (chain) = 20.1168 公尺 (m)',
    p_furlong: '一單位長度等於 660 呎(英尺)或 220 碼或 10 鏈，約等於公制的 201.168 公尺。8 化朗等於 1 哩，5 化朗等於 1005.84 公尺，約等於 1 公里',
  },
  en: {
    clear: 'Clear',
    copyOk: 'Copied to clipboard!!!',
    ut_ms: 'Metric',
    ut_iu: 'Imperial',
    ut_cn: 'Chinese',
    u_km: 'Kilometre', u_m: 'Metre', u_dm: 'Decimetre', u_cm: 'Centimetre', u_mm: 'Millimetre', u_μm: 'Micrometre', u_nm: 'Nanometre', u_pm: 'Picometre', u_nmile: 'Nautical mile',
    u_inch: 'Inch', u_foot: 'Foot', u_yard: 'Yard', u_mile: 'Mile', u_fathom: 'Fathom', u_chain: 'Chain', u_furlong: 'Furlong',
    u_li: 'Li', u_ying: 'Yin', u_zhang: 'Zhang', u_chi: 'Chi', u_cun: 'Cun', u_fen: 'Fen', u_l: 'Li', u_hao: 'Hao', u_si: 'Si',
    r_km: 'Kilometre', r_m: 'Metre', r_dm: 'Decimetre', r_cm: 'Centimetre', r_mm: 'Millimetre', r_μm: 'Micrometre', r_nm: 'Nanometre', r_pm: 'Picometre', r_nmile: 'Nautical mile',
    r_inch: 'Inch (in)', r_foot: 'Foot (ft)', r_yard: 'Yard (yd)', r_mile: 'Mile (mi)', r_fathom: 'Fathom', r_chain: 'Chain', r_furlong: 'Furlong',
    r_li: 'Li', r_ying: 'Yin', r_zhang: 'Zhang', r_chi: 'Chi', r_cun: 'Cun', r_fen: 'Fen', r_l: 'Li', r_hao: 'Hao', r_si: 'Si',
    p_nmile: 'One nautical mile = 4,000,000 m / 360 / 60 ≈ 1,852 m, i.e. about 1.852 km',
    p_chain: 'Also called surveyor’s chain: 1 chain = 20.1168 m',
    p_furlong: '1 furlong = 660 ft = 220 yd = 10 chains ≈ 201.168 m; 8 furlongs = 1 mile, 5 furlongs ≈ 1005.84 m ≈ 1 km',
  },
} as const;
