// IPConvert 语言包: UI 文案 (zh-CN 默认, 缺省回退 zh-CN)
export default {
  default: 'zh-CN',
  'zh-CN': {
    appName: '',
    ipPh: 'IPv4 地址, 如 192.168.1.1',
    intPh: '十进制整数, 支持 0x 前缀',
    ipv6Title: '对应的 IPv6 写法',
    ipv6Hint: '同一条 IPv4 在不同过渡方案下的写法, 点右侧图标可复制',
    ipv6Mapped: 'IPv4 映射地址',
    ipv6MappedHex: 'IPv4 映射地址 (十六进制)',
    ipv6Compat: 'IPv4 兼容地址 (已废弃)',
    ipv6SixToFour: '6to4',
    ipv6Nat64: 'NAT64 / DNS64',
    ipv6Full: '完整展开',
  },
  'zh-TW': {
    appName: 'IP 轉換',
    ipPh: 'IPv4 位址, 如 192.168.1.1',
    intPh: '十進位整數, 支援 0x 前綴',
    ipv6Title: '對應的 IPv6 寫法',
    ipv6Hint: '同一條 IPv4 在不同過渡方案下的寫法, 點右側圖示可複製',
    ipv6Mapped: 'IPv4 對映位址',
    ipv6MappedHex: 'IPv4 對映位址 (十六進位)',
    ipv6Compat: 'IPv4 相容位址 (已廢棄)',
    ipv6SixToFour: '6to4',
    ipv6Nat64: 'NAT64 / DNS64',
    ipv6Full: '完整展開',
  },
  'en': {
    appName: 'IP Converter',
    ipPh: 'IPv4 address, e.g. 192.168.1.1',
    intPh: 'Decimal integer (0x prefix supported)',
    ipv6Title: 'IPv6 equivalents',
    ipv6Hint: 'The same IPv4 address written for different transition mechanisms; click the icon to copy',
    ipv6Mapped: 'IPv4-mapped',
    ipv6MappedHex: 'IPv4-mapped (hex)',
    ipv6Compat: 'IPv4-compatible (deprecated)',
    ipv6SixToFour: '6to4',
    ipv6Nat64: 'NAT64 / DNS64',
    ipv6Full: 'Full expansion',
  },
} as const;
