export default {
  default: 'zh-CN',
  'zh-CN': {
    copyOk: '复制到粘贴板成功！！！',
    errParse: '解析输入内容出错',
    parsedTpl: '已按 {fmt} 解析 {name}',
    extWarn: '未能识别文件扩展名, 按当前所选格式解析',
    readFail: '读取文件失败',
    openBtn: '打开配置文件',
    clear: '清除',
    tipDbl: '双击复制内容到粘贴板',
    tipResult: '单击复制内容到粘贴板,右击保存配置文件',
    ph: '输入需要转换的配置内容 或 拖拽配置文件到框内打开 (自动识别 xml/ini/json/yaml/toml/properties)',
    divResult: ' 转换结果 ',
    saveBtnTpl: '保存为 .{ext} 文件',
    svTitleTpl: '将当前结果保存为 config.{ext}',
    svTitleDisabled: '先输入内容生成转换结果',
    savedTpl: '已保存 config.{ext} 文件',
    saveDialog: '保存配置文件',
    filterTpl: '{label} 配置文件',
  },
  'zh-TW': {
    copyOk: '複製到剪貼簿成功！！！',
    errParse: '解析輸入內容出錯',
    parsedTpl: '已按 {fmt} 解析 {name}',
    extWarn: '未能辨識檔案副檔名, 依目前所選格式解析',
    readFail: '讀取檔案失敗',
    openBtn: '開啟設定檔',
    clear: '清除',
    tipDbl: '雙擊複製內容到剪貼簿',
    tipResult: '單擊複製內容到剪貼簿, 右鍵儲存設定檔',
    ph: '輸入需要轉換的設定內容, 或將設定檔拖曳到框內開啟 (自動辨識 xml/ini/json/yaml/toml/properties)',
    divResult: ' 轉換結果 ',
    saveBtnTpl: '儲存為 .{ext} 檔案',
    svTitleTpl: '將目前結果儲存為 config.{ext}',
    svTitleDisabled: '先輸入內容產生轉換結果',
    savedTpl: '已儲存 config.{ext} 檔案',
    saveDialog: '儲存設定檔',
    filterTpl: '{label} 設定檔',
  },
  en: {
    copyOk: 'Copied to clipboard!!!',
    errParse: 'Failed to parse the input content',
    parsedTpl: 'Parsed as {fmt}: {name}',
    extWarn: 'Could not detect the file extension; parsed with the currently selected format',
    readFail: 'Failed to read the file',
    openBtn: 'Open config file',
    clear: 'Clear',
    tipDbl: 'Double-click to copy the content to clipboard',
    tipResult: 'Click to copy the content to clipboard; right-click to save the config file',
    ph: 'Enter config content to convert, or drop a config file here (auto-detects xml/ini/json/yaml/toml/properties)',
    divResult: ' Result ',
    saveBtnTpl: 'Save as .{ext} file',
    svTitleTpl: 'Save the current result as config.{ext}',
    svTitleDisabled: 'Enter content to generate a conversion result first',
    savedTpl: 'Saved config.{ext} file',
    saveDialog: 'Save config file',
    filterTpl: '{label} config file',
  },
} as const;
