// GPSConvert 语言包 (默认 zh-CN; 缺失词条回退默认语言)
// 面板交互文案 (按需扩展); 说明性长文 (tips/intro/算法说明) 暂保留简中, 后续批次再翻
export default {
  default: 'zh-CN',
  'zh-CN': {
    // appName 缺省回退 define.tsx AppName (= 'GPS坐标转换')
    clear: '清除',
    copyOk: '复制到粘贴板成功！！！',
    tencentLabel: '腾讯地图 (lat,lng)',
    unit_WGS84: 'WGS84坐标系',
    unit_GCJ02: 'GCJ02坐标系',
    unit_BD09: 'BD09坐标系',
    unit_TXMAP: '腾讯地图',
    ph_WGS84: '地球坐标系,国际通用坐标系',
    ph_GCJ02: '火星坐标系,WGS84 坐标系加密后的坐标系；Google国内地图、高德、QQ地图 使用',
    ph_BD09: '百度坐标系，GCJ02 坐标系加密后的坐标系',
    ph_TXMAP: '火星坐标系,WGS84展示 纬度在前，经度在后',
    pick_baidu: '百度地图',
    pick_amap: '高德地图',
    pick_qq: '腾讯地图',
  },
  'zh-TW': {
    appName: 'GPS 座標轉換',
    clear: '清除',
    copyOk: '複製到剪貼簿成功！！！',
    tencentLabel: '騰訊地圖 (lat,lng)',
    unit_WGS84: 'WGS84 座標系',
    unit_GCJ02: 'GCJ02 座標系',
    unit_BD09: 'BD09 座標系',
    unit_TXMAP: '騰訊地圖',
    ph_WGS84: '地球座標系，國際通用座標系',
    ph_GCJ02: '火星座標系，WGS84 座標系加密後的座標系；Google 中國地圖、高德、QQ 地圖使用',
    ph_BD09: '百度座標系，GCJ02 座標系加密後的座標系',
    ph_TXMAP: '火星座標系，WGS84 展示時緯度在前、經度在後',
    pick_baidu: '百度地圖',
    pick_amap: '高德地圖',
    pick_qq: '騰訊地圖',
  },
  en: {
    appName: 'GPS Coordinate Converter',
    clear: 'Clear',
    copyOk: 'Copied to clipboard!',
    tencentLabel: 'Tencent Map (lat,lng)',
    unit_WGS84: 'WGS84',
    unit_GCJ02: 'GCJ02',
    unit_BD09: 'BD09',
    unit_TXMAP: 'Tencent Map',
    ph_WGS84: 'Earth coordinate system (GPS), the international standard',
    ph_GCJ02: 'Mars (GCJ-02) — WGS-84 with China’s offset; used by Google China, AMap and QQ Maps',
    ph_BD09: 'Baidu coordinate system — GCJ-02 offset again',
    ph_TXMAP: 'Mars coordinate system; Tencent shows latitude first, then longitude',
    pick_baidu: 'Baidu Maps',
    pick_amap: 'AMap',
    pick_qq: 'Tencent Maps',
  },
} as const;
