export default {
  default: 'zh-CN',
  'zh-CN': {
    copyOk: '复制到粘贴板成功！！！',
    clear: '清除',
    ph: '输入 10位时间戳 / 13位时间戳 / UTC 格式字符串 / YYYY-MM-DD HH:ii:ss 格式字符串',
    wkSec: '{wk} 周 + {sec} 秒',
    lb_ts10: '时间戳(10位)', lb_ts13: '时间戳(13位)',
    lb_gps: 'GPS 时间', lb_gps_ws: 'GPS 时间 (周,秒)', lb_gps_ts: 'GPS 时间 (总秒)',
    lb_bdt: '北斗时间', lb_bdt_ws: '北斗时间 (周,秒)', lb_bdt_ts: '北斗时间 (总秒)',
    lb_gst: '伽利略时间', lb_gst_ws: '伽利略时间 (周,秒)', lb_gst_ts: '伽利略时间 (总秒)',
    lb_glonass: '格洛纳斯时间 (UTC+3)',
    lb_jd: '儒略日 (JD)', lb_mjd: '简化儒略日 (MJD)',
    tl_nowTs: '当前时间戳', tl_now: '当前时间', tl_lastW: '上周', tl_nextW: '下周',
    tl_lastM: '上月', tl_nextM: '下月', tl_mBegin: '本月初', tl_mEnd: '本月末',
    tl_lmBegin: '上月初', tl_lmEnd: '上月末', tl_nmBegin: '下月初', tl_nmEnd: '下月末',
  },
  'zh-TW': {
    copyOk: '複製到剪貼簿成功！！！',
    clear: '清除',
    ph: '輸入 10 位時間戳 / 13 位時間戳 / UTC 格式字串 / YYYY-MM-DD HH:ii:ss 格式字串',
    wkSec: '{wk} 週 + {sec} 秒',
    lb_ts10: '時間戳(10 位)', lb_ts13: '時間戳(13 位)',
    lb_gps: 'GPS 時間', lb_gps_ws: 'GPS 時間 (週,秒)', lb_gps_ts: 'GPS 時間 (總秒)',
    lb_bdt: '北斗時間', lb_bdt_ws: '北斗時間 (週,秒)', lb_bdt_ts: '北斗時間 (總秒)',
    lb_gst: '伽利略時間', lb_gst_ws: '伽利略時間 (週,秒)', lb_gst_ts: '伽利略時間 (總秒)',
    lb_glonass: '格洛納斯時間 (UTC+3)',
    lb_jd: '儒略日 (JD)', lb_mjd: '簡化儒略日 (MJD)',
    tl_nowTs: '目前時間戳', tl_now: '目前時間', tl_lastW: '上週', tl_nextW: '下週',
    tl_lastM: '上月', tl_nextM: '下月', tl_mBegin: '本月初', tl_mEnd: '本月末',
    tl_lmBegin: '上月初', tl_lmEnd: '上月末', tl_nmBegin: '下月初', tl_nmEnd: '下月末',
  },
  en: {
    copyOk: 'Copied to clipboard!!!',
    clear: 'Clear',
    ph: 'Enter a 10-digit timestamp / 13-digit timestamp / UTC string / YYYY-MM-DD HH:ii:ss string',
    wkSec: 'Week {wk} + {sec} sec',
    lb_ts10: 'Timestamp (10-digit)', lb_ts13: 'Timestamp (13-digit)',
    lb_gps: 'GPS Time', lb_gps_ws: 'GPS Time (week, sec)', lb_gps_ts: 'GPS Time (total sec)',
    lb_bdt: 'BeiDou Time', lb_bdt_ws: 'BeiDou Time (week, sec)', lb_bdt_ts: 'BeiDou Time (total sec)',
    lb_gst: 'Galileo Time', lb_gst_ws: 'Galileo Time (week, sec)', lb_gst_ts: 'Galileo Time (total sec)',
    lb_glonass: 'GLONASS Time (UTC+3)',
    lb_jd: 'Julian Day (JD)', lb_mjd: 'Modified Julian Day (MJD)',
    tl_nowTs: 'Current timestamp', tl_now: 'Now', tl_lastW: 'Last week', tl_nextW: 'Next week',
    tl_lastM: 'Last month', tl_nextM: 'Next month', tl_mBegin: 'This month start', tl_mEnd: 'This month end',
    tl_lmBegin: 'Last month start', tl_lmEnd: 'Last month end', tl_nmBegin: 'Next month start', tl_nmEnd: 'Next month end',
  },
} as const;
