// 提词器内置口令彩蛋: 稿件内容正好是口令时, 点「开始」不滚动, 而是铺一层「应用名雨」
// 实现: 口令与载荷都以 base64 存放, 命中后 atob 解码 → eval 执行 (见 startEgg)
// 约束: 载荷保持纯 ASCII (否则 atob 解出的 UTF-8 会乱码); 应用名列表由组件注入, 载荷内不含任何业务文案

/** 口令 (base64) */
const EGG_KEY_B64 = 'Ymx1ZWZyb2c=';

/** 载荷 (base64): 解码后是一个函数表达式, 调用后返回「退出」函数 */
const EGG_CODE_B64 =
  'KGZ1bmN0aW9uIChjdHgpIHsKICB2YXIgZG9jID0gY3R4LmRvYywgd2luID0gY3R4LndpbiwgaG9zdCA9IGN0eC5ob3N0LCByYWYgPSBjdHgucmFmLCBjYWYgPSBjdHguY2FmOwogIHZhciBuYW1lcyA9IFtdLCByYXcgPSBjdHgubmFtZXMgfHwgW10sIGk7CiAgZm9yIChpID0gMDsgaSA8IHJhdy5sZW5ndGg7IGkrKykgewogICAgdmFyIHMgPSBTdHJpbmcocmF3W2ldID09IG51bGwgPyAnJyA6IHJhd1tpXSkucmVwbGFjZSgvXHMrL2csICcgJykudHJpbSgpOwogICAgaWYgKHMgJiYgbmFtZXMuaW5kZXhPZihzKSA8IDApIG5hbWVzLnB1c2gocyk7CiAgfQogIGlmICghbmFtZXMubGVuZ3RoKSBuYW1lcy5wdXNoKCdNYWdpY1Rvb2xzJyk7CiAgdmFyIGNhbnZhcyA9IGRvYy5jcmVhdGVFbGVtZW50KCdjYW52YXMnKTsKICBjYW52YXMuY2xhc3NOYW1lID0gJ3RwLWVnZy1jYW52YXMnOwogIGNhbnZhcy5zZXRBdHRyaWJ1dGUoJ2FyaWEtaGlkZGVuJywgJ3RydWUnKTsKICBjYW52YXMuc3R5bGUucG9zaXRpb24gPSAnZml4ZWQnOwogIGNhbnZhcy5zdHlsZS5sZWZ0ID0gJzAnOwogIGNhbnZhcy5zdHlsZS50b3AgPSAnMCc7CiAgY2FudmFzLnN0eWxlLndpZHRoID0gJzEwMCUnOwogIGNhbnZhcy5zdHlsZS5oZWlnaHQgPSAnMTAwJSc7CiAgY2FudmFzLnN0eWxlLnpJbmRleCA9ICcyMTQ3NDgzMDAwJzsKICBjYW52YXMuc3R5bGUuY3Vyc29yID0gJ3BvaW50ZXInOwogIGNhbnZhcy5zdHlsZS5iYWNrZ3JvdW5kID0gJ3JnYmEoMiw4LDQsMC45NCknOwogIGhvc3QuYXBwZW5kQ2hpbGQoY2FudmFzKTsKICB2YXIgZyA9IGNhbnZhcy5nZXRDb250ZXh0ID8gY2FudmFzLmdldENvbnRleHQoJzJkJykgOiBudWxsOwogIHZhciBkb25lID0gZmFsc2UsIHJhZklkID0gMCwgY29scyA9IDAsIHJvd3MgPSAwLCBjb2xXID0gMCwgcm93SCA9IDAsIGRyb3BzID0gW107CiAgdmFyIHJuZCA9IGZ1bmN0aW9uIChuKSB7IHJldHVybiBNYXRoLmZsb29yKE1hdGgucmFuZG9tKCkgKiBuKTsgfTsKICB2YXIgZml0ID0gZnVuY3Rpb24gKCkgewogICAgdmFyIGRwciA9IHdpbi5kZXZpY2VQaXhlbFJhdGlvID4gMiA/IDIgOiB3aW4uZGV2aWNlUGl4ZWxSYXRpbyB8fCAxOwogICAgdmFyIHcgPSBNYXRoLm1heCgzMjAsIGhvc3QuY2xpZW50V2lkdGggfHwgd2luLmlubmVyV2lkdGggfHwgMTAyNCk7CiAgICB2YXIgaCA9IE1hdGgubWF4KDI0MCwgaG9zdC5jbGllbnRIZWlnaHQgfHwgd2luLmlubmVySGVpZ2h0IHx8IDc2OCk7CiAgICBjYW52YXMud2lkdGggPSBNYXRoLmZsb29yKHcgKiBkcHIpOwogICAgY2FudmFzLmhlaWdodCA9IE1hdGguZmxvb3IoaCAqIGRwcik7CiAgICBjb2xXID0gTWF0aC5mbG9vcigyMiAqIGRwcik7CiAgICByb3dIID0gTWF0aC5mbG9vcigyMCAqIGRwcik7CiAgICBjb2xzID0gTWF0aC5tYXgoMSwgTWF0aC5mbG9vcihjYW52YXMud2lkdGggLyBjb2xXKSk7CiAgICByb3dzID0gTWF0aC5tYXgoMSwgTWF0aC5mbG9vcihjYW52YXMuaGVpZ2h0IC8gcm93SCkpICsgMTsKICAgIGRyb3BzID0gW107CiAgICBmb3IgKHZhciBjID0gMDsgYyA8IGNvbHM7IGMrKykgZHJvcHMucHVzaCh7IHk6IC1ybmQocm93cyksIHA6IG5hbWVzW3JuZChuYW1lcy5sZW5ndGgpXSB9KTsKICAgIGcuZm9udCA9IE1hdGguZmxvb3IoMTYgKiBkcHIpICsgJ3B4IHVpLW1vbm9zcGFjZSxDb25zb2xhcyxtb25vc3BhY2UnOwogICAgZy50ZXh0QmFzZWxpbmUgPSAndG9wJzsKICB9OwogIHZhciBzdGVwID0gZnVuY3Rpb24gKCkgewogICAgaWYgKGRvbmUpIHJldHVybjsKICAgIGcuZmlsbFN0eWxlID0gJ3JnYmEoMiw4LDQsMC4xNiknOwogICAgZy5maWxsUmVjdCgwLCAwLCBjYW52YXMud2lkdGgsIGNhbnZhcy5oZWlnaHQpOwogICAgZm9yICh2YXIgYyA9IDA7IGMgPCBjb2xzOyBjKyspIHsKICAgICAgdmFyIGQgPSBkcm9wc1tjXSwgeCA9IGMgKiBjb2xXICsgNDsKICAgICAgZm9yICh2YXIgayA9IDA7IGsgPCBkLnAubGVuZ3RoOyBrKyspIHsKICAgICAgICB2YXIgeSA9IChkLnkgKyBrKSAqIHJvd0g7CiAgICAgICAgaWYgKHkgPCAtcm93SCB8fCB5ID4gY2FudmFzLmhlaWdodCkgY29udGludWU7CiAgICAgICAgZy5maWxsU3R5bGUgPSBrID09PSAwID8gJyNlYWZmZjInIDogayA8IDMgPyAnIzdkZmZhOCcgOiAncmdiYSgwLDIyNSwxMjAsMC41KSc7CiAgICAgICAgZy5maWxsVGV4dChkLnAuY2hhckF0KGspLCB4LCB5KTsKICAgICAgfQogICAgICBkLnkgKz0gMTsKICAgICAgaWYgKChkLnkgLSBkLnAubGVuZ3RoKSAqIHJvd0ggPiBjYW52YXMuaGVpZ2h0KSB7IGQueSA9IC1ybmQocm93cyk7IGQucCA9IG5hbWVzW3JuZChuYW1lcy5sZW5ndGgpXTsgfQogICAgfQogICAgcmFmSWQgPSByYWYoc3RlcCk7CiAgfTsKICB2YXIgb25LZXkgPSBmdW5jdGlvbiAoZSkgeyBpZiAoZSAmJiAoZS5rZXkgPT09ICdFc2NhcGUnIHx8IGUua2V5ID09PSAnICcpKSBzdG9wKCk7IH07CiAgZnVuY3Rpb24gc3RvcCgpIHsKICAgIGlmIChkb25lKSByZXR1cm47CiAgICBkb25lID0gdHJ1ZTsKICAgIGlmIChyYWZJZCAmJiBjYWYpIGNhZihyYWZJZCk7CiAgICB3aW4ucmVtb3ZlRXZlbnRMaXN0ZW5lcigna2V5ZG93bicsIG9uS2V5KTsKICAgIHdpbi5yZW1vdmVFdmVudExpc3RlbmVyKCdyZXNpemUnLCBmaXQpOwogICAgY2FudmFzLnJlbW92ZUV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgc3RvcCk7CiAgICBpZiAoY2FudmFzLnBhcmVudE5vZGUpIGNhbnZhcy5wYXJlbnROb2RlLnJlbW92ZUNoaWxkKGNhbnZhcyk7CiAgICBpZiAoY3R4LmRvbmUpIGN0eC5kb25lKCk7CiAgfQogIGlmICghZykgeyBpZiAoY2FudmFzLnBhcmVudE5vZGUpIGNhbnZhcy5wYXJlbnROb2RlLnJlbW92ZUNoaWxkKGNhbnZhcyk7IHJldHVybiBzdG9wOyB9CiAgY2FudmFzLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgc3RvcCk7CiAgd2luLmFkZEV2ZW50TGlzdGVuZXIoJ2tleWRvd24nLCBvbktleSk7CiAgd2luLmFkZEV2ZW50TGlzdGVuZXIoJ3Jlc2l6ZScsIGZpdCk7CiAgZml0KCk7CiAgcmFmSWQgPSByYWYoc3RlcCk7CiAgcmV0dXJuIHN0b3A7Cn0pCg==';

/** 载荷运行环境 (由组件注入; 载荷本身不依赖模块作用域) */
export interface EggEnv {
  /** 浏览器窗口 (取 devicePixelRatio / 尺寸 / 事件) */
  win: Window;
  doc: Document;
  /** 画布挂载到哪个元素上 (全屏时挂全屏元素, 否则 body) */
  host: HTMLElement;
  /** 雨滴字符来源: 应用中心里的全部应用名 */
  names: string[];
  raf: (cb: FrameRequestCallback) => number;
  caf: (id: number) => void;
  /** 退出 (点画布 / Esc / 主动停止) 时回调 */
  done?: () => void;
}

/** 口令原文 (仅供内部判断与测试) */
export const eggKey = (): string => atob(EGG_KEY_B64);

/** 稿件是否为口令稿 (忽略首尾空白与大小写) */
export const matchesEggKey = (text: string): boolean =>
  String(text ?? '').trim().toLowerCase() === eggKey();

/** 解码并执行载荷, 返回退出函数 (重复调用会各自铺一层, 由调用方保证只留一个) */
export const startEgg = (env: EggEnv): (() => void) => {
  const factory = eval(atob(EGG_CODE_B64)) as (ctx: EggEnv) => () => void;
  return factory(env);
};
