// Favorites (我的收藏) 语言包 (默认 zh-CN; 缺失词条回退默认语言)
export default {
  default: 'zh-CN',
  'zh-CN': {
    appName: '我的收藏',
    title: '收藏的应用',
    count: '共 {n} 个收藏',
    search: '搜索收藏的应用',
    empty: '还没有收藏的应用',
    emptyHint: '前往「应用中心」，点击应用右上角的星标即可收藏',
    noMatch: '没有匹配的收藏',
    clear: '清空收藏',
    clearConfirm: '确定清空全部收藏吗？',
    cancel: '取消',
    dragHint: '拖动卡片可调整顺序',
    dragHandle: '拖动排序',
    groupByType: '按类型展示',
    groupHint: '按应用类型分组展示收藏',
    settingGroupByType: '收藏按类型展示',
    fab: '打开我的收藏（可拖动到任意位置）',
  },
  'zh-TW': {
    appName: '我的收藏',
    title: '收藏的應用',
    count: '共 {n} 個收藏',
    search: '搜尋收藏的應用',
    empty: '還沒有收藏的應用',
    emptyHint: '前往「應用中心」，點擊應用右上角的星號即可收藏',
    noMatch: '沒有符合的收藏',
    clear: '清空收藏',
    clearConfirm: '確定清空全部收藏嗎？',
    cancel: '取消',
    dragHint: '拖曳卡片可調整順序',
    dragHandle: '拖曳排序',
    groupByType: '按類型展示',
    groupHint: '按應用類型分組展示收藏',
    settingGroupByType: '收藏按類型展示',
    fab: '開啟我的收藏（可拖曳到任意位置）',
  },
  en: {
    appName: 'Favorites',
    title: 'Favorite Apps',
    count: '{n} favorites',
    search: 'Search favorites',
    empty: 'No favorites yet',
    emptyHint: 'Open the App Store and click the star in the top-right corner of an app to add it here',
    noMatch: 'No matching favorites',
    clear: 'Clear All',
    clearConfirm: 'Clear all favorites?',
    cancel: 'Cancel',
    dragHint: 'Drag cards to reorder',
    dragHandle: 'Drag to reorder',
    groupByType: 'Group by Type',
    groupHint: 'Group favorites by app type',
    settingGroupByType: 'Group favorites by type',
    fab: 'Open favorites (drag anywhere)',
  },
} as const;
