// Help 页数据: 使用组件 / 开发者 / 开发时间线
// 开发时间线 (eventList) 三语: zh-CN 与 update.md 各版本节同步 (发布说明原文), zh-TW / en 为译文
export const compomentList = [
  { name: "Tauri 2", url: "https://tauri.app/" },
  { name: "React 18", url: "https://react.dev/" },
  { name: "Ant Design 5", url: "https://ant.design/" },
  { name: "CryptoJS", url: "https://github.com/brix/crypto-js" },
  { name: "js-base64", url: "https://github.com/dankogai/js-base64" },
  { name: "color-convert", url: "https://github.com/Qix-/color-convert" },
  { name: "SQL Formatter", url: "https://github.com/sql-formatter-org/sql-formatter" },
  { name: "highlight.js", url: "https://highlightjs.org/" },
  { name: "base-x", url: "https://github.com/cryptocoinjs/base-x" },
  { name: "pinyin-pro", url: "https://pinyin-pro.cn/" },
  { name: "js-ini", url: "https://github.com/Sdju/js-ini" },
  { name: "yaml", url: "https://github.com/eemeli/yaml" },
  { name: "toml-patch", url: "https://github.com/timhall/toml-patch" },
  { name: "deepmerge", url: "https://github.com/TehShrike/deepmerge" },
];

// 开发者列表
export const developerList = [
  { name: "bluefrog",url: "https://github.com/freewu",avater: "https://www.gravatar.com/avatar/c2bd3e109318983039778c259cc78db890c1b1f93b574a95c76807759c386db9" },
];

export type LKey = 'zh-CN' | 'zh-TW' | 'en';
export interface HelpEvent { color: string; title: Record<LKey, string>; items: Record<LKey, string[]>; }

const tri = (zh: string, tw: string, en: string) => ({ 'zh-CN': zh, 'zh-TW': tw, en });
const trio = (zh: string[], tw: string[], en: string[]) => ({ 'zh-CN': zh, 'zh-TW': tw, en });

export const eventList: HelpEvent[] = [
  {
    color: "green",
    title: tri("2026-09-17 V2.12.0 Release", "2026-09-17 V2.12.0 Release", "2026-09-17 V2.12.0 Release"),
    items: trio(
      [
        "「正则表达式」新增「代码生成」页签: 底部说明区改为「说明 / 代码生成」双页签, 选好语言即按当前正则 + i/g/m/s 标志位 (连同上方文本) 生成对应语言的调用代码, 支持 21 种语言 (Python / C / C++ / Java / C# / JavaScript / R / Rust / Delphi / PHP / Go / Ruby / Swift / Perl / Objective-C / Julia / Kotlin / TypeScript / Erlang / Lua / PowerShell), 带 highlight.js 语法高亮与一键复制; 每个语言都按自身惯例生成 (原始字符串、内联标志位、选项枚举、全局匹配方式差异, 模式里出现引号或 / 等分隔符时自动降级转义), 示例文本取上方输入内容、最多前 6 行",
        "新增「提词器」工具 (其它): 调速 / 字号 / 行距 / 淡入淡出 / 全屏, 空格 开始·暂停; 默认示例稿按语言随机载入示范诗; 参数可「保存为默认设置」, 也可在 设置 → 其它 → 提词器 里预设默认值",
        "提词器新增「逐行焦点高亮」(只高亮当前阅读行, 越远越透明越淡) 与「按阅读进度从左到右逐字点亮」",
        "新增「Mermaid 编辑器」工具 (格式化): 实时预览 + 源码编辑, 内置 32 个示例 (覆盖 mermaid 可预览的全部图形, 按图形家族分组), 支持缩放 / 背景 / 面板开关与导出",
        "新增「CSR 申请文件」工具 (站长工具): 本机生成 RSA 私钥 + PKCS#10 请求, 支持 SAN",
        "新增「图片水印」工具 (图片): 文字 / logo 水印, 九宫格·平铺 + 旋转·透明度·描边, PNG·JPEG·WebP 导出",
        "新增「图片负片」「图片黑白化」「图片锐化」「图片取色」四个图片工具: 负片可调强度反相; 黑白化支持灰度 / 二值与大津法自动阈值; 锐化支持 USM 半径 / 强度 / 阈值; 取色带放大镜与 HEX/RGB/HSL 及历史色",
        "新增「DNS 查询」「Whois 查询」「MTR 查询」三个站长工具 (仅桌面版): DNS 支持多记录类型与指定服务器; Whois 走 3 跳 referral 链; MTR 即 traceroute + ping, 逐跳给出丢包 / RTT / 抖动",
        "「IP 转换」新增 IPv6 写法换算; 新增「生成器」分类, 「IP 转换」改归「类型转换」",
        "修复「时间戳转换」上月末 / 下月末时间取成 00:00:00 (应为 23:59:59), 以及上月 / 下月日期不存在时年份算错 (3-31 的上月应为 2-28、1-31 的下月应为 2-28)",
        "修复「Mermaid 编辑器」缩放与背景显示异常、面板开关失效; 正则表达式输入框占位符中的 \\d 未转义 (界面上显示成了 d)",
        "「网页 TDK 信息检测」改为仅桌面版; 去掉 7 个工具顶部的说明区; 「JSONL 转换」工具条移到上方 JSON 框之上; 「时间戳转换」GPS / 北斗 / 伽利略 各用分组框展示",
      ],
      [
        "「正則表達式」新增「程式碼產生」頁籤: 底部說明區改為「說明 / 程式碼產生」雙頁籤, 選好語言即依目前正則 + i/g/m/s 旗標 (連同上方文字) 產生對應語言的呼叫程式碼, 支援 21 種語言 (Python / C / C++ / Java / C# / JavaScript / R / Rust / Delphi / PHP / Go / Ruby / Swift / Perl / Objective-C / Julia / Kotlin / TypeScript / Erlang / Lua / PowerShell), 帶 highlight.js 語法高亮與一鍵複製; 每種語言都依自身慣例產生 (原始字串、內聯旗標、選項列舉、全域比對方式差異, 樣式裡出現引號或 / 等分隔符時自動降級轉義), 範例文字取上方輸入內容、最多前 6 行",
        "新增「提詞器」工具 (其他): 調速 / 字號 / 行距 / 淡入淡出 / 全螢幕, 空白鍵 開始·暫停; 預設範例稿依語言隨機載入示範詩; 參數可「儲存為預設設定」, 也可在 設定 → 其他 → 提詞器 裡預設預設值",
        "提詞器新增「逐行焦點高亮」(只高亮目前閱讀行, 越遠越透明越淡) 與「依閱讀進度由左到右逐字點亮」",
        "新增「Mermaid 編輯器」工具 (格式化): 即時預覽 + 原始碼編輯, 內建 32 個範例 (涵蓋 mermaid 可預覽的全部圖形, 依圖形家族分組), 支援縮放 / 背景 / 面板開關與匯出",
        "新增「CSR 申請檔案」工具 (站長工具): 本機產生 RSA 私鑰 + PKCS#10 請求, 支援 SAN",
        "新增「圖片浮水印」工具 (圖片): 文字 / logo 浮水印, 九宮格·平鋪 + 旋轉·透明度·描邊, PNG·JPEG·WebP 匯出",
        "新增「圖片負片」「圖片黑白化」「圖片銳化」「圖片取色」四個圖片工具: 負片可調強度反相; 黑白化支援灰階 / 二值與大津法自動閾值; 銳化支援 USM 半徑 / 強度 / 閾值; 取色帶放大鏡與 HEX/RGB/HSL 及歷史色",
        "新增「DNS 查詢」「Whois 查詢」「MTR 查詢」三個站長工具 (僅桌面版): DNS 支援多記錄類型與指定伺服器; Whois 走 3 跳 referral 鏈; MTR 即 traceroute + ping, 逐跳給出丟包 / RTT / 抖動",
        "「IP 轉換」新增 IPv6 寫法換算; 新增「產生器」分類, 「IP 轉換」改歸「類型轉換」",
        "修正「時間戳轉換」上月末 / 下月末時間取成 00:00:00 (應為 23:59:59), 以及上月 / 下月日期不存在時年份算錯 (3-31 的上月應為 2-28、1-31 的下月應為 2-28)",
        "修正「Mermaid 編輯器」縮放與背景顯示異常、面板開關失效; 正則表達式輸入框佔位符中的 \\d 未轉義 (介面上顯示成了 d)",
        "「網頁 TDK 資訊偵測」改為僅桌面版; 去掉 7 個工具頂部的說明區; 「JSONL 轉換」工具列移到上方 JSON 框之上; 「時間戳轉換」GPS / 北斗 / 伽利略 各用分組框展示",
      ],
      [
        "Regex Tester: new “Code” tab — the notes area at the bottom is now a two-tab “Notes / Code” panel; pick a language and it generates ready-to-copy usage code for the current pattern + the i/g/m/s flags (plus the text above) in 21 languages (Python / C / C++ / Java / C# / JavaScript / R / Rust / Delphi / PHP / Go / Ruby / Swift / Perl / Objective-C / Julia / Kotlin / TypeScript / Erlang / Lua / PowerShell), with highlight.js syntax colouring and one-click copy. Each language follows its own conventions (raw strings, inline flags, option enums, different global-match handling; quote or / delimiter conflicts degrade to escaped strings automatically); the sample text is taken from the box above, capped at 6 lines",
        "New “Teleprompter” tool (Other): speed / font size / line height / fade / fullscreen, Space to play and pause; the default script loads a random demo poem per language; settings can be saved as defaults, and presets live in Settings → Other → Teleprompter",
        "Teleprompter: new line-focus highlight (only the current line is highlighted; the further away, the fainter) and left-to-right, character-by-character illumination following the reading progress",
        "New “Mermaid Editor” tool (Formatter): live preview plus source editing with 32 built-in samples (covering every previewable mermaid diagram family, grouped by family) and zoom / background / panel toggles plus export",
        "New “CSR Generator” tool (Webmaster): creates an RSA key and a PKCS#10 request locally, with SAN support",
        "New “Image Watermark” tool (Image): text / logo watermarks with 3×3 placement or tiling plus rotation, opacity and outline, exported as PNG / JPEG / WebP",
        "New “Image Negative”, “Image Grayscale”, “Image Sharpen” and “Image Color Picker” tools: adjustable-strength inversion; grayscale / threshold with automatic Otsu thresholding; unsharp masking with radius, strength and threshold; a colour picker with a magnifier and HEX/RGB/HSL plus recent colours",
        "New “DNS Query”, “Whois Query” and “MTR Query” webmaster tools (desktop only): DNS supports multiple record types and a custom server; Whois follows a 3-hop referral chain; MTR is traceroute + ping reporting loss, RTT and jitter per hop",
        "IP Converter: new IPv6 notation output; new “Generators” category, IP Converter moved to “Converters”",
        "Fixed Timestamp Converter taking 00:00:00 for end of previous / next month (should be 23:59:59) and computing the wrong year when the target day does not exist (previous month of 3-31 should be 2-28, next month of 1-31 should be 2-28)",
        "Fixed Mermaid Editor zoom and background rendering plus broken panel toggles; fixed the unescaped \\d in the Regex Tester pattern placeholder (it showed as d)",
        "Web TDK Check is now desktop-only; removed the top description area from 7 tools; moved the JSONL Converter toolbar above the top JSON box; Timestamp Converter now groups GPS / BeiDou / Galileo into separate fieldsets",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-16 V2.11.0 Release", "2026-09-16 V2.11.0 Release", "2026-09-16 V2.11.0 Release"),
    items: trio(
      [
        "新增「JSONL 转换」工具 (类型转换): JSON 数组 ↔ JSONL 互转 —— 上方 JSON 框 / 下方 JSONL 框两个框都既可输入也可输出, 结果写进目标格式的框 (源内容保留); 支持 2 空格 / 4 空格 / Tab 缩进、忽略空行、拖拽或选择文件载入、双击复制、载入示例",
        "「JSONL 转换」: 点错按钮或把内容放进另一个框时会自动按正确方向转换并给出提示; 「下载」改为弹出系统保存对话框 (可选目录与文件名, 扩展名随结果框为 .jsonl / .json)",
        "「数据生成」新增 .jsonl 输出格式 (每行一条紧凑 JSON, 便于导入大数据平台)",
        "「图片尺寸调整」更名为「图片调整」, 并新增 90° / 180° / 270° 旋转与 WebP 输出格式 (WebP 可选输出质量, 浏览器不支持时该选项自动禁用)",
        "修复所有「保存 / 导出文本」类工具在桌面版保存对话框选好路径后却没有生成文件的问题 (capabilities 缺少 fs:allow-write-text-file, 写入被拒后又静默回退为浏览器下载); 现在补齐权限并增加字节写入兜底, 真失败会明确报错 —— 影响配置转换、数据生成、JSON / JSON5 / SQL 格式化、RSA / SM2 密钥导出、robots.txt、htpasswd、点阵字库、图像取色、WebSocket 调试等",
        "修复「Markdown 编辑器」深色模式下预览区标题 (h1 - h6) 与正文几乎看不清的问题",
        "just release 现在会输出开始时间 / 结束时间 / 耗时",
      ],
      [
        "新增「JSONL 轉換」工具 (類型轉換): JSON 陣列 ↔ JSONL 互轉 —— 上方 JSON 框 / 下方 JSONL 框兩個框都既可輸入也可輸出, 結果寫進目標格式的框 (來源內容保留); 支援 2 空格 / 4 空格 / Tab 縮排、忽略空行、拖曳或選擇檔案載入、雙擊複製、載入範例",
        "「JSONL 轉換」: 點錯按鈕或把內容放進另一個框時會自動依正確方向轉換並給出提示; 「下載」改為彈出系統儲存對話框 (可選目錄與檔名, 副檔名依結果框為 .jsonl / .json)",
        "「資料產生」新增 .jsonl 輸出格式 (每列一筆緊湊 JSON, 便於匯入大資料平台)",
        "「圖片尺寸調整」更名為「圖片調整」, 並新增 90° / 180° / 270° 旋轉與 WebP 輸出格式 (WebP 可選輸出品質, 瀏覽器不支援時該選項自動停用)",
        "修正所有「儲存 / 匯出文字」類工具在桌面版儲存對話框選好路徑後卻沒有產生檔案的問題 (capabilities 缺少 fs:allow-write-text-file, 寫入被拒後又靜默退回瀏覽器下載); 現在補齊權限並增加位元組寫入備援, 真失敗會明確報錯 —— 影響設定轉換、資料產生、JSON / JSON5 / SQL 格式化、RSA / SM2 金鑰匯出、robots.txt、htpasswd、點陣字庫、影像取色、WebSocket 偵錯等",
        "修正「Markdown 編輯器」深色模式下預覽區標題 (h1 - h6) 與正文幾乎看不清的問題",
        "just release 現在會輸出開始時間 / 結束時間 / 耗時",
      ],
      [
        "New “JSONL Converter” tool (Converters): convert a JSON array ↔ JSONL — the top JSON box and the bottom JSONL box both accept input and show output, the result is written into the box matching its format and the source is kept. Supports 2-space / 4-space / Tab indent, skipping blank lines, drag & drop or file picking, double-click copy and a sample",
        "JSONL Converter: clicking the wrong button — or putting the content into the other box — now converts the correct way automatically and tells you; “Download” opens the system save dialog (pick folder and file name, the extension follows the result box: .jsonl / .json)",
        "Mock Data Generator: new .jsonl output format (one compact JSON per line, ready for big-data platforms)",
        "“Image Resize” renamed to “Image Adjust” with new 90° / 180° / 270° rotation and WebP output (optional quality; the option is disabled automatically when the browser cannot encode WebP)",
        "Fixed every “save / export text” tool producing no file on desktop after picking a path in the save dialog (the capabilities were missing fs:allow-write-text-file, so the write was rejected and then silently fell back to a browser download). A byte-level writeFile fallback was added and real failures now report an error — affects Config Converter, Mock Data, JSON / JSON5 / SQL Formatter, RSA / SM2 key export, robots.txt, htpasswd, Dot Matrix Font, Image Color and WebSocket Debug",
        "Fixed Markdown Editor preview headings (h1 - h6) and body text being almost unreadable in dark mode",
        "just release now prints start time / end time / elapsed time",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-15 V2.10.1 Release", "2026-09-15 V2.10.1 Release", "2026-09-15 V2.10.1 Release"),
    items: trio(
      [
        "字帖生成器: 新增「按行填充」开关 (一行练一个字, 同一行重复同一个字、第 N 行用第 N 个字); 格线颜色新增「淡绿」",
        "字帖生成器: 修复「字在格子里偏右 / 偏下」—— 中文字体字形在字身框里本身不居中, 现在按字逐个光栅化实测墨迹包围盒并反向微调, 米字格十字正好穿过字的中心 (实测 93mm 格子 / 67mm 字号: 偏右 2.16mm → 0.27mm, 偏下 0.84mm → 0.09mm)",
        "字帖生成器: 修复「上传的自定义字体不生效」—— font-family 里的双引号未转义导致整个 style 属性被截断; 自定义字体为异步加载, 加载完成后自动重新测量字形偏移",
        "设置中心 → 其它 → 字帖生成器: 新增「默认格间距」「默认循环填充」「默认按行填充」(此前「默认循环填充」只在说明里提到, 界面上无法配置)",
        "字帖生成器: 设置面板重排 (文本置顶), 「格间距」支持 0 - 5mm 步进 0.5mm 并带单位提示; 关闭循环填充时统计文案直接显示实际填充格数",
        "侧边栏: 修复折叠状态下鼠标悬停展开的二级菜单浮层超出窗口底部被裁掉的问题 (「其它」分类的子项看不到也点不到), 现在会自动向上翻转并留出安全边距",
      ],
      [
        "字帖產生器: 新增「依行填充」開關 (一行練一個字, 同一行重複同一個字、第 N 行用第 N 個字); 格線顏色新增「淡綠」",
        "字帖產生器: 修正「字在格子裡偏右 / 偏下」—— 中文字體字形在字身框裡本身不居中, 現在依字逐個光柵化實測墨跡包圍盒並反向微調, 米字格十字正好穿過字的中心 (實測 93mm 格子 / 67mm 字號: 偏右 2.16mm → 0.27mm, 偏下 0.84mm → 0.09mm)",
        "字帖產生器: 修正「上傳的自訂字型不生效」—— font-family 裡的雙引號未轉義導致整個 style 屬性被截斷; 自訂字型為非同步載入, 載入完成後自動重新測量字形偏移",
        "設定中心 → 其他 → 字帖產生器: 新增「預設格間距」「預設循環填充」「預設依行填充」(此前「預設循環填充」只在說明裡提到, 介面上無法設定)",
        "字帖產生器: 設定面板重排 (文字置頂), 「格間距」支援 0 - 5mm 步進 0.5mm 並帶單位提示; 關閉循環填充時統計文案直接顯示實際填充格數",
        "側邊欄: 修正折疊狀態下滑鼠懸停展開的二級選單浮層超出視窗底部被裁掉的問題 (「其他」分類的子項看不到也點不到), 現在會自動向上翻轉並留出安全邊距",
      ],
      [
        "Copybook Generator: new “One char per row” switch (every cell in a row repeats the same character, row N uses character N) and a new light-green guide line colour",
        "Copybook Generator: fixed characters sitting right of / below the cell centre — CJK glyphs are not centred inside their em box, so every character's ink box is now rasterised and measured, then nudged back per character (93mm cell / 67mm glyph: 2.16mm → 0.27mm right, 0.84mm → 0.09mm down)",
        "Copybook Generator: fixed uploaded custom fonts not being applied (unescaped double quotes in font-family truncated the whole style attribute); the offset is also re-measured once the asynchronous font finishes loading",
        "Settings → Utilities → Copybook Generator: new default cell gap, default repeat-to-fill and default one-char-per-row options (the repeat default previously existed in the docs only)",
        "Copybook Generator: settings panel reordered (text first), cell gap now 0 - 5mm in 0.5mm steps with a unit hint, and the stats line reports the real number of filled cells when repeat is off",
        "Sidebar: fixed the collapsed flyout submenu being clipped at the bottom of the window (sub-items of the Utilities category were invisible and unclickable); it now flips upwards with a safe margin",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-15 V2.10.0 Release", "2026-09-15 V2.10.0 Release", "2026-09-15 V2.10.0 Release"),
    items: trio(
      [
        "新增「数独生成器」工具: 随机生成唯一解的 4 / 6 / 9 宫格数独题, 采用「随机回溯生成完整解 → 中心对称挖空 → 校验唯一解」三步保证唯一解, 难度分高 / 中 / 低",
        "数独生成器: 按 A4 版式自动排布 (4 宫 4 题 / 6 宫上下 2 题 / 9 宫 1 题), 可选「仅题目 / 仅答案 (红色) / 题目 + 答案」, 一键「打印 A4」调用系统打印对话框 (也可另存为 PDF)",
        "新增「字帖生成器」工具: 生成可打印的 A4 练字字帖, 支持米字格 / 田字格 / 回宫格 / 作文格四种格型与楷体 / 行楷 / 隶书 / 宋体 / 黑体 / 仿宋 / 微软雅黑七种字体, 可上传本地 ttf / otf / woff / woff2 字体",
        "字帖生成器: 内容模式含描红 / 黑字 / 首字示范 / 空白格, 格线红 / 灰 / 蓝可选; 格子尺寸由「每行格数 × 每页行数」自动均分 A4 可用区域, 整页不溢出、不裁切",
        "新增打印辅助模块 src/lib/print.ts: 用离屏 iframe 承载 A4 版式 HTML 再唤起系统打印, 与页面深色主题样式完全隔离, 打印结果恒为白底",
        "设置中心 → 其它: 新增「数独生成器」「字帖生成器」面板 (默认宫格 / 难度 / 页数 / 打印内容; 默认格型 / 字体 / 格线颜色 / 内容模式 / 行列数 / 文本等)",
        "工具总数 113 (含内置页面共 116 个工具目录), 其中「其它」分类 17 个; 三个 README 与官网计数、工具清单同步",
      ],
      [
        "新增「數獨產生器」工具: 隨機產生唯一解的 4 / 6 / 9 宮格數獨題, 採用「隨機回溯產生完整解 → 中心對稱挖空 → 校驗唯一解」三步保證唯一解, 難度分高 / 中 / 低",
        "數獨產生器: 依 A4 版式自動排布 (4 宮 4 題 / 6 宮上下 2 題 / 9 宮 1 題), 可選「僅題目 / 僅答案 (紅色) / 題目 + 答案」, 一鍵「列印 A4」開啟系統列印對話框 (也可另存為 PDF)",
        "新增「字帖產生器」工具: 產生可列印的 A4 練字字帖, 支援米字格 / 田字格 / 回宮格 / 作文格四種格型與楷體 / 行楷 / 隸書 / 宋體 / 黑體 / 仿宋 / 微軟雅黑七種字型, 可上傳本機 ttf / otf / woff / woff2 字型",
        "字帖產生器: 內容模式含描紅 / 黑字 / 首字示範 / 空白格, 格線紅 / 灰 / 藍可選; 格子尺寸由「每行格數 × 每頁行數」自動均分 A4 可用區域, 整頁不溢出、不裁切",
        "新增列印輔助模組 src/lib/print.ts: 用離屏 iframe 承載 A4 版式 HTML 再開啟系統列印, 與頁面深色主題樣式完全隔離, 列印結果恆為白底",
        "設定中心 → 其他: 新增「數獨產生器」「字帖產生器」面板 (預設宮格 / 難度 / 頁數 / 列印內容; 預設格型 / 字型 / 格線顏色 / 內容模式 / 行列數 / 文字等)",
        "工具總數 113 (含內建頁面共 116 個工具目錄), 其中「其他」分類 17 個; 三個 README 與官網計數、工具清單同步",
      ],
      [
        "New tool: Sudoku Generator — random puzzles with a proven unique solution in 4×4 / 6×6 / 9×9 grids, built by randomized backtracking, centre-symmetric hole digging and a uniqueness check; three difficulty levels",
        "Sudoku Generator: A4 layout packs 4 puzzles (4×4), 2 stacked (6×6) or 1 (9×9) per page, with puzzle-only / answers-only (red) / puzzle + answers output and one-click \"Print A4\" through the system print dialog (or Save as PDF)",
        "New tool: Copybook Generator — printable A4 handwriting practice sheets in mi / tian / hui / essay grids with KaiTi, Xingkai, LiSu, SimSun, SimHei, FangSong and Microsoft YaHei, plus your own local ttf / otf / woff / woff2 font",
        "Copybook Generator: trace / ink / first-character-demo / blank content modes and red, gray or blue guide lines; cell size is derived from columns × rows so a page always fits the A4 printable area without clipping",
        "New print helper src/lib/print.ts — renders A4 HTML inside an off-screen iframe and opens the system print dialog, fully isolated from the app's dark theme so prints are always black-on-white",
        "Settings → Utilities: new Sudoku Generator and Copybook Generator panels (default grid / difficulty / pages / print content; default grid style / font / line color / content mode / columns / rows / text)",
        "Tool count is now 113 (116 directories including the built-in pages), 17 in the Utilities category; the three READMEs and the website counts and tool lists were synced",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-15 V2.9.0 Release", "2026-09-15 V2.9.0 Release", "2026-09-15 V2.9.0 Release"),
    items: trio(
      [
        "新增「图片分割」工具: 按 2 / 3 / 4 / 6 / 9 份把图片切成整齐的小图, 支持 8 种分割方向、顺序/行列编号、每块输出宽度与文件名前缀, 一键「保存全部到文件夹」",
        "新增「图片尺寸调整」工具: 按比例 (1-400%) 或按像素缩放图片, 支持锁定宽高比、不放大图片、PNG / JPEG 输出与 JPEG 质量调节, 缩小超过一半时分多步绘制避免锯齿",
        "图片分割: 预览紧密拼合为整图并在每块左上角标注序号, 新增「图块间隔」0-12 (默认 2) 画出分割线, 0 为无缝拼合; 移除单张保存, 统一走「保存全部到文件夹」",
        "设置中心 → 图片: 新增「图片分割」「图片尺寸调整」面板 (默认份数 / 输出格式 / JPEG 质量 / 缩放比例 / 锁定宽高比)",
        "多语言: 补齐遗漏词条并修复未走 t() 的硬编码文案 (图片主题色、Blowfish ~ RC6、JSON / JSON5、RSA / SM2、WebTDK、ASCII 文字与图片、Markdown 等)",
        "工具总数 111 (图片分类 12 个), README 三语与官网计数、工具清单同步",
      ],
      [
        "新增「圖片分割」工具: 依 2 / 3 / 4 / 6 / 9 份把圖片切成整齊的小圖, 支援 8 種分割方向、順序/行列編號、每塊輸出寬度與檔名前綴, 一鍵「儲存全部到資料夾」",
        "新增「圖片尺寸調整」工具: 依比例 (1-400%) 或依像素縮放圖片, 支援鎖定長寬比、不放大圖片、PNG / JPEG 輸出與 JPEG 品質調節, 縮小超過一半時分多步繪製避免鋸齒",
        "圖片分割: 預覽緊密拼合為整圖並在每塊左上角標註序號, 新增「圖塊間隔」0-12 (預設 2) 畫出分割線, 0 為無縫拼合; 移除單張儲存, 統一走「儲存全部到資料夾」",
        "設定中心 → 圖片: 新增「圖片分割」「圖片尺寸調整」面板 (預設份數 / 輸出格式 / JPEG 品質 / 縮放比例 / 鎖定長寬比)",
        "多語言: 補齊遺漏詞條並修復未走 t() 的硬編碼文案 (圖片主題色、Blowfish ~ RC6、JSON / JSON5、RSA / SM2、WebTDK、ASCII 文字與圖片、Markdown 等)",
        "工具總數 111 (圖片分類 12 個), README 三語與官網計數、工具清單同步",
      ],
      [
        "New tool: Image Splitter — cut one image into 2 / 3 / 4 / 6 / 9 neat tiles with 8 layouts, sequential or row-column numbering, per-tile output width and a file-name prefix, exported at once via \"Save all to folder\"",
        "New tool: Image Resizer — resize by percentage (1-400%) or by pixels, with aspect-ratio lock, never-enlarge (shrink only), PNG / JPEG output and adjustable JPEG quality; reductions over half are drawn in steps to avoid aliasing",
        "Image Splitter: the preview is assembled seamlessly into the whole picture with a translucent index on each tile; a new \"Tile gap\" (0-12, default 2) draws the separator lines and 0 joins them seamlessly; per-tile saving was removed in favour of \"Save all to folder\"",
        "Settings → Image: new Image Splitter and Image Resizer panels (default parts / output format / JPEG quality / scale / aspect-ratio lock)",
        "i18n: filled in missing entries and fixed hard-coded strings that bypassed t() (dominant color, Blowfish ~ RC6, JSON / JSON5, RSA / SM2, WebTDK, ASCII text and image, Markdown, …)",
        "Tool count is now 111 (12 in the image category); the three READMEs and the website counts and tool lists were synced",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-14 V2.8.0 Release", "2026-09-14 V2.8.0 Release", "2026-09-14 V2.8.0 Release"),
    items: trio(
      [
        "新增「数据生成」工具: 按 Mock.js 语法生成测试数据 (JSON / CSV / SQL), 支持模板、区间、自增、枚举、占位符等规则, 可在设置中心配置默认格式 / 表名 / 生成数量",
        "新增「WebSocket 调试」工具: 浏览器原生 WebSocket 调试台, 支持 ws/wss 连接、心跳保活、JSON 美化、收发日志复制与下载",
        "图片主题色: 重构为「统计像素 -> 合并相近色 -> 按占比排序」, 可调相似度级别 / 输出颜色数 / 透明阈值, 支持占比条、复制、导出 CSV 与色卡 PNG, 并归入「图片」分类",
        "图片主题色: 颜色值支持 HEX / RGB / HSL / CMYK / HSV / LAB / LCH / XYZ 共 8 种格式展示与导出 (默认 HEX), 默认值可在 设置中心 → 图片 修改",
        "新增工具需在 src/App/index.tsx 的工具注册表 list 中登记, 三个 README 已补充该步骤说明; 工具总数 109, 分类计数同步修正",
      ],
      [
        "新增「資料產生」工具: 依 Mock.js 語法產生測試資料 (JSON / CSV / SQL), 支援模板、區間、自增、列舉、佔位符等規則, 可在設定中心設定預設格式 / 表名 / 產生數量",
        "新增「WebSocket 偵錯」工具: 瀏覽器原生 WebSocket 偵錯台, 支援 ws/wss 連線、心跳保活、JSON 美化、收發日誌複製與下載",
        "圖片主題色: 重構為「統計像素 -> 合併相近色 -> 依佔比排序」, 可調相似度級別 / 輸出顏色數 / 透明閾值, 支援佔比條、複製、匯出 CSV 與色卡 PNG, 並歸入「圖片」分類",
        "圖片主題色: 顏色值支援 HEX / RGB / HSL / CMYK / HSV / LAB / LCH / XYZ 共 8 種格式顯示與匯出 (預設 HEX), 預設值可在 設定中心 → 圖片 修改",
        "新增工具需在 src/App/index.tsx 的工具註冊表 list 中登記, 三個 README 已補充該步驟說明; 工具總數 109, 分類計數同步修正",
      ],
      [
        "New Mock Data tool: generates test data (JSON / CSV / SQL) from Mock.js syntax — templates, ranges, auto-increment, enums and placeholders — with default format / table name / record count configurable in Settings",
        "New WebSocket Debugger tool: a browser-native WebSocket console with ws/wss connections, heartbeat, JSON pretty-printing, and copy/download of the send & receive log",
        "Dominant colors: rebuilt around count → merge similar colors → sort by share, with adjustable similarity level, color count and alpha threshold, plus a share bar, copy, CSV and swatch-PNG export; moved into the Image category",
        "Dominant colors: color values can be shown and exported in 8 formats (HEX / RGB / HSL / CMYK / HSV / LAB / LCH / XYZ), HEX by default and configurable in Settings → Image",
        "New tools must be registered in the tool registry list of src/App/index.tsx; all three READMEs document this step. Tool count is 109 and the per-category counts were corrected",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-10 V2.7.3 Release", "2026-09-10 V2.7.3 Release", "2026-09-10 V2.7.3 Release"),
    items: trio(
      [
        "颜色格式转换: 新增「自动识别」输入格式 (按格式前缀或 (a,b,c) 元组自动判定 HEX/RGB/HSL/HSV/CMYK/LAB/LCH/XYZ), 取色器选色默认按 HEX; 「自动识别」位于类型选项首位且为默认",
        "颜色格式转换: 设置中心 → 类型转换 可配置默认选中类型 (默认「自动识别」)",
        "新增 just dev-init: 一键检查/安装开发环境组件 (Node.js >=18 / 前端依赖 / Rust 工具链 / 后端依赖), 已就绪的组件打绿色 ✓ 并跳过, 可重复执行",
        "README: 三个语言版补充 just 安装说明与 dev-init 初始化流程 (git clone -> cd -> just dev-init -> just dev), 项目结构展开 src/App/ 子结构与 110 个工具清单",
      ],
      [
        "顏色格式轉換: 新增「自動識別」輸入格式 (依格式前綴或 (a,b,c) 元組自動判定 HEX/RGB/HSL/HSV/CMYK/LAB/LCH/XYZ), 取色器選色預設按 HEX; 「自動識別」位於類型選項首位且為預設",
        "顏色格式轉換: 設定中心 → 類型轉換 可設定預設選中類型 (預設「自動識別」)",
        "新增 just dev-init: 一鍵檢查/安裝開發環境元件 (Node.js >=18 / 前端依賴 / Rust 工具鏈 / 後端依賴), 已就緒的元件顯示綠色 ✓ 並跳過, 可重複執行",
        "README: 三個語言版本補充 just 安裝說明與 dev-init 初始化流程 (git clone -> cd -> just dev-init -> just dev), 專案結構展開 src/App/ 子結構與 110 個工具清單",
      ],
      [
        "Color Convert: added an Auto-detect input type (infers HEX/RGB/HSL/HSV/CMYK/LAB/LCH/XYZ from a format prefix or an (a,b,c) tuple); the color picker defaults to HEX in this mode. Auto is now the first option and the default selection",
        "Color Convert: Settings → Convert now offers a Color Format Convert panel to set the default selected type (defaults to Auto)",
        "Added `just dev-init`: checks/installs the dev components in one shot (Node.js >=18 / frontend deps / Rust toolchain / backend deps), skips what is ready with a green ✓ and is safe to re-run",
        "README: all three languages document installing just and the dev-init flow (git clone -> cd -> just dev-init -> just dev), and the repository layout now expands the src/App/ subtree plus the full 110-tool list",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-10 V2.7.2 Release", "2026-09-10 V2.7.2 Release", "2026-09-10 V2.7.2 Release"),
    items: trio(
      [
        "Web 版 (网页演示) 支持 URL ?lang= 参数指定界面语言 (如 ?lang=en / zh-TW), 优先级高于本地记忆; 官网 demo 入口链接按页面语言自动带上参数",
        "颜色格式转换: 「格式/配色方案」页签移到输入框下方, 输入区常驻顶部",
        "颜色格式转换修复: 取色器填充非 #rrggbb 且不生成配色方案 (onChange 参数误用 css 字符串); LAB/LCH/XYZ 负值通道解析失败导致无结果/无方案; HSV 误用 hsl 转换",
        "删除 App 级共享 ui-lang / crypto-lang 等公共词条表, 各工具词条拆回自己的 lang.ts, 便于独立维护",
      ],
      [
        "Web 版 (網頁示範) 支援 URL ?lang= 參數指定介面語言 (如 ?lang=en / zh-TW), 優先於本地記憶; 官網 demo 入口連結按頁面語言自動帶上參數",
        "顏色格式轉換:「格式/配色方案」頁籤移到輸入框下方, 輸入區常駐頂部",
        "顏色格式轉換修正: 取色器填入非 #rrggbb 且不產生配色方案 (onChange 參數誤用 css 字串); LAB/LCH/XYZ 負值通道解析失敗導致無結果/無方案; HSV 誤用 hsl 轉換",
        "刪除 App 層級共享 ui-lang / crypto-lang 等公共詞條表, 各工具詞條拆回自己的 lang.ts, 便於獨立維護",
      ],
      [
        "Web demo now supports a URL ?lang= parameter to pick the UI language (e.g. ?lang=en / zh-TW), taking precedence over the saved preference; official-site demo buttons carry the matching parameter automatically",
        "Color Convert: the Format / Color-scheme tabs moved below the textarea so the input stays on top",
        "Color Convert fixes: color-picker fill was not #rrggbb and produced no color schemes (misread onChange's CSS-string argument); LAB/LCH/XYZ negative-channel values failed to parse so results and schemes were missing; HSV mistakenly used the HSL conversion",
        "Removed App-level shared ui-lang / crypto-lang dictionaries; each tool's rows now live in its own lang.ts for easier maintenance",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-09 V2.7.1 Release", "2026-09-09 V2.7.1 Release", "2026-09-09 V2.7.1 Release"),
    items: trio(
      [
        "界面全面三语化 (简中/繁中/English)：全部工具页面、设置中心（单位与下拉选项）、About/说明、Help 时间线均按界面语言切换",
        "托盘菜单 (原生) 文案随语言动态切换；新增 ui-lang / rows-lang 三语词条表 (470+ 条)",
        "About 三语化：正则表达式、Morse、JWT、BCD、BaseX (含 16 种码型详述)、HTTP Basic Auth 等；Cron 解析支持按语言输出",
        "侧边栏宽度/底部按钮样式调整，修复多处残留硬编码中文与显示问题",
      ],
      [
        "介面全面三語化 (簡中/繁中/English)：全部工具頁面、設定中心 (單位與下拉選項)、About/說明、Help 時間軸均隨介面語言切換",
        "托盤選單 (原生) 文案隨語言動態切換；新增 ui-lang / rows-lang 三語詞條表 (470+ 條)",
        "About 三語化：正則表達式、Morse、JWT、BCD、BaseX (含 16 種碼型詳述)、HTTP Basic Auth 等；Cron 解析支援依語言輸出",
        "側邊欄寬度/底部按鈕樣式調整，修復多處殘留硬編碼中文與顯示問題",
      ],
      [
        "Full UI trilingual (Simplified / Traditional Chinese / English): every tool page, the Settings center (units and dropdown options), About sections and the Help timeline follow the UI language",
        "Native tray menu text switches with the language; added shared ui-lang / rows-lang tri-lingual dictionaries (470+ rows)",
        "About sections trilingual: Regex Tester, Morse, JWT, BCD, BaseX (incl. notes for all 16 alphabets), HTTP Basic Auth, etc.; Cron parsing output is locale-aware",
        "Sidebar width / bottom-button style tweaks; fixed assorted leftover hardcoded Chinese and display issues",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-08 V2.7.0 Release", "2026-09-08 V2.7.0 Release", "2026-09-08 V2.7.0 Release"),
    items: trio(
      [
        "二维码 / 条形码生成新增「批量」tab: 多行内容一次生成并预览, 桌面版选择文件夹一次导出全部 PNG (不再逐个弹保存框)",
        "格式化分类新增 Markdown 编辑器 (自研渲染, 支持常用语法与行内/块级 LaTeX 公式子集, 可导出 .md 与自带样式 .html); 预览面板可一键隐藏专注编辑",
        "其它分类新增密码生成: 安全随机生成 + 启发式强度检测 (熵估算 / 常见弱口令库含 leet 变体 / 破解时间估算); 站长工具新增 Sitemap 检测、关键词密度",
        "Shield Badge 生成新增图片尺寸 (1-10 倍率) 设置与放大 PNG 导出; 新增路径转树工具",
        "菜单分类调整: 占位图片 / Shield Badge / AppIcon / ICO 生成迁入「图片」分类, CIDR 计算器迁入「其它」, 设置页分组同步迁移",
        "修复 RC2 / RC6 / Blowfish 与 Markdown 编辑器不在侧边菜单显示的问题; 字幕格式转换桌面版下载不弹保存框; 深色模式下固定灰字提示不可见; 左下角版本号移除多余悬停提示",
      ],
      [
        "二維碼 / 條碼產生器新增「批次」頁籤: 多行內容一次產生並預覽, 桌面版可選擇資料夾一次匯出全部 PNG (不再逐個跳出儲存視窗)",
        "格式化分類新增 Markdown 編輯器 (自研渲染, 支援常用語法與行內/區塊 LaTeX 公式子集, 可匯出 .md 與帶樣式的 .html); 預覽面板可一鍵隱藏專注編輯",
        "其他分類新增密碼產生器: 安全隨機產生 + 啟發式強度偵測 (熵估算 / 常見弱密碼庫含 leet 變體 / 破解時間估算); 站長工具新增 Sitemap 檢測、關鍵字密度",
        "Shield Badge 產生器新增圖片尺寸 (1-10 倍率) 設定與放大 PNG 匯出; 新增路徑轉樹狀工具",
        "選單分類調整: 占位圖片 / Shield Badge / AppIcon / ICO 產生器移入「圖片」分類, CIDR 計算器移入「其他」, 設定頁分組同步調整",
        "修復 RC2 / RC6 / Blowfish 與 Markdown 編輯器未顯示於側邊選單的問題; 字幕格式轉換桌面版下載不再彈儲存視窗; 修復深色模式下固定灰字提示不可見; 左下角版本號移除多餘的懸停提示",
      ],
      [
        "QR / barcode generator adds a “Batch” tab: generate and preview many lines at once; the desktop build exports all PNGs into a chosen folder in one go (no more per-file save dialogs)",
        "The Formatting category gains a Markdown editor (self-built renderer: common syntax plus inline/block LaTeX formula subsets, exports .md and self-styled .html); the preview panel can be hidden for focused editing",
        "The Others category gains a password generator (secure random + heuristic strength checks: entropy estimate / common weak-password list incl. leet variants / crack-time estimate); webmaster tools add Sitemap check and keyword density",
        "Shield Badge generator adds an image size (1–10×) setting and scaled-up PNG export; new “Path to Tree” tool",
        "Menu category reshuffle: Placeholder Image / Shield Badge / AppIcon / ICO moved to “Image”, CIDR Calculator to “Others”, settings-page groups moved to match",
        "Fixed RC2 / RC6 / Blowfish and the Markdown editor not showing in the sidebar menu; Subtitle converter downloads no longer pop a save dialog on desktop; fixed dim-gray hints being invisible in dark mode; removed the redundant hover tooltip on the bottom-left version number",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-08 V2.6.0 Release", "2026-09-08 V2.6.0 Release", "2026-09-08 V2.6.0 Release"),
    items: trio(
      [
        "新增「格式化」分类: JSON / JSON5 / SQL 格式化移入独立分类 (侧边菜单/应用中心/设置页同步分组)",
        "字幕格式转换: SRT/VTT/SBV/SUB/SSA/ASS/SMI/LRC/JSON 九格式互转 (本地解析, 样式指令剥除, 自动检测 + MicroDVD fps)",
        "加解密新增 RC5 / RC2 / Blowfish / RC6 (参考 AES 的五模式 UI) 与 ChaCha20 (RFC 7539, 官方向量验证)",
        "值计算新增 CMAC / HKDF / KMAC、原码/反码/补码; 颜色格式转换新增 7 组配色方案 (主色居中, 点击复制 HEX)",
        "编解码新增 HTTP Basic Auth 与 Chmod 权限; 其它新增 IP 转换 (IPv4 ↔ 整数/HEX/BIN) 与 OTP 密码生成器 (TOTP/HOTP, otpauth URI 扫码导入)",
        "其它新增键盘按键信息、点阵字生成器、文件比较; 配置转换支持 XML 互转 + 拖入自动识别",
        "时间工具新增 GPS/北斗/伽利略/格洛纳斯/儒略日输出",
        "启动后自动检测 GitHub 新版本 (右下角弹窗提示, 点击打开下载页)",
        "修复应用中心分类布局与分割线显示问题",
      ],
      [
        "新增「格式化」分類: JSON / JSON5 / SQL 格式化移入獨立分類 (側邊選單/應用中心/設定頁同步分組)",
        "字幕格式轉換: SRT/VTT/SBV/SUB/SSA/ASS/SMI/LRC/JSON 九格式互轉 (本機解析, 剝除樣式指令, 自動偵測 + MicroDVD fps)",
        "加解密新增 RC5 / RC2 / Blowfish / RC6 (參考 AES 的五模式 UI) 與 ChaCha20 (RFC 7539, 以官方測試向量驗證)",
        "值計算新增 CMAC / HKDF / KMAC、原碼/反碼/補碼; 顏色格式轉換新增 7 組配色方案 (主色置中, 點擊複製 HEX)",
        "編解碼新增 HTTP Basic Auth 與 Chmod 權限; 其他新增 IP 轉換 (IPv4 ↔ 整數/HEX/BIN) 與 OTP 密碼產生器 (TOTP/HOTP, 可掃 otpauth URI 匯入)",
        "其他新增鍵盤按鍵資訊、點陣字產生器、檔案比較; 設定檔轉換支援 XML 互轉 + 拖入自動辨識",
        "時間工具新增 GPS/北斗/伽利略/格洛納斯/儒略日輸出",
        "啟動後自動偵測 GitHub 新版本 (右下角彈窗提示, 點擊開啟下載頁)",
        "修復應用中心分類版面與分隔線顯示問題",
      ],
      [
        "New “Formatting” category: JSON / JSON5 / SQL formatters moved into a category of their own (sidebar menu / app center / settings groups kept in sync)",
        "Subtitle format conversion: SRT/VTT/SBV/SUB/SSA/ASS/SMI/LRC/JSON — nine formats interconverted (parsed locally, style directives stripped, auto-detection + MicroDVD fps)",
        "Crypto adds RC5 / RC2 / Blowfish / RC6 (five-mode AES-style UI) and ChaCha20 (RFC 7539, verified with official vectors)",
        "Value calculators add CMAC / HKDF / KMAC and sign-magnitude / ones' complement / two's complement; the color converter adds 7 palette schemes (primary color centered, click to copy HEX)",
        "Codecs add HTTP Basic Auth and Chmod permissions; Others add IP conversion (IPv4 ↔ integer/HEX/BIN) and an OTP password generator (TOTP/HOTP, scan-to-import via otpauth URI)",
        "Others add keyboard key info, a dot-matrix font generator and file comparison; Config converter supports XML interchange plus drop-in auto-detection",
        "Time tools add GPS / BeiDou / Galileo / GLONASS and Julian-day output",
        "Checks for new GitHub releases on startup (toast in the bottom-right corner; clicking opens the download page)",
        "Fixed the app-center category layout and divider display issues",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-07 V2.5.0 Release", "2026-09-07 V2.5.0 Release", "2026-09-07 V2.5.0 Release"),
    items: trio(
      [
        "值计算新增 BCrypt 生成/校验、Scrypt (RFC 7914 零依赖实现)、PPI 计算 (标准 RGB / Pentile 等效 PPI, 含 13 种常用屏幕预设)",
        "加解密新增 Cisco Type 7; 编解码新增 Gzip (压缩率统计/双格式展示); Hash 值计算页移除 bcrypt 算法区",
        "站长工具新增占位图片与 Shield Badge 生成, 设置页新增站长工具分类 tab, App Icon 三平台可勾选",
        "其它分类新增 ASCII 图片与 ASCII 文字 (figlet 风格大字)",
        "侧边菜单展开时分类标题显示所属应用数量徽标",
        "修复 just release 产物复制 (路径层级/安装包过滤) 与面包屑误带徽标问题",
      ],
      [
        "值計算新增 BCrypt 產生/驗證、Scrypt (RFC 7914 零依賴實作)、PPI 計算 (標準 RGB / Pentile 等效 PPI, 含 13 種常用螢幕預設)",
        "加解密新增 Cisco Type 7; 編解碼新增 Gzip (壓縮率統計/雙格式顯示); Hash 值計算頁移除 bcrypt 演算法區",
        "站長工具新增占位圖片與 Shield Badge 產生器, 設定頁新增站長工具分類頁籤, App Icon 三平台可勾選",
        "其他分類新增 ASCII 圖片與 ASCII 文字 (figlet 風格大字)",
        "側邊選單展開時分類標題顯示所含應用數量徽章",
        "修復 just release 產物複製 (路徑層級/安裝包過濾) 與麵包屑誤帶徽章的問題",
      ],
      [
        "Value calculators add BCrypt generation/verification, Scrypt (RFC 7914, zero-dependency implementation) and a PPI calculator (standard RGB / Pentile effective PPI, 13 common screen presets)",
        "Crypto adds Cisco Type 7; codecs add Gzip (compression-ratio stats / dual-format display); the bcrypt algorithm section is removed from the Hash page",
        "Webmaster tools add Placeholder Image and Shield Badge generators; the settings page gains a webmaster-tools category tab; App Icon platforms are checkable",
        "The Others category adds ASCII images and ASCII text (figlet-style banner letters)",
        "Category titles in the sidebar show a count badge of their apps when expanded",
        "Fixed just release artifact copying (path depth / installer filtering) and the breadcrumb wrongly carrying badges",
      ],
    ),
  },
  {
    color: "green",
    title: tri(
      "2026-09-05 V2.4.1 Release（修复 v2.4.0 黑屏后的重新发布版）",
      "2026-09-05 V2.4.1 Release（修復 v2.4.0 黑畫面後的重新發布版）",
      "2026-09-05 V2.4.1 Release (re-release fixing the v2.4.0 black screen)",
    ),
    items: trio(
      [
        "【本版发布原因】修复 v2.4.0 安装包启动黑屏: 残留 CJS require 改 ESM import + CSP 调整兼容 antd 运行时样式 (webpack→Vite 产物兼容问题)",
        "新增站长工具分类: 网页 TDK 信息检测与 robots.txt 生成",
        "编解码新增摩斯码编解码 (播放高亮/多音效/常用编码/一键保存 WAV 弹窗选择位置)、UUencode/XXencode、JWT 解码器",
        "加解密新增 RSA / SM2 国密、SM4、AES GCM 认证加密、Caesar/Rail Fence/Vigenere/Hill 古典密码",
        "值计算新增 SHA3 Hash / Keccak Hash; 其它分类新增 htpasswd 生成、正则表达式工具、Cron 规则生成",
        "正则表达式: 预设增至 17 条 (常用 5 条新增) + 一键复制规则",
        "Cron 规则生成新增「解析」页签 (逐字段中文解读 + 未来 10 次触发时间)",
        "设置页改为 VSCode 式布局 (分类导航移至左侧栏, 记住上次分类)",
        "修复 App 列表加载竞态与网页 TDK 深色模式显示问题",
        "渲染进程构建由 webpack 迁移至 Vite",
      ],
      [
        "【本版發布原因】修復 v2.4.0 安裝包啟動黑畫面: 殘留 CJS require 改為 ESM import + 調整 CSP 以相容 antd 執行期樣式 (webpack→Vite 產物相容問題)",
        "新增站長工具分類: 網頁 TDK 資訊偵測與 robots.txt 產生",
        "編解碼新增摩斯電碼編解碼 (播放高亮/多種音效/常用編碼/一鍵儲存 WAV 彈窗選擇位置)、UUencode/XXencode、JWT 解碼器",
        "加解密新增 RSA / SM2 國密、SM4、AES GCM 認證加密、Caesar/Rail Fence/Vigenere/Hill 古典密碼",
        "值計算新增 SHA3 Hash / Keccak Hash; 其他分類新增 htpasswd 產生、正則表達式工具、Cron 規則產生",
        "正則表達式: 預設增至 17 條 (常用新增 5 條) + 一鍵複製規則",
        "Cron 規則產生新增「解析」頁籤 (逐欄位解讀 + 未來 10 次觸發時間)",
        "設定頁改為 VSCode 式版面 (分類導覽移至左側欄, 記住上次分類)",
        "修復 App 清單載入競態與網頁 TDK 深色模式顯示問題",
        "渲染程序建置由 webpack 遷移至 Vite",
      ],
      [
        "[Reason for this release] Fixes the v2.4.0 installer black screen on startup: leftover CJS requires converted to ESM imports + CSP adjusted to accommodate antd runtime styles (webpack→Vite artifact compatibility)",
        "New webmaster-tools category: webpage TDK info detection and robots.txt generation",
        "Codecs add Morse encoding/decoding (playback highlight / multiple tones / common codes / one-click WAV save with a location picker), UUencode/XXencode and a JWT decoder",
        "Crypto adds RSA / SM2 (Chinese national standard), SM4, AES-GCM authenticated encryption and the Caesar / Rail Fence / Vigenère / Hill classical ciphers",
        "Value calculators add SHA3 Hash / Keccak Hash; the Others category adds htpasswd generation, a regex tester and a Cron rule generator",
        "Regex tester: presets raised to 17 (5 new common ones) + one-click rule copying",
        "Cron rule generator adds a “Parse” tab (field-by-field breakdown + next 10 firing times)",
        "Settings page switched to a VSCode-style layout (category nav moved to the left rail, last category remembered)",
        "Fixed the app-list loading race and the webpage-TDK display issue in dark mode",
        "Renderer build migrated from webpack to Vite",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-03 V2.2.0 Release", "2026-09-03 V2.2.0 Release", "2026-09-03 V2.2.0 Release"),
    items: trio(
      [
        "编解码新增 Punycode 编解码",
        "值计算新增 BCC 校验 (XOR) / LRC 校验 (累加和·Modbus 补码) / CRC 校验 (44 种标准 CRC-3~64 参数化计算, 含多项式公式展示)",
        "校验结果输出行点击即复制, 展示样式与 Hash 计算对齐",
        "设置新增 BCC/LRC/CRC 默认输入格式 (默认 ASCII/文本) 与 CRC 默认校验算法 (默认 CRC-16/MODBUS)",
        "CRC 算法下拉可搜索并展示多项式公式, 深色模式适配",
      ],
      [
        "編解碼新增 Punycode 編解碼",
        "值計算新增 BCC 校驗 (XOR) / LRC 校驗 (累加和·Modbus 補碼) / CRC 校驗 (44 種標準 CRC-3~64 參數化計算, 含多項式公式展示)",
        "校驗結果輸出列點擊即複製, 顯示樣式與 Hash 計算對齊",
        "設定新增 BCC/LRC/CRC 預設輸入格式 (預設 ASCII/文字) 與 CRC 預設校驗演算法 (預設 CRC-16/MODBUS)",
        "CRC 演算法下拉可搜尋並顯示多項式公式, 已適配深色模式",
      ],
      [
        "Codecs add Punycode encoding/decoding",
        "Value calculators add BCC check (XOR) / LRC check (running sum, Modbus complement) / CRC check (44 standard CRC-3~64 parametrized computations incl. polynomial-formula display)",
        "Checksum result rows copy on click; the display style is aligned with the Hash page",
        "Settings add a default input format for BCC/LRC/CRC (default ASCII/text) and a default CRC algorithm (default CRC-16/MODBUS)",
        "The CRC algorithm dropdown is searchable and shows polynomial formulas; dark mode adapted",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-03 V2.1.1 Release", "2026-09-03 V2.1.1 Release", "2026-09-03 V2.1.1 Release"),
    items: trio(
      [
        "目录重构: src/renderer 代码上移到 src 根目录",
        "Tab 切换保活: 切换标签页不丢失已填写数据",
        "条形码生成: 下载 PNG 弹出系统保存对话框选位置",
        "二维码生成: 新增「保存图片」按钮, 点击二维码预览也可保存 PNG",
      ],
      [
        "目錄重構: src/renderer 程式碼上移到 src 根目錄",
        "Tab 切換保活: 切換分頁不遺失已填寫的資料",
        "條碼產生: 下載 PNG 時彈出系統儲存對話框選擇位置",
        "二維碼產生: 新增「儲存圖片」按鈕, 點擊二維碼預覽也可儲存 PNG",
      ],
      [
        "Directory restructure: src/renderer code moved up to the src root",
        "Tab keep-alive: switching tabs no longer loses entered data",
        "Barcode generator: downloading a PNG opens the system save dialog to pick a location",
        "QR generator: new “Save image” button; clicking the QR preview also saves a PNG",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-09-03 V2.1.0 Release", "2026-09-03 V2.1.0 Release", "2026-09-03 V2.1.0 Release"),
    items: trio(
      [
        "新增 TEA / XTEA / XXTEA 加解密工具",
        "Hash 值计算新增 SM3 / BCrypt",
        "新增条形码生成 (CODE128 / EAN-13 / UPC-A / CODE39 / ITF / MSI / Pharmacode 等 16 种格式)",
        "应用只运行单实例; 托盘菜单支持直达设置/帮助/应用中心; 内容区顶部应用标签页与面包屑、标签右键菜单",
      ],
      [
        "新增 TEA / XTEA / XXTEA 加解密工具",
        "Hash 值計算新增 SM3 / BCrypt",
        "新增條碼產生 (CODE128 / EAN-13 / UPC-A / CODE39 / ITF / MSI / Pharmacode 等 16 種格式)",
        "應用僅執行單一實例; 托盤選單可直接開啟設定/說明/應用中心; 內容區頂部應用分頁與麵包屑、分頁右鍵選單",
      ],
      [
        "New TEA / XTEA / XXTEA crypto tools",
        "Hash calculator adds SM3 / BCrypt",
        "New barcode generator (CODE128 / EAN-13 / UPC-A / CODE39 / ITF / MSI / Pharmacode — 16 formats in all)",
        "Single-instance app; tray menu links straight to Settings / Help / App Center; app tabs with breadcrumbs and a tab right-click menu atop the content area",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2026-02-28 V2.0.0 Release", "2026-02-28 V2.0.0 Release", "2026-02-28 V2.0.0 Release"),
    items: trio(
      [
        "核心重构: 从 Electron 迁移到 Tauri 2 (体积更小、内存占用更低)",
        "构建发布: just 命令 + GitHub Actions 三平台自动打包 (win / macos / linux)",
        "Windows 提供单体免安装 exe, Linux 提供免安装 AppImage",
      ],
      [
        "核心重構: 從 Electron 遷移至 Tauri 2 (體積更小、記憶體占用更低)",
        "建置發布: just 指令 + GitHub Actions 三平台自動打包 (win / macos / linux)",
        "Windows 提供單體免安裝 exe, Linux 提供免安裝 AppImage",
      ],
      [
        "Core rewrite: migrated from Electron to Tauri 2 (smaller size, lower memory usage)",
        "Build & release: just commands + GitHub Actions auto-packaging for three platforms (win / macos / linux)",
        "Portable single-file exe for Windows; install-free AppImage for Linux",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2023-07-11 V1.3.0 Release", "2023-07-11 V1.3.0 Release", "2023-07-11 V1.3.0 Release"),
    items: trio(
      [
        "温度转换", "距离转换", "速度转换",
        "配置文件转换 (ini / json / yaml / toml / properties)",
        "面积转换", "容积转换", "质量转换",
      ],
      [
        "溫度轉換", "距離轉換", "速度轉換",
        "設定檔轉換 (ini / json / yaml / toml / properties)",
        "面積轉換", "容積轉換", "質量轉換",
      ],
      [
        "Temperature conversion", "Distance conversion", "Speed conversion",
        "Config file conversion (ini / json / yaml / toml / properties)",
        "Area conversion", "Volume conversion", "Mass conversion",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2023-06-30 V1.2.0 Release", "2023-06-30 V1.2.0 Release", "2023-06-30 V1.2.0 Release"),
    items: trio(
      [
        "Base64 图片", "中文拼音", "GPS坐标转换", "人民币大写", "字节转换",
      ],
      [
        "Base64 圖片", "中文拼音", "GPS 座標轉換", "人民幣大寫", "位元組轉換",
      ],
      [
        "Base64 image", "Chinese Pinyin", "GPS coordinate conversion", "RMB uppercase amount", "Byte conversion",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2023-06-15 V1.1.0 Release", "2023-06-15 V1.1.0 Release", "2023-06-15 V1.1.0 Release"),
    items: trio(
      [
        "DES 加密 / 解密", "AES 加密 / 解密", "Rabbit 加密 / 解密",
        "RC4 加密 / 解密", "3DES 加密 / 解密", "Base58 编码 / 解码", "PBKDF2 值计算",
      ],
      [
        "DES 加密 / 解密", "AES 加密 / 解密", "Rabbit 加密 / 解密",
        "RC4 加密 / 解密", "3DES 加密 / 解密", "Base58 編碼 / 解碼", "PBKDF2 值計算",
      ],
      [
        "DES encryption / decryption", "AES encryption / decryption", "Rabbit encryption / decryption",
        "RC4 encryption / decryption", "3DES encryption / decryption", "Base58 encoding / decoding", "PBKDF2 calculator",
      ],
    ),
  },
  {
    color: "green",
    title: tri("2023-06-07 V1.0.0 Release", "2023-06-07 V1.0.0 Release", "2023-06-07 V1.0.0 Release"),
    items: trio(
      [
        "Hash 值计算", "Base64 编码 / 解码", "URL 编码 / 解码", "时间戳转换", "CSS 配色",
        "颜色格式转换", "进制转换 ( BIN / OCT / DEC / HEX )", "二维码生成", "HmacHash 值计算",
        "SQL 格式化", "行数统计", "Unicode 编码 / 解码",
      ],
      [
        "Hash 值計算", "Base64 編碼 / 解碼", "URL 編碼 / 解碼", "時間戳轉換", "CSS 配色",
        "顏色格式轉換", "進位轉換 ( BIN / OCT / DEC / HEX )", "二維碼產生", "HmacHash 值計算",
        "SQL 格式化", "行數統計", "Unicode 編碼 / 解碼",
      ],
      [
        "Hash calculator", "Base64 encoding / decoding", "URL encoding / decoding", "Timestamp converter", "CSS Colors",
        "Color format conversion", "Base conversion (BIN / OCT / DEC / HEX)", "QR code generator", "HmacHash calculator",
        "SQL formatter", "Line counter", "Unicode encoding / decoding",
      ],
    ),
  },
];
